// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> kInkFormatCodes@0x0c104fe8:u16:12 kInkStrokeCodes@0x0c105000:u16:16 -o src/ink/CICTables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

#include "CICCodec.h"

extern const unsigned short	kInkFormatCodes[12];
extern const unsigned short	kInkStrokeCodes[16];

// ROM 0x0c104fe8 (unnamed) - kInkFormatCodes
const unsigned short	kInkFormatCodes[12] = {
	0x0007, 0x0001, 0x0000, 0x0000, 0x0008, 0x0001, 0x0000, 0x0001,
	0x0000, 0x0000, 0x0000, 0x0000,
};

// ROM 0x0c105000 (unnamed) - kInkStrokeCodes
const unsigned short	kInkStrokeCodes[16] = {
	0x0000, 0x0001, 0x0000, 0x0001, 0x0001, 0x0002, 0x0000, 0x0002,
	0x0002, 0x0004, 0x0000, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000,
};
