"""Extract types and prototypes from the Newton DDK headers with libclang.

The headers in `headers/` are cfront-era C++ with classic Mac line endings and
Mac Roman text.  `prepare()` normalises them into a flat include directory,
`parse()` runs clang on one translation unit that includes them all, and
`extract()` walks the AST into a plain JSON-able dictionary (see `types.json`
in the README) that `ghidra_import` turns into Ghidra data types.

Memory layout comes from clang itself (`--target=armeb-none-eabi
-mabi=apcs-gnu`, i.e. big-endian 32-bit ARM with APCS 4-byte alignment for
8-byte scalars).  That is correct for this ROM: constructors in the ROM show
the vtable pointer stored at offset 0 and empty base classes (`SingleObject`)
taking no space, e.g. `TAEventHandler::TAEventHandler` allocates 0x14 bytes and
writes the vtable at [r0,#0] and its four fields at 4..0x10 - exactly clang's
layout.  Only base-class offsets are not available through libclang; they are
computed here with the same rules and checked against the first field.

Types are encoded with the same JSON schema as `demangle.type_to_json`
({"k": "named"|"ptr"|"ref"|"qual"|"array"|"func"|"memptr", ...}) so both
sources feed one type mapper.  Typedef names are preserved (a field declared
`ULong` stays `ULong`); `typedefs` in the output map them to their targets.
"""

from __future__ import annotations

import fnmatch
import os
from typing import Dict, List, Optional

# Product configuration for the MP2100 D ROM: hasVoyager (-> hasCirrus,
# forSenior) comes from forQ in ConfigGlobal.h; forGerman selects the locale;
# __arm marks the ARM compiler (true/false keywords in NewtonTypes.h).
DEFAULT_DEFINES = ["forQ", "forGerman", "__arm=1"]

# Headers left out of the translation unit and why.
DEFAULT_EXCLUDES = {
    "*.f.h": "NewtonScript source, not C",
    "CommToolProtocol.h": "version 1 of TCommToolProtocol; CommToolProtocolV2.h is the 2.x ROM version",
    "SerialChip.h": "version 1 of TSerialChip; SerialChipV2.h is the 2.x ROM version",
}

# Headers that use types they do not include themselves; put their providers first.
INCLUDE_FIRST = ["Newton.h", "NewtonTime.h", "LongTime.h", "KernelTypes.h", "SharedTypes.h"]

CLANG_ARGS = ["-x", "c++", "-std=c++98", "--target=armeb-none-eabi", "-mabi=apcs-gnu",
              "-fsyntax-only", "-ferror-limit=0", "-nostdinc", "-Wno-everything"]

# libclang TypeKind name -> C spelling (as used by the demangler's builtins)
BUILTIN_SPELLING = {
    "VOID": "void", "BOOL": "bool", "CHAR_U": "char", "UCHAR": "unsigned char", "CHAR_S": "char",
    "SCHAR": "signed char", "WCHAR": "wchar_t", "SHORT": "short", "USHORT": "unsigned short",
    "INT": "int", "UINT": "unsigned int", "LONG": "long", "ULONG": "unsigned long",
    "LONGLONG": "long long", "ULONGLONG": "unsigned long long", "FLOAT": "float",
    "DOUBLE": "double", "LONGDOUBLE": "long double", "CHAR16": "wchar_t", "CHAR32": "wchar_t",
}


def prepare(src_dir: str, out_dir: str, excludes: Optional[Dict[str, str]] = None,
            write_all_cpp: bool = True) -> List[str]:
    """Copy headers into a flat UTF-8/LF include directory; return the names to include."""
    excludes = DEFAULT_EXCLUDES if excludes is None else excludes
    os.makedirs(out_dir, exist_ok=True)
    names: List[str] = []
    seen = set()
    for root, _, files in os.walk(src_dir):
        for f in sorted(files):
            if not f.endswith(".h"):
                continue
            if f in seen:
                raise ValueError(f"duplicate header basename {f}; includes are flat")
            seen.add(f)
            with open(os.path.join(root, f), "rb") as src:
                raw = src.read()
            text = raw.decode("mac-roman").replace("\r\n", "\n").replace("\r", "\n")
            with open(os.path.join(out_dir, f), "w", encoding="utf-8", newline="\n") as out:
                out.write(text)
            if not any(fnmatch.fnmatch(f, pat) for pat in excludes):
                names.append(f)
    ordered = [n for n in INCLUDE_FIRST if n in names] + sorted(n for n in names if n not in INCLUDE_FIRST)
    if not write_all_cpp:
        return ordered
    with open(os.path.join(out_dir, "all.cpp"), "w", encoding="utf-8", newline="\n") as out:
        out.write("// generated by newtonrom.headers.prepare - includes every DDK header\n")
        for n in ordered:
            out.write(f'#include "{n}"\n')
    return ordered


def parse(include_dir: str, defines: Optional[List[str]] = None):
    """Parse all.cpp; returns the libclang TranslationUnit."""
    import clang.cindex as ci
    defines = DEFAULT_DEFINES if defines is None else defines
    args = CLANG_ARGS + ["-I" + include_dir] + ["-D" + d for d in defines]
    index = ci.Index.create()
    return index.parse(os.path.join(include_dir, "all.cpp"), args=args)


# --------------------------------------------------------------------------
# Type conversion
# --------------------------------------------------------------------------

def type_to_json(t) -> dict:
    """Convert a libclang Type to the shared JSON type schema."""
    base = _base_json(t)
    if t.is_const_qualified() or t.is_volatile_qualified():
        return {"k": "qual", "const": t.is_const_qualified(), "volatile": t.is_volatile_qualified(),
                "t": base}
    return base


def _base_json(t) -> dict:
    import clang.cindex as ci
    TK = ci.TypeKind
    k = t.kind
    if k == TK.ELABORATED:
        return _base_json(t.get_named_type())
    if k == TK.POINTER:
        return {"k": "ptr", "t": type_to_json(t.get_pointee())}
    if k in (TK.LVALUEREFERENCE, TK.RVALUEREFERENCE):
        return {"k": "ref", "t": type_to_json(t.get_pointee())}
    if k == TK.CONSTANTARRAY:
        return {"k": "array", "n": t.get_array_size(), "t": type_to_json(t.get_array_element_type())}
    if k == TK.INCOMPLETEARRAY:
        return {"k": "ptr", "t": type_to_json(t.get_array_element_type())}
    if k == TK.TYPEDEF:
        return {"k": "named", "name": t.get_declaration().spelling}
    if k in (TK.RECORD, TK.ENUM):
        decl = t.get_declaration()
        return {"k": "named", "name": decl.spelling or t.spelling}
    if k == TK.FUNCTIONPROTO:
        return {"k": "func", "params": [type_to_json(a) for a in t.argument_types()],
                "ret": type_to_json(t.get_result()), "variadic": t.is_function_variadic()}
    if k == TK.FUNCTIONNOPROTO:
        return {"k": "func", "params": [], "ret": type_to_json(t.get_result())}
    if k == TK.MEMBERPOINTER:
        cls = t.get_class_type()
        return {"k": "memptr", "cls": cls.get_declaration().spelling or cls.spelling,
                "t": type_to_json(t.get_pointee())}
    if k.name in BUILTIN_SPELLING:
        return {"k": "named", "name": BUILTIN_SPELLING[k.name]}
    if k == TK.UNEXPOSED:
        can = t.get_canonical()
        if can.kind != TK.UNEXPOSED:
            return _base_json(can)
    return {"k": "named", "name": t.spelling, "unresolved": True}


# --------------------------------------------------------------------------
# Declarations
# --------------------------------------------------------------------------

def _in_dir(cursor, include_dir: str) -> bool:
    f = cursor.location.file
    return f is not None and os.path.abspath(os.path.dirname(f.name)) == os.path.abspath(include_dir)


def _file(cursor) -> str:
    return os.path.basename(cursor.location.file.name)


def _method(c) -> dict:
    import clang.cindex as ci
    CK = ci.CursorKind
    kind = {CK.CONSTRUCTOR: "ctor", CK.DESTRUCTOR: "dtor", CK.CONVERSION_FUNCTION: "conversion"}.get(c.kind, "method")
    if kind == "method" and c.spelling.startswith("operator"):
        kind = "operator"
    return {
        "name": c.spelling,
        "kind": kind,
        "params": [{"name": a.spelling, "type": type_to_json(a.type)} for a in c.get_arguments()],
        "ret": type_to_json(c.result_type),
        "virtual": bool(c.is_virtual_method()) if c.kind != CK.CONSTRUCTOR else False,
        "static": bool(c.is_static_method()) if c.kind == CK.CXX_METHOD else False,
        "const": bool(c.is_const_method()) if c.kind in (CK.CXX_METHOD, CK.CONVERSION_FUNCTION) else False,
        "variadic": bool(c.type.is_function_variadic()),
        "line": c.location.line,
    }


def _record(c, records: Dict[str, dict]) -> dict:
    import clang.cindex as ci
    CK = ci.CursorKind
    fields, bases, methods = [], [], []
    for ch in c.get_children():
        if ch.kind == CK.CXX_BASE_SPECIFIER:
            bases.append({"name": ch.type.get_declaration().spelling or ch.type.spelling,
                          "virtual": False})
        elif ch.kind == CK.FIELD_DECL:
            f = {"name": ch.spelling, "type": type_to_json(ch.type),
                 "offset": ch.get_field_offsetof() // 8}
            if ch.is_bitfield():
                f["bit_offset"] = ch.get_field_offsetof()
                f["bit_width"] = ch.get_bitfield_width()
            fields.append(f)
        elif ch.kind in (CK.CXX_METHOD, CK.CONSTRUCTOR, CK.DESTRUCTOR, CK.CONVERSION_FUNCTION):
            methods.append(_method(ch))
    has_virtual = any(m["virtual"] for m in methods)
    base_poly = any(records.get(b["name"], {}).get("polymorphic") for b in bases)
    polymorphic = has_virtual or base_poly
    rec = {
        "name": c.spelling,
        "kind": {CK.CLASS_DECL: "class", CK.STRUCT_DECL: "struct", CK.UNION_DECL: "union"}[c.kind],
        "file": _file(c), "line": c.location.line,
        "size": c.type.get_size(), "align": c.type.get_align(),
        "polymorphic": polymorphic,
        "introduces_vptr": polymorphic and not base_poly,
        "bases": bases, "fields": fields, "methods": methods,
    }
    _place_bases(rec, records)
    return rec


def _place_bases(rec: dict, records: Dict[str, dict]) -> None:
    """Compute base subobject offsets (Itanium rules: primary base at 0, EBO)."""
    off = 4 if rec["introduces_vptr"] else 0
    primary_done = False
    for b in rec["bases"]:
        base = records.get(b["name"])
        if base is None:
            b["offset"] = None
            rec.setdefault("warnings", []).append(f"unknown base {b['name']}")
            continue
        if base["size"] <= 1 and not base["fields"] and not base["polymorphic"]:
            b["offset"] = 0          # empty base optimisation
            continue
        if base["polymorphic"] and not primary_done:
            b["offset"] = 0          # primary base shares the vptr
            primary_done = True
            off = max(off, base["size"])
            continue
        align = max(base["align"], 1)
        off = (off + align - 1) // align * align
        b["offset"] = off
        off += base["size"]
    if rec["fields"]:
        first = min(f["offset"] for f in rec["fields"])
        if first < off:
            rec.setdefault("warnings", []).append(
                f"first field at {first} but bases end at {off}: base layout uncertain")


def extract(tu, include_dir: str) -> dict:
    """Walk the translation unit into a JSON-able dictionary."""
    import clang.cindex as ci
    CK = ci.CursorKind
    records: Dict[str, dict] = {}
    enums: Dict[str, dict] = {}
    typedefs: Dict[str, dict] = {}
    functions: List[dict] = []
    diagnostics = []
    for d in tu.diagnostics:
        if d.severity >= 3:
            diagnostics.append({"file": os.path.basename(d.location.file.name) if d.location.file else None,
                                "line": d.location.line, "message": d.spelling})

    def walk(cursor):
        for c in cursor.get_children():
            if not _in_dir(c, include_dir):
                continue
            if c.kind in (CK.CLASS_DECL, CK.STRUCT_DECL, CK.UNION_DECL):
                if c.is_definition() and c.spelling:
                    records[c.spelling] = _record(c, records)
                    walk(c)   # nested types
            elif c.kind == CK.ENUM_DECL and c.is_definition():
                name = c.spelling or f"anon_enum_{_file(c).replace('.', '_')}_{c.location.line}"
                enums[name] = {
                    "name": name, "file": _file(c), "line": c.location.line,
                    "size": c.enum_type.get_size(), "anonymous": not c.spelling,
                    "values": [[v.spelling, v.enum_value] for v in c.get_children()
                               if v.kind == CK.ENUM_CONSTANT_DECL],
                }
            elif c.kind == CK.TYPEDEF_DECL:
                typedefs[c.spelling] = type_to_json(c.underlying_typedef_type)
            elif c.kind == CK.FUNCTION_DECL:
                functions.append({
                    "name": c.spelling, "file": _file(c), "line": c.location.line,
                    "params": [{"name": a.spelling, "type": type_to_json(a.type)} for a in c.get_arguments()],
                    "ret": type_to_json(c.result_type),
                    "variadic": c.type.is_function_variadic(),
                })
            elif c.kind in (CK.NAMESPACE, CK.LINKAGE_SPEC, CK.UNEXPOSED_DECL):
                walk(c)

    walk(tu.cursor)
    return {"records": records, "enums": enums, "typedefs": typedefs,
            "functions": functions, "diagnostics": diagnostics}


# --------------------------------------------------------------------------
# Matching header prototypes against demangled symbols
# --------------------------------------------------------------------------

class HeaderTypes:
    """Convenience view over types.json: typedef resolution and prototype lookup."""

    def __init__(self, data: dict):
        self.records: Dict[str, dict] = data["records"]
        self.enums: Dict[str, dict] = data["enums"]
        self.typedefs: Dict[str, dict] = data["typedefs"]
        self.functions: Dict[str, List[dict]] = {}
        for f in data["functions"]:
            self.functions.setdefault(f["name"], []).append(f)
        self._canon_cache: Dict[str, str] = {}

    def resolve(self, t: dict, depth: int = 0) -> dict:
        """Replace typedef names by their definitions, recursively."""
        if depth > 32:
            return t
        k = t["k"]
        if k == "named":
            target = self.typedefs.get(t["name"])
            return self.resolve(target, depth + 1) if target is not None else t
        if k in ("ptr", "ref", "qual", "array"):
            return dict(t, t=self.resolve(t["t"], depth))
        if k == "func":
            return dict(t, params=[self.resolve(p, depth) for p in t["params"]],
                        ret=self.resolve(t["ret"], depth) if t.get("ret") else None)
        if k == "memptr":
            return dict(t, t=self.resolve(t["t"], depth))
        return t

    def canonical_params(self, params: List[dict], resolve: bool = True) -> str:
        """Comparable rendering of a parameter list (typedefs resolved, noise removed)."""
        import json
        out = []
        for p in params:
            t = self.resolve(p) if resolve else p
            out.append(_normalise(t, top=True))
        return json.dumps(out, sort_keys=True)

    def find_method(self, cls: str, name: str, params: List[dict], static: Optional[bool] = None) -> Optional[dict]:
        """Header declaration of cls::name with exactly these (demangled) parameter types."""
        rec = self.records.get(cls)
        if rec is None:
            return None
        params, variadic = _split_ellipsis(params)
        want = self.canonical_params(params, resolve=False)
        hits = [m for m in rec["methods"]
                if m["name"] == name and len(m["params"]) == len(params)
                and bool(m.get("variadic")) == variadic
                and self.canonical_params([p["type"] for p in m["params"]]) == want]
        if static is not None:
            hits = [m for m in hits if m["static"] == static] or hits
        return hits[0] if len(hits) == 1 else None

    def find_function(self, name: str, params: Optional[List[dict]] = None) -> Optional[dict]:
        """Header declaration of a free function; params=None matches by name alone (C linkage)."""
        cands = self.functions.get(name, [])
        if params is not None:
            params, variadic = _split_ellipsis(params)
            want = self.canonical_params(params, resolve=False)
            cands = [f for f in cands if len(f["params"]) == len(params)
                     and bool(f.get("variadic")) == variadic
                     and self.canonical_params([p["type"] for p in f["params"]]) == want]
        else:
            # a C function declared identically in several headers still counts as unique
            uniq = {self.canonical_params([p["type"] for p in f["params"]]) for f in cands}
            if len(uniq) == 1:
                return cands[0]
        return cands[0] if len(cands) == 1 else None


ELLIPSIS = {"k": "named", "name": "..."}


def _split_ellipsis(params: List[dict]):
    """Demangled lists carry '...' as a pseudo parameter; clang reports a flag."""
    if params and params[-1] == ELLIPSIS:
        return params[:-1], True
    return params, False


def _normalise(t: dict, top: bool = False) -> dict:
    """Drop what the mangler does not encode: top-level cv, array decay, variadic flag."""
    k = t["k"]
    if k == "qual":
        inner = _normalise(t["t"])
        if top or not (t.get("const") or t.get("volatile")):
            return inner
        return {"k": "qual", "const": bool(t.get("const")), "volatile": bool(t.get("volatile")), "t": inner}
    if k == "array" and top:
        return {"k": "ptr", "t": _normalise(t["t"])}
    if k in ("ptr", "ref", "array"):
        out = dict(t, t=_normalise(t["t"]))
        return out
    if k == "func":
        params = [_normalise(p, top=True) for p in t["params"] if p != {"k": "named", "name": "..."}]
        ret = _normalise(t["ret"]) if t.get("ret") else {"k": "named", "name": "void"}
        return {"k": "func", "params": params, "ret": ret}
    if k == "memptr":
        return {"k": "memptr", "cls": t["cls"], "t": _normalise(t["t"])}
    if k == "named":
        return {"k": "named", "name": t["name"]}
    return t
