// Generated by tools/newton-rom/analysis/nsgrammar.py; do not edit.
//   python tools/newton-rom/analysis/nsgrammar.py <build_dir> -o src/frames
// The NewtonScript parser's tokens, constants and tables, read from the
// MP2100 D ROM (TCompiler::Parser is a Berkeley yacc parser; the tables
// are its own, at the addresses cited in ParserTables.cpp).

#ifndef __PARSERTABLES_H
#define __PARSERTABLES_H

// the tokens (yyname); characters are their own tokens
enum {
	tokenOPTIONALEXPR = 257,
	tokenCONST = 258,
	tokenSYMBOL = 259,
	tokenINTEGER = 260,
	tokenREAL = 261,
	tokenREFCONST = 262,
	tokenBEGIN = 263,
	tokenEND = 264,
	tokenFUNC = 265,
	tokenNATIVE = 266,
	tokenGLOBAL = 267,
	tokenGFUNCTION = 268,
	tokenCONSTANT = 269,
	tokenIF = 270,
	tokenTHEN = 271,
	tokenELSE = 272,
	tokenTRY = 273,
	tokenONEXCEPTION = 274,
	tokenBUILDARRAY = 275,
	tokenBUILDFRAME = 276,
	tokenLOCAL = 277,
	tokenLOOP = 278,
	tokenFOR = 279,
	tokenTO = 280,
	tokenBY = 281,
	tokenWHILE = 282,
	tokenREPEAT = 283,
	tokenUNTIL = 284,
	tokenDO = 285,
	tokenCALL = 286,
	tokenWITH = 287,
	tokenINVOKE = 288,
	tokenFOREACH = 289,
	tokenIN = 290,
	tokenDEEPLY = 291,
	tokenSELF = 292,
	tokenINHERITED = 293,
	tokenRETURN = 294,
	tokenBREAK = 295,
	tokenKEEPGOING = 296,
	tokenASSIGN = 297,
	tokenAND = 298,
	tokenOR = 299,
	tokenNOT = 300,
	tokenLEQ = 301,
	tokenGEQ = 302,
	tokenEQL = 303,
	tokenNEQ = 304,
	tokenEXISTS = 305,
	tokenAMPERAMPER = 306,
	tokenDIV = 307,
	tokenMOD = 308,
	tokenLSHIFT = 309,
	tokenRSHIFT = 310,
	tokenUMINUS = 311,
	tokenSENDIFDEFINED = 312,
};

const int YYTABLESIZE = 4401;
const int YYFINAL = 31;
const int YYMAXTOKEN = 312;
const int YYERRCODE = 256;
const int kNumParserRules = 151;
const int kNumReservedWords = 35;

extern const short	yylhs[152];
extern const short	yylen[152];
extern const short	yydefred[308];
extern const short	yydgoto[46];
extern const short	yysindex[308];
extern const short	yyrindex[308];
extern const short	yygindex[46];
extern const short	yytable[4402];
extern const short	yycheck[4402];
extern const char* const	yyname[313];
extern const char* const	yyrule[151];

// the lexer's reserved words and their tokens (sorted by name)
struct ReservedWord { const char* fName; int fToken; };
extern const ReservedWord	gReservedWords[35];

#endif	/* __PARSERTABLES_H */
