// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> gPrintLiterals:cstr:35 -o src/frames/PrintLiterals.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const char* const	gPrintLiterals[35];

// ROM 0x0c1052cc gPrintLiterals
const char* const	gPrintLiterals[35] = {
	0,
	"unary1",
	"unary2",
	"unary3",
	"push",
	"push-constant",
	"call",
	"invoke",
	"send",
	"send-if-defined",
	"resend",
	"resend-if-defined",
	"branch",
	"branch-t",
	"branch-f",
	"find-var",
	"get-var",
	"make-frame",
	"make-array",
	"get-path",
	"set-path",
	"set-var",
	"set-find-var",
	"incr-var",
	"branch-if-loop-not-done",
	"freq-func",
	"new-handlers",
	"pop",
	"dup",
	"return",
	"push-self",
	"set-lex-scope",
	"iter-next",
	"iter-done",
	"pop-handlers",
};
