add_executable(test_RecObject test_RecObject.cpp)
target_link_libraries(test_RecObject PRIVATE recognition)
add_test(NAME recognition.RecObject COMMAND test_RecObject)
add_executable(test_Stroke test_Stroke.cpp)
target_link_libraries(test_Stroke PRIVATE recognition)
add_test(NAME recognition.Stroke COMMAND test_Stroke)
add_executable(test_Unit test_Unit.cpp)
target_link_libraries(test_Unit PRIVATE recognition)
add_test(NAME recognition.Unit COMMAND test_Unit)

add_executable(test_Areas test_Areas.cpp)
target_link_libraries(test_Areas PRIVATE recognition)
add_test(NAME recognition.Areas COMMAND test_Areas)

add_executable(test_Words test_Words.cpp)
target_link_libraries(test_Words PRIVATE recognition)
add_test(NAME recognition.Words COMMAND test_Words)

add_executable(test_Airus test_Airus.cpp)
target_link_libraries(test_Airus PRIVATE recognition)
add_test(NAME recognition.Airus COMMAND test_Airus)

add_executable(test_RecConfig test_RecConfig.cpp)
target_link_libraries(test_RecConfig PRIVATE recognition)
target_compile_definitions(test_RecConfig PRIVATE "NEWTON_ROM_BIN=\"${NEWTON_ROM_BIN}\"")
add_test(NAME recognition.RecConfig COMMAND test_RecConfig)

add_executable(test_Controller test_Controller.cpp)
target_link_libraries(test_Controller PRIVATE recognition)
add_test(NAME recognition.Controller COMMAND test_Controller)
