// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> kAirusRPMask@0x0c100834:u32:4 kAirusNodeSize@0x0c100844:u32:4 -o src/recognition/AirusTables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const unsigned int	kAirusRPMask[4];
extern const unsigned int	kAirusNodeSize[4];

// ROM 0x0c100834 (unnamed) - kAirusRPMask
const unsigned int	kAirusRPMask[4] = {
	0xffffffff, 0x0000000f, 0x00000fff, 0xffffffff,
};

// ROM 0x0c100844 (unnamed) - kAirusNodeSize
const unsigned int	kAirusNodeSize[4] = {
	0x00000002, 0x00000002, 0x00000003, 0x00000005,
};
