/*
	File:		recognition/BPNet.h

	Contains:	The handwriting engine's classifier: a back-propagation
				net, and the bottom of reading a word.

				Every character the engine offers comes out of this.
				`WordRecogNetEvaluate` fills the net's inputs from a
				patternizer, runs it, and maps its 134 outputs through
				the common info's tables into scores for the 256
				character codes; `CharBoxNetEvaluate` does the same for
				a letter written in a box.

				The net is **fixed point and tiny**, which is what let
				it run on a 162 MHz StrongARM with no floating point at
				all:

				* a unit's activation is **one byte**, 0 to 255, with
				  128 standing for nought;
				* a weight is **one byte** biased by 128, so the sum a
				  unit accumulates is
				  `sum += activation * (weight - 128)`;
				* the sigmoid is a **lookup table**, `QSigLu`: the
				  magnitude of the sum is clamped at 0x5900, shifted
				  down six bits and used as an index, and a negative
				  sum answers 255 minus the result.  So the whole
				  non-linearity is one `ldrb`.

				There are 1002 units: 384 inputs, 484 hidden and 134
				outputs, laid end to end in one byte array, and they are
				worked out in order so that a unit may read any unit
				before it.  The connections are a *program* rather than
				a matrix: `newtConnects` is 2392 words, each saying how
				many connections follow, where in the unit array they
				start, and whether to take four more weight bytes; a
				word whose count is nought ends a unit and carries the
				next one's bias.  There are 619 of those - 618 units and
				the terminator - and the weights they call for come to
				the 91,124 bytes of `bpWeight`.

	The layers above it - the patternizers, the segment layer and the
	feature extraction - are NOT YET, so nothing has inputs to give it
	yet; the evaluator itself is here, and `docs/recognition/bpnet.md`
	writes up the assembly it came out of.

	Reconstructed from the MP2x00 US ROM (0x0001a260, 0x0003b14c-
	0x0003b298); each function cites its origin.
*/

#ifndef __BPNET_H
#define __BPNET_H

#ifndef __NEWTONTYPES_H
#include "NewtonTypes.h"
#endif


// The net.  The ROM's object is 0x84 bytes and `BPNetCreateNumOut`
// makes one by copying the template `bpNet` (`BPNetTables.cpp`,
// generated by `analysis/bpnet.py`), so the template is constant and
// the copy is not: `BPNetAllocateNet` hangs the unit array off it and
// `BPNetLearnEnable` writes its last byte.
//
// A field named `fFieldNN` is one nothing reconstructed so far reads;
// the offsets in the comments are the ROM's.
struct BPNet
{
	ULong			fField00[3];		// +0x00
	const ULong*	fNGS;				// +0x0c  bpNGS
	const ULong*	fInputType;			// +0x10  inputType: the four input groups
	ULong			fField14;			// +0x14
	const ULong*	fCSS;				// +0x18  bpCSS
	const ULong*	fConnectRanges;		// +0x1c  numConnectRanges
	// the connection program: one word per group of connections, and a
	// word whose count is nought ends a unit and gives the next one's
	// bias in its low halfword (times 256, signed)
	const ULong*	fConnects;			// +0x20  newtConnects
	ULong			fField24[2];		// +0x24
	// the unit array, `fUnitCount` bytes, made by BPNetAllocateNet
	UByte*			fBlock;				// +0x2c
	ULong			fField30[2];		// +0x30
	// one byte per connection, biased by 128
	const UByte*	fWeights;			// +0x38  bpWeight
	UByte*			fUnits;				// +0x3c  = fBlock
	UByte*			fOutputs;			// +0x40  = fUnits + fUnitCount - fOutputCount
	short			fInputCount;		// +0x44  384
	short			fOutputCount;		// +0x46  134
	short			fUnitCount;			// +0x48  1002
	short			fComputedCount;		// +0x4a  618 = hidden + outputs
	short			fHiddenCount;		// +0x4c  484
	short			fField4e;			// +0x4e
	ULong			fConnectionCount;	// +0x50  90540
	ULong			fWeightSize;		// +0x54  91124, the size of bpWeight
	ULong			fField58[5];		// +0x58 .. +0x68
	ULong			fParamCount;		// +0x6c  57, the size of bpParam in words
	const ULong*	fParams;			// +0x70  bpParam
	const ULong*	fArParams;			// +0x74  arBPParam
	ULong			fField78;			// +0x78
	UByte			fField7c;			// +0x7c
	UByte			fField7d;			// +0x7d  cleared by an evaluate
	UByte			fField7e;
	UByte			fField7f;
	UByte			fLearning;			// +0x80  BPNetLearnEnable's
	UByte			fPad81[3];
};


// The trained tables, as the ROM has them (`BPNetTables.cpp`,
// generated - do not edit).
extern const BPNet	bpNet;								// ROM 0x0036e618 bpNet
extern const UByte	bpWeight[91124];					// ROM 0x003948f0 bpWeight
extern const ULong	newtConnects[2392];					// ROM 0x003aace4 newtConnects
// The sigmoid: 128 for a sum of nought, rising to 255.  A sum is taken
// as a magnitude, clamped at kBPNetSigmoidLimit, shifted down six bits
// and looked up; a negative sum answers 255 minus the result.
extern const UByte	QSigLu[360];						// ROM 0x0036500c QSigLu

const long	kBPNetSigmoidLimit	= 0x5900;	// beyond this the answer is 255
const long	kBPNetSigmoidShift	= 6;
// What a connection word says.
const long	kBPNetCountShift	= 18;		// the count, signed, in the top 14 bits
const ULong	kBPNetNextWeights	= 0x00010000;	// take four more weight bytes
const ULong	kBPNetNextRegister	= 0x00020000;	// ... or step on within them


// A net with `outputs` output nodes: the ROM's template copied into a
// block of its own.  Throws `evt.ex.abt.stack`.
BPNet*	BPNetCreateNumOut(long outputs);				// ROM 0x0003b1cc BPNetCreateNumOut
// The unit array hung off it, and the three pointers into it.
NewtonErr	BPNetAllocateNet(BPNet* net);			// ROM 0x0003b14c BPNetAllocateNet
// ... which is all `BPNetLoad` does: the weights are in the ROM, so
// there is nothing to read in.
NewtonErr	BPNetLoad(BPNet* net, void* from);		// ROM 0x0003b280 BPNetLoad
// The unit array given back, and the net with it.
void	BPNetFree(BPNet* net);						// ROM 0x0003b268 BPNetFree
void	BPNetDestroy(BPNet* net);					// ROM 0x0003b240 BPNetDestroy
// Whether the net may learn from what it is shown.  The engine turns
// it off and never turns it on.
void	BPNetLearnEnable(BPNet* net, long enable);	// ROM 0x0003b278 BPNetLearnEnable

// The net run: every unit after the inputs worked out in order, and
// the outputs left in `fOutputs`.
void	BPNetEvaluate(BPNet* net);					// ROM 0x0001a260 BPNetEvaluate

#endif	/* __BPNET_H */
