// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> kChunkSin@0x0037add4:i32:4 kChunkCos@0x0037ade4:i32:4 -o src/recognition/ChunkTables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const int	kChunkSin[4];
extern const int	kChunkCos[4];

// ROM 0x0037add4 (unnamed) - kChunkSin
const int	kChunkSin[4] = {
	   0, 2588, 5000, 7071,
};

// ROM 0x0037ade4 (unnamed) - kChunkCos
const int	kChunkCos[4] = {
	10000,  9659,  8660,  7071,
};
