/*
	File:		recognition/Fragment.h

	Contains:	The ligature fragmenter - one stroke cut into letters.

				Joined-up writing arrives as a single stroke that
				covers several letters, and nothing above can read it
				until it has been cut.  This is what decides where.  It
				is a pipeline of four passes over the stroke's points,
				which `FindStrokeFragments` runs and `FragmentStroke`
				then acts on:

				1. **the good runs.**  Every step from one point to the
				   next is a (dx, dy, length); a step is *good* when it
				   goes rightwards and does so more than it goes
				   downwards.  A stretch of good steps is a candidate
				   ligature - the join between two letters - and
				   `FindGoodRuns` gathers them into a list.
				2. **the cusps.**  A run that turns sharply one way and
				   then back is really two runs, and `CheckCusps` cuts
				   it at the turn.
				3. **the crossings.**  `CalcXProjection` counts, for
				   every column of the stroke's width, how many times
				   the ink crosses it, and `CheckXProjection` narrows
				   each run to the stretch where that count is at its
				   lowest - throwing the run away entirely when even
				   its best is more than one crossing, because a place
				   the pen has been twice is not a place to cut.
				4. **the break points.**  `DefineBreakPoints` puts the
				   break three quarters of the way along each surviving
				   run, holding every piece to at least a fraction of
				   the writing's size.

				`RUN` is a copy of the writer's hand - the twenty-two
				running measurements `WordRecog::fRun` carries - which
				`FragmentStroke` takes before it starts, because the
				passes below reach it as a global rather than being
				handed it.

	Reconstructed from the MP2x00 US ROM (0x000cbdcc-0x000cd138); each
	function cites its origin.
*/

#ifndef __FRAGMENT_H
#define __FRAGMENT_H

#ifndef __NEWTONTYPES_H
#include "NewtonTypes.h"
#endif
#include "FixedGeometry.h"

struct RosStroke;
struct RosStrokeList;
struct List;
struct ListEntry;

// One step from a point of a stroke to the next.
struct StrokeDelta
{
	Fixed	fDX;			// +0x00
	Fixed	fDY;			// +0x04
	Fixed	fLength;		// +0x08
};

// A stretch of a stroke that might be cut: two point indices.
struct StrokeRun
{
	long	fFirst;			// +0x00
	long	fLast;			// +0x04
};

// ... and where it was decided to cut.
struct StrokeBreaks
{
	long	fCount;			// +0x00
	long*	fAt;			// +0x04
};

// How often the stroke crosses each column of its own width, and what
// that count is at each of its points.
// DEVIATION: the two arrays are pointer-sized on the host.
struct XProjection
{
	Fixed	fLeft;			// +0x00  the x the first column starts at
	short	fColumns;		// +0x04
	short	fPad06;
	short*	fCounts;		// +0x08  one per column
	short*	fPointValue;	// +0x0c  one per point of the stroke
};

// The writer's hand, as `FragmentStroke` copied it in: the same
// twenty-two running measurements `WordRecog::fRun` carries.  The
// passes below reach it here rather than being handed it.
extern Fixed	RUN[22];							// ROM 0x0c106074 RUN

// What the passes work to.  (FragmentTables.cpp, generated by
// analysis/romtable.py; they live in the initialised data, so the
// engine could in principle change them.)
extern const int	gFragmentParams[6];				// ROM 0x0c100de4 (unnamed)
extern const short	gXProjectionParams[2];			// ROM 0x0c100dfc (unnamed)

const long	kFragMinPiece		= 0;	// 0.15 of the writing: the least a piece may be
const long	kFragBreakAt		= 1;	// 0.75: how far along a run the break goes
const long	kFragCuspMinRun		= 2;	// 0.40: the least a run must be to look for a cusp
const long	kFragCuspMin		= 3;	// -0.5: the turn back a cusp needs
const long	kFragCuspMax		= 4;	// 0.30: ... having first turned this far
const long	kFragCuspGate		= 5;	// 0.30: the same again, as a fixed threshold
const long	kXProjMaxCrossings	= 0;	// 1: the most crossings a break may sit on
const long	kXProjColumnsPerPixel = 1;	// 8

// Every step of the stroke as a (dx, dy, length); nil for a stroke of
// fewer than two points.  The caller frees it.
StrokeDelta*	CalcDeltas(const RosStroke* stroke);		// ROM 0x000cbdcc CalcDeltas

// Whether a stroke is four times wider than it is tall, and big enough
// to be worth saying so about.
Boolean		StrokeIsHorizontal(const RosStroke* stroke);	// ROM 0x000cc0a4 StrokeIsHorizontal
// ... and whether one step goes rightwards, and more than it goes
// downwards.
Boolean		IsThisRunGood(Fixed dx, Fixed dy);			// ROM 0x000cc088 IsThisRunGood

// Every stretch of good steps, appended to the list as a `StrokeRun`.
void		FindGoodRuns(const RosStroke* stroke, const StrokeDelta* deltas,
					List* runs);						// ROM 0x000cbedc FindGoodRuns

// How long a stretch of the stroke is, and where along it a given
// length is reached (rounded to the nearer point).
Fixed		FindFragmentLength(const StrokeDelta* deltas, long first,
					long last);							// ROM 0x000cc3a4 FindFragmentLength
long		FindBreakPoint(const StrokeDelta* deltas, long first, long last,
					Fixed want);						// ROM 0x000cc328 FindBreakPoint

// A run that turns sharply one way and then back, cut at the turn.
void		CheckCusps(List* runs, ListEntry* cursor, const FPoint* points,
					const StrokeDelta* deltas);			// ROM 0x000cc420 CheckCusps
void		ProcessCusps(const RosStroke* stroke, List* runs,
					const StrokeDelta* deltas);			// ROM 0x000cc3d8 ProcessCusps

// How often the ink crosses each column of the stroke's width.
XProjection*	CalcXProjection(const RosStroke* stroke);	// ROM 0x000cc8d8 CalcXProjection
XProjection*	XProjectionDestroy(XProjection* proj);		// ROM 0x000ccee8 XProjectionDestroy
// One point's value, and the one before it lowered if this step found
// something smaller.
void		XProjectionSetPtVals(const short* counts, short from, short to,
					short* before, short* here);		// ROM 0x000ccd9c XProjectionSetPtVals
// A run narrowed to where the ink crosses least, or dropped when even
// that is more than once.
void		CheckXProjection(List* runs, ListEntry* cursor, const FPoint* points,
					const XProjection* proj);			// ROM 0x000ccf6c CheckXProjection
void		ProcessXProjection(const RosStroke* stroke, List* runs,
					const XProjection* proj);			// ROM 0x000ccf24 ProcessXProjection

// The surviving runs turned into break points.
void		DefineBreakPoints(const RosStroke* stroke, List* runs, StrokeBreaks* out,
					const StrokeDelta* deltas);			// ROM 0x000cc100 DefineBreakPoints

// All four passes: where this stroke should be cut.  The caller frees
// `out->fAt`.
void		FindStrokeFragments(RosStroke* stroke, StrokeBreaks* out);	// ROM 0x000cd4cc FindStrokeFragments

// A stretch of a stroke's points as a stroke of its own, marked as a
// piece (`fFragment`) and as running on (`fJoinsNext`) where it does.
RosStroke*	StrokeSubsection(const RosStroke* stroke, short from,
					short count);						// ROM 0x000cd0cc StrokeSubsection

// ... and the whole thing: the stroke cut into pieces, answered as a
// stroke list.  A stroke of no points answers an empty list.
RosStrokeList*	FragmentStroke(RosStroke* stroke, const Fixed* run);	// ROM 0x000cc638 FragmentStroke

#endif	/* __FRAGMENT_H */
