// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> gFragmentParams@0x0c100de4:i32:6 gXProjectionParams@0x0c100dfc:i16:2 -o src/recognition/FragmentTables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const int	gFragmentParams[6];
extern const short	gXProjectionParams[2];

// ROM 0x0c100de4 (unnamed) - gFragmentParams
const int	gFragmentParams[6] = {
	  9830,  49152,  26214, -32768,  19660,  19660,
};

// ROM 0x0c100dfc (unnamed) - gXProjectionParams
const short	gXProjectionParams[2] = {
	1, 8,
};
