/*
	File:		recognition/GeoContext.h

	Contains:	What the geometry between two letters costs.

				This is the part of the lexical search that looks at
				how two pieces of writing *sit against each other*
				rather than at what they look like on their own.  It is
				what tells `rn` from `m`: the classifier sees much the
				same ink either way, and only the two boxes' sizes and
				places say which reading the writer meant.

				The engine keeps a nominal drawing of every character -
				sixteen numbers apiece in `rosCharParams`, all as
				fractions of the cap height: where its bottom sits above
				the baseline, how tall it is, how wide, how much room it
				wants before and after it, and how big its smallest
				stroke ought to be when it is written in one stroke and
				when it is written in more.  Given two character codes
				and the two segments they would be read from, it lays
				the two nominal boxes side by side, lays the two
				observed boxes beside each other likewise, brings both
				pairs to the same size and place, and measures the nine
				ways they differ.

				Those nine residuals are then put through a symmetric
				nine-by-nine matrix (`kGeoWeights`) as a **quadratic
				form** - `sum over i of v[i] times sum over j of
				M[i][j] v[j]` - which is a Mahalanobis distance: the
				residuals are not simply added up, they are weighed
				against each other, so that (say) both boxes being a
				little too tall costs much less than one being too tall
				and the other too short.  The answer is scaled by
				`RosCommonInfo::fGeoWeight` and handed back as a score
				in the engine's own units, which are negative natural
				logarithms times five hundred.

				Because `SearchDoVStepFromNode` asks the same question
				over and over for the same pair of segments, the answers
				are cached: a hundred (first character, second
				character) pairs, thrown away whenever the pair of
				segments changes, which the search also does by hand
				through `GeoContextClearCache`.

	Reconstructed from the MP2x00 US ROM (0x000d9ad4-0x000daee8); each
	function cites its origin.
*/

#ifndef __GEOCONTEXT_H
#define __GEOCONTEXT_H

#ifndef __NEWTONTYPES_H
#include "NewtonTypes.h"
#endif
#include "FixedGeometry.h"

struct RosSegment;

// The sixteen numbers `rosCharParams` holds for each character code,
// all as fractions of the cap height.  The first seven are the nominal
// drawing of the character and the next seven are what each measurement
// of it is worth; the last two are not read here.
const long	kGeoBottom			= 0;	// its bottom, above the baseline
const long	kGeoHeight			= 1;	// ... and how tall it is
const long	kGeoWidth			= 2;	// how wide
const long	kGeoGapBefore		= 3;	// the room it wants before it
const long	kGeoGapAfter		= 4;	// ... and after it
const long	kGeoStrokeOne		= 5;	// its smallest stroke, written in one
const long	kGeoStrokeMany		= 6;	// ... and written in more than one
const long	kGeoWeightBottom	= 7;
const long	kGeoWeightTop		= 8;
const long	kGeoWeightWidth		= 9;
const long	kGeoWeightGapBefore	= 10;
const long	kGeoWeightGapAfter	= 11;
const long	kGeoWeightStrokeOne	= 12;
const long	kGeoWeightStrokeMany = 13;

// The nine things measured, in the order the weight matrix wants them.
const long	kGeoBottom1		= 0;
const long	kGeoBottom2		= 1;
const long	kGeoTop1		= 2;
const long	kGeoTop2		= 3;
const long	kGeoWidth1		= 4;
const long	kGeoWidth2		= 5;
const long	kGeoGap			= 6;	// between the two, when they are neighbours
const long	kGeoStroke1		= 7;
const long	kGeoStroke2		= 8;
const long	kGeoMeasurements = 9;

// The quadratic form the nine are weighed through: symmetric, so it is
// a covariance and this is a Mahalanobis distance.
// GeoTables.cpp, generated by analysis/romtable.py
extern const int	kGeoWeights[81];			// ROM 0x003714d0 (unnamed)

// One piece of writing as the geometry sees it.  `GeoContextAux1` fills
// two of these out of the two segments and brings them to a common size
// and place; the y values are turned over, so that up is positive as it
// is in the nominal drawing, and everything is divided by 64 first so
// that the sums below cannot overflow a 16.16 number.
struct GeoBox
{
	Fixed		fWidth;				// +0x00  right - left
	Fixed		fSmallestStroke;	// +0x04  the segment's own
	Fixed		fBottom;			// +0x08  -bounds.bottom
	Fixed		fTop;				// +0x0c  -bounds.top
	Fixed		fLeft;				// +0x10
	Fixed		fRight;				// +0x14
};

// The two boxes, and the cache of answers about the pair of segments
// they were made from.  All of it is allocated once and kept.
extern GeoBox*		gGeoBox1;			// ROM 0x0c100e1c (unnamed)
extern GeoBox*		gGeoBox2;			// ROM 0x0c100e20 (unnamed)
extern UByte*		gGeoCacheChar1;		// ROM 0x0c100e24 (unnamed)
extern UByte*		gGeoCacheChar2;		// ROM 0x0c100e28 (unnamed)
extern short*		gGeoCacheScore;		// ROM 0x0c100e2c (unnamed)
extern long			gGeoCacheCount;		// ROM 0x0c100e0c (unnamed)
// what the cache is for, and how it has been doing
extern RosSegment*	gGeoCacheSeg1;		// ROM 0x0c100e30 (unnamed)
extern RosSegment*	gGeoCacheSeg2;		// ROM 0x0c100e34 (unnamed)
extern long			gGeoCacheHits;		// ROM 0x0c100e10 (unnamed)
extern long			gGeoCacheMisses;	// ROM 0x0c100e14 (unnamed)
extern long			gGeoCacheHighWater;	// ROM 0x0c100e18 (unnamed)

// How many answers the cache holds.
const long	kGeoCacheSize = 100;

// The cache made and given back.  `GeoCacheAllocate` does nothing if it
// has been made already, and gives back whatever it managed before a
// failure throws.
void	GeoCacheAllocate(void);							// ROM 0x000d9ad4 GeoCacheAllocate
void	GeoCacheDeallocate(void);						// ROM 0x000d9c44 GeoCacheDeallocate
// ... and emptied, which the search does whenever it moves to another
// pair of segments.
void	GeoContextClearCache(void);						// ROM 0x000d9cc8 GeoContextClearCache
void	GeoCQuiesence(void);							// ROM 0x000d9ce4 GeoCQuiesence

// What it costs to read `now` out of `nowSeg` with `before` out of
// `beforeSeg` in front of it.  Either character may be nought, meaning
// the start or the end of the word, and `acrossWords` says the two are
// in different words.  A character of 0x1f is the engine's own
// stand-in and costs four times as much.
long	GeoContextPenalty(UByte before, RosSegment* beforeSeg, UByte now,
				RosSegment* nowSeg, long acrossWords);	// ROM 0x000d9ce8 GeoContextPenalty

// The two halves of it: the observed boxes brought to a common size and
// place, and the nine measurements weighed against the nominal drawing.
void	GeoContextAux1(const FRect* bounds1, const FRect* bounds2,
				Fixed smallest1, Fixed smallest2);		// ROM 0x000da19c GeoContextAux1
long	GeoContextAux2(ULong char1, ULong char2, long strokes1, long strokes2,
				long oneCharacter, long adjacency);		// ROM 0x000da600 GeoContextAux2

#endif	/* __GEOCONTEXT_H */
