// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> kGeoWeights@0x003714d0:i32:81 -o src/recognition/GeoTables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const int	kGeoWeights[81];

// ROM 0x003714d0 (unnamed) - kGeoWeights
const int	kGeoWeights[81] = {
	541982, 428146, 369360, 415236, -66453, -55967, -79953,  52887,
	 -4128, 428146, 547225, 406847, 370081, -59965, -73465, -92995,
	 -1638,  50987, 369360, 406847, 517341, 426246,  63373,  52559,
	 82444, -45416,   6356, 415236, 370081, 426246, 518651,  42598,
	 57475,  63176,   3866, -48496, -66453, -59965,  63373,  42598,
	186712,  90963, 178323, -37486,  11010, -55967, -73465,  52559,
	 57475,  90963, 191496, 171769,   7536, -38928, -79953, -92995,
	 82444,  63176, 178323, 171769, 327548,   6291,  11206,  52887,
	 -1638, -45416,   3866, -37486,   7536,   6291, 112525,  -5832,
	 -4128,  50987,   6356, -48496,  11010, -38928,  11206,  -5832,
	117571,
};
