// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> AckNodeSizeTab:u8:4 -o src/recognition/LELangTables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const unsigned char	AckNodeSizeTab[4];

// ROM 0x00371e94 AckNodeSizeTab
const unsigned char	AckNodeSizeTab[4] = {
	0x00, 0x00, 0x01, 0x03,
};
