// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> qdDepthShift@0x00380c31:u8:9 -o src/recognition/LiveInkerTables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const unsigned char	qdDepthShift[9];

// ROM 0x00380c31 (unnamed) - qdDepthShift
const unsigned char	qdDepthShift[9] = {
	0x00, 0x03, 0x02, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00,
};
