// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> _2C16:i32:8 -o src/recognition/OrthoTables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const int	_2C16[8];

// ROM 0x0037415c _2C16
const int	_2C16[8] = {
	 32926,  34242,  37155,  42390,  51652,  69512, 112882, 334308,
};
