// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> charWeights:u8:26 -o src/recognition/RandomWordTables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const unsigned char	charWeights[26];

// ROM 0x0c101634 charWeights
const unsigned char	charWeights[26] = {
	0x04, 0x02, 0x03, 0x03, 0x04, 0x02, 0x03, 0x04, 0x04, 0x02, 0x02, 0x03, 0x03, 0x04, 0x04, 0x03,
	0x02, 0x04, 0x04, 0x04, 0x03, 0x02, 0x02, 0x02, 0x03, 0x02,
};
