/*
	File:		recognition/Render.h

	Contains:	The handwriting engine's own renderer: how a piece of
				writing is drawn into a small grey grid for the
				classifier to look at.

				It is two objects.  A `RenderRec` is a **one-bit
				bitmap** with a pen: `RenderLine` draws into it with
				Bresenham, and the pen is a set of eight pre-shifted
				stencils, one per position within a byte, so that
				putting the pen down is an OR and never a shift.  A
				`RenderAA` is one of those at two, four or eight times
				the size, with a byte-per-pixel grid beside it;
				`RenderAAFlush` counts the set sub-pixels of each cell
				into that grid.

				So the anti-aliasing is done by *drawing big and
				counting*, and the counting is a table lookup: `rat0`
				to `rat3` answer, for each of the 256 byte values, how
				much each output cell of that byte gains.  A set
				sub-pixel is worth 15, so a four-by-four block comes to
				240 and a byte still holds it.

				The image patternizer asks for a 14 x 14 grid at scale
				four, which means a 56 x 56 one-bit bitmap and a pen
				four sub-pixels across.

	Reconstructed from the MP2x00 US ROM (0x001a69b0-0x001a7100); each
	function cites its origin.
*/

#ifndef __RENDER_H
#define __RENDER_H

#ifndef __NEWTONTYPES_H
#include "NewtonTypes.h"
#endif


// One position of the pen within a byte: a little bitmap to OR in.
struct RenderStencil
{
	long			fByteWidth;		// +0x00
	long			fRows;			// +0x04
	const UByte*	fBits;			// +0x08
};

// A one-bit bitmap with a pen.  The ROM's object is 0x20 bytes.
struct RenderRec
{
	UByte*			fBits;			// +0x00
	long			fWidth;			// +0x04  in pixels
	long			fHeight;		// +0x08
	long			fRowBytes;		// +0x0c  (fWidth + 7) / 8
	long			fSize;			// +0x10  fRowBytes * fHeight
	long			fDotSize;		// +0x14  how wide the pen is
	long			fDotOffset;		// +0x18  half of it: what a point is moved by
	const RenderStencil*	fStencils;	// +0x1c  eight of them
};

// That bitmap at a multiple of the size, with the grey grid it is
// counted into.  The ROM's object is 0x18 bytes.
struct RenderAA
{
	UByte*			fPixels;		// +0x00  fWidth * fHeight bytes
	long			fWidth;			// +0x04
	long			fHeight;		// +0x08
	long			fScale;			// +0x0c  1 << fShift
	long			fShift;		 	// +0x10  0 to 3
	RenderRec*		fRec;			// +0x14
};

// What a set sub-pixel is worth in the counted grid.
const long	kRenderSubPixelWeight	= 15;
const long	kRenderMaxShift			= 3;

// The tables (`RenderTables.cpp`, generated by `analysis/render.py`).
extern const RenderStencil	raw1[8];					// ROM 0x0036e71c raw1
extern const RenderStencil	raw2[8];					// ROM 0x0036e7bc raw2
extern const RenderStencil	raw4[8];					// ROM 0x0036e868 raw4
// Which set a pen of each size uses; three of the six are nil.
extern const RenderStencil* const	kDotStencils[6];	// ROM 0x0036f0d0 xDotStencils
// For each scale, what each output cell of a byte gains.
extern const UByte	rat0[256][8];						// ROM 0x0036bfcc rat0
extern const UByte	rat1[256][4];						// ROM 0x0036c7d0 rat1
extern const UByte	rat2[256][2];						// ROM 0x0036cfd4 rat2
extern const UByte	rat3[256][1];						// ROM 0x0036d7d8 rat3
extern const UByte* const	kAATables[4];				// ROM 0x0036dbdc AAtables


// A one-bit bitmap of that size, cleared, with a pen one pixel across.
RenderRec*	RenderRecCreate(long width, long height);	// ROM 0x001a6dd8 RenderRecCreate
RenderRec*	RenderRecNew(void);							// ROM 0x001a6d40 RenderRecNew
void	RenderRecDestroy(RenderRec* rec);				// ROM 0x001a6da8 RenderRecDestroy
// Every bit cleared.
void	RenderClear(RenderRec* rec);					// ROM 0x001a70d8 RenderClear
// The pen, by how many pixels across it is.
void	RenderSetDotSize(RenderRec* rec, long size);	// ROM 0x001a70b4 RenderSetDotSize
// A line, with the pen put down at every step.  Anything that would
// fall outside the bitmap draws nothing at all.
void	RenderLine(RenderRec* rec, long x0, long y0, long x1, long y1);	// ROM 0x001a6edc RenderLine

// A grid of that size, with a one-bit bitmap `1 << shift` times as
// wide and tall behind it and a pen that size across.
RenderAA*	RenderAACreate(long width, long height, long shift);	// ROM 0x001a6bb0 RenderAACreate
RenderAA*	RenderAANew(void);							// ROM 0x001a6b18 RenderAANew
void	RenderAADestroy(RenderAA* aa);					// ROM 0x001a6b78 RenderAADestroy
// The sub-pixels counted into the grid.
void	RenderAAFlush(RenderAA* aa);					// ROM 0x001a69b0 RenderAAFlush

#endif	/* __RENDER_H */
