// Generated by tools/newton-rom/analysis/romdicts.py; do not edit.
//   python tools/newton-rom/analysis/romdicts.py <build_dir> -o src/recognition
// The lexicons built into the 2.1 (717006) ROM, as
// InitROMDictionaryData (ROM 0x0019b0d4) writes their addresses into
// gROMDictionaryData (ROM 0x0c106840).  A slot the ROM leaves alone has no
// dictionary; the name is the debug symbol on the data.

#include "ROMDictionaryData.h"

// ROM 0x0c106840 gROMDictionaryData
const ROMDictionaryEntry	gROMDictionaryTable[kROMDictionaryCount] =
{
	{ 0x00685508, "gEnum80Letters" },        // 0
	{ 0x0071a8e4, "gSymb80Symbols" },        // 1
	{ 0x0070a788, "gEnum81IAWordList" },     // 2
	{ 0x006853dc, "gEnum80DaysMonths" },     // 3
	{ 0x00685500, "gEnum80Empty" },          // 4
	{ 0x00685500, "gEnum80Empty" },          // 5
	{ 0x00685500, "gEnum80Empty" },          // 6
	{ 0x0070d914, "gLex8date" },             // 7
	{ 0x0070d914, "gLex8date" },             // 8
	{ 0x00685500, "gEnum80Empty" },          // 9
	{ 0x00685500, "gEnum80Empty" },          // 10
	{ 0x00685500, "gEnum80Empty" },          // 11
	{ 0x00685500, "gEnum80Empty" },          // 12
	{ 0x00685500, "gEnum80Empty" },          // 13
	{ 0x00685500, "gEnum80Empty" },          // 14
	{ 0x00718dac, "gLex8phone" },            // 15
	{ 0x00719d64, "gLex8time" },             // 16
	{ 0x0069943c, "gEnum80sh_words" },       // 17
	{ 0x00685500, "gEnum80Empty" },          // 18
	{ 0x0070ac74, "gEnum81sh_common_freq_fwd" },// 19
	{ 0x00685500, "gEnum80Empty" },          // 20
	{ 0x00685500, "gEnum80Empty" },          // 21
	{ 0x00692a4c, "gEnum80sh_first" },       // 22
	{ 0x0069943c, "gEnum80sh_words" },       // 23
	{ 0x00697388, "gEnum80sh_honorific" },   // 24
	{ 0x0069943c, "gEnum80sh_words" },       // 25
	{ 0x0069943c, "gEnum80sh_words" },       // 26
	{ 0x0069943c, "gEnum80sh_words" },       // 27
	{ 0x0070ab14, "gEnum81sh_address" },     // 28
	{ 0x0068cc50, "gEnum80sh_city" },        // 29
	{ 0x00691e40, "gEnum80sh_country" },     // 30
	{ 0x00697ef4, "gEnum80sh_state" },       // 31
	{ 0x00685544, "gEnum80loc_words" },      // 32
	{ 0x00685500, "gEnum80Empty" },          // 33
	{ 0x00685500, "gEnum80Empty" },          // 34
	{ 0x00685500, "gEnum80Empty" },          // 35
	{ 0x00685500, "gEnum80Empty" },          // 36
	{ 0x00685500, "gEnum80Empty" },          // 37
	{ 0x00685500, "gEnum80Empty" },          // 38
	{ 0x00685500, "gEnum80Empty" },          // 39
	{ 0x00685500, "gEnum80Empty" },          // 40
	{ 0x00685500, "gEnum80Empty" },          // 41
	{ 0x00685544, "gEnum80loc_words" },      // 42
	{ 0x00685500, "gEnum80Empty" },          // 43
	{ 0x00685500, "gEnum80Empty" },          // 44
	{ 0x00685544, "gEnum80loc_words" },      // 45
	{ 0x00685544, "gEnum80loc_words" },      // 46
	{ 0x00685500, "gEnum80Empty" },          // 47
	{ 0x00685544, "gEnum80loc_words" },      // 48
	{ 0x00685500, "gEnum80Empty" },          // 49
	{ 0x00685500, "gEnum80Empty" },          // 50
	{ 0x00685500, "gEnum80Empty" },          // 51
	{ 0x00685500, "gEnum80Empty" },          // 52
	{ 0x00685500, "gEnum80Empty" },          // 53
	{ 0x00685500, "gEnum80Empty" },          // 54
	{ 0x00685500, "gEnum80Empty" },          // 55
	{ 0x00685500, "gEnum80Empty" },          // 56
	{ 0x00685500, "gEnum80Empty" },          // 57
	{ 0x00685544, "gEnum80loc_words" },      // 58
	{ 0x00685500, "gEnum80Empty" },          // 59
	{ 0x00685500, "gEnum80Empty" },          // 60
	{ 0x00685544, "gEnum80loc_words" },      // 61
	{ 0x00685544, "gEnum80loc_words" },      // 62
	{ 0x00685500, "gEnum80Empty" },          // 63
	{ 0x00685544, "gEnum80loc_words" },      // 64
	{ 0x00685500, "gEnum80Empty" },          // 65
	{ 0x00685500, "gEnum80Empty" },          // 66
	{ 0x00685500, "gEnum80Empty" },          // 67
	{ 0x00685500, "gEnum80Empty" },          // 68
	{ 0x00685500, "gEnum80Empty" },          // 69
	{ 0x00685500, "gEnum80Empty" },          // 70
	{ 0x00685500, "gEnum80Empty" },          // 71
	{ 0x00685500, "gEnum80Empty" },          // 72
	{ 0x00685500, "gEnum80Empty" },          // 73
	{ 0x00685544, "gEnum80loc_words" },      // 74
	{ 0x00685500, "gEnum80Empty" },          // 75
	{ 0x00685500, "gEnum80Empty" },          // 76
	{ 0x00685544, "gEnum80loc_words" },      // 77
	{ 0x00685544, "gEnum80loc_words" },      // 78
	{ 0x00685500, "gEnum80Empty" },          // 79
	{ 0x00708fc4, "gEnum80us_words" },       // 80
	{ 0x00685500, "gEnum80Empty" },          // 81
	{ 0x00685500, "gEnum80Empty" },          // 82
	{ 0x00685500, "gEnum80Empty" },          // 83
	{ 0x00685500, "gEnum80Empty" },          // 84
	{ 0x00685500, "gEnum80Empty" },          // 85
	{ 0x00685500, "gEnum80Empty" },          // 86
	{ 0x00685500, "gEnum80Empty" },          // 87
	{ 0x00685500, "gEnum80Empty" },          // 88
	{ 0x00685500, "gEnum80Empty" },          // 89
	{ 0x0068cc50, "gEnum80sh_city" },        // 90
	{ 0x00685500, "gEnum80Empty" },          // 91
	{ 0x00685500, "gEnum80Empty" },          // 92
	{ 0x00697ef4, "gEnum80sh_state" },       // 93
	{ 0x00697ef4, "gEnum80sh_state" },       // 94
	{ 0x00685500, "gEnum80Empty" },          // 95
	{ 0x0069943c, "gEnum80sh_words" },       // 96
	{ 0x00685500, "gEnum80Empty" },          // 97
	{ 0x00697388, "gEnum80sh_honorific" },   // 98
	{ 0x0069943c, "gEnum80sh_words" },       // 99
	{ 0x0069943c, "gEnum80sh_words" },       // 100
	{ 0x00685544, "gEnum80loc_words" },      // 101
	{ 0x00685544, "gEnum80loc_words" },      // 102
	{ 0x00685544, "gEnum80loc_words" },      // 103
	{ 0x0069943c, "gEnum80sh_words" },       // 104
	{ 0x0070c220, "gLex8FunnyPhone" },       // 105
	{ 0x0070c538, "gLex8WorldPhone" },       // 106
	{ 0x00719b4c, "gLex8postcode" },         // 107
	{ 0x0071a7a4, "gLex8wordlike" },         // 108
	{ 0x0070c63c, "gLex8calcsheet" },        // 109
	{ 0x0070d8e8, "gLex8closequote" },       // 110
	{ 0x00711c9c, "gLex8daymonth" },         // 111
	{ 0x00711f90, "gLex8endpunct" },         // 112
	{ 0x00711fd0, "gLex8hyphen" },           // 113
	{ 0x0070c3c4, "gLex8IDNumbers" },        // 114
	{ 0x00711ff4, "gLex8money" },            // 115
	{ 0x007173f0, "gLex8numbers" },          // 116
	{ 0x00718d7c, "gLex8openquote" },        // 117
	{ 0x00719c4c, "gLex8ssn" },              // 118
	{ 0x00719c9c, "gLex8symbolsPart1" },     // 119
	{ 0x00714d00, "gLex8moneyCFr" },         // 120
	{ 0x007180b8, "gLex8numbersCFr" },       // 121
	{ 0x0070881c, "gEnum80suffixes" },       // 122
	{ 0x0068c948, "gEnum80prefixes" },       // 123
	{ 0x00685500, "gEnum80Empty" },          // 124
	{ 0x00685500, "gEnum80Empty" },          // 125
	{ 0x0071a864, "gSymb80SwedishSymbols" }, // 126
	{ 0x006f7d60, "gEnum80spellcheck_ignore" },// 127
	{ 0x00719d0c, "gLex8symbolsPart2" },     // 128
};
