/*
	File:		recognition/ROMDictionaryData.h

	Contains:	The lexicons built into the ROM, and how a dictionary is
				opened over one of them.

				The ROM's word data is not one table: it is 129 separate
				blobs scattered through the ROM - the letters, the word
				lists, the days and months, the phone and date and money
				lexicons, the symbols - each beginning with a big-endian
				size word and then the Airus trie itself.  A table of
				pointers to them, `gROMDictionaryData`, lives in RAM and
				is filled in at boot by `InitROMDictionaryData`, which is
				a long straight line of loads and stores with one pair per
				lexicon.  A dictionary frame's `romDictID` is the slot of
				that table its data is in.

				The table is therefore not in the ROM's bytes to be read;
				it has to be recovered from the code that writes it, which
				is what `tools/newton-rom/analysis/romdicts.py` does -
				`ROMDictionaryTable.cpp` is what it wrote.

				DEVIATION: the addresses the ROM stores are the machine's
				own; here they are offsets into the imported ROM image
				(`frames/ROMImport.h`), so `InitROMDictionaryData` adds
				the image's base to each and a host that has imported no
				image gets no dictionaries.

	Reconstructed from the MP2x00 US ROM (0x0019b078-0x0019b380); each
	function cites its origin.
*/

#ifndef __ROMDICTIONARYDATA_H
#define __ROMDICTIONARYDATA_H

#ifndef __NEWTON_H
#include "Newton.h"
#endif
#include "NewtonMemory.h"

// One slot of the table: where the lexicon is in the ROM, and the debug
// symbol on it (kept so that a dictionary can be named in a test or a
// report; the ROM has only the address).
struct ROMDictionaryEntry
{
	ULong		fAddress;
	const char*	fName;
};

const long	kROMDictionaryCount = 129;

// ROMDictionaryTable.cpp, generated by analysis/romdicts.py
extern const ROMDictionaryEntry	gROMDictionaryTable[kROMDictionaryCount];

// ROM 0x0c106840 gROMDictionaryData - the addresses, as the boot leaves them
extern const UByte*	gROMDictionaryData[kROMDictionaryCount];

void	InitROMDictionaryData(void);					// ROM 0x0019b0d4 InitROMDictionaryData__Fv

// The bytes of a lexicon: `size` is the size word it begins with, and the
// answer is what follows it - which is what a dictionary is opened over.
// nil, and a size of 0, for a slot with nothing in it.
const void*	GetROMDictionaryData(ULong id, ULong* size);	// ROM 0x0019b078 GetROMDictionaryData__FUlPUl

// ... and the dictionary itself, with `id` as its dictID.
Handle	GetROMDictionary(ULong id);						// ROM 0x0019b09c GetROMDictionary__FUl

#endif	/* __ROMDICTIONARYDATA_H */
