// Generated by tools/newton-rom/analysis/bigrammar.py; do not edit.
//   build/venv/Scripts/python tools/newton-rom/analysis/bigrammar.py build/MP2x00US -o src/recognition/ROMGrammar.cpp
// The handwriting engine's bigram grammar: the eight grammars a word is
// read against, from the 2.1 (717006) ROM at the addresses cited.
//
// A slice is a kind of word - a lexicon out of gROMDictionaryData, a score
// of its own, and a score for every kind that may follow it.  0x7ffe means
// never.

#include "RosEngine.h"

/*--------------------------------------------------------------------
	General: 25 kinds of word.
--------------------------------------------------------------------*/
extern const BiGSlice	BiGSSharedAttrCommon1;
extern const BiGSlice	BiGSendpunct1;
extern const BiGSlice	BiGSclosequote1;
extern const BiGSlice	BiGShyphen1;
extern const BiGSlice	BiGSSuffixes1;
extern const BiGSlice	BiGSSharedCommons1;
extern const BiGSlice	BiGSSpellCheckIgnore1;
extern const BiGSlice	BiGSuser1;
extern const BiGSlice	BiGSnull11;
extern const BiGSlice	BiGSnull21;
extern const BiGSlice	BiGSnull31;
extern const BiGSlice	BiGSnull41;
extern const BiGSlice	BiGSnull51;
extern const BiGSlice	BiGSnumbers1;
extern const BiGSlice	BiGSPrefixes1;
extern const BiGSlice	BiGSmoney1;
extern const BiGSlice	BiGSTimeR_US_B_C_X1;
extern const BiGSlice	BiGSDateR_US1;
extern const BiGSlice	BiGSPhoneR_US_C1;
extern const BiGSlice	BiGSPostalCode1;
extern const BiGSlice	BiGSIDNumbers1;
extern const BiGSlice	BiGSopenquote1;
extern const BiGSlice	BiGSwordlike1;
extern const BiGSlice	BiGSLexicalSymbols11;
extern const BiGSlice	BiGSLexicalSymbols21;

// ROM 0x00365e5c BiSLSharedAttrCommon1
extern const BiGSlice* const	BiSLSharedAttrCommon1[14] = {
	&BiGSendpunct1, &BiGSclosequote1, &BiGShyphen1,
	&BiGSSuffixes1, &BiGSSharedAttrCommon1, &BiGSSharedCommons1,
	&BiGSSpellCheckIgnore1, &BiGSuser1, &BiGSnull11,
	&BiGSnull21, &BiGSnull31, &BiGSnull41,
	&BiGSnull51, &BiGSnumbers1
};
// ROM 0x00365e94 BiSPSharedAttrCommon1
extern const short	BiSPSharedAttrCommon1[14] = { 255, 601, 693, 804, 1039, 1039, 1151, 1151, 1295, 1295, 1295, 1295, 1295, 1497 };

// ROM 0x00365eb0 BiSLendpunct1
extern const BiGSlice* const	BiSLendpunct1[2] = {
	&BiGSclosequote1, &BiGSendpunct1
};
// ROM 0x00365eb8 BiSPendpunct1
extern const short	BiSPendpunct1[2] = { 346, 346 };

// ROM 0x00365ebc BiSLclosequote1
extern const BiGSlice* const	BiSLclosequote1[2] = {
	&BiGSclosequote1, &BiGSendpunct1
};
// ROM 0x00365ec4 BiSPclosequote1
extern const short	BiSPclosequote1[2] = { 346, 346 };

// ROM 0x00365ec8 BiSLhyphen1
extern const BiGSlice* const	BiSLhyphen1[14] = {
	&BiGSSharedAttrCommon1, &BiGSSharedCommons1, &BiGSSpellCheckIgnore1,
	&BiGSPrefixes1, &BiGSuser1, &BiGSnull11,
	&BiGSnull21, &BiGSnull31, &BiGSnull41,
	&BiGSnull51, &BiGSwordlike1, &BiGSnumbers1,
	&BiGSmoney1, &BiGSIDNumbers1
};
// ROM 0x00365f00 BiSPhyphen1
extern const short	BiSPhyphen1[14] = { 458, 524, 804, 601, 458, 601, 601, 601, 601, 601, 948, 693, 804, 1151 };

// ROM 0x00365f1c BiSLSuffixes1
extern const BiGSlice* const	BiSLSuffixes1[3] = {
	&BiGSSuffixes1, &BiGSclosequote1, &BiGSendpunct1
};
// ROM 0x00365f28 BiSPSuffixes1
extern const short	BiSPSuffixes1[3] = { 804, 601, 601 };

// ROM 0x00365f30 BiSLSharedCommons1
extern const BiGSlice* const	BiSLSharedCommons1[14] = {
	&BiGSendpunct1, &BiGSclosequote1, &BiGShyphen1,
	&BiGSSuffixes1, &BiGSSharedAttrCommon1, &BiGSSharedCommons1,
	&BiGSSpellCheckIgnore1, &BiGSuser1, &BiGSnull11,
	&BiGSnull21, &BiGSnull31, &BiGSnull41,
	&BiGSnull51, &BiGSnumbers1
};
// ROM 0x00365f68 BiSPSharedCommons1
extern const short	BiSPSharedCommons1[14] = { 255, 601, 693, 693, 1039, 1039, 1151, 1151, 1295, 1295, 1295, 1295, 1295, 1497 };

// ROM 0x00365f84 BiSLSpellCheckIgnore1
extern const BiGSlice* const	BiSLSpellCheckIgnore1[14] = {
	&BiGSendpunct1, &BiGSclosequote1, &BiGShyphen1,
	&BiGSSuffixes1, &BiGSSharedAttrCommon1, &BiGSSharedCommons1,
	&BiGSSpellCheckIgnore1, &BiGSuser1, &BiGSnull11,
	&BiGSnull21, &BiGSnull31, &BiGSnull41,
	&BiGSnull51, &BiGSnumbers1
};
// ROM 0x00365fbc BiSPSpellCheckIgnore1
extern const short	BiSPSpellCheckIgnore1[14] = { 255, 601, 693, 693, 1039, 1039, 1151, 1151, 1295, 1295, 1295, 1295, 1295, 1497 };

// ROM 0x00365fd8 BiSLuser1
extern const BiGSlice* const	BiSLuser1[14] = {
	&BiGSendpunct1, &BiGSclosequote1, &BiGShyphen1,
	&BiGSSuffixes1, &BiGSSharedAttrCommon1, &BiGSSharedCommons1,
	&BiGSSpellCheckIgnore1, &BiGSuser1, &BiGSnull11,
	&BiGSnull21, &BiGSnull31, &BiGSnull41,
	&BiGSnull51, &BiGSnumbers1
};
// ROM 0x00366010 BiSPuser1
extern const short	BiSPuser1[14] = { 255, 601, 693, 804, 1039, 1039, 1151, 1151, 1295, 1295, 1295, 1295, 1295, 1497 };

// ROM 0x0036602c BiSLnull11
extern const BiGSlice* const	BiSLnull11[14] = {
	&BiGSendpunct1, &BiGSclosequote1, &BiGShyphen1,
	&BiGSSuffixes1, &BiGSSharedAttrCommon1, &BiGSSharedCommons1,
	&BiGSSpellCheckIgnore1, &BiGSuser1, &BiGSnull11,
	&BiGSnull21, &BiGSnull31, &BiGSnull41,
	&BiGSnull51, &BiGSnumbers1
};
// ROM 0x00366064 BiSPnull11
extern const short	BiSPnull11[14] = { 255, 601, 693, 804, 1039, 1039, 1151, 1151, 1295, 1295, 1295, 1295, 1295, 1497 };

// ROM 0x00366080 BiSLnull21
extern const BiGSlice* const	BiSLnull21[14] = {
	&BiGSendpunct1, &BiGSclosequote1, &BiGShyphen1,
	&BiGSSuffixes1, &BiGSSharedAttrCommon1, &BiGSSharedCommons1,
	&BiGSSpellCheckIgnore1, &BiGSuser1, &BiGSnull11,
	&BiGSnull21, &BiGSnull31, &BiGSnull41,
	&BiGSnull51, &BiGSnumbers1
};
// ROM 0x003660b8 BiSPnull21
extern const short	BiSPnull21[14] = { 255, 601, 693, 804, 1039, 1039, 1151, 1151, 1295, 1295, 1295, 1295, 1295, 1497 };

// ROM 0x003660d4 BiSLnull31
extern const BiGSlice* const	BiSLnull31[14] = {
	&BiGSendpunct1, &BiGSclosequote1, &BiGShyphen1,
	&BiGSSuffixes1, &BiGSSharedAttrCommon1, &BiGSSharedCommons1,
	&BiGSSpellCheckIgnore1, &BiGSuser1, &BiGSnull11,
	&BiGSnull21, &BiGSnull31, &BiGSnull41,
	&BiGSnull51, &BiGSnumbers1
};
// ROM 0x0036610c BiSPnull31
extern const short	BiSPnull31[14] = { 255, 601, 693, 804, 1039, 1039, 1151, 1151, 1295, 1295, 1295, 1295, 1295, 1497 };

// ROM 0x00366128 BiSLnull41
extern const BiGSlice* const	BiSLnull41[14] = {
	&BiGSendpunct1, &BiGSclosequote1, &BiGShyphen1,
	&BiGSSuffixes1, &BiGSSharedAttrCommon1, &BiGSSharedCommons1,
	&BiGSSpellCheckIgnore1, &BiGSuser1, &BiGSnull11,
	&BiGSnull21, &BiGSnull31, &BiGSnull41,
	&BiGSnull51, &BiGSnumbers1
};
// ROM 0x00366160 BiSPnull41
extern const short	BiSPnull41[14] = { 255, 601, 693, 804, 1039, 1039, 1151, 1151, 1295, 1295, 1295, 1295, 1295, 1497 };

// ROM 0x0036617c BiSLnull51
extern const BiGSlice* const	BiSLnull51[14] = {
	&BiGSendpunct1, &BiGSclosequote1, &BiGShyphen1,
	&BiGSSuffixes1, &BiGSSharedAttrCommon1, &BiGSSharedCommons1,
	&BiGSSpellCheckIgnore1, &BiGSuser1, &BiGSnull11,
	&BiGSnull21, &BiGSnull31, &BiGSnull41,
	&BiGSnull51, &BiGSnumbers1
};
// ROM 0x003661b4 BiSPnull51
extern const short	BiSPnull51[14] = { 255, 601, 693, 804, 1039, 1039, 1151, 1151, 1295, 1295, 1295, 1295, 1295, 1497 };

// ROM 0x003661d0 BiSLnumbers1
extern const BiGSlice* const	BiSLnumbers1[12] = {
	&BiGSSharedAttrCommon1, &BiGSSharedCommons1, &BiGSSpellCheckIgnore1,
	&BiGSuser1, &BiGSnull11, &BiGSnull21,
	&BiGSnull31, &BiGSnull41, &BiGSnull51,
	&BiGSendpunct1, &BiGSclosequote1, &BiGShyphen1
};
// ROM 0x00366200 BiSPnumbers1
extern const short	BiSPnumbers1[12] = { 1295, 1295, 1295, 1295, 1295, 1295, 1295, 1295, 1295, 458, 601, 804 };

// ROM 0x00366218 BiSLPrefixes1
extern const BiGSlice* const	BiSLPrefixes1[13] = {
	&BiGShyphen1, &BiGSSuffixes1, &BiGSSharedAttrCommon1,
	&BiGSSharedCommons1, &BiGSSpellCheckIgnore1, &BiGSPrefixes1,
	&BiGSuser1, &BiGSnull11, &BiGSnull21,
	&BiGSnull31, &BiGSnull41, &BiGSnull51,
	&BiGSnumbers1
};
// ROM 0x0036624c BiSPPrefixes1
extern const short	BiSPPrefixes1[13] = { 693, 1151, 948, 745, 1151, 948, 601, 745, 745, 745, 745, 745, 1497 };

// ROM 0x00366268 BiSLmoney1
extern const BiGSlice* const	BiSLmoney1[3] = {
	&BiGSendpunct1, &BiGSclosequote1, &BiGShyphen1
};
// ROM 0x00366274 BiSPmoney1
extern const short	BiSPmoney1[3] = { 601, 601, 804 };

// ROM 0x0036627c BiSLTimeR_US_B_C_X1
extern const BiGSlice* const	BiSLTimeR_US_B_C_X1[2] = {
	&BiGSendpunct1, &BiGSclosequote1
};
// ROM 0x00366284 BiSPTimeR_US_B_C_X1
extern const short	BiSPTimeR_US_B_C_X1[2] = { 601, 601 };

// ROM 0x00366288 BiSLDateR_US1
extern const BiGSlice* const	BiSLDateR_US1[2] = {
	&BiGSendpunct1, &BiGSclosequote1
};
// ROM 0x00366290 BiSPDateR_US1
extern const short	BiSPDateR_US1[2] = { 601, 601 };

// ROM 0x00366294 BiSLPhoneR_US_C1
extern const BiGSlice* const	BiSLPhoneR_US_C1[2] = {
	&BiGSendpunct1, &BiGSclosequote1
};
// ROM 0x0036629c BiSPPhoneR_US_C1
extern const short	BiSPPhoneR_US_C1[2] = { 601, 601 };

// ROM 0x003662a0 BiSLPostalCode1
extern const BiGSlice* const	BiSLPostalCode1[2] = {
	&BiGSendpunct1, &BiGSclosequote1
};
// ROM 0x003662a8 BiSPPostalCode1
extern const short	BiSPPostalCode1[2] = { 601, 601 };

// ROM 0x003662ac BiSLIDNumbers1
extern const BiGSlice* const	BiSLIDNumbers1[3] = {
	&BiGShyphen1, &BiGSendpunct1, &BiGSclosequote1
};
// ROM 0x003662b8 BiSPIDNumbers1
extern const short	BiSPIDNumbers1[3] = { 601, 601, 601 };

// ROM 0x003662c0 BiSLopenquote1
extern const BiGSlice* const	BiSLopenquote1[19] = {
	&BiGSSharedAttrCommon1, &BiGSSharedCommons1, &BiGSSpellCheckIgnore1,
	&BiGSPrefixes1, &BiGSuser1, &BiGSnull11,
	&BiGSnull21, &BiGSnull31, &BiGSnull41,
	&BiGSnull51, &BiGSwordlike1, &BiGSnumbers1,
	&BiGSmoney1, &BiGSTimeR_US_B_C_X1, &BiGSDateR_US1,
	&BiGSPhoneR_US_C1, &BiGSPostalCode1, &BiGSIDNumbers1,
	&BiGSopenquote1
};
// ROM 0x0036630c BiSPopenquote1
extern const short	BiSPopenquote1[19] = { 458, 524, 804, 601, 458, 601, 601, 601, 601, 601, 948, 693, 804, 804, 804, 804, 1151, 1151, 1295 };

// ROM 0x00366334 BiSLwordlike1
extern const BiGSlice* const	BiSLwordlike1[3] = {
	&BiGSendpunct1, &BiGSclosequote1, &BiGShyphen1
};
// ROM 0x00366340 BiSPwordlike1
extern const short	BiSPwordlike1[3] = { 255, 601, 948 };

// ROM 0x00366348 BiSLLexicalSymbols11
extern const BiGSlice* const	BiSLLexicalSymbols11[1] = {
	&BiGSLexicalSymbols21
};
// ROM 0x0036634c BiSPLexicalSymbols11
extern const short	BiSPLexicalSymbols11[1] = { 298 };

// ROM 0x00366350 BiSLLexicalSymbols21
extern const BiGSlice* const	BiSLLexicalSymbols21[1] = {
	&BiGSLexicalSymbols11
};
// ROM 0x00366354 BiSPLexicalSymbols21
extern const short	BiSPLexicalSymbols21[1] = { 298 };

// ROM 0x00366358 BiGSSharedAttrCommon1
extern const BiGSlice	BiGSSharedAttrCommon1 =
	{ "SharedAttrCommon", 19, 0, 0, 0, 0, 0x0000002f, 52, 0, 0, 346, 14, 14, BiSLSharedAttrCommon1, BiSPSharedAttrCommon1, 0xff };
// ROM 0x00366388 BiGSendpunct1
extern const BiGSlice	BiGSendpunct1 =
	{ "endpunct", 112, 32766, 0, 0, 0, 0x00000005, 0, 0, 0, 0, 2, 2, BiSLendpunct1, BiSPendpunct1, 0xff };
// ROM 0x003663b8 BiGSclosequote1
extern const BiGSlice	BiGSclosequote1 =
	{ "closequote", 110, 32766, 0, 0, 0, 0x00000000, 0, 0, 0, 0, 2, 2, BiSLclosequote1, BiSPclosequote1, 0xff };
// ROM 0x003663e8 BiGShyphen1
extern const BiGSlice	BiGShyphen1 =
	{ "hyphen", 113, 1497, 1497, 0, 0, 0x00000000, 0, 0, 0, 0, 14, 14, BiSLhyphen1, BiSPhyphen1, 0xff };
// ROM 0x00366418 BiGSSuffixes1
extern const BiGSlice	BiGSSuffixes1 =
	{ "Suffixes", 122, 32766, 0, 0, 0, 0x00000005, 111, 0, 0, 0, 3, 3, BiSLSuffixes1, BiSPSuffixes1, 0xff };
// ROM 0x00366448 BiGSSharedCommons1
extern const BiGSlice	BiGSSharedCommons1 =
	{ "SharedCommons", 17, 81, 0, 0, 0, 0x0000002f, 52, 0, 0, 346, 14, 14, BiSLSharedCommons1, BiSPSharedCommons1, 0xff };
// ROM 0x00366478 BiGSSpellCheckIgnore1
extern const BiGSlice	BiGSSpellCheckIgnore1 =
	{ "SpellCheckIgnore", 127, 178, 0, 0, 0, 0x0000002f, 52, 0, 0, 346, 14, 14, BiSLSpellCheckIgnore1, BiSPSpellCheckIgnore1, 0xff };
// ROM 0x003664a8 BiGSuser1
extern const BiGSlice	BiGSuser1 =
	{ "~user", 0, 0, 0, 0, 0, 0x0000002f, 52, 0, 0, 346, 14, 14, BiSLuser1, BiSPuser1, 0xff };
// ROM 0x003664d8 BiGSnull11
extern const BiGSlice	BiGSnull11 =
	{ "~null1", 0, 81, 0, 0, 0, 0x0000002f, 52, 0, 0, 346, 14, 14, BiSLnull11, BiSPnull11, 0xff };
// ROM 0x00366508 BiGSnull21
extern const BiGSlice	BiGSnull21 =
	{ "~null2", 0, 81, 0, 0, 0, 0x0000002f, 52, 0, 0, 346, 14, 14, BiSLnull21, BiSPnull21, 0xff };
// ROM 0x00366538 BiGSnull31
extern const BiGSlice	BiGSnull31 =
	{ "~null3", 0, 81, 0, 0, 0, 0x0000002f, 52, 0, 0, 346, 14, 14, BiSLnull31, BiSPnull31, 0xff };
// ROM 0x00366568 BiGSnull41
extern const BiGSlice	BiGSnull41 =
	{ "~null4", 0, 81, 0, 0, 0, 0x0000002f, 52, 0, 0, 346, 14, 14, BiSLnull41, BiSPnull41, 0xff };
// ROM 0x00366598 BiGSnull51
extern const BiGSlice	BiGSnull51 =
	{ "~null5", 0, 81, 0, 0, 0, 0x0000002f, 52, 0, 0, 346, 14, 14, BiSLnull51, BiSPnull51, 0xff };
// ROM 0x003665c8 BiGSnumbers1
extern const BiGSlice	BiGSnumbers1 =
	{ "numbers", 116, 111, 0, 0, 0, 0x00000000, 0, 0, 0, 0, 12, 12, BiSLnumbers1, BiSPnumbers1, 0xff };
// ROM 0x003665f8 BiGSPrefixes1
extern const BiGSlice	BiGSPrefixes1 =
	{ "Prefixes", 123, 143, 1497, 0, 0, 0x0000002f, 52, 0, 0, 346, 13, 13, BiSLPrefixes1, BiSPPrefixes1, 0xff };
// ROM 0x00366628 BiGSmoney1
extern const BiGSlice	BiGSmoney1 =
	{ "money", 115, 215, 0, 0, 0, 0x00000000, 0, 0, 0, 0, 3, 3, BiSLmoney1, BiSPmoney1, 0xff };
// ROM 0x00366658 BiGSTimeR_US_B_C_X1
extern const BiGSlice	BiGSTimeR_US_B_C_X1 =
	{ "TimeR_US_B_C_X", 16, 215, 0, 0, 0, 0x00000000, 0, 0, 0, 0, 2, 2, BiSLTimeR_US_B_C_X1, BiSPTimeR_US_B_C_X1, 0xff };
// ROM 0x00366688 BiGSDateR_US1
extern const BiGSlice	BiGSDateR_US1 =
	{ "DateR_US", 7, 215, 0, 0, 0, 0x00000000, 0, 0, 0, 0, 2, 2, BiSLDateR_US1, BiSPDateR_US1, 0xff };
// ROM 0x003666b8 BiGSPhoneR_US_C1
extern const BiGSlice	BiGSPhoneR_US_C1 =
	{ "PhoneR_US_C", 15, 215, 0, 0, 0, 0x00000000, 0, 0, 0, 0, 2, 2, BiSLPhoneR_US_C1, BiSPPhoneR_US_C1, 0xff };
// ROM 0x003666e8 BiGSPostalCode1
extern const BiGSlice	BiGSPostalCode1 =
	{ "PostalCode", 107, 346, 0, 178, 0, 0x00000000, 0, 0, 0, 0, 2, 2, BiSLPostalCode1, BiSPPostalCode1, 0xff };
// ROM 0x00366718 BiGSIDNumbers1
extern const BiGSlice	BiGSIDNumbers1 =
	{ "IDNumbers", 114, 399, 0, 192, 0, 0x00000004, 0, 111, 0, 111, 3, 3, BiSLIDNumbers1, BiSPIDNumbers1, 0xff };
// ROM 0x00366748 BiGSopenquote1
extern const BiGSlice	BiGSopenquote1 =
	{ "openquote", 117, 0, 1151, 0, 0, 0x00000000, 0, 0, 0, 0, 19, 19, BiSLopenquote1, BiSPopenquote1, 0xff };
// ROM 0x00366778 BiGSwordlike1
extern const BiGSlice	BiGSwordlike1 =
	{ "wordlike", 108, 255, 0, 215, 0, 0x00000015, 0, 0, 0, 0, 3, 3, BiSLwordlike1, BiSPwordlike1, 0x01 };
// ROM 0x003667a8 BiGSLexicalSymbols11
extern const BiGSlice	BiGSLexicalSymbols11 =
	{ "LexicalSymbols1", 119, 433, 0, 298, 0, 0x00000010, 0, 0, 0, 0, 1, 1, BiSLLexicalSymbols11, BiSPLexicalSymbols11, 0x00 };
// ROM 0x003667d8 BiGSLexicalSymbols21
extern const BiGSlice	BiGSLexicalSymbols21 =
	{ "LexicalSymbols2", 128, 433, 0, 298, 0, 0x00000010, 0, 0, 0, 0, 1, 1, BiSLLexicalSymbols21, BiSPLexicalSymbols21, 0x00 };

// ROM 0x00366808 BiGSLGeneral1
extern const BiGSlice* const	BiGSLGeneral1[25] = {
	&BiGSSharedAttrCommon1, &BiGSendpunct1, &BiGSclosequote1,
	&BiGShyphen1, &BiGSSuffixes1, &BiGSSharedCommons1,
	&BiGSSpellCheckIgnore1, &BiGSuser1, &BiGSnull11,
	&BiGSnull21, &BiGSnull31, &BiGSnull41,
	&BiGSnull51, &BiGSnumbers1, &BiGSPrefixes1,
	&BiGSmoney1, &BiGSTimeR_US_B_C_X1, &BiGSDateR_US1,
	&BiGSPhoneR_US_C1, &BiGSPostalCode1, &BiGSIDNumbers1,
	&BiGSopenquote1, &BiGSwordlike1, &BiGSLexicalSymbols11,
	&BiGSLexicalSymbols21
};

// ROM 0x0036686c BiGGeneral
extern const BiGrammar	BiGGeneral = {
	"General", 3, 25, 25, BiGSLGeneral1,
	2, { 2, 2, 0, 0, 0, 0, 0, 0, 0, 0 }
};

/*--------------------------------------------------------------------
	Date: 4 kinds of word.
--------------------------------------------------------------------*/
extern const BiGSlice	BiGSDateR_US2;
extern const BiGSlice	BiGSendpunct2;
extern const BiGSlice	BiGSdaymonth2;
extern const BiGSlice	BiGSLexicalSymbols2;

// ROM 0x0036688c BiSLDateR_US2
extern const BiGSlice* const	BiSLDateR_US2[1] = {
	&BiGSendpunct2
};
// ROM 0x00366890 BiSPDateR_US2
extern const short	BiSPDateR_US2[1] = { 601 };

// ROM 0x00366894 BiSLdaymonth2
extern const BiGSlice* const	BiSLdaymonth2[1] = {
	&BiGSendpunct2
};
// ROM 0x00366898 BiSPdaymonth2
extern const short	BiSPdaymonth2[1] = { 255 };

// ROM 0x0036689c BiGSDateR_US2
extern const BiGSlice	BiGSDateR_US2 =
	{ "DateR_US", 7, 0, 0, 0, 0, 0x00000000, 0, 0, 0, 0, 1, 1, BiSLDateR_US2, BiSPDateR_US2, 0xff };
// ROM 0x003668cc BiGSendpunct2
extern const BiGSlice	BiGSendpunct2 =
	{ "endpunct", 112, 32766, 0, 0, 0, 0x00000005, 0, 0, 0, 0, 0, 0, nil, nil, 0xff };
// ROM 0x003668fc BiGSdaymonth2
extern const BiGSlice	BiGSdaymonth2 =
	{ "daymonth", 111, 0, 0, 0, 0, 0x0000000f, 0, 255, 0, 255, 1, 1, BiSLdaymonth2, BiSPdaymonth2, 0xff };
// ROM 0x0036692c BiGSLexicalSymbols2
extern const BiGSlice	BiGSLexicalSymbols2 =
	{ "LexicalSymbols", 119, 1497, 0, 399, 0, 0x00000010, 0, 0, 0, 0, 0, 0, nil, nil, 0x00 };

// ROM 0x0036695c BiGSLDate2
extern const BiGSlice* const	BiGSLDate2[4] = {
	&BiGSDateR_US2, &BiGSendpunct2, &BiGSdaymonth2,
	&BiGSLexicalSymbols2
};

// ROM 0x0036696c BiGDate
extern const BiGrammar	BiGDate = {
	"Date", 2, 4, 4, BiGSLDate2,
	1, { 2, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
};

/*--------------------------------------------------------------------
	Numbers&Money: 3 kinds of word.
--------------------------------------------------------------------*/
extern const BiGSlice	BiGSnumbers3;
extern const BiGSlice	BiGSmoney3;
extern const BiGSlice	BiGSLexicalSymbols3;

// ROM 0x0036698c BiGSnumbers3
extern const BiGSlice	BiGSnumbers3 =
	{ "numbers", 116, 0, 0, 0, 0, 0x00000000, 0, 0, 0, 0, 0, 0, nil, nil, 0xff };
// ROM 0x003669bc BiGSmoney3
extern const BiGSlice	BiGSmoney3 =
	{ "money", 115, 0, 0, 0, 0, 0x00000000, 0, 0, 0, 0, 0, 0, nil, nil, 0xff };
// ROM 0x003669ec BiGSLexicalSymbols3
extern const BiGSlice	BiGSLexicalSymbols3 =
	{ "LexicalSymbols", 119, 1497, 0, 399, 0, 0x00000010, 0, 0, 0, 0, 0, 0, nil, nil, 0x00 };

// ROM 0x00366a1c BiGSLNumbersAndMoney3
extern const BiGSlice* const	BiGSLNumbersAndMoney3[3] = {
	&BiGSnumbers3, &BiGSmoney3, &BiGSLexicalSymbols3
};

// ROM 0x00366a28 BiGNumbersAndMoney
extern const BiGrammar	BiGNumbersAndMoney = {
	"Numbers&Money", 2, 3, 3, BiGSLNumbersAndMoney3,
	1, { 2, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
};

/*--------------------------------------------------------------------
	Numbers: 2 kinds of word.
--------------------------------------------------------------------*/
extern const BiGSlice	BiGSnumbers4;
extern const BiGSlice	BiGSLexicalSymbols4;

// ROM 0x00366a48 BiGSnumbers4
extern const BiGSlice	BiGSnumbers4 =
	{ "numbers", 116, 0, 0, 0, 0, 0x00000000, 0, 0, 0, 0, 0, 0, nil, nil, 0xff };
// ROM 0x00366a78 BiGSLexicalSymbols4
extern const BiGSlice	BiGSLexicalSymbols4 =
	{ "LexicalSymbols", 119, 1497, 0, 399, 0, 0x00000010, 0, 0, 0, 0, 0, 0, nil, nil, 0x00 };

// ROM 0x00366aa8 BiGSLNumbers4
extern const BiGSlice* const	BiGSLNumbers4[2] = {
	&BiGSnumbers4, &BiGSLexicalSymbols4
};

// ROM 0x00366ab0 BiGNumbers
extern const BiGrammar	BiGNumbers = {
	"Numbers", 2, 2, 2, BiGSLNumbers4,
	1, { 2, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
};

/*--------------------------------------------------------------------
	Phone: 5 kinds of word.
--------------------------------------------------------------------*/
extern const BiGSlice	BiGSPhoneR_US_C5;
extern const BiGSlice	BiGShyphen5;
extern const BiGSlice	BiGSWorldPhone5;
extern const BiGSlice	BiGSFunnyPhone5;
extern const BiGSlice	BiGSLexicalSymbols5;

// ROM 0x00366ad0 BiSLPhoneR_US_C5
extern const BiGSlice* const	BiSLPhoneR_US_C5[1] = {
	&BiGShyphen5
};
// ROM 0x00366ad4 BiSPPhoneR_US_C5
extern const short	BiSPPhoneR_US_C5[1] = { 458 };

// ROM 0x00366ad8 BiSLhyphen5
extern const BiGSlice* const	BiSLhyphen5[3] = {
	&BiGSPhoneR_US_C5, &BiGSWorldPhone5, &BiGSFunnyPhone5
};
// ROM 0x00366ae4 BiSPhyphen5
extern const short	BiSPhyphen5[3] = { 0, 458, 804 };

// ROM 0x00366aec BiSLWorldPhone5
extern const BiGSlice* const	BiSLWorldPhone5[1] = {
	&BiGShyphen5
};
// ROM 0x00366af0 BiSPWorldPhone5
extern const short	BiSPWorldPhone5[1] = { 458 };

// ROM 0x00366af4 BiSLFunnyPhone5
extern const BiGSlice* const	BiSLFunnyPhone5[1] = {
	&BiGShyphen5
};
// ROM 0x00366af8 BiSPFunnyPhone5
extern const short	BiSPFunnyPhone5[1] = { 458 };

// ROM 0x00366afc BiGSPhoneR_US_C5
extern const BiGSlice	BiGSPhoneR_US_C5 =
	{ "PhoneR_US_C", 15, 0, 25, 0, 0, 0x00000000, 0, 0, 0, 0, 1, 1, BiSLPhoneR_US_C5, BiSPPhoneR_US_C5, 0xff };
// ROM 0x00366b2c BiGShyphen5
extern const BiGSlice	BiGShyphen5 =
	{ "hyphen", 113, 1151, 1151, 0, 0, 0x00000000, 0, 0, 0, 0, 3, 3, BiSLhyphen5, BiSPhyphen5, 0xff };
// ROM 0x00366b5c BiGSWorldPhone5
extern const BiGSlice	BiGSWorldPhone5 =
	{ "WorldPhone", 106, 458, 25, 0, 0, 0x00000000, 0, 0, 0, 0, 1, 1, BiSLWorldPhone5, BiSPWorldPhone5, 0xff };
// ROM 0x00366b8c BiGSFunnyPhone5
extern const BiGSlice	BiGSFunnyPhone5 =
	{ "FunnyPhone", 105, 804, 25, 0, 0, 0x00000004, 0, 0, 0, 0, 1, 1, BiSLFunnyPhone5, BiSPFunnyPhone5, 0xff };
// ROM 0x00366bbc BiGSLexicalSymbols5
extern const BiGSlice	BiGSLexicalSymbols5 =
	{ "LexicalSymbols", 119, 2302, 1151, 399, 0, 0x00000010, 0, 0, 0, 0, 0, 0, nil, nil, 0x00 };

// ROM 0x00366bec BiGSLPhone5
extern const BiGSlice* const	BiGSLPhone5[5] = {
	&BiGSPhoneR_US_C5, &BiGShyphen5, &BiGSWorldPhone5,
	&BiGSFunnyPhone5, &BiGSLexicalSymbols5
};

// ROM 0x00366c00 BiGPhone
extern const BiGrammar	BiGPhone = {
	"Phone", 2, 5, 5, BiGSLPhone5,
	1, { 2, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
};

/*--------------------------------------------------------------------
	Time: 2 kinds of word.
--------------------------------------------------------------------*/
extern const BiGSlice	BiGSTimeR_US_B_C_X6;
extern const BiGSlice	BiGSLexicalSymbols6;

// ROM 0x00366c20 BiGSTimeR_US_B_C_X6
extern const BiGSlice	BiGSTimeR_US_B_C_X6 =
	{ "TimeR_US_B_C_X", 16, 0, 0, 0, 0, 0x00000000, 0, 0, 0, 0, 0, 0, nil, nil, 0xff };
// ROM 0x00366c50 BiGSLexicalSymbols6
extern const BiGSlice	BiGSLexicalSymbols6 =
	{ "LexicalSymbols", 119, 1497, 0, 399, 0, 0x00000010, 0, 0, 0, 0, 0, 0, nil, nil, 0x00 };

// ROM 0x00366c80 BiGSLTime6
extern const BiGSlice* const	BiGSLTime6[2] = {
	&BiGSTimeR_US_B_C_X6, &BiGSLexicalSymbols6
};

// ROM 0x00366c88 BiGTime
extern const BiGrammar	BiGTime = {
	"Time", 2, 2, 2, BiGSLTime6,
	1, { 2, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
};

/*--------------------------------------------------------------------
	Money: 2 kinds of word.
--------------------------------------------------------------------*/
extern const BiGSlice	BiGSmoney7;
extern const BiGSlice	BiGSLexicalSymbols7;

// ROM 0x00366ca8 BiGSmoney7
extern const BiGSlice	BiGSmoney7 =
	{ "money", 115, 0, 0, 0, 0, 0x00000000, 0, 0, 0, 0, 0, 0, nil, nil, 0xff };
// ROM 0x00366cd8 BiGSLexicalSymbols7
extern const BiGSlice	BiGSLexicalSymbols7 =
	{ "LexicalSymbols", 119, 1497, 0, 399, 0, 0x00000010, 0, 0, 0, 0, 0, 0, nil, nil, 0x00 };

// ROM 0x00366d08 BiGSLMoney7
extern const BiGSlice* const	BiGSLMoney7[2] = {
	&BiGSmoney7, &BiGSLexicalSymbols7
};

// ROM 0x00366d10 BiGMoney
extern const BiGrammar	BiGMoney = {
	"Money", 2, 2, 2, BiGSLMoney7,
	1, { 2, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
};

/*--------------------------------------------------------------------
	PostalCode: 3 kinds of word.
--------------------------------------------------------------------*/
extern const BiGSlice	BiGSnumbers8;
extern const BiGSlice	BiGSPostalCode8;
extern const BiGSlice	BiGSLexicalSymbols8;

// ROM 0x00366d30 BiGSnumbers8
extern const BiGSlice	BiGSnumbers8 =
	{ "numbers", 116, 111, 0, 0, 0, 0x00000000, 0, 0, 0, 0, 0, 0, nil, nil, 0xff };
// ROM 0x00366d60 BiGSPostalCode8
extern const BiGSlice	BiGSPostalCode8 =
	{ "PostalCode", 107, 346, 0, 0, 0, 0x00000000, 0, 0, 0, 0, 0, 0, nil, nil, 0xff };
// ROM 0x00366d90 BiGSLexicalSymbols8
extern const BiGSlice	BiGSLexicalSymbols8 =
	{ "LexicalSymbols", 119, 2302, 1151, 399, 0, 0x00000010, 0, 0, 0, 0, 0, 0, nil, nil, 0x00 };

// ROM 0x00366dc0 BiGSLPostalCode8
extern const BiGSlice* const	BiGSLPostalCode8[3] = {
	&BiGSnumbers8, &BiGSPostalCode8, &BiGSLexicalSymbols8
};

// ROM 0x00366dcc BiGPostalCode
extern const BiGrammar	BiGPostalCode = {
	"PostalCode", 2, 3, 3, BiGSLPostalCode8,
	1, { 2, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
};

// ROM 0x00366dec ROMGList
extern const BiGrammar* const	ROMGList[8] = {
	&BiGGeneral,
	&BiGDate,
	&BiGNumbersAndMoney,
	&BiGNumbers,
	&BiGPhone,
	&BiGTime,
	&BiGMoney,
	&BiGPostalCode
};

// ROM 0x00366e0c ROMGrammar
extern const BiGrammars	ROMGrammar = { 8, ROMGList };
