/*
	File:		recognition/RosEngine.h

	Contains:	The parts of the handwriting engine the word recogniser
				leans on that are not reconstructed yet.

				`recognition/Rosetta.h` draws the seam between the
				Newton and ParaGraph's engine; this file draws the
				smaller seams *inside* the engine, so that one layer of
				it can be reconstructed at a time.  Everything declared
				here is called by `WordRecog.h` and answers nothing
				useful until it is written.

				- the **common info** (`RosCI`) is the block of trained
				  numbers the whole engine measures against.  Two of its
				  fields are known, because the word recogniser reads
				  them: a nominal width for every character code, and
				  the smallest cap height it will believe.

				- a **grammar** is the finite-state machine the engine
				  reads a word against.  The ROM has eight of them built
				  in (`ROMGrammar`, 0x00366e0c): General, Date,
				  Numbers&Money, Numbers, Phone, Time, Money and
				  PostalCode.  `WordRecogSetContext` picks one by name.

				- a **segment** is a piece of a stroke the engine has
				  decided is one character, or part of one.

				- the **net** is the back-propagation classifier, and a
				  **patternizer** is what turns a segment into the
				  inputs it takes.

	NOT YET RECONSTRUCTED.  Each function does as little as it can
	without lying: the destroyers do nothing, and `BiGrammarsLoad`
	answers the grammar it is handed rather than the ROM's own trained
	one, so that a caller (or a test) can drive the word recogniser with
	a grammar of its own until `ROMGrammar` is extracted.

	Reconstructed from the MP2x00 US ROM; each declaration cites its
	origin.
*/

#ifndef __ROSENGINE_H
#define __ROSENGINE_H

#ifndef __NEWTONTYPES_H
#include "NewtonTypes.h"
#endif

#ifndef __FIXEDGEOMETRY_H
#include "FixedGeometry.h"
#endif


/*--------------------------------------------------------------------
	The engine's common info.
--------------------------------------------------------------------*/

// The block of trained numbers the whole engine measures against.  The
// ROM's is 0x10c bytes and `CharInitialize` makes one by copying the
// template `rosCI` (`RosCITables.cpp`, generated by
// `analysis/rosci.py`) into a block of its own, because an area may
// replace `fLegalUse` with a set of its own.
//
// A field named `fFieldNNN` is one nothing reconstructed so far reads;
// the offsets in the comments are the ROM's.
struct RosCommonInfo
{
	ULong				fField00[3];		// +0x00
	// eight numbers per character code, on eight scales of the
	// engine's own.  Table 1 is the nominal width a character takes,
	// which is what the cap height is worked out from.
	const Fixed* const*	fCharParams;		// +0x0c  rosCharParams
	ULong				fField10;			// +0x10
	// 256 bits each: which character codes there are, and which of
	// them the engine may answer at the moment.  `fLegalUse` starts as
	// the ROM's own `rosCharLegalUse` and is replaced by a set of the
	// area's when one is set, which is what `RSfRcl` checks before it
	// gives the block back.
	const ULong*		fLegalNet;			// +0x14  rosCharLegalNet
	const ULong*		fLegalUse;			// +0x18  rosCharLegalUse
	// the classifier's output nodes and the character codes they stand
	// for, each way round
	const UByte*		fCharOfNetNode;		// +0x1c  rosCharOfNetNode
	const UByte*		fCharToNetNode;		// +0x20  rosCharToNetNode
	// a character that is really two: the two it is made of, whose net
	// outputs are multiplied together to score it
	const UByte*		fCompoundPart1;		// +0x24  rosCharCompoundPart1
	const UByte*		fCompoundPart2;		// +0x28  rosCharCompoundPart2
	// the capitals hack: whether a character has a case, and the one
	// or two characters it may be read as instead
	const UByte*		fCapCaseFlags;		// +0x2c  rosCapHackCaseFlags
	const UByte*		fCapAltCase1;		// +0x30  rosCapHackAltCase1
	const UByte*		fCapAltCase2;		// +0x34  rosCapHackAltCase2
	ULong				fField38[5];		// +0x38
	// under this a stroke has no shape at all - and, because it is the
	// same number, the smallest cap height that will be believed
	Fixed				fMinStrokeSize;		// +0x4c
	ULong				fField50[47];		// +0x50 .. +0x108
};

// The eight tables and the ten the common info points at, as the ROM
// has them (`RosCITables.cpp`, generated - do not edit).
extern const RosCommonInfo	rosCI;						// ROM 0x0036b6c0 rosCI
extern const ULong			rosCharLegalUse[8];			// ROM 0x00366f60 rosCharLegalUse

// How many output nodes the classifier has; the block made and `RosCI`
// pointed at it.
long	CharInitialize(long unused);						// ROM 0x00057074 CharInitialize
// ... and given back, `fLegalUse` put back to the ROM's own first.
void	RSfRcl(void);										// ROM 0x001b8334 RSfRcl

// ROM 0x0c100b08 RosCI
// There is one, and it is nil until the engine is started.
extern RosCommonInfo*	RosCI;


/*--------------------------------------------------------------------
	The grammars.
--------------------------------------------------------------------*/

// One context: the name it is asked for by, and the finite-state
// grammar itself, which is NOT YET.
struct RosGrammarContext
{
	const char*	fName;		// +0x00
};

// The list of them, as `BiGrammarsLoad` answers it.
struct RosGrammars
{
	long				fCount;			// +0x00
	RosGrammarContext**	fContexts;		// +0x04
};

// What `RosettaAwaken` asks for.  The ROM's `BiGrammarsLoad` ignores
// its argument and answers `ROMGrammar` whatever it is handed, so the
// ROM passes the constant 1; nothing ever dereferences it.
#define kROMGrammars	((RosGrammars*) 1)

// NOT YET: the ROM's answers `ROMGrammar` (0x00366e0c), its eight
// built-in contexts.  Ours answers nil for `kROMGrammars`, because
// that table has not been extracted, and otherwise answers what it is
// handed - so a caller can bring a grammar of its own and the word
// recogniser can be driven before the ROM's is there.
RosGrammars*	BiGrammarsLoad(RosGrammars* source);		// ROM 0x0003e0b4 BiGrammarsLoad
// A context the engine built for itself, given back.
void			BiGrammarDestroy(RosGrammarContext* context);	// ROM 0x0003df4c BiGrammarDestroy


/*--------------------------------------------------------------------
	The segments, and the classifier.
--------------------------------------------------------------------*/

struct RosStroke;

// A piece of writing the engine has decided is a character, or part of
// one.  What is in it is NOT YET.
struct RosSegment;
// The classifier's pattern, and what fills it in.
struct RosNetPattern;
struct RosNetPatternizer;

// The strokes of a word cut into characters; answers how many segments
// were made.
short	SegmentChars(short count, RosStroke** strokes, Fixed meanSize,
					RosSegment** segments, UByte how, void* net);	// ROM 0x001d48a4 SegmentChars
// What the segment layer wants remembered about a stroke as it comes in.
void	SegmentStrokeData(RosStroke* stroke, UByte how, short index, Fixed separation);	// ROM 0x001d2224 SegmentStrokeData

void	SegmentDestroy(RosSegment* segment);				// ROM 0x001d1cac SegmentDestroy
// Everything the segment layer is holding on to, given back.
void	SegmentQuiesce(void);								// ROM 0x001d0f3c SegmentQuiesce
void	SegmentIntegrated(long how);						// ROM 0x001d4cbc SegmentIntegrated

// The smallest a stroke may be and still be said to go one way rather
// than another - and, because it is the same number, the smallest cap
// height the word recogniser will believe.
Fixed	SegmentMinStrokeSize(void);							// ROM 0x001d1890 SegmentMinStrokeSize

void	NetPatternDestroy(RosNetPattern* pattern);			// ROM 0x00133a08 NetPatternDestroy
void	NetPatternizerDestroy(RosNetPatternizer* patternizer);	// ROM 0x00133a58 NetPatternizerDestroy

// The back-propagation classifier: made with a number of output nodes,
// told whether it may learn, loaded, and given back.
void*	BPNetCreateNumOut(long outputs);						// ROM 0x0003b1cc BPNetCreateNumOut
void	BPNetLearnEnable(void* net, long enable);			// ROM 0x0003b278 BPNetLearnEnable
void	BPNetLoad(void* net, void* from);					// ROM 0x0003b280 BPNetLoad
void	BPNetDestroy(void* net);							// ROM 0x0003b240 BPNetDestroy

// The boxed-character recogniser, given back.
void	CharBoxDestroy(void* charBox);						// ROM 0x00056684 CharBoxDestroy
// The lexical search and the geometry, quietened; the sentence read so
// far, forgotten.
void	LEquiesant(void);									// ROM 0x000ffd60 LEquiesant
void	GeoCQuiesence(void);								// ROM 0x000d9ce4 GeoCQuiesence
void	SearchDeallocateGlobals(void);						// ROM 0x001d02ec SearchDeallocateGlobals

// The engine's own free list, emptied.
void	ListZap(void);										// ROM 0x0011343c ListZap

// True once the layers above are real.
Boolean	RosEngineLayersAreReconstructed(void);

#endif	/* __ROSENGINE_H */
