/*
	File:		recognition/RosEngine.h

	Contains:	The parts of the handwriting engine the word recogniser
				leans on that are not reconstructed yet.

				`recognition/Rosetta.h` draws the seam between the
				Newton and ParaGraph's engine; this file draws the
				smaller seams *inside* the engine, so that one layer of
				it can be reconstructed at a time.  Everything declared
				here is called by `WordRecog.h` and answers nothing
				useful until it is written.

				- the **common info** (`RosCI`) is the block of trained
				  numbers the whole engine measures against.  Two of its
				  fields are known, because the word recogniser reads
				  them: a nominal width for every character code, and
				  the smallest cap height it will believe.

				- a **grammar** is the finite-state machine the engine
				  reads a word against.  The ROM has eight of them built
				  in (`ROMGrammar`, 0x00366e0c): General, Date,
				  Numbers&Money, Numbers, Phone, Time, Money and
				  PostalCode.  `WordRecogSetContext` picks one by name.

				- a **segment** is a piece of a stroke the engine has
				  decided is one character, or part of one.

				- the **net** is the back-propagation classifier, and a
				  **patternizer** is what turns a segment into the
				  inputs it takes.

	The common info and the grammar are **real**: `CharInitialize`
	copies the ROM's template and `BiGrammarsLoad` answers the ROM's
	own eight grammars (`RosCITables.cpp` and `ROMGrammar.cpp`, both
	generated).  The segments, the classifier and its patternizers are
	NOT YET, and each does as little as it can without lying.

	Reconstructed from the MP2x00 US ROM; each declaration cites its
	origin.
*/

#ifndef __ROSENGINE_H
#define __ROSENGINE_H

#ifndef __NEWTONTYPES_H
#include "NewtonTypes.h"
#endif

#ifndef __FIXEDGEOMETRY_H
#include "FixedGeometry.h"
#endif

#ifndef __BPNET_H
#include "BPNet.h"			// the classifier the engine reads with
#endif


/*--------------------------------------------------------------------
	The engine's common info.
--------------------------------------------------------------------*/

// The block of trained numbers the whole engine measures against.  The
// ROM's is 0x10c bytes and `CharInitialize` makes one by copying the
// template `rosCI` (`RosCITables.cpp`, generated by
// `analysis/rosci.py`) into a block of its own, because an area may
// replace `fLegalUse` with a set of its own.
//
// A field named `fFieldNNN` is one nothing reconstructed so far reads;
// the offsets in the comments are the ROM's.
struct RosCommonInfo
{
	// Four numbers per character code saying how likely it is to be
	// written in one, two, three or four strokes.  Nil in the US ROM,
	// and `fStrokeCountWeight` is nought to match, so nothing uses it.
	const Fixed*		fCharStrokeProbs;	// +0x00
	ULong				fField04[2];		// +0x04
	// eight numbers per character code, on eight scales of the
	// engine's own.  Table 1 is the nominal width a character takes,
	// which is what the cap height is worked out from.
	const Fixed* const*	fCharParams;		// +0x0c  rosCharParams
	ULong				fField10;			// +0x10
	// 256 bits each: which character codes there are, and which of
	// them the engine may answer at the moment.  `fLegalUse` starts as
	// the ROM's own `rosCharLegalUse` and is replaced by a set of the
	// area's when one is set, which is what `RSfRcl` checks before it
	// gives the block back.
	const ULong*		fLegalNet;			// +0x14  rosCharLegalNet
	const ULong*		fLegalUse;			// +0x18  rosCharLegalUse
	// the classifier's output nodes and the character codes they stand
	// for, each way round
	const UByte*		fCharOfNetNode;		// +0x1c  rosCharOfNetNode
	const UByte*		fCharToNetNode;		// +0x20  rosCharToNetNode
	// a character that is really two: the two it is made of, whose net
	// outputs are multiplied together to score it
	const UByte*		fCompoundPart1;		// +0x24  rosCharCompoundPart1
	const UByte*		fCompoundPart2;		// +0x28  rosCharCompoundPart2
	// the capitals hack: whether a character has a case, and the one
	// or two characters it may be read as instead
	const UByte*		fCapCaseFlags;		// +0x2c  rosCapHackCaseFlags
	const UByte*		fCapAltCase1;		// +0x30  rosCapHackAltCase1
	const UByte*		fCapAltCase2;		// +0x34  rosCapHackAltCase2
	// The four things `CharModifyProbs` leans the classifier's answer
	// with, and how much each is worth.  **Two of them are nought in
	// the shipped ROM**: the stroke-count penalty and the shape fit
	// are compiled in and switched off, leaving the capitals hack and
	// the height model.
	Fixed				fStrokeCountWeight;	// +0x38  (0: off)
	Fixed				fCapCaseWeight;		// +0x3c  a fifth
	Fixed				fHeightSpread;		// +0x40  0.26 - and the gate for it
	Fixed				fShapeWeight;		// +0x44  (0: off)
	ULong				fField48;			// +0x48
	// under this a stroke has no shape at all - and, because it is the
	// same number, the smallest cap height that will be believed
	Fixed				fMinStrokeSize;		// +0x4c
	ULong				fField50;			// +0x50
	// The narrowest a letter may be taken to be, four pixels, and the
	// fractions of the writing's height that a letter is wide (a half)
	// and that two strokes must come within to count as touching (a
	// tenth).  `SegmentChars` works the two widths out from them.
	Fixed				fMinCharWidth;		// +0x54
	ULong				fField58[2];		// +0x58
	Fixed				fCharWidthFraction;	// +0x60
	Fixed				fReachFraction;		// +0x64
	ULong				fField68[4];		// +0x68
	// How wide a piece of writing may get before it is cut in two
	// whatever else the strokes say: one and a half times as wide as
	// it is tall, or one and three quarters when there is a dot
	// somewhere in it - because the dot has already widened the box
	// without being a letter of its own.
	Fixed				fCutAspect;			// +0x78
	Fixed				fCutAspectWithDot;	// +0x7c
	// How much of the line two neighbouring strokes must share before
	// they are said to be part of one letter.  Seven tenths on its
	// own; else sixty-five hundredths if they *cross*, or 0.675 if
	// they are joined somewhere other than end to end.  And no cut
	// may go between two strokes that share more than a half.
	Fixed				fLinkOverlap;		// +0x80
	Fixed				fCrossOverlap;		// +0x84
	Fixed				fJoinOverlap;		// +0x88
	Fixed				fBreakOverlap;		// +0x8c
	// how near an end of a stroke counts as *at* the end: three
	// tenths of its points at either end.  Two strokes whose nearest
	// points are both well inside them cross; two whose nearest
	// points are both at an end merely meet.
	Fixed				fEndFraction;		// +0x90
	// ... and how near two strokes must come to be said to touch at
	// all: three pixels.
	Fixed				fLinkDistance;		// +0x94
	ULong				fField98[6];		// +0x98
	// What the classifier's score for a letter is worth against
	// everything else the search weighs: four fifths.
	Fixed				fNetScoreWeight;	// +0xb0
	// What a character of each case costs in each of the twelve
	// contexts `CapHackDetermineContext` answers.  This is the
	// capitals model: what having just written a capital, or two,
	// or a lower-case letter, says about what may follow.
	UShort				fCapCostUpper[12];	// +0xb4
	UShort				fCapCostLower[12];	// +0xcc
	UShort				fCapCostOther[12];	// +0xe4
	// What a stroke costs the search when the letter it is part of
	// was written loosely.  Two shorts: nothing when the segment's
	// strokes lie on each other well (above `fStrokeCostGate`, a
	// half), and up to 322 when they do not, interpolated by the
	// confidence scaled by `fStrokeCostScale`.
	// (one word, because that is how the generated table writes it:
	//  the minimum is the high half and the maximum the low)
	ULong				fStrokeCost;		// +0xfc
	Fixed				fStrokeCostGate;	// +0x100
	Fixed				fStrokeCostScale;	// +0x104
	// What a piece of writing the engine cut for itself, or one that
	// runs into the next, is worth: one, so nothing.
	Fixed				fFragmentWeight;	// +0x108
};

// The eight tables and the ten the common info points at, as the ROM
// has them (`RosCITables.cpp`, generated - do not edit).
extern const RosCommonInfo	rosCI;						// ROM 0x0036b6c0 rosCI
extern const ULong			rosCharLegalUse[8];			// ROM 0x00366f60 rosCharLegalUse

// How tall each character is written, as a fraction of the word's size:
// **a mean and a spread**, one pair per character code, so that
// `CharModifyProbs` can ask how surprising this piece of writing's
// height would be for that character.  A spread of nought means
// nothing is known about it (`CharHeightTable.cpp`, generated by
// `analysis/romtable.py` - do not edit).
extern const int	CharHeight[512];					// ROM 0x0036f174 CharHeight
const long	kCharHeightMean		= 0;
const long	kCharHeightSpread	= 1;

// How many output nodes the classifier has; the block made and `RosCI`
// pointed at it.
long	CharInitialize(long unused);						// ROM 0x00057074 CharInitialize
// ... and given back, `fLegalUse` put back to the ROM's own first.
void	RSfRcl(void);										// ROM 0x001b8334 RSfRcl

// ROM 0x0c100b08 RosCI
// There is one, and it is nil until the engine is started.
extern RosCommonInfo*	RosCI;


/*--------------------------------------------------------------------
	The grammars.
--------------------------------------------------------------------*/

// One *kind of word*: a lexicon out of `gROMDictionaryData`, a score of
// its own, and a score for every kind that may follow it.  A lower
// score is better and 0x7ffe means never; they are the arithmetic
// coder's, which is what `ArProbDecodeLu` turns into a probability.
//
// `BiGSliceNew` (0x0003dfb4) allocates one with its two arrays behind
// it, so the ROM's object is 0x30 bytes plus six per transition.
struct BiGSlice
{
	const char*		fName;			// +0x00
	// Which lexicon, by its place in `gROMDictionaryData` - until
	// `RosettaSetArea` runs, which replaces the index with the data
	// itself.  A grammar the engine builds for an area has slices
	// named `~user` and `~null1`..`~null5` whose dictionary is filled
	// in later, and `RosettaClassifySetup` writes the *locked data
	// pointer* into this same field when it does.
	// DEVIATION: pointer-sized on the host, because that is what it
	// ends up holding and a host pointer is twice the ROM's.
	ULong			fDictionary;	// +0x04
	short			fScore;			// +0x08  what a word of this kind costs
	short			fField0a;		// +0x0a
	short			fCharCost;		// +0x0c  ... and each character of one
	short			fField0e;		// +0x0e
	long			fField10;		// +0x10  (bits: 0x2f, 0x15, 0x10, 0x0f, 5, 4)
	// What a capital and a lower-case letter cost in this kind of word.
	// `SearchDoVStepFromNode` charges the first pair on top of
	// everything else when the reading is in one of the upper six
	// capitals contexts, and the second pair *instead of* the common
	// info's twelve-entry tables when this kind of word says it will
	// have the case being tried.
	short			fCapExtraUpper;	// +0x14
	short			fCapExtraLower;	// +0x16
	short			fCapCostUpper;	// +0x18
	short			fCapCostLower;	// +0x1a
	// How many kinds may follow this one, and how many there is room
	// for.  `BiGSliceNew` sets the second and leaves the first at
	// nought; in the ROM's own tables they are equal, because those
	// slices are full.
	long			fNextCount;		// +0x1c
	long			fNextCapacity;	// +0x20
	const BiGSlice* const*	fNext;	// +0x24
	const short*	fWeights;		// +0x28  what each of them costs
	// What kind of lexicon this is.  `BiGSliceNew` sets 0xff and the
	// ROM's tables keep it in 36 of their 46 slices; the nine named
	// `LexicalSymbols` carry 0, and `wordlike` carries 1.
	UByte			fField2c;		// +0x2c
};

// One grammar: the name a field asks for it by, and its kinds of word.
// `BiGrammarNew` (0x0003de8c) allocates one with the slice array behind
// it, so the ROM's object is 0x20 bytes plus four per slice; the eight
// built into the ROM point at an array of their own instead.
struct BiGrammar
{
	const char*		fName;			// +0x00
	long			fField04;		// +0x04
	long			fCount;			// +0x08
	long			fCapacity;		// +0x0c
	const BiGSlice* const*	fSlices;	// +0x10
	UByte			fField14;		// +0x14
	// How many readings of each kind of word the search may keep in
	// one column, indexed by the lexicon class a slice carries in
	// `fField2c`.  The General grammar allows two of class 0 and two
	// of class 1, and nothing of the rest.
	UByte			fClassLimits[10];	// +0x15 .. +0x1e
	UByte			fPad1f;
};

// The list of them, as `BiGrammarsLoad` answers it.
struct BiGrammars
{
	long				fCount;		// +0x00
	const BiGrammar* const*	fContexts;	// +0x04
};

// The eight built into the ROM (`ROMGrammar.cpp`, generated by
// `analysis/bigrammar.py` - do not edit): General, Date,
// Numbers&Money, Numbers, Phone, Time, Money and PostalCode.  They are
// written out in `docs/recognition/grammar.md`.
extern const BiGrammars	ROMGrammar;						// ROM 0x00366e0c ROMGrammar

// What `RosettaAwaken` asks for.  The ROM's `BiGrammarsLoad` ignores
// its argument and answers `ROMGrammar` whatever it is handed, so the
// ROM passes the constant 1 and nothing ever dereferences it.
#define kROMGrammars	((const BiGrammars*) 1)

// One instruction in the ROM: it answers `ROMGrammar` whatever it is
// asked for.  Ours does the same for `kROMGrammars` and otherwise
// answers what it is handed, so a caller may bring a grammar of its
// own.
const BiGrammars*	BiGrammarsLoad(const BiGrammars* source);	// ROM 0x0003e0b4 BiGrammarsLoad
// A grammar the engine built for itself, given back.  NOT YET; the
// eight in the ROM are never destroyed.
// A grammar and one kind of word in it, made and given back.  Both keep
// their arrays *behind the struct in the same block*, so each is one
// allocation and one `DisposPtr`.
BiGrammar*	BiGrammarNew(short capacity);					// ROM 0x0003de8c BiGrammarNew
BiGrammar*	BiGrammarCreate(const char* name, short capacity);	// ROM 0x0003df2c BiGrammarCreate
BiGSlice*	BiGSliceNew(short capacity);					// ROM 0x0003dfb4 BiGSliceNew
void	BiGSliceDestroy(const BiGSlice* slice);				// ROM 0x0003dfa8 BiGSliceDestroy
void				BiGrammarDestroy(const BiGrammar* grammar);	// ROM 0x0003df4c BiGrammarDestroy

/*--------------------------------------------------------------------
	The arithmetic coder's two ways round.

	A grammar's scores are **negative natural logarithms of
	probabilities, scaled by five hundred**: a kind of word with an even
	chance costs 347, one chance in 65536 costs 5545, and 0x7ffe means
	never.  These two tables are how the engine goes between the two
	without a logarithm, and they are why `BiGrammarModifyContext` can
	reweigh a grammar in fixed point.

	`ArProbDecodeLu` answers the probability for a score, indexed by the
	score divided by eight, so it covers scores up to 0x2000 (a chance
	of about one in 34 million); anything dearer is nought.

	The other two go the other way and are chosen by how likely the
	thing is: `ArProbEncodeLu2` is indexed by the probability itself and
	covers the first 1/64 of the range finely, `ArProbEncodeLu1` by the
	probability over 128 for everything above that.
--------------------------------------------------------------------*/

// (`ArProbTables.cpp`, generated by `analysis/romtable.py` - do not edit)
extern const short	ArProbEncodeLu1[512];				// ROM 0x0036340c ArProbEncodeLu1
extern const short	ArProbEncodeLu2[1024];				// ROM 0x0036380c ArProbEncodeLu2
extern const int	ArProbDecodeLu[1024];				// ROM 0x0036400c ArProbDecodeLu

// The most a score may be and still mean anything, and the score that
// means never.
const long	kArProbNever		= 0x7ffe;
const long	kArProbMaxScore		= 0x2000;

// The two halves of the arithmetic coder's table lookup: the
// probability a score stands for, and the score a probability costs.
Fixed	ArProbDecode(long score);
short	ArProbEncode(Fixed probability);

// One kind of word, with room for `capacity` kinds after it and every
// other thing about it left to the caller.  The seven doubles are the
// training interface showing through and are not read.
BiGSlice*	BiGSliceCreate(const char* name, ULong dictionary,
					double a, double b, double c, long flag,
					double d, double e, double f, double g,
					short capacity);					// ROM 0x0003e048 BiGSliceCreate
// A kind of word looked up in a grammar by its dictionary and name, and
// added if it is not there yet.  This is what makes a clone's
// transitions point at the clone's own slices rather than the
// original's.
BiGSlice*	BiGrammarAddSlice(BiGrammar* grammar, ULong dictionary,
					const char* name, short capacity);	// ROM 0x0003e45c (unnamed)

// A grammar copied, slices, transitions and all.
BiGrammar*	BiGrammarClone(const BiGrammar* grammar);	// ROM 0x0003e534 BiGrammarClone
// A grammar cloned and then **reweighed**: the `count` kinds of word
// named by `slices` share `weight` of the probability, the rest share
// what is left, and every score is brought down so that the likeliest
// kind costs nothing.  This is what turns the General grammar into the
// grammar for a particular field.
BiGrammar*	BiGrammarModifyContext(const BiGrammar* grammar, long count,
					const long* slices, Fixed weight);	// ROM 0x0003e0c0 BiGrammarModifyContext


/*--------------------------------------------------------------------
	The segments, and the classifier.
--------------------------------------------------------------------*/

struct RosStroke;

// The segment layer - what a segment is and the measurements the
// cutting is made of - is `recognition/Segment.h`.
struct RosSegment;

// The lexical search and the geometry, quietened; the sentence read so
// far, forgotten.
void	LEquiesant(void);									// ROM 0x000ffd60 LEquiesant
void	GeoContextClearCache(void);						// ROM 0x000d9cc8 GeoContextClearCache
void	GeoCQuiesence(void);								// ROM 0x000d9ce4 GeoCQuiesence

// The engine's own free list, emptied.
void	ListZap(void);										// ROM 0x0011343c ListZap

// True once the layers above are real.
Boolean	RosEngineLayersAreReconstructed(void);


/*--------------------------------------------------------------------
	Measuring a word, and reading it.
--------------------------------------------------------------------*/

struct RosSegment;
struct WordRecog;

// The base, the height and the width of a word: three means over its
// segments and three extremes, which is everything the classifier is
// told about how big the writing is.
void	CharGetAvgBoxBHW(RosSegment* const* segments, short count, Fixed leastStroke,
				Fixed meanSize, Fixed widthScale, Fixed heightScale, short how,
				Fixed* base, Fixed* height, Fixed* width,
				Fixed* altBase, Fixed* maxHeight, Fixed* maxWidth);	// ROM 0x00056b7c CharGetAvgBoxBHW

// The classifier's answer leaned on by where and how big the piece of
// writing is: the capitals hack and a Gaussian height model.  Only the
// ten best character codes survive it.
void	CharModifyProbs(const FRect* bounds, short strokes, UByte hasDot,
				UByte fragment, UByte joinsNext, Fixed size,
				Fixed run18, Fixed run19, Fixed run20, Fixed run21,
				Fixed startSize, Fixed wordSize, Fixed* scratch,
				Fixed altBase, Fixed altHeight, Fixed arg9, Fixed* probs);	// ROM 0x00057108 CharModifyProbs

// The lexical search is `recognition/Search.h`.

#endif	/* __ROSENGINE_H */
