/*
	File:		recognition/RosEngine.h

	Contains:	The parts of the handwriting engine the word recogniser
				leans on that are not reconstructed yet.

				`recognition/Rosetta.h` draws the seam between the
				Newton and ParaGraph's engine; this file draws the
				smaller seams *inside* the engine, so that one layer of
				it can be reconstructed at a time.  Everything declared
				here is called by `WordRecog.h` and answers nothing
				useful until it is written.

				- the **common info** (`RosCI`) is the block of trained
				  numbers the whole engine measures against.  Two of its
				  fields are known, because the word recogniser reads
				  them: a nominal width for every character code, and
				  the smallest cap height it will believe.

				- a **grammar** is the finite-state machine the engine
				  reads a word against.  The ROM has eight of them built
				  in (`ROMGrammar`, 0x00366e0c): General, Date,
				  Numbers&Money, Numbers, Phone, Time, Money and
				  PostalCode.  `WordRecogSetContext` picks one by name.

				- a **segment** is a piece of a stroke the engine has
				  decided is one character, or part of one.

				- the **net** is the back-propagation classifier, and a
				  **patternizer** is what turns a segment into the
				  inputs it takes.

	The common info and the grammar are **real**: `CharInitialize`
	copies the ROM's template and `BiGrammarsLoad` answers the ROM's
	own eight grammars (`RosCITables.cpp` and `ROMGrammar.cpp`, both
	generated).  The segments, the classifier and its patternizers are
	NOT YET, and each does as little as it can without lying.

	Reconstructed from the MP2x00 US ROM; each declaration cites its
	origin.
*/

#ifndef __ROSENGINE_H
#define __ROSENGINE_H

#ifndef __NEWTONTYPES_H
#include "NewtonTypes.h"
#endif

#ifndef __FIXEDGEOMETRY_H
#include "FixedGeometry.h"
#endif

#ifndef __BPNET_H
#include "BPNet.h"			// the classifier the engine reads with
#endif


/*--------------------------------------------------------------------
	The engine's common info.
--------------------------------------------------------------------*/

// The block of trained numbers the whole engine measures against.  The
// ROM's is 0x10c bytes and `CharInitialize` makes one by copying the
// template `rosCI` (`RosCITables.cpp`, generated by
// `analysis/rosci.py`) into a block of its own, because an area may
// replace `fLegalUse` with a set of its own.
//
// A field named `fFieldNNN` is one nothing reconstructed so far reads;
// the offsets in the comments are the ROM's.
struct RosCommonInfo
{
	ULong				fField00[3];		// +0x00
	// eight numbers per character code, on eight scales of the
	// engine's own.  Table 1 is the nominal width a character takes,
	// which is what the cap height is worked out from.
	const Fixed* const*	fCharParams;		// +0x0c  rosCharParams
	ULong				fField10;			// +0x10
	// 256 bits each: which character codes there are, and which of
	// them the engine may answer at the moment.  `fLegalUse` starts as
	// the ROM's own `rosCharLegalUse` and is replaced by a set of the
	// area's when one is set, which is what `RSfRcl` checks before it
	// gives the block back.
	const ULong*		fLegalNet;			// +0x14  rosCharLegalNet
	const ULong*		fLegalUse;			// +0x18  rosCharLegalUse
	// the classifier's output nodes and the character codes they stand
	// for, each way round
	const UByte*		fCharOfNetNode;		// +0x1c  rosCharOfNetNode
	const UByte*		fCharToNetNode;		// +0x20  rosCharToNetNode
	// a character that is really two: the two it is made of, whose net
	// outputs are multiplied together to score it
	const UByte*		fCompoundPart1;		// +0x24  rosCharCompoundPart1
	const UByte*		fCompoundPart2;		// +0x28  rosCharCompoundPart2
	// the capitals hack: whether a character has a case, and the one
	// or two characters it may be read as instead
	const UByte*		fCapCaseFlags;		// +0x2c  rosCapHackCaseFlags
	const UByte*		fCapAltCase1;		// +0x30  rosCapHackAltCase1
	const UByte*		fCapAltCase2;		// +0x34  rosCapHackAltCase2
	ULong				fField38[5];		// +0x38
	// under this a stroke has no shape at all - and, because it is the
	// same number, the smallest cap height that will be believed
	Fixed				fMinStrokeSize;		// +0x4c
	ULong				fField50[47];		// +0x50 .. +0x108
};

// The eight tables and the ten the common info points at, as the ROM
// has them (`RosCITables.cpp`, generated - do not edit).
extern const RosCommonInfo	rosCI;						// ROM 0x0036b6c0 rosCI
extern const ULong			rosCharLegalUse[8];			// ROM 0x00366f60 rosCharLegalUse

// How many output nodes the classifier has; the block made and `RosCI`
// pointed at it.
long	CharInitialize(long unused);						// ROM 0x00057074 CharInitialize
// ... and given back, `fLegalUse` put back to the ROM's own first.
void	RSfRcl(void);										// ROM 0x001b8334 RSfRcl

// ROM 0x0c100b08 RosCI
// There is one, and it is nil until the engine is started.
extern RosCommonInfo*	RosCI;


/*--------------------------------------------------------------------
	The grammars.
--------------------------------------------------------------------*/

// One *kind of word*: a lexicon out of `gROMDictionaryData`, a score of
// its own, and a score for every kind that may follow it.  A lower
// score is better and 0x7ffe means never; they are the arithmetic
// coder's, which is what `ArProbDecodeLu` turns into a probability.
//
// `BiGSliceNew` (0x0003dfb4) allocates one with its two arrays behind
// it, so the ROM's object is 0x30 bytes plus six per transition.
struct BiGSlice
{
	const char*		fName;			// +0x00
	// which lexicon, by its place in `gROMDictionaryData`.  A grammar
	// the engine builds for an area has slices named `~user` and
	// `~null1`..`~null5` whose dictionary is filled in later, and
	// `RosettaClassifySetup` writes the *locked data pointer* into
	// this same field when it does.
	long			fDictionary;	// +0x04
	short			fScore;			// +0x08  what a word of this kind costs
	short			fField0a;		// +0x0a
	short			fField0c;		// +0x0c
	short			fField0e;		// +0x0e
	long			fField10;		// +0x10  (bits: 0x2f, 0x15, 0x10, 0x0f, 5, 4)
	short			fField14;		// +0x14
	short			fField16;		// +0x16
	short			fField18;		// +0x18
	short			fField1a;		// +0x1a
	long			fField1c;		// +0x1c  (the ROM's tables repeat fCount here)
	long			fCount;			// +0x20  how many kinds may follow
	const BiGSlice* const*	fNext;	// +0x24
	const short*	fWeights;		// +0x28  what each of them costs
	UByte			fField2c;		// +0x2c  0xff in every one of the ROM's
};

// One grammar: the name a field asks for it by, and its kinds of word.
// `BiGrammarNew` (0x0003de8c) allocates one with the slice array behind
// it, so the ROM's object is 0x20 bytes plus four per slice; the eight
// built into the ROM point at an array of their own instead.
struct BiGrammar
{
	const char*		fName;			// +0x00
	long			fField04;		// +0x04
	long			fCount;			// +0x08
	long			fCapacity;		// +0x0c
	const BiGSlice* const*	fSlices;	// +0x10
	UByte			fField14;		// +0x14
	UByte			fField15;		// +0x15
	UByte			fField16;		// +0x16
	UByte			fField17;		// +0x17
	long			fField18;		// +0x18
	long			fField1c;		// +0x1c
};

// The list of them, as `BiGrammarsLoad` answers it.
struct BiGrammars
{
	long				fCount;		// +0x00
	const BiGrammar* const*	fContexts;	// +0x04
};

// The eight built into the ROM (`ROMGrammar.cpp`, generated by
// `analysis/bigrammar.py` - do not edit): General, Date,
// Numbers&Money, Numbers, Phone, Time, Money and PostalCode.  They are
// written out in `docs/recognition/grammar.md`.
extern const BiGrammars	ROMGrammar;						// ROM 0x00366e0c ROMGrammar

// What `RosettaAwaken` asks for.  The ROM's `BiGrammarsLoad` ignores
// its argument and answers `ROMGrammar` whatever it is handed, so the
// ROM passes the constant 1 and nothing ever dereferences it.
#define kROMGrammars	((const BiGrammars*) 1)

// One instruction in the ROM: it answers `ROMGrammar` whatever it is
// asked for.  Ours does the same for `kROMGrammars` and otherwise
// answers what it is handed, so a caller may bring a grammar of its
// own.
const BiGrammars*	BiGrammarsLoad(const BiGrammars* source);	// ROM 0x0003e0b4 BiGrammarsLoad
// A grammar the engine built for itself, given back.  NOT YET; the
// eight in the ROM are never destroyed.
void				BiGrammarDestroy(const BiGrammar* grammar);	// ROM 0x0003df4c BiGrammarDestroy


/*--------------------------------------------------------------------
	The segments, and the classifier.
--------------------------------------------------------------------*/

struct RosStroke;

// A piece of writing the engine has decided is a character, or part of
// one.  What is in it is NOT YET.
struct RosSegment;
// The classifier's pattern, and what fills it in.
struct RosNetPattern;
struct RosNetPatternizer;

// The strokes of a word cut into characters; answers how many segments
// were made.
short	SegmentChars(short count, RosStroke** strokes, Fixed meanSize,
					RosSegment** segments, UByte how, void* net);	// ROM 0x001d48a4 SegmentChars
// What the segment layer wants remembered about a stroke as it comes in.
void	SegmentStrokeData(RosStroke* stroke, UByte how, short index, Fixed separation);	// ROM 0x001d2224 SegmentStrokeData

void	SegmentDestroy(RosSegment* segment);				// ROM 0x001d1cac SegmentDestroy
// Everything the segment layer is holding on to, given back.
void	SegmentQuiesce(void);								// ROM 0x001d0f3c SegmentQuiesce
void	SegmentIntegrated(long how);						// ROM 0x001d4cbc SegmentIntegrated

// The smallest a stroke may be and still be said to go one way rather
// than another - and, because it is the same number, the smallest cap
// height the word recogniser will believe.
Fixed	SegmentMinStrokeSize(void);							// ROM 0x001d1890 SegmentMinStrokeSize

void	NetPatternDestroy(RosNetPattern* pattern);			// ROM 0x00133a08 NetPatternDestroy
void	NetPatternizerDestroy(RosNetPatternizer* patternizer);	// ROM 0x00133a58 NetPatternizerDestroy

// The boxed-character recogniser, given back.
void	CharBoxDestroy(void* charBox);						// ROM 0x00056684 CharBoxDestroy
// The lexical search and the geometry, quietened; the sentence read so
// far, forgotten.
void	LEquiesant(void);									// ROM 0x000ffd60 LEquiesant
void	GeoCQuiesence(void);								// ROM 0x000d9ce4 GeoCQuiesence
void	SearchDeallocateGlobals(void);						// ROM 0x001d02ec SearchDeallocateGlobals

// The engine's own free list, emptied.
void	ListZap(void);										// ROM 0x0011343c ListZap

// True once the layers above are real.
Boolean	RosEngineLayersAreReconstructed(void);

#endif	/* __ROSENGINE_H */
