// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> kSearchEasterWords@0x0037757c:str9:8 kSearchEasterReplies@0x003775c4:str23:8 -o src/recognition/SearchEasterEgg.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const char	kSearchEasterWords[8][9];
extern const char	kSearchEasterReplies[8][23];

// ROM 0x0037757c (unnamed) - kSearchEasterWords
const char	kSearchEasterWords[8][9] = {
	"larryy",
	"Larry",
	"Mondello",
	"Brandyn",
	"Rosetta!",
	"stafford",
	"Les",
	"lyon",
};

// ROM 0x003775c4 (unnamed) - kSearchEasterReplies
const char	kSearchEasterReplies[8][23] = {
	"The Doctor is on.",
	"larryy@apple.com",
	"Fine food 408/257-2383",
	"brandyn@brainstorm.com",
	"Hey, that's me!",
	"bill",
	"lesv@angeltech.com",
	"Richard",
};
