// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> displayAngle:i32:25 -o src/recognition/ShapeTables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const int	displayAngle[25];

// ROM 0x00377464 displayAngle
const int	displayAngle[25] = {
	       0,   983040,  1966080,  2949120,  3932160,  4915200,  5898240,  6881280,
	 7864320,  8847360,  9830400, 10813440, 11796480, 12779520, 13762560, 14745600,
	15728640, 16711680, 17694720, 18677760, 19660800, 20643840, 21626880, 22609920,
	23592960,
};
