/*
	File:		recognition/Spelling.h

	Contains:	The spelling checker: whether a word is spelled right, and
				what it might have been meant to be.

				It is a self-contained thing sitting on top of the
				dictionaries - it knows nothing about the recogniser, and
				the recogniser reaches it only through the seven
				NewtonScript functions below (`SpellDocBegin`,
				`SpellCheck`, `SpellCorrect`, `SpellSkip`, `SpellDocEnd`,
				and the learn/unlearn pair).  That is the ROM's own seam,
				and it is the place a modern checker would go in.

				A *session* is a `spell_state`: the chains of dictionaries
				a word is checked against, a dictionary of the words this
				session has been told to skip, and the table of guesses a
				correction fills in.  A script holds it as a frame
				(`spellFrame`, whose `speller` slot is the block's
				address), which is what `SpellDocBegin` answers and every
				other call is given.

				The words themselves are eight-bit through all of this:
				the checker works in Mac Roman, and the curly right
				single quote a paragraph writes is turned into a plain
				apostrophe on the way in (`FixQuotes`) and back again on
				the way out (`RestoreQuotes`), because the dictionaries
				hold the plain one.

	Reconstructed from the MP2x00 US ROM (0x001f1b74-0x001f6600); each
	function cites its origin.
*/

#ifndef __SPELLING_H
#define __SPELLING_H

#ifndef __OBJECTS_H
#include "objects.h"
#endif
#ifndef __UNICODE_H
#include "Unicode.h"
#endif
#include "NewtonMemory.h"
#include "Dictionaries.h"		// TDictChain

// The checker guesses what a word was meant to be by walking the
// dictionary with a *map*: a list of (what is written, what it might
// stand for) pairs.  An alternative is either a spelling or a number -
// the cost of everything after it, and 9 to end the list - which is the
// ROM's own overload of a pointer and a small integer, written out
// here.  `SpellMaps.cpp` is generated by analysis/spellmaps.py.
struct SpellItem
{
	const char*	fText;				// nil: this item is the number below
	long		fValue;
};

struct SpellMapEntry
{
	const char*			fPattern;	// nil ends the map
	const SpellItem*	fItems;
};

const long	kSpellEndOfList = 9;

// ROM 0x0c104490 wc_map - what a character may be read as, and what the
// wildcard `?` may stand for (any letter, at a cost of seven)
extern const SpellMapEntry	gwc_map[];
// ROM 0x0c104658 substitution_map - the letter groups that are written
// for one another ("ph" for "f", and so on)
extern const SpellMapEntry	gsubstitution_map[];

// One guess at what a word was meant to be: how far it is from what was
// written, and the word itself.
struct SpellGuess						// 8 bytes
{
	long	fScore;						// +0x00  kSpellNoGuess until one is put there
	char*	fWord;						// +0x04  0x32 bytes of its own
};

const long	kSpellGuessCount	= 7;		// how many the checker offers
const long	kSpellNoGuess		= 10000;	// the score an empty slot carries
const long	kSpellWordMax		= 0x32;		// the longest word it will look at

// One state of the walk `DoWord` makes: a piece of the word matched
// through one entry of the map, and where that left the trie.  (The
// ROM's is 0x110 bytes; the characters are the rest of it.)
struct word_state
{
	UByte	fList;				// +0x00  the map entry, or one of the three markers
	UByte	fElement;			// +0x01  which of its spellings
	UByte	fCost;				// +0x02  what the map charges for them
	UByte	fFrom;				// +0x03  where in the word this state starts
	UByte	fTake;				// +0x04  how much of it the entry matches
	UByte	fAt;				// +0x05  where in the guess it writes
	UByte	fPut;				// +0x06  how much it writes
	UByte	fEdits;				// +0x07  how many pieces have not matched
	UByte	fResult;			// +0x08  what the trie said at this node
	UByte	fPad[3];
	long	fNode;				// +0x0c  the node it left the trie at
	char	fChars[0x100];		// +0x10  the characters the trie can go on with
};

// what fList holds when it is not a map entry
const UByte	kSpellStateStart	= 0xfe;	// not looked for one yet
const UByte	kSpellStateRest		= 0xfd;	// out of edits: the rest of the word as it stands
const UByte	kSpellStateDone		= 0xff;
const long	kSpellMaxEdits		= 6;
const long	kSpellStateMax		= 0x30;	// how deep the walk may go

// A spelling session.  (The ROM's is 0x54 bytes; here the pointers are
// pointer-sized, so it is not - nothing outside reads it by offset.)
struct spell_state
{
	void*		fWork;					// +0x00  the stack of word_states
	long		fDepth;					// +0x04  how far down it the walk is
	char*		fWord;					// +0x08  the word being matched, bracketed
	long		fWordLength;			// +0x0c
	char*		fScratch;				// +0x10  the spelling being built
	long		fField14;
	SpellGuess*	fGuesses;				// +0x18  kSpellGuessCount of them
	long		fGuessCount;			// +0x1c
	TDictChain*	fChains[kDictChainCount];		// +0x20  the dictionaries a word is checked against
	TDictChain*	fNumberChains[kDictChainCount];	// +0x2c  ... and the ones a number-like word is
	TDictChain*	fChain;					// +0x38  the chain being walked
	Handle		fDictionary;			// +0x3c  the one of it being asked now
	Handle		fIgnore;				// +0x40  the words this session was told to skip
	UByte		fQuoted;				// +0x44  the word had a curly quote in it
	long		fCost;					// +0x48  what the walk has spent so far
	long		fBaseCost;				// +0x4c  what this pass charges on top
	const SpellMapEntry*	fMap;	// +0x50  the map it is walking with
};

extern spell_state*	gSpeller;			// ROM 0x0c101b20 gSpeller - the session being worked on

// The chains a session checks against: every dictionary of the machine's
// list whose `domainType` says it holds words (0x1000, and not the 1 bit
// that marks the ones a lookup must not offer), and separately the ones
// that hold numbers, dates and the like (0x1c2000).
void	InitSpellChains(TDictChain** chains);				// ROM 0x001f1b74 InitSpellChains__FPP10TDictChain
void	InitNumberChains(TDictChain** chains);				// ROM 0x001f40a4 InitNumberChains__FPP10TDictChain

// The frame a script holds a session by, and the session behind one.
Ref			MakeSpellFrame(spell_state* speller);			// ROM 0x001f62ac MakeSpellFrame__FP11spell_state
spell_state*	GetSpeller(RefArg frame);					// ROM 0x001f6314 GetSpeller__FRC6RefVar

// The curly right single quote turned into a plain apostrophe and back:
// the dictionaries hold the plain one, and the paragraph writes the
// curly one.  ==> whether there was one.
Boolean	FixQuotes(char* word);								// ROM 0x001f5d50 FixQuotes__FPc
void	RestoreQuotes(char* word, Boolean quoted);			// ROM 0x001f5da0 RestoreQuotes__FPcUc
// The first character of that one in the string; nil for none.
char*	strpos(char* str, char c);							// ROM 0x001f4b98 strpos__FPcc

// Whether every character of the word is a capital Roman letter (an
// empty word is).  The ROM writes this test out twice; the corrector has
// its own copy.
Boolean	SpellAllCapitals(const UniChar* word);				// ROM 0x001f5d10 (unnamed) - AllCapitals

// The session: SpellDocBegin() answers the frame, and every other call
// is given it.  A session holds a dictionary of its own for the words it
// has been told to skip, and DocEnd writes the user dictionary out when
// anything was learnt.
Ref		FSpellDocBegin(RefArg rcvr);						// ROM 0x001f6360 FSpellDocBegin
Ref		FSpellDocEnd(RefArg rcvr, RefArg frame);			// ROM 0x001f63f8 FSpellDocEnd

// Is this a word?  One dictionary, the whole of the session's chain,
// or the dictionaries that hold numbers.  ==> the id of the dictionary
// it was found in, or -1.
long	ValidateWord(Handle dictionary, char* word, ULong* attribute);	// ROM 0x001f4dc8 ValidateWord__FPP15AirusAParmBlockPcPUl
// ... and the same with the first letter's case turned over as well.
long	ValidateWord2(Handle dictionary, char* word, ULong* attribute);	// ROM 0x001f4e48 ValidateWord2__FPP15AirusAParmBlockPcPUl
long	ValidateWordInChain(char* word, ULong* attribute, Boolean skipped);	// ROM 0x001f4bcc ValidateWordInChain__FPcPUlUc
long	ValidateWordInNumberChain(char* word);				// ROM 0x001f4c68 ValidateWordInNumberChain__FPc

// Whether the word is made of things the checker looks at at all
// (letters and the two apostrophes), and whether a word with a digit in
// it is one the number dictionaries know.
Boolean	CheckSymbols(const UniChar* word);					// ROM 0x001f4cdc CheckSymbols__FPUs
Boolean	CheckNumbers(const UniChar* word);					// ROM 0x001f54e4 CheckNumbers__FPUs

// SpellCheck(frame, word): nil when the spelling is right, true when
// the dictionaries do not have the word at all, 128 when they have it
// only with a capital first letter and 192 when only in capitals.
Ref		FSpellCheck(RefArg rcvr, RefArg frame, RefArg word);	// ROM 0x001f41bc FSpellCheck

// The walk: one state per piece of the word matched so far.
void	InvalidateListState(word_state* state);				// ROM 0x001f5b08 InvalidateListState__FP10word_state
void	GetNextElement(word_state* state);					// ROM 0x001f5c9c GetNextElement__FP10word_state
void	FindList(word_state* state);							// ROM 0x001f5a1c FindList__FP10word_state
UByte	BumpListState(word_state* state);					// ROM 0x001f59d0 BumpListState__FP10word_state
long	GetCurrentList(word_state* state);					// ROM 0x001f5950 GetCurrentList__FP10word_state
void	GetNextList(word_state* state);						// ROM 0x001f5994 GetNextList__FP10word_state
const char*	GetCurrentElement(word_state* state);		// ROM 0x001f5b14 GetCurrentElement__FP10word_state
void	GetNextCharacters(word_state* state);				// ROM 0x001f5570 GetNextCharacters__FP10word_state
void	ResetWordState(char* word, const SpellMapEntry* map, long cost);	// ROM 0x001f4d44 ResetWordState__FPcPPvl
long	ScoreGuess(void);									// ROM 0x001f6250 ScoreGuess__Fv
void	DoWord(void);										// ROM 0x001f55ac DoWord__Fv

// The guesses: seven of them, nearest first.
void	FixCapitalization(char* word, ULong attribute);		// ROM 0x001f5cac FixCapitalization__FPcUl
long	MeasureDistance(const char* a, long aLength, const char* b, long bLength);	// ROM 0x001f612c MeasureDistance__FPclT1T2
long	FindGuess(const char* word);							// ROM 0x001f5e68 FindGuess__FPc
void	DeleteGuess(long at);								// ROM 0x001f5ebc DeleteGuess__Fl
Boolean	InsertGuess(const char* word, long score);			// ROM 0x001f5f54 InsertGuess__FPcl
void	ReportGuess(const char* word, ULong attribute, long score);	// ROM 0x001f5df0 ReportGuess__FPcUll

// The five kinds of change a misspelling is put through.
void	SwapTwo(char* word, long a, long b);				// ROM 0x001f4f7c SwapTwo__FPclT2
void	DoTranspositions(const char* word);					// ROM 0x001f4f90 DoTranspositions__FPc
void	DoTwoTranspositions(const char* word);				// ROM 0x001f5068 DoTwoTranspositions__FPc
void	DoDeletions(const char* word);						// ROM 0x001f5170 DoDeletions__FPc
void	DoInsertions(const char* word);						// ROM 0x001f5248 DoInsertions__FPc
void	DoSubstitutions(char* word);							// ROM 0x001f546c DoSubstitutions__FPc
void	DoWordSplits(const char* word);						// ROM 0x001f52f0 DoWordSplits__FPc
void	CheckWord(char* word);								// ROM 0x001f4aac CheckWord__FPc
void	CorrectWordInChain(char* word);						// ROM 0x001f49ac CorrectWordInChain__FPc

// The dictionaries of a chain pinned while the guessing runs.
void	LockChain(TDictChain* chain);						// ROM 0x001f4a14 LockChain__FP10TDictChain
void	UnlockChain(TDictChain* chain);						// ROM 0x001f4a60 UnlockChain__FP10TDictChain

// What was taken off the word put back on a guess.
Ref		RestorePunctSymbols(RefArg word, const UniChar* leading, const UniChar* trailing, Boolean capitalized, Boolean allCapitals);	// ROM 0x001f4828 RestorePunctSymbols__FRC6RefVarPUsT2UcT4

// SpellCorrect(frame, word): what the word might have been meant to be,
// as an array of spellings, nearest first.
Ref		FSpellCorrect(RefArg rcvr, RefArg frame, RefArg word);	// ROM 0x001f44c8 FSpellCorrect

// SpellSkip(frame, word): a word this session is to stop complaining
// about.  It goes into the session's own dictionary and goes with it.
Ref		FSpellSkip(RefArg rcvr, RefArg frame, RefArg word);	// ROM 0x001f651c FSpellSkip

void	RegisterSpellingNatives(void);

#endif	/* __SPELLING_H */
