// Generated by tools/newton-rom/analysis/spellmaps.py; do not edit.
//   python tools/newton-rom/analysis/spellmaps.py <build_dir> -o src/recognition
// The spelling checker's character maps, out of the 2.1 (717006)
// ROM.  Each entry is a pattern and the spellings it may stand for; a
// number among the spellings is the cost of everything after it, and 9
// ends the list.

#include "Spelling.h"

static const SpellItem	kwc_map_0[] =
{
	{ "" }, { nil, 9 }
};
static const SpellItem	kwc_map_1[] =
{
	{ "'" }, { nil, 9 }
};
static const SpellItem	kwc_map_2[] =
{
	{ nil, 7 }, { "'" }, { "e" }, { "t" }, { "a" }, { "i" }, { "o" }, { "n" }, { "s" }, { "h" }, { "r" }, { "d" }, { "l" }, { "u" }, { "b" }, { "c" }, { "p" }, { "g" }, { "f" }, { "j" }, { "k" }, { "m" }, { "q" }, { "v" }, { "w" }, { "x" }, { "y" }, { "z" }, { nil, 9 }
};
static const SpellItem	kwc_map_3[] =
{
	{ "" }, { nil, 9 }
};
static const SpellItem	kwc_map_4[] =
{
	{ "A" }, { nil, 2 }, { "a" }, { nil, 9 }
};
static const SpellItem	kwc_map_5[] =
{
	{ "B" }, { nil, 2 }, { "b" }, { nil, 9 }
};
static const SpellItem	kwc_map_6[] =
{
	{ "C" }, { nil, 2 }, { "c" }, { nil, 9 }
};
static const SpellItem	kwc_map_7[] =
{
	{ "D" }, { nil, 2 }, { "d" }, { nil, 9 }
};
static const SpellItem	kwc_map_8[] =
{
	{ "E" }, { nil, 2 }, { "e" }, { nil, 9 }
};
static const SpellItem	kwc_map_9[] =
{
	{ "F" }, { nil, 2 }, { "g" }, { nil, 9 }
};
static const SpellItem	kwc_map_10[] =
{
	{ "G" }, { nil, 2 }, { "g" }, { nil, 9 }
};
static const SpellItem	kwc_map_11[] =
{
	{ "H" }, { nil, 2 }, { "h" }, { nil, 9 }
};
static const SpellItem	kwc_map_12[] =
{
	{ "I" }, { nil, 2 }, { "i" }, { nil, 9 }
};
static const SpellItem	kwc_map_13[] =
{
	{ "J" }, { nil, 2 }, { "j" }, { nil, 9 }
};
static const SpellItem	kwc_map_14[] =
{
	{ "K" }, { nil, 2 }, { "k" }, { nil, 9 }
};
static const SpellItem	kwc_map_15[] =
{
	{ "L" }, { nil, 2 }, { "l" }, { nil, 9 }
};
static const SpellItem	kwc_map_16[] =
{
	{ "M" }, { nil, 2 }, { "m" }, { nil, 9 }
};
static const SpellItem	kwc_map_17[] =
{
	{ "N" }, { nil, 2 }, { "n" }, { nil, 9 }
};
static const SpellItem	kwc_map_18[] =
{
	{ "O" }, { nil, 2 }, { "o" }, { nil, 9 }
};
static const SpellItem	kwc_map_19[] =
{
	{ "P" }, { nil, 2 }, { "p" }, { nil, 9 }
};
static const SpellItem	kwc_map_20[] =
{
	{ "Q" }, { nil, 2 }, { "q" }, { nil, 9 }
};
static const SpellItem	kwc_map_21[] =
{
	{ "R" }, { nil, 2 }, { "r" }, { nil, 9 }
};
static const SpellItem	kwc_map_22[] =
{
	{ "S" }, { nil, 2 }, { "s" }, { nil, 9 }
};
static const SpellItem	kwc_map_23[] =
{
	{ "T" }, { nil, 2 }, { "t" }, { nil, 9 }
};
static const SpellItem	kwc_map_24[] =
{
	{ "U" }, { nil, 2 }, { "u" }, { nil, 9 }
};
static const SpellItem	kwc_map_25[] =
{
	{ "V" }, { nil, 2 }, { "v" }, { nil, 9 }
};
static const SpellItem	kwc_map_26[] =
{
	{ "W" }, { nil, 2 }, { "w" }, { nil, 9 }
};
static const SpellItem	kwc_map_27[] =
{
	{ "X" }, { nil, 2 }, { "x" }, { nil, 9 }
};
static const SpellItem	kwc_map_28[] =
{
	{ "Y" }, { nil, 2 }, { "y" }, { nil, 9 }
};
static const SpellItem	kwc_map_29[] =
{
	{ "Z" }, { nil, 2 }, { "z" }, { nil, 9 }
};
static const SpellItem	kwc_map_30[] =
{
	{ "a" }, { nil, 2 }, { "A" }, { nil, 9 }
};
static const SpellItem	kwc_map_31[] =
{
	{ "b" }, { nil, 2 }, { "B" }, { nil, 9 }
};
static const SpellItem	kwc_map_32[] =
{
	{ "c" }, { nil, 2 }, { "C" }, { nil, 9 }
};
static const SpellItem	kwc_map_33[] =
{
	{ "d" }, { nil, 2 }, { "D" }, { nil, 9 }
};
static const SpellItem	kwc_map_34[] =
{
	{ "e" }, { nil, 2 }, { "E" }, { nil, 9 }
};
static const SpellItem	kwc_map_35[] =
{
	{ "f" }, { nil, 2 }, { "F" }, { nil, 9 }
};
static const SpellItem	kwc_map_36[] =
{
	{ "g" }, { nil, 2 }, { "G" }, { nil, 9 }
};
static const SpellItem	kwc_map_37[] =
{
	{ "h" }, { nil, 2 }, { "H" }, { nil, 9 }
};
static const SpellItem	kwc_map_38[] =
{
	{ "i" }, { nil, 2 }, { "I" }, { nil, 9 }
};
static const SpellItem	kwc_map_39[] =
{
	{ "j" }, { nil, 2 }, { "J" }, { nil, 9 }
};
static const SpellItem	kwc_map_40[] =
{
	{ "k" }, { nil, 2 }, { "K" }, { nil, 9 }
};
static const SpellItem	kwc_map_41[] =
{
	{ "l" }, { nil, 2 }, { "L" }, { nil, 9 }
};
static const SpellItem	kwc_map_42[] =
{
	{ "m" }, { nil, 2 }, { "M" }, { nil, 9 }
};
static const SpellItem	kwc_map_43[] =
{
	{ "n" }, { nil, 2 }, { "N" }, { nil, 9 }
};
static const SpellItem	kwc_map_44[] =
{
	{ "o" }, { nil, 2 }, { "O" }, { nil, 9 }
};
static const SpellItem	kwc_map_45[] =
{
	{ "p" }, { nil, 2 }, { "P" }, { nil, 9 }
};
static const SpellItem	kwc_map_46[] =
{
	{ "q" }, { nil, 2 }, { "Q" }, { nil, 9 }
};
static const SpellItem	kwc_map_47[] =
{
	{ "r" }, { nil, 2 }, { "R" }, { nil, 9 }
};
static const SpellItem	kwc_map_48[] =
{
	{ "s" }, { nil, 2 }, { "S" }, { nil, 9 }
};
static const SpellItem	kwc_map_49[] =
{
	{ "t" }, { nil, 2 }, { "T" }, { nil, 9 }
};
static const SpellItem	kwc_map_50[] =
{
	{ "u" }, { nil, 2 }, { "U" }, { nil, 9 }
};
static const SpellItem	kwc_map_51[] =
{
	{ "v" }, { nil, 2 }, { "V" }, { nil, 9 }
};
static const SpellItem	kwc_map_52[] =
{
	{ "w" }, { nil, 2 }, { "W" }, { nil, 9 }
};
static const SpellItem	kwc_map_53[] =
{
	{ "x" }, { nil, 2 }, { "X" }, { nil, 9 }
};
static const SpellItem	kwc_map_54[] =
{
	{ "y" }, { nil, 2 }, { "Y" }, { nil, 9 }
};
static const SpellItem	kwc_map_55[] =
{
	{ "z" }, { nil, 2 }, { "Z" }, { nil, 9 }
};

// ROM 0x0c104490 wc_map
const SpellMapEntry	gwc_map[] =
{
	{ "$", kwc_map_0 },
	{ "'", kwc_map_1 },
	{ "?", kwc_map_2 },
	{ "@", kwc_map_3 },
	{ "A", kwc_map_4 },
	{ "B", kwc_map_5 },
	{ "C", kwc_map_6 },
	{ "D", kwc_map_7 },
	{ "E", kwc_map_8 },
	{ "F", kwc_map_9 },
	{ "G", kwc_map_10 },
	{ "H", kwc_map_11 },
	{ "I", kwc_map_12 },
	{ "J", kwc_map_13 },
	{ "K", kwc_map_14 },
	{ "L", kwc_map_15 },
	{ "M", kwc_map_16 },
	{ "N", kwc_map_17 },
	{ "O", kwc_map_18 },
	{ "P", kwc_map_19 },
	{ "Q", kwc_map_20 },
	{ "R", kwc_map_21 },
	{ "S", kwc_map_22 },
	{ "T", kwc_map_23 },
	{ "U", kwc_map_24 },
	{ "V", kwc_map_25 },
	{ "W", kwc_map_26 },
	{ "X", kwc_map_27 },
	{ "Y", kwc_map_28 },
	{ "Z", kwc_map_29 },
	{ "a", kwc_map_30 },
	{ "b", kwc_map_31 },
	{ "c", kwc_map_32 },
	{ "d", kwc_map_33 },
	{ "e", kwc_map_34 },
	{ "f", kwc_map_35 },
	{ "g", kwc_map_36 },
	{ "h", kwc_map_37 },
	{ "i", kwc_map_38 },
	{ "j", kwc_map_39 },
	{ "k", kwc_map_40 },
	{ "l", kwc_map_41 },
	{ "m", kwc_map_42 },
	{ "n", kwc_map_43 },
	{ "o", kwc_map_44 },
	{ "p", kwc_map_45 },
	{ "q", kwc_map_46 },
	{ "r", kwc_map_47 },
	{ "s", kwc_map_48 },
	{ "t", kwc_map_49 },
	{ "u", kwc_map_50 },
	{ "v", kwc_map_51 },
	{ "w", kwc_map_52 },
	{ "x", kwc_map_53 },
	{ "y", kwc_map_54 },
	{ "z", kwc_map_55 },
	{ nil, nil }
};

static const SpellItem	ksubstitution_map_0[] =
{
	{ "" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_1[] =
{
	{ "'" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_2[] =
{
	{ "" }, { nil, 3 }, { "e" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_3[] =
{
	{ "A" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_4[] =
{
	{ "B" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_5[] =
{
	{ "C" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_6[] =
{
	{ "D" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_7[] =
{
	{ "E" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_8[] =
{
	{ "F" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_9[] =
{
	{ "G" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_10[] =
{
	{ "H" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_11[] =
{
	{ "I" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_12[] =
{
	{ "J" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_13[] =
{
	{ "K" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_14[] =
{
	{ "L" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_15[] =
{
	{ "M" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_16[] =
{
	{ "N" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_17[] =
{
	{ "O" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_18[] =
{
	{ "P" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_19[] =
{
	{ "Q" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_20[] =
{
	{ "R" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_21[] =
{
	{ "S" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_22[] =
{
	{ "T" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_23[] =
{
	{ "U" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_24[] =
{
	{ "V" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_25[] =
{
	{ "W" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_26[] =
{
	{ "X" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_27[] =
{
	{ "Y" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_28[] =
{
	{ "Z" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_29[] =
{
	{ "a" }, { nil, 2 }, { "A" }, { nil, 3 }, { "ai" }, { nil, 4 }, { "ay" }, { "ah" }, { "aa" }, { "aw" }, { nil, 6 }, { "ae" }, { "au" }, { "augh" }, { "eig" }, { "eigh" }, { "ey" }, { "al" }, { "e" }, { "ea" }, { "ei" }, { "i" }, { "ia" }, { "ie" }, { "io" }, { "o" }, { "oa" }, { "oe" }, { "ou" }, { "ow" }, { "u" }, { "ua" }, { "ue" }, { "ao" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_30[] =
{
	{ "aa" }, { nil, 6 }, { "a" }, { "ae" }, { "ah" }, { "ai" }, { "au" }, { "augh" }, { "aw" }, { "awe" }, { "ay" }, { "e" }, { "ea" }, { "eau" }, { "ei" }, { "eo" }, { "o" }, { "oa" }, { "ou" }, { "ough" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_31[] =
{
	{ "ae" }, { nil, 4 }, { "ea" }, { "e" }, { nil, 6 }, { "a" }, { "aa" }, { "ai" }, { "ao" }, { "au" }, { "ay" }, { "ee" }, { "ei" }, { "eig" }, { "eigh" }, { "eo" }, { "ey" }, { "i" }, { "ie" }, { "oe" }, { "u" }, { "ui" }, { "y" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_32[] =
{
	{ "ah" }, { nil, 4 }, { "a" }, { "aa" }, { "aw" }, { nil, 6 }, { "al" }, { "au" }, { "augh" }, { "awe" }, { "e" }, { "ea" }, { "eau" }, { "eo" }, { "i" }, { "o" }, { "oa" }, { "ou" }, { "ough" }, { "ua" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_33[] =
{
	{ "ai" }, { nil, 3 }, { "a" }, { "ay" }, { nil, 4 }, { "e" }, { "ei" }, { nil, 6 }, { "ae" }, { "ao" }, { "au" }, { "ea" }, { "ee" }, { "eig" }, { "eigh" }, { "eo" }, { "ey" }, { "i" }, { "u" }, { "ui" }, { "oe" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_34[] =
{
	{ "ain" }, { nil, 4 }, { "en" }, { nil, 6 }, { "gn" }, { "kn" }, { "mn" }, { "n" }, { "nn" }, { "on" }, { "pn" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_35[] =
{
	{ "al" }, { nil, 4 }, { "le" }, { "el" }, { "yl" }, { nil, 6 }, { "all" }, { "il" }, { "l" }, { "lh" }, { "ll" }, { "ln" }, { "ul" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_36[] =
{
	{ "all" }, { nil, 4 }, { "al" }, { "el" }, { "le" }, { nil, 6 }, { "il" }, { "l" }, { "lh" }, { "ll" }, { "ln" }, { "ul" }, { "yl" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_37[] =
{
	{ "au" }, { nil, 4 }, { "a" }, { "ay" }, { "ey" }, { "ei" }, { "ah" }, { "aw" }, { "ei" }, { nil, 6 }, { "aa" }, { "ae" }, { "ai" }, { "ae" }, { "ao" }, { "aue" }, { "augh" }, { "awe" }, { "e" }, { "ea" }, { "eau" }, { "eig" }, { "eigh" }, { "eo" }, { "ui" }, { "o" }, { "oa" }, { "oe" }, { "oh" }, { "oo" }, { "ou" }, { "ough" }, { "ow" }, { "ua" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_38[] =
{
	{ "aw" }, { nil, 4 }, { "ah" }, { "au" }, { "awe" }, { nil, 6 }, { "a" }, { "aa" }, { "augh" }, { "e" }, { "ea" }, { "eau" }, { "eo" }, { "i" }, { "o" }, { "oa" }, { "ou" }, { "ough" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_39[] =
{
	{ "awy" }, { nil, 6 }, { "aw" }, { "eu" }, { "oi" }, { "oy" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_40[] =
{
	{ "ay" }, { nil, 4 }, { "ai" }, { "ey" }, { "ei" }, { "a" }, { "eigh" }, { nil, 6 }, { "ae" }, { "aigh" }, { "y" }, { "eig" }, { "aye" }, { "i" }, { "igh" }, { "ao" }, { "au" }, { "e" }, { "ea" }, { "ee" }, { "ui" }, { "ie" }, { "uy" }, { "ye" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_41[] =
{
	{ "b" }, { nil, 2 }, { "B" }, { nil, 3 }, { "bb" }, { nil, 6 }, { "bh" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_42[] =
{
	{ "bb" }, { nil, 3 }, { "b" }, { nil, 6 }, { "bh" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_43[] =
{
	{ "bh" }, { nil, 6 }, { "b" }, { "bb" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_44[] =
{
	{ "bt" }, { nil, 4 }, { "t" }, { "ght" }, { nil, 6 }, { "ed" }, { "te" }, { "th" }, { "tt" }, { "tw" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_45[] =
{
	{ "c" }, { nil, 2 }, { "C" }, { nil, 3 }, { "ck" }, { "cc" }, { "k" }, { "s" }, { nil, 4 }, { "kk" }, { nil, 6 }, { "ch" }, { "ci" }, { "cq" }, { "cqu" }, { "cu" }, { "kh" }, { "lk" }, { "q" }, { "qu" }, { "que" }, { "sc" }, { "sch" }, { "sh" }, { "ss" }, { "st" }, { "ti" }, { "ts" }, { "tz" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_46[] =
{
	{ "cc" }, { nil, 3 }, { "c" }, { "kk" }, { "ck" }, { "k" }, { nil, 4 }, { "ch" }, { "s" }, { nil, 6 }, { "cq" }, { "cqu" }, { "cu" }, { "kh" }, { "lk" }, { "q" }, { "qu" }, { "que" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_47[] =
{
	{ "cch" }, { nil, 6 }, { "c" }, { "cc" }, { "ch" }, { "ck" }, { "cq" }, { "cqu" }, { "cu" }, { "k" }, { "kh" }, { "kk" }, { "lk" }, { "q" }, { "qu" }, { "que" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_48[] =
{
	{ "ch" }, { nil, 4 }, { "cc" }, { "tch" }, { nil, 6 }, { "c" }, { "ck" }, { "cq" }, { "cqu" }, { "cu" }, { "cz" }, { "gh" }, { "k" }, { "kh" }, { "kk" }, { "lk" }, { "q" }, { "qu" }, { "que" }, { "si" }, { "te" }, { "ti" }, { "tu" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_49[] =
{
	{ "chm" }, { nil, 6 }, { "gm" }, { "lm" }, { "m" }, { "mb" }, { "mh" }, { "mm" }, { "mn" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_50[] =
{
	{ "cht" }, { nil, 6 }, { "bt" }, { "ct" }, { "ed" }, { "ght" }, { "t" }, { "te" }, { "th" }, { "tt" }, { "tw" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_51[] =
{
	{ "ci" }, { nil, 4 }, { "ti" }, { nil, 6 }, { "c" }, { "ch" }, { "ps" }, { "s" }, { "sc" }, { "sch" }, { "sh" }, { "ss" }, { "st" }, { "ts" }, { "tz" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_52[] =
{
	{ "ck" }, { nil, 4 }, { "k" }, { "kk" }, { "c" }, { nil, 6 }, { "cc" }, { "cch" }, { "ch" }, { "cq" }, { "cqu" }, { "cu" }, { "kh" }, { "lk" }, { "q" }, { "qu" }, { "que" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_53[] =
{
	{ "cks" }, { nil, 4 }, { "cs" }, { "ks" }, { "x" }, { "xh" }, { nil, 6 }, { "chs" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_54[] =
{
	{ "cq" }, { nil, 6 }, { "c" }, { "cc" }, { "cch" }, { "ch" }, { "ck" }, { "cqu" }, { "cu" }, { "k" }, { "kh" }, { "kk" }, { "lk" }, { "q" }, { "qu" }, { "que" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_55[] =
{
	{ "cqu" }, { nil, 6 }, { "c" }, { "cc" }, { "cch" }, { "ch" }, { "ck" }, { "cq" }, { "cu" }, { "k" }, { "kh" }, { "kk" }, { "lk" }, { "q" }, { "qu" }, { "que" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_56[] =
{
	{ "cs" }, { nil, 4 }, { "ks" }, { "cks" }, { "x" }, { "xh" }, { nil, 6 }, { "chs" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_57[] =
{
	{ "cu" }, { nil, 6 }, { "c" }, { "cc" }, { "cch" }, { "ch" }, { "ck" }, { "cq" }, { "cqu" }, { "k" }, { "kh" }, { "lk" }, { "q" }, { "qu" }, { "que" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_58[] =
{
	{ "cz" }, { nil, 4 }, { "ts" }, { "tz" }, { "z" }, { nil, 6 }, { "c" }, { "ch" }, { "s" }, { "sc" }, { "si" }, { "ss" }, { "tch" }, { "te" }, { "ti" }, { "tu" }, { "x" }, { "zz" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_59[] =
{
	{ "d" }, { nil, 2 }, { "D" }, { nil, 3 }, { "dd" }, { nil, 4 }, { "ed" }, { "ld" }, { nil, 6 }, { "dh" }, { "t" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_60[] =
{
	{ "dd" }, { nil, 3 }, { "d" }, { nil, 4 }, { "ed" }, { nil, 6 }, { "dh" }, { "ld" }, { "th" }, { "the" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_61[] =
{
	{ "dg" }, { nil, 3 }, { "dge" }, { nil, 4 }, { "j" }, { nil, 6 }, { "ch" }, { "di" }, { "dj" }, { "d" }, { "g" }, { "gg" }, { "gh" }, { "gi" }, { "gu" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_62[] =
{
	{ "dge" }, { nil, 3 }, { "dg" }, { nil, 4 }, { "g" }, { "dj" }, { nil, 6 }, { "ch" }, { "di" }, { "d" }, { "gg" }, { "gh" }, { "gi" }, { "gu" }, { "j" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_63[] =
{
	{ "dh" }, { nil, 6 }, { "d" }, { "dd" }, { "ed" }, { "ld" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_64[] =
{
	{ "dj" }, { nil, 6 }, { "ch" }, { "dg" }, { "dge" }, { "di" }, { "d" }, { "g" }, { "gg" }, { "gi" }, { "j" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_65[] =
{
	{ "e" }, { nil, 2 }, { "E" }, { nil, 3 }, { "ee" }, { "ea" }, { nil, 4 }, { "ie" }, { "a" }, { "ae" }, { "ai" }, { "au" }, { "aw" }, { "ay" }, { "i" }, { "y" }, { nil, 6 }, { "" }, { "ei" }, { "eo" }, { "eu" }, { "ia" }, { "io" }, { "o" }, { "oa" }, { "oe" }, { "oi" }, { "oo" }, { "ou" }, { "ow" }, { "oy" }, { "u" }, { "ua" }, { "ue" }, { "ui" }, { "w" }, { "ye" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_66[] =
{
	{ "e" }, { nil, 3 }, { "" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_67[] =
{
	{ "eau" }, { nil, 6 }, { "a" }, { "ao" }, { "au" }, { "eo" }, { "o" }, { "oa" }, { "oe" }, { "oh" }, { "oo" }, { "ou" }, { "ough" }, { "ow" }, { "ua" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_68[] =
{
	{ "ed" }, { nil, 6 }, { "bt" }, { "d" }, { "dd" }, { "de" }, { "dh" }, { "ght" }, { "ld" }, { "t" }, { "te" }, { "th" }, { "tt" }, { "tw" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_69[] =
{
	{ "ee" }, { nil, 3 }, { "e" }, { "ea" }, { nil, 4 }, { "ae" }, { "ay" }, { "ey" }, { nil, 6 }, { "ei" }, { "eo" }, { "i" }, { "ie" }, { "oe" }, { "y" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_70[] =
{
	{ "ei" }, { nil, 3 }, { "ie" }, { nil, 4 }, { "ai" }, { "ay" }, { "ey" }, { "ee" }, { "ea" }, { "e" }, { nil, 6 }, { "i" }, { "a" }, { "ae" }, { "ao" }, { "au" }, { "eo" }, { "oe" }, { "ui" }, { "y" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_71[] =
{
	{ "el" }, { nil, 4 }, { "le" }, { "al" }, { "yl" }, { nil, 6 }, { "all" }, { "il" }, { "l" }, { "lh" }, { "ll" }, { "ln" }, { "ul" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_72[] =
{
	{ "en" }, { nil, 4 }, { "ain" }, { "ing" }, { nil, 6 }, { "gn" }, { "kn" }, { "mn" }, { "n" }, { "nn" }, { "on" }, { "pn" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_73[] =
{
	{ "eo" }, { nil, 6 }, { "eou" }, { "oe" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_74[] =
{
	{ "eu" }, { nil, 4 }, { "ew" }, { "ue" }, { nil, 6 }, { "aw" }, { "awe" }, { "awy" }, { "ieu" }, { "o" }, { "oe" }, { "oeu" }, { "oi" }, { "oo" }, { "ou" }, { "oy" }, { "u" }, { "ui" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_75[] =
{
	{ "ew" }, { nil, 4 }, { "eu" }, { nil, 6 }, { "ieu" }, { "o" }, { "oe" }, { "oeu" }, { "oo" }, { "ou" }, { "u" }, { "ue" }, { "ui" }, { "w" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_76[] =
{
	{ "ey" }, { nil, 3 }, { "ay" }, { nil, 4 }, { "ai" }, { "ei" }, { "eigh" }, { nil, 6 }, { "a" }, { "ae" }, { "aigh" }, { "ao" }, { "au" }, { "e" }, { "ea" }, { "ee" }, { "eig" }, { "ui" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_77[] =
{
	{ "f" }, { nil, 2 }, { "F" }, { nil, 3 }, { "ff" }, { nil, 4 }, { "gh" }, { "lf" }, { "ph" }, { nil, 6 }, { "v" }, { "vv" }, { "w" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_78[] =
{
	{ "ff" }, { nil, 3 }, { "f" }, { nil, 4 }, { "gh" }, { "lf" }, { "ph" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_79[] =
{
	{ "g" }, { nil, 2 }, { "G" }, { nil, 3 }, { "gg" }, { nil, 4 }, { "dg" }, { "dge" }, { "j" }, { "dj" }, { "gue" }, { nil, 6 }, { "ch" }, { "di" }, { "gh" }, { "gi" }, { "d" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_80[] =
{
	{ "gg" }, { nil, 3 }, { "g" }, { nil, 6 }, { "ch" }, { "dg" }, { "d" }, { "di" }, { "dj" }, { "gh" }, { "gi" }, { "gu" }, { "j" }, { "gue" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_81[] =
{
	{ "gh" }, { nil, 4 }, { "lf" }, { "ph" }, { "f" }, { "ff" }, { nil, 6 }, { "c" }, { "cc" }, { "ch" }, { "ck" }, { "cq" }, { "cqu" }, { "cu" }, { "dg" }, { "gu" }, { "gue" }, { "g" }, { "gg" }, { "k" }, { "kh" }, { "lk" }, { "q" }, { "qu" }, { "que" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_82[] =
{
	{ "ght" }, { nil, 4 }, { "t" }, { "te" }, { nil, 6 }, { "bt" }, { "ct" }, { "ed" }, { "th" }, { "tt" }, { "tw" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_83[] =
{
	{ "gi" }, { nil, 6 }, { "ch" }, { "dg" }, { "di" }, { "dj" }, { "d" }, { "g" }, { "gg" }, { "j" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_84[] =
{
	{ "gm" }, { nil, 4 }, { "m" }, { "mm" }, { nil, 6 }, { "chm" }, { "lm" }, { "mb" }, { "mh" }, { "mn" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_85[] =
{
	{ "gn" }, { nil, 4 }, { "n" }, { nil, 6 }, { "ain" }, { "en" }, { "kn" }, { "mn" }, { "nn" }, { "on" }, { "pn" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_86[] =
{
	{ "gu" }, { nil, 6 }, { "dg" }, { "g" }, { "gg" }, { "gh" }, { "gue" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_87[] =
{
	{ "h" }, { nil, 2 }, { "H" }, { nil, 4 }, { "wh" }, { "hh" }, { nil, 6 }, { "ch" }, { "g" }, { "j" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_88[] =
{
	{ "hw" }, { nil, 4 }, { "wh" }, { nil, 6 }, { "ju" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_89[] =
{
	{ "i" }, { nil, 2 }, { "I" }, { nil, 3 }, { "igh" }, { "y" }, { nil, 4 }, { "ie" }, { "ei" }, { nil, 6 }, { "a" }, { "ai" }, { "ay" }, { "aye" }, { "e" }, { "ea" }, { "ee" }, { "ey" }, { "eye" }, { "ia" }, { "o" }, { "u" }, { "ui" }, { "uy" }, { "ye" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_90[] =
{
	{ "ia" }, { nil, 4 }, { "ai" }, { nil, 6 }, { "a" }, { "ah" }, { "e" }, { "ea" }, { "eau" }, { "ee" }, { "ei" }, { "i" }, { "ie" }, { "io" }, { "o" }, { "oa" }, { "oe" }, { "oi" }, { "oo" }, { "ou" }, { "u" }, { "ue" }, { "ui" }, { "y" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_91[] =
{
	{ "ie" }, { nil, 3 }, { "ei" }, { nil, 4 }, { "ee" }, { "ea" }, { "ye" }, { nil, 6 }, { "e" }, { "i" }, { "ay" }, { "aye" }, { "ey" }, { "eye" }, { "igh" }, { "ae" }, { "ai" }, { "eo" }, { "oe" }, { "uy" }, { "y" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_92[] =
{
	{ "ieu" }, { nil, 6 }, { "eu" }, { "ew" }, { "o" }, { "oe" }, { "oeu" }, { "oo" }, { "ou" }, { "u" }, { "ue" }, { "ui" }, { "w" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_93[] =
{
	{ "il" }, { nil, 6 }, { "al" }, { "all" }, { "el" }, { "l" }, { "le" }, { "lh" }, { "ll" }, { "ln" }, { "ul" }, { "yl" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_94[] =
{
	{ "io" }, { nil, 6 }, { "a" }, { "ah" }, { "ai" }, { "e" }, { "ea" }, { "eau" }, { "ei" }, { "i" }, { "ia" }, { "o" }, { "oa" }, { "oe" }, { "oi" }, { "oo" }, { "ou" }, { "u" }, { "ue" }, { "y" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_95[] =
{
	{ "j" }, { nil, 2 }, { "J" }, { nil, 4 }, { "dg" }, { "dj" }, { "g" }, { nil, 6 }, { "ch" }, { "di" }, { "d" }, { "gg" }, { "gi" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_96[] =
{
	{ "k" }, { nil, 2 }, { "K" }, { nil, 3 }, { "kk" }, { nil, 4 }, { "ck" }, { "cc" }, { nil, 6 }, { "c" }, { "cch" }, { "ch" }, { "cq" }, { "cqu" }, { "cu" }, { "kh" }, { "lk" }, { "q" }, { "qu" }, { "que" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_97[] =
{
	{ "kh" }, { nil, 6 }, { "c" }, { "cc" }, { "cch" }, { "ch" }, { "ck" }, { "cq" }, { "cqu" }, { "cu" }, { "k" }, { "kk" }, { "lk" }, { "q" }, { "qu" }, { "que" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_98[] =
{
	{ "kk" }, { nil, 3 }, { "k" }, { nil, 4 }, { "ck" }, { "cc" }, { nil, 6 }, { "c" }, { "cch" }, { "ch" }, { "cq" }, { "cqu" }, { "cu" }, { "kh" }, { "lk" }, { "q" }, { "qu" }, { "que" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_99[] =
{
	{ "kn" }, { nil, 4 }, { "n" }, { nil, 6 }, { "ain" }, { "en" }, { "gn" }, { "mn" }, { "nn" }, { "on" }, { "pn" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_100[] =
{
	{ "ks" }, { nil, 4 }, { "cs" }, { "cks" }, { "x" }, { "xh" }, { nil, 6 }, { "chs" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_101[] =
{
	{ "kw" }, { nil, 6 }, { "cq" }, { "cqu" }, { "q" }, { "qu" }, { "que" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_102[] =
{
	{ "l" }, { nil, 2 }, { "L" }, { nil, 3 }, { "ll" }, { nil, 4 }, { "al" }, { "le" }, { "el" }, { nil, 6 }, { "all" }, { "il" }, { "lh" }, { "ln" }, { "ul" }, { "yl" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_103[] =
{
	{ "ld" }, { nil, 6 }, { "d" }, { "dd" }, { "dh" }, { "ed" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_104[] =
{
	{ "le" }, { nil, 4 }, { "al" }, { "el" }, { nil, 6 }, { "all" }, { "il" }, { "l" }, { "lh" }, { "ll" }, { "ln" }, { "ul" }, { "yl" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_105[] =
{
	{ "lf" }, { nil, 4 }, { "f" }, { "ff" }, { "gh" }, { "ph" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_106[] =
{
	{ "lh" }, { nil, 6 }, { "al" }, { "all" }, { "el" }, { "il" }, { "l" }, { "le" }, { "ll" }, { "ln" }, { "ul" }, { "yl" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_107[] =
{
	{ "lk" }, { nil, 6 }, { "c" }, { "cc" }, { "ch" }, { "ck" }, { "cq" }, { "cqu" }, { "cu" }, { "k" }, { "kh" }, { "q" }, { "qu" }, { "que" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_108[] =
{
	{ "ll" }, { nil, 3 }, { "l" }, { nil, 6 }, { "al" }, { "all" }, { "el" }, { "il" }, { "le" }, { "lh" }, { "ln" }, { "ul" }, { "yl" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_109[] =
{
	{ "lm" }, { nil, 6 }, { "chm" }, { "gm" }, { "m" }, { "mb" }, { "mh" }, { "mm" }, { "mn" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_110[] =
{
	{ "ln" }, { nil, 6 }, { "al" }, { "all" }, { "el" }, { "il" }, { "l" }, { "le" }, { "lh" }, { "ll" }, { "ul" }, { "yl" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_111[] =
{
	{ "m" }, { nil, 2 }, { "M" }, { nil, 3 }, { "mm" }, { nil, 4 }, { "me" }, { nil, 6 }, { "chm" }, { "gm" }, { "lm" }, { "mb" }, { "mh" }, { "mn" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_112[] =
{
	{ "mb" }, { nil, 4 }, { "m" }, { "mm" }, { nil, 6 }, { "chm" }, { "gm" }, { "lm" }, { "mh" }, { "mn" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_113[] =
{
	{ "mh" }, { nil, 6 }, { "chm" }, { "gm" }, { "lm" }, { "m" }, { "mb" }, { "mm" }, { "mn" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_114[] =
{
	{ "mm" }, { nil, 3 }, { "m" }, { nil, 4 }, { "mb" }, { "me" }, { nil, 6 }, { "chm" }, { "gm" }, { "lm" }, { "mh" }, { "mn" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_115[] =
{
	{ "mn" }, { nil, 6 }, { "chm" }, { "gm" }, { "lm" }, { "m" }, { "mb" }, { "mh" }, { "mm" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_116[] =
{
	{ "n" }, { nil, 2 }, { "N" }, { nil, 3 }, { "nn" }, { nil, 4 }, { "n'" }, { "kn" }, { nil, 6 }, { "gn" }, { "mn" }, { "ng" }, { "on" }, { "pn" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_117[] =
{
	{ "ng" }, { nil, 6 }, { "n" }, { "ngu" }, { "ngue" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_118[] =
{
	{ "ngg" }, { nil, 6 }, { "n" }, { "ng" }, { "ngu" }, { "ngue" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_119[] =
{
	{ "ngu" }, { nil, 6 }, { "n" }, { "ng" }, { "ngue" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_120[] =
{
	{ "ngue" }, { nil, 6 }, { "n" }, { "ng" }, { "ngu" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_121[] =
{
	{ "nn" }, { nil, 3 }, { "n" }, { nil, 4 }, { "kn" }, { nil, 6 }, { "ain" }, { "en" }, { "gn" }, { "mn" }, { "on" }, { "pn" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_122[] =
{
	{ "nt" }, { nil, 3 }, { "n't" }, { nil, 4 }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_123[] =
{
	{ "o" }, { nil, 2 }, { "O" }, { nil, 3 }, { "oh" }, { "ow" }, { nil, 4 }, { "oo" }, { "owe" }, { "oa" }, { nil, 6 }, { "io" }, { "a" }, { "aa" }, { "ah" }, { "ao" }, { "au" }, { "augh" }, { "aw" }, { "awe" }, { "e" }, { "ea" }, { "eau" }, { "eo" }, { "eu" }, { "ew" }, { "i" }, { "ieu" }, { "oe" }, { "oeu" }, { "ou" }, { "ough" }, { "u" }, { "ua" }, { "ue" }, { "ui" }, { "w" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_124[] =
{
	{ "oa" }, { nil, 4 }, { "o" }, { "oh" }, { "au" }, { "ah" }, { "aw" }, { nil, 6 }, { "a" }, { "aa" }, { "ao" }, { "augh" }, { "awe" }, { "e" }, { "ea" }, { "eau" }, { "eo" }, { "i" }, { "oe" }, { "oo" }, { "ou" }, { "ough" }, { "ow" }, { "ua" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_125[] =
{
	{ "oe" }, { nil, 3 }, { "eo" }, { nil, 4 }, { "o" }, { "oo" }, { "oa" }, { "ew" }, { "u" }, { "ou" }, { nil, 6 }, { "ue" }, { "eu" }, { "a" }, { "ae" }, { "ao" }, { "au" }, { "ay" }, { "e" }, { "ea" }, { "eau" }, { "ee" }, { "ei" }, { "ey" }, { "i" }, { "ie" }, { "ieu" }, { "oeu" }, { "oh" }, { "ough" }, { "ow" }, { "ua" }, { "ui" }, { "w" }, { "y" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_126[] =
{
	{ "oh" }, { nil, 4 }, { "o" }, { "oa" }, { "au" }, { nil, 6 }, { "ough" }, { "eau" }, { "oe" }, { "eo" }, { "a" }, { "ao" }, { "oo" }, { "ou" }, { "ow" }, { "ua" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_127[] =
{
	{ "oi" }, { nil, 4 }, { "oy" }, { nil, 6 }, { "eu" }, { "aw" }, { "awy" }, { "io" }, { "uoy" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_128[] =
{
	{ "on" }, { nil, 4 }, { "en" }, { "ain" }, { "ion" }, { nil, 6 }, { "gn" }, { "kn" }, { "mn" }, { "n" }, { "nn" }, { "pn" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_129[] =
{
	{ "oo" }, { nil, 4 }, { "u" }, { "o" }, { "oa" }, { "ou" }, { nil, 6 }, { "ew" }, { "ough" }, { "oh" }, { "ow" }, { "oe" }, { "eo" }, { "eu" }, { "ui" }, { "a" }, { "ah" }, { "ai" }, { "ao" }, { "au" }, { "e" }, { "ea" }, { "eau" }, { "ei" }, { "i" }, { "ia" }, { "ieu" }, { "io" }, { "oeu" }, { "oi" }, { "ua" }, { "ue" }, { "w" }, { "y" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_130[] =
{
	{ "ou" }, { nil, 4 }, { "oo" }, { "o" }, { "u" }, { "ow" }, { "aw" }, { "au" }, { nil, 6 }, { "a" }, { "aa" }, { "ah" }, { "ai" }, { "ao" }, { "aou" }, { "aue" }, { "augh" }, { "awe" }, { "e" }, { "ea" }, { "eau" }, { "ei" }, { "eo" }, { "eu" }, { "ew" }, { "i" }, { "ia" }, { "ieu" }, { "io" }, { "oa" }, { "oe" }, { "oeu" }, { "oh" }, { "oi" }, { "oub" }, { "ough" }, { "ua" }, { "ue" }, { "ui" }, { "uo" }, { "w" }, { "y" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_131[] =
{
	{ "ow" }, { nil, 4 }, { "o" }, { "au" }, { "ou" }, { "oa" }, { "oh" }, { nil, 6 }, { "a" }, { "ao" }, { "aou" }, { "aue" }, { "eau" }, { "eo" }, { "oe" }, { "oo" }, { "ough" }, { "ua" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_132[] =
{
	{ "oy" }, { nil, 4 }, { "oi" }, { nil, 6 }, { "aw" }, { "awy" }, { "eu" }, { "uoy" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_133[] =
{
	{ "p" }, { nil, 2 }, { "P" }, { nil, 3 }, { "pp" }, { nil, 6 }, { "ph" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_134[] =
{
	{ "ph" }, { nil, 4 }, { "f" }, { "ff" }, { "gh" }, { "lf" }, { nil, 6 }, { "p" }, { "pp" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_135[] =
{
	{ "pn" }, { nil, 4 }, { "n" }, { nil, 6 }, { "ain" }, { "en" }, { "gn" }, { "kn" }, { "mn" }, { "nn" }, { "on" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_136[] =
{
	{ "pp" }, { nil, 3 }, { "p" }, { nil, 6 }, { "ph" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_137[] =
{
	{ "ps" }, { nil, 4 }, { "s" }, { nil, 6 }, { "c" }, { "ch" }, { "ci" }, { "sc" }, { "sch" }, { "ss" }, { "st" }, { "ts" }, { "tz" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_138[] =
{
	{ "q" }, { nil, 2 }, { "Q" }, { nil, 4 }, { "qu" }, { nil, 6 }, { "c" }, { "cc" }, { "ck" }, { "cq" }, { "cqu" }, { "cu" }, { "k" }, { "kh" }, { "kk" }, { "lk" }, { "ch" }, { "que" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_139[] =
{
	{ "qu" }, { nil, 4 }, { "kw" }, { nil, 6 }, { "c" }, { "cc" }, { "ch" }, { "ck" }, { "cq" }, { "cqu" }, { "cu" }, { "k" }, { "kh" }, { "kk" }, { "lk" }, { "q" }, { "que" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_140[] =
{
	{ "r" }, { nil, 2 }, { "R" }, { nil, 3 }, { "rr" }, { nil, 4 }, { "wr" }, { nil, 6 }, { "rh" }, { "rrh" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_141[] =
{
	{ "rh" }, { nil, 6 }, { "r" }, { "rr" }, { "rrh" }, { "wr" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_142[] =
{
	{ "rr" }, { nil, 3 }, { "r" }, { nil, 6 }, { "rh" }, { "rrh" }, { "wr" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_143[] =
{
	{ "rrh" }, { nil, 6 }, { "r" }, { "rh" }, { "rr" }, { "wr" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_144[] =
{
	{ "s" }, { nil, 2 }, { "S" }, { nil, 3 }, { "ss" }, { nil, 4 }, { "'s" }, { "s'" }, { "es" }, { nil, 6 }, { "c" }, { "cc" }, { "ci" }, { "ps" }, { "sc" }, { "st" }, { "ti" }, { "ts" }, { "tz" }, { "z" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_145[] =
{
	{ "sc" }, { nil, 4 }, { "sk" }, { nil, 6 }, { "c" }, { "ch" }, { "ci" }, { "ps" }, { "s" }, { "sch" }, { "sh" }, { "ss" }, { "st" }, { "ti" }, { "ts" }, { "tz" }, { "x" }, { "z" }, { "zz" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_146[] =
{
	{ "sch" }, { nil, 4 }, { "sk" }, { "sc" }, { "sh" }, { nil, 6 }, { "c" }, { "ch" }, { "chsi" }, { "ci" }, { "ps" }, { "s" }, { "ss" }, { "st" }, { "ti" }, { "ts" }, { "tz" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_147[] =
{
	{ "sh" }, { nil, 4 }, { "sch" }, { "ci" }, { "ti" }, { nil, 6 }, { "c" }, { "ch" }, { "chsi" }, { "s" }, { "sc" }, { "ss" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_148[] =
{
	{ "si" }, { nil, 4 }, { "ti" }, { "ci" }, { nil, 6 }, { "c" }, { "ch" }, { "tch" }, { "te" }, { "tu" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_149[] =
{
	{ "sk" }, { nil, 4 }, { "sc" }, { "sch" }, { nil, 6 }, { "c" }, { "ch" }, { "ci" }, { "s" }, { "sh" }, { "ss" }, { "ti" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_150[] =
{
	{ "ss" }, { nil, 3 }, { "s" }, { nil, 6 }, { "c" }, { "ch" }, { "ci" }, { "ps" }, { "sc" }, { "sch" }, { "sh" }, { "st" }, { "ti" }, { "ts" }, { "tz" }, { "x" }, { "z" }, { "zz" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_151[] =
{
	{ "st" }, { nil, 6 }, { "c" }, { "ch" }, { "ci" }, { "ps" }, { "s" }, { "sc" }, { "sch" }, { "ss" }, { "ts" }, { "tz" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_152[] =
{
	{ "sth" }, { nil, 6 }, { "c" }, { "ch" }, { "ci" }, { "ps" }, { "s" }, { "sc" }, { "sch" }, { "ss" }, { "st" }, { "ts" }, { "tz" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_153[] =
{
	{ "t" }, { nil, 2 }, { "T" }, { nil, 3 }, { "tt" }, { nil, 4 }, { "ght" }, { "te" }, { "bt" }, { nil, 6 }, { "ct" }, { "th" }, { "d" }, { "ed" }, { "tw" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_154[] =
{
	{ "tch" }, { nil, 4 }, { "ch" }, { nil, 6 }, { "c" }, { "si" }, { "te" }, { "ti" }, { "tu" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_155[] =
{
	{ "te" }, { nil, 2 }, { nil, 6 }, { "tt" }, { "t" }, { "ght" }, { "bt" }, { "ct" }, { "th" }, { "ed" }, { "tw" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_156[] =
{
	{ "th" }, { nil, 4 }, { "the" }, { nil, 6 }, { "bt" }, { "dd" }, { "ed" }, { "ght" }, { "t" }, { "te" }, { "tt" }, { "tw" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_157[] =
{
	{ "the" }, { nil, 4 }, { "th" }, { nil, 6 }, { "dd" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_158[] =
{
	{ "ti" }, { nil, 4 }, { "si" }, { "ci" }, { "sh" }, { "sch" }, { nil, 6 }, { "c" }, { "ch" }, { "s" }, { "sc" }, { "ss" }, { "tch" }, { "te" }, { "tu" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_159[] =
{
	{ "ts" }, { nil, 4 }, { "tz" }, { "cz" }, { nil, 6 }, { "c" }, { "ch" }, { "ci" }, { "ps" }, { "s" }, { "sc" }, { "sch" }, { "ss" }, { "st" }, { "x" }, { "z" }, { "zz" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_160[] =
{
	{ "tt" }, { nil, 3 }, { "t" }, { nil, 4 }, { "te" }, { nil, 6 }, { "bt" }, { "ed" }, { "ght" }, { "th" }, { "tw" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_161[] =
{
	{ "tu" }, { nil, 6 }, { "c" }, { "ch" }, { "si" }, { "tch" }, { "te" }, { "ti" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_162[] =
{
	{ "tz" }, { nil, 4 }, { "cz" }, { "ts" }, { nil, 6 }, { "c" }, { "ch" }, { "ci" }, { "ps" }, { "s" }, { "sc" }, { "sch" }, { "ss" }, { "st" }, { "x" }, { "z" }, { "zz" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_163[] =
{
	{ "u" }, { nil, 2 }, { "U" }, { nil, 3 }, { "oo" }, { nil, 4 }, { "ew" }, { "ou" }, { "ough" }, { "eu" }, { "ue" }, { "oe" }, { nil, 6 }, { "a" }, { "ah" }, { "ai" }, { "au" }, { "e" }, { "ea" }, { "eau" }, { "ei" }, { "i" }, { "ia" }, { "ieu" }, { "io" }, { "o" }, { "oa" }, { "oeu" }, { "oi" }, { "ui" }, { "uu" }, { "w" }, { "y" }, { "yu" }, { "you" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_164[] =
{
	{ "ua" }, { nil, 4 }, { "au" }, { "a" }, { nil, 6 }, { "ao" }, { "eau" }, { "eo" }, { "ew" }, { "o" }, { "oa" }, { "oe" }, { "oh" }, { "oo" }, { "ou" }, { "ow" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_165[] =
{
	{ "ub" }, { nil, 6 }, { "upb" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_166[] =
{
	{ "ue" }, { nil, 4 }, { "oo" }, { "ew" }, { "eu" }, { "ou" }, { nil, 6 }, { "a" }, { "ah" }, { "ai" }, { "e" }, { "ea" }, { "eau" }, { "ei" }, { "i" }, { "ia" }, { "ieu" }, { "io" }, { "o" }, { "oa" }, { "oe" }, { "oeu" }, { "oi" }, { "ow" }, { "u" }, { "ui" }, { "w" }, { "y" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_167[] =
{
	{ "ui" }, { nil, 4 }, { "oo" }, { "i" }, { "ou" }, { "u" }, { nil, 6 }, { "a" }, { "ae" }, { "ai" }, { "ao" }, { "au" }, { "ay" }, { "e" }, { "ea" }, { "ee" }, { "ei" }, { "eu" }, { "ew" }, { "ey" }, { "ia" }, { "ie" }, { "ieu" }, { "iu" }, { "o" }, { "oe" }, { "oeu" }, { "ue" }, { "w" }, { "y" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_168[] =
{
	{ "ul" }, { nil, 6 }, { "al" }, { "all" }, { "el" }, { "il" }, { "l" }, { "le" }, { "lh" }, { "ll" }, { "ln" }, { "yl" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_169[] =
{
	{ "v" }, { nil, 2 }, { "V" }, { nil, 3 }, { "vv" }, { nil, 6 }, { "f" }, { "w" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_170[] =
{
	{ "vv" }, { nil, 3 }, { "v" }, { nil, 6 }, { "f" }, { "w" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_171[] =
{
	{ "w" }, { nil, 2 }, { "W" }, { nil, 4 }, { "wh" }, { "ww" }, { nil, 6 }, { "j" }, { "ju" }, { "ou" }, { "u" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_172[] =
{
	{ "wh" }, { nil, 4 }, { "w" }, { "h" }, { nil, 6 }, { "ch" }, { "g" }, { "j" }, { "ju" }, { "ou" }, { "u" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_173[] =
{
	{ "wr" }, { nil, 4 }, { "r" }, { nil, 6 }, { "rh" }, { "rr" }, { "rrh" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_174[] =
{
	{ "x" }, { nil, 2 }, { "X" }, { nil, 4 }, { "cks" }, { "xc" }, { "xh" }, { "cs" }, { nil, 6 }, { "c" }, { "chs" }, { "cz" }, { "ks" }, { "s" }, { "sc" }, { "ss" }, { "ts" }, { "tz" }, { "z" }, { "zz" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_175[] =
{
	{ "y" }, { nil, 2 }, { "Y" }, { nil, 3 }, { "i" }, { nil, 6 }, { "a" }, { "ae" }, { "ai" }, { "ay" }, { "aye" }, { "e" }, { "ea" }, { "ee" }, { "ei" }, { "eo" }, { "ey" }, { "eye" }, { "ia" }, { "ie" }, { "igh" }, { "j" }, { "ju" }, { "o" }, { "oe" }, { "oy" }, { "u" }, { "ui" }, { "uy" }, { "ye" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_176[] =
{
	{ "ye" }, { nil, 4 }, { "y" }, { "ie" }, { "igh" }, { nil, 6 }, { "ai" }, { "ay" }, { "aye" }, { "ei" }, { "ey" }, { "eye" }, { "i" }, { "oy" }, { "uy" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_177[] =
{
	{ "yl" }, { nil, 6 }, { "al" }, { "all" }, { "el" }, { "il" }, { "l" }, { "le" }, { "lh" }, { "ll" }, { "ln" }, { "ul" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_178[] =
{
	{ "ys" }, { nil, 4 }, { "ies" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_179[] =
{
	{ "z" }, { nil, 2 }, { "Z" }, { nil, 3 }, { "zz" }, { nil, 4 }, { "s" }, { "cz" }, { "ts" }, { "tz" }, { nil, 6 }, { "sc" }, { "ss" }, { "x" }, { nil, 9 }
};
static const SpellItem	ksubstitution_map_180[] =
{
	{ "zz" }, { nil, 3 }, { "z" }, { nil, 6 }, { "cz" }, { "s" }, { "sc" }, { "ss" }, { "ts" }, { "tz" }, { "x" }, { nil, 9 }
};

// ROM 0x0c104658 substitution_map
const SpellMapEntry	gsubstitution_map[] =
{
	{ "$", ksubstitution_map_0 },
	{ "'", ksubstitution_map_1 },
	{ "@", ksubstitution_map_2 },
	{ "A", ksubstitution_map_3 },
	{ "B", ksubstitution_map_4 },
	{ "C", ksubstitution_map_5 },
	{ "D", ksubstitution_map_6 },
	{ "E", ksubstitution_map_7 },
	{ "F", ksubstitution_map_8 },
	{ "G", ksubstitution_map_9 },
	{ "H", ksubstitution_map_10 },
	{ "I", ksubstitution_map_11 },
	{ "J", ksubstitution_map_12 },
	{ "K", ksubstitution_map_13 },
	{ "L", ksubstitution_map_14 },
	{ "M", ksubstitution_map_15 },
	{ "N", ksubstitution_map_16 },
	{ "O", ksubstitution_map_17 },
	{ "P", ksubstitution_map_18 },
	{ "Q", ksubstitution_map_19 },
	{ "R", ksubstitution_map_20 },
	{ "S", ksubstitution_map_21 },
	{ "T", ksubstitution_map_22 },
	{ "U", ksubstitution_map_23 },
	{ "V", ksubstitution_map_24 },
	{ "W", ksubstitution_map_25 },
	{ "X", ksubstitution_map_26 },
	{ "Y", ksubstitution_map_27 },
	{ "Z", ksubstitution_map_28 },
	{ "a", ksubstitution_map_29 },
	{ "aa", ksubstitution_map_30 },
	{ "ae", ksubstitution_map_31 },
	{ "ah", ksubstitution_map_32 },
	{ "ai", ksubstitution_map_33 },
	{ "ain", ksubstitution_map_34 },
	{ "al", ksubstitution_map_35 },
	{ "all", ksubstitution_map_36 },
	{ "au", ksubstitution_map_37 },
	{ "aw", ksubstitution_map_38 },
	{ "awy", ksubstitution_map_39 },
	{ "ay", ksubstitution_map_40 },
	{ "b", ksubstitution_map_41 },
	{ "bb", ksubstitution_map_42 },
	{ "bh", ksubstitution_map_43 },
	{ "bt", ksubstitution_map_44 },
	{ "c", ksubstitution_map_45 },
	{ "cc", ksubstitution_map_46 },
	{ "cch", ksubstitution_map_47 },
	{ "ch", ksubstitution_map_48 },
	{ "chm", ksubstitution_map_49 },
	{ "cht", ksubstitution_map_50 },
	{ "ci", ksubstitution_map_51 },
	{ "ck", ksubstitution_map_52 },
	{ "cks", ksubstitution_map_53 },
	{ "cq", ksubstitution_map_54 },
	{ "cqu", ksubstitution_map_55 },
	{ "cs", ksubstitution_map_56 },
	{ "cu", ksubstitution_map_57 },
	{ "cz", ksubstitution_map_58 },
	{ "d", ksubstitution_map_59 },
	{ "dd", ksubstitution_map_60 },
	{ "dg", ksubstitution_map_61 },
	{ "dge", ksubstitution_map_62 },
	{ "dh", ksubstitution_map_63 },
	{ "dj", ksubstitution_map_64 },
	{ "e", ksubstitution_map_65 },
	{ "e@", ksubstitution_map_66 },
	{ "eau", ksubstitution_map_67 },
	{ "ed", ksubstitution_map_68 },
	{ "ee", ksubstitution_map_69 },
	{ "ei", ksubstitution_map_70 },
	{ "el", ksubstitution_map_71 },
	{ "en", ksubstitution_map_72 },
	{ "eo", ksubstitution_map_73 },
	{ "eu", ksubstitution_map_74 },
	{ "ew", ksubstitution_map_75 },
	{ "ey", ksubstitution_map_76 },
	{ "f", ksubstitution_map_77 },
	{ "ff", ksubstitution_map_78 },
	{ "g", ksubstitution_map_79 },
	{ "gg", ksubstitution_map_80 },
	{ "gh", ksubstitution_map_81 },
	{ "ght", ksubstitution_map_82 },
	{ "gi", ksubstitution_map_83 },
	{ "gm", ksubstitution_map_84 },
	{ "gn", ksubstitution_map_85 },
	{ "gu", ksubstitution_map_86 },
	{ "h", ksubstitution_map_87 },
	{ "hw", ksubstitution_map_88 },
	{ "i", ksubstitution_map_89 },
	{ "ia", ksubstitution_map_90 },
	{ "ie", ksubstitution_map_91 },
	{ "ieu", ksubstitution_map_92 },
	{ "il", ksubstitution_map_93 },
	{ "io", ksubstitution_map_94 },
	{ "j", ksubstitution_map_95 },
	{ "k", ksubstitution_map_96 },
	{ "kh", ksubstitution_map_97 },
	{ "kk", ksubstitution_map_98 },
	{ "kn", ksubstitution_map_99 },
	{ "ks", ksubstitution_map_100 },
	{ "kw", ksubstitution_map_101 },
	{ "l", ksubstitution_map_102 },
	{ "ld", ksubstitution_map_103 },
	{ "le", ksubstitution_map_104 },
	{ "lf", ksubstitution_map_105 },
	{ "lh", ksubstitution_map_106 },
	{ "lk", ksubstitution_map_107 },
	{ "ll", ksubstitution_map_108 },
	{ "lm", ksubstitution_map_109 },
	{ "ln", ksubstitution_map_110 },
	{ "m", ksubstitution_map_111 },
	{ "mb", ksubstitution_map_112 },
	{ "mh", ksubstitution_map_113 },
	{ "mm", ksubstitution_map_114 },
	{ "mn", ksubstitution_map_115 },
	{ "n", ksubstitution_map_116 },
	{ "ng", ksubstitution_map_117 },
	{ "ngg", ksubstitution_map_118 },
	{ "ngu", ksubstitution_map_119 },
	{ "ngue", ksubstitution_map_120 },
	{ "nn", ksubstitution_map_121 },
	{ "nt", ksubstitution_map_122 },
	{ "o", ksubstitution_map_123 },
	{ "oa", ksubstitution_map_124 },
	{ "oe", ksubstitution_map_125 },
	{ "oh", ksubstitution_map_126 },
	{ "oi", ksubstitution_map_127 },
	{ "on", ksubstitution_map_128 },
	{ "oo", ksubstitution_map_129 },
	{ "ou", ksubstitution_map_130 },
	{ "ow", ksubstitution_map_131 },
	{ "oy", ksubstitution_map_132 },
	{ "p", ksubstitution_map_133 },
	{ "ph", ksubstitution_map_134 },
	{ "pn", ksubstitution_map_135 },
	{ "pp", ksubstitution_map_136 },
	{ "ps", ksubstitution_map_137 },
	{ "q", ksubstitution_map_138 },
	{ "qu", ksubstitution_map_139 },
	{ "r", ksubstitution_map_140 },
	{ "rh", ksubstitution_map_141 },
	{ "rr", ksubstitution_map_142 },
	{ "rrh", ksubstitution_map_143 },
	{ "s", ksubstitution_map_144 },
	{ "sc", ksubstitution_map_145 },
	{ "sch", ksubstitution_map_146 },
	{ "sh", ksubstitution_map_147 },
	{ "si", ksubstitution_map_148 },
	{ "sk", ksubstitution_map_149 },
	{ "ss", ksubstitution_map_150 },
	{ "st", ksubstitution_map_151 },
	{ "sth", ksubstitution_map_152 },
	{ "t", ksubstitution_map_153 },
	{ "tch", ksubstitution_map_154 },
	{ "te", ksubstitution_map_155 },
	{ "th", ksubstitution_map_156 },
	{ "the", ksubstitution_map_157 },
	{ "ti", ksubstitution_map_158 },
	{ "ts", ksubstitution_map_159 },
	{ "tt", ksubstitution_map_160 },
	{ "tu", ksubstitution_map_161 },
	{ "tz", ksubstitution_map_162 },
	{ "u", ksubstitution_map_163 },
	{ "ua", ksubstitution_map_164 },
	{ "ub", ksubstitution_map_165 },
	{ "ue", ksubstitution_map_166 },
	{ "ui", ksubstitution_map_167 },
	{ "ul", ksubstitution_map_168 },
	{ "v", ksubstitution_map_169 },
	{ "vv", ksubstitution_map_170 },
	{ "w", ksubstitution_map_171 },
	{ "wh", ksubstitution_map_172 },
	{ "wr", ksubstitution_map_173 },
	{ "x", ksubstitution_map_174 },
	{ "y", ksubstitution_map_175 },
	{ "ye", ksubstitution_map_176 },
	{ "yl", ksubstitution_map_177 },
	{ "ys@", ksubstitution_map_178 },
	{ "z", ksubstitution_map_179 },
	{ "zz", ksubstitution_map_180 },
	{ nil, nil }
};
