// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> pdfMaskArray:u8:8 -o src/recognition/XrRulesTables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const unsigned char	pdfMaskArray[8];

// ROM 0x0037687c pdfMaskArray
const unsigned char	pdfMaskArray[8] = {
	0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01,
};
