/*
	File:		comms/fax/T4FaxLine.h

	Contains:	TT4FaxLine, the fax tool's decoder of received pages: the
				modified Huffman (MH, ITU-T T.4) code of a page's scan
				lines, kept as it arrives in a ring of bytes (AppendTo drops
				the fill - every nought byte after two in a row), read a bit
				at a time least significant first, and decoded a line at a
				time into a row of pixels, most significant bit first, a
				black pixel a 1 (DecodeLine).

				A code is found by walking a small binary tree: a white
				code's first four bits (a black code's first bits, bit by
				bit) choose one of the trees of kMajorIndexWhite (Black),
				whose bytes are indexed as a heap (the root at 1, a node's
				children at 2n and 2n + 1) - 0xff an inner node, 0 to 63 a
				terminating run, 0x40 and up a make-up run of (n - 0x3f) x
				64, 0x68 an end of line and 0xfe an error (T4Tables.cpp,
				generated by analysis/romtable.py).

				The ROM's class; its declaration is not in the DDK, so the
				names of the fields are ours, their order the ROM's
				(offsets noted, for the ROM's layout of 0x34 bytes).

	Reconstructed from the MP2x00 US ROM (0x00204698-0x00204e34); each
	function cites its origin.  docs/comms/README.md, "Fax".
*/

#ifndef __COMMS_FAX_T4FAXLINE_H
#define __COMMS_FAX_T4FAXLINE_H

#ifndef __NEWTON_H
#include "Newton.h"
#endif

class TT4FaxLine
{
public:
	enum RunColor { kBlack = 0, kWhite = 1 };

						TT4FaxLine();
	virtual				~TT4FaxLine();

	void				Init(UChar* buffer, int size);
	void				Reset();
	Boolean				AppendTo(UChar** data, int* count, int* appended);
	Boolean				DecodeLine(UChar* line, int lineBytes, int& bytesDecoded, ULong catchOverrun);
	int					GetLength();
	Boolean				SkipPastEOL();

	Boolean				EmitBits(RunColor color, int run, int* bytesWritten);
	int					MHGetNextCode(RunColor color);
	int					GetNextBit();
	int					GetBits(int count);
	Boolean				DoMHDecodeLine(UChar* line, int lineBytes, int& bytesDecoded);

	UChar*				fBufStart;				// +0x04  the ring of received code
	int					fBufSize;				// +0x08
	UChar*				fBufEnd;				// +0x0c
	UChar*				fReadPtr;				// +0x10  the byte last read
	UByte				fCurByte;				// +0x14  its bits not yet read
	int					fBitsLeft;				// +0x18
	Boolean				fWrapped;				// +0x1c  the writer is a lap ahead
	UChar*				fWritePtr;				// +0x20
	UChar*				fOut;					// +0x24  the line being decoded into
	int					fOutBitsFree;			// +0x28  of fOutByte
	UByte				fOutByte;				// +0x2c
	UChar*				fOutEnd;				// +0x30
};

// the decoding trees (T4Tables.cpp)
extern const unsigned char	kFaxMaskBelow[8];
extern const unsigned char	kFaxMaskFrom[8];
extern const unsigned char* const	kMajorIndexWhite[16];
extern const unsigned char* const	kMajorIndexBlack[4];

#endif	/* __COMMS_FAX_T4FAXLINE_H */
