add_executable(test_Options test_Options.cpp)
target_link_libraries(test_Options PRIVATE comms os600_kernel os600_user)
add_test(NAME comms.Options COMMAND test_Options)
set_tests_properties(comms.Options PROPERTIES TIMEOUT 30)

add_executable(test_CommTool test_CommTool.cpp)
target_link_libraries(test_CommTool PRIVATE comms os600_kernel os600_user)
add_test(NAME comms.CommTool COMMAND test_CommTool)
set_tests_properties(comms.CommTool PROPERTIES TIMEOUT 60)

add_executable(test_CommManager test_CommManager.cpp)
target_link_libraries(test_CommManager PRIVATE comms os600_kernel os600_user)
add_test(NAME comms.CommManager COMMAND test_CommManager)
set_tests_properties(comms.CommManager PROPERTIES TIMEOUT 60)

add_executable(test_Endpoint test_Endpoint.cpp)
target_link_libraries(test_Endpoint PRIVATE comms os600_kernel os600_user)
add_test(NAME comms.Endpoint COMMAND test_Endpoint)
set_tests_properties(comms.Endpoint PROPERTIES TIMEOUT 60)

add_executable(test_Translators test_Translators.cpp)
target_link_libraries(test_Translators PRIVATE comms_script os600_kernel os600_user)
target_compile_definitions(test_Translators PRIVATE "NEWTON_ROM_BIN=\"${NEWTON_ROM_BIN}\"")
add_test(NAME comms.Translators COMMAND test_Translators)
set_tests_properties(comms.Translators PROPERTIES TIMEOUT 60)
