// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> gTXGraphicsRunChar:u16:1 -o src/text/TXGraphicsRunChar.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const unsigned short	gTXGraphicsRunChar[1];

// ROM 0x0c104d88 gTXGraphicsRunChar
const unsigned short	gTXGraphicsRunChar[1] = {
	0x2206,
};
