/*
	File:		armcpu/PrivateJumpTable.h

	Contains:	Slots of the ROM's private (patchable) jump table - virtual
				0x01A00000 on - that native code may call directly, by
				slot address and mangled name: native code built against a
				particular ROM calls some functions there rather than
				through the public table (Kallisys's ATA Support calls
				TStore::New and TStore::SetStore so, picking the slots for
				the ROM version Gestalt names).  Only the slots of functions
				src/armcpu's glue answers are listed: PrivateJumpTable.cpp
				is generated by tools/newton-rom/analysis/gluetable.py
				--private-for src/armcpu, to be run again when glue is added
				for a function a package calls by its private slot.
*/

#ifndef __PRIVATEJUMPTABLE_H
#define __PRIVATEJUMPTABLE_H

struct PrivateJumpEntry
{
	unsigned long	fSlot;			// its address (0x01A00000...)
	const char*		fName;			// the mangled name of the function
};

extern const PrivateJumpEntry	kPrivateJumpTable[];		// sorted by slot
extern const unsigned long		kPrivateJumpTableCount;

const unsigned long	kPrivateJumpTableBase = 0x01A00000;
const unsigned long	kPrivateJumpTableLimit = 0x01C40000;

#endif	/* __PRIVATEJUMPTABLE_H */
