/*
	File:		armcpu/PublicJumpTable.h

	Contains:	The ROM's public jump table - the entry points third-party
				native code calls the ROM through (virtual 0x01800000 +
				offset) - by offset and mangled name.  PublicJumpTable.cpp
				is generated by tools/newton-rom/analysis/gluetable.py.
*/

#ifndef __PUBLICJUMPTABLE_H
#define __PUBLICJUMPTABLE_H

struct PublicJumpEntry
{
	unsigned long	fOffset;		// from 0x01800000
	const char*		fName;			// the mangled name of the function it reaches
	unsigned long	fSlot;			// its slot in the private jump table (0x01A00000...)
};

extern const PublicJumpEntry	kPublicJumpTable[];
extern const unsigned long		kPublicJumpTableCount;

const unsigned long	kPublicJumpTableBase = 0x01800000;
const unsigned long	kPublicJumpTableSize = 0x00002e0c;

#endif	/* __PUBLICJUMPTABLE_H */
