add_executable(test_Views test_Views.cpp)
target_link_libraries(test_Views PRIVATE views recognition hal_host_tablet)
target_compile_definitions(test_Views PRIVATE "NEWTON_ROM_BIN=\"${NEWTON_ROM_BIN}\"")
add_test(NAME views.Views COMMAND test_Views)
set_tests_properties(views.Views PROPERTIES TIMEOUT 120)
