add_executable(test_Views test_Views.cpp)
target_link_libraries(test_Views PRIVATE views)
target_compile_definitions(test_Views PRIVATE "NEWTON_ROM_BIN=\"${CMAKE_SOURCE_DIR}/../build/MP2100D/rom.bin\"")
add_test(NAME views.Views COMMAND test_Views)
set_tests_properties(views.Views PROPERTIES TIMEOUT 120)
