// Generated by tools/newton-rom/analysis/soupdefs.py; do not edit.
//   python tools/newton-rom/analysis/soupdefs.py <build_dir> -o src/host/FactorySoups.cpp
// The soups the 2.1 (717006) ROM's built-in applications keep: the name each
// application's soup supervisor carries and the magic pointer of the
// indexes beside it.  host/HostStores.cpp makes them, because a
// Newton's internal store already has them and the boot takes that
// for granted (the script says why).

#include "FactorySoups.h"

const FactorySoup gFactorySoups[] = {
	// the Cardfile package's soup supervisor, at 0x00738e4d in the image;
	// its index list is the ROM object 0x0063c0c1, magic pointer 44
	{ "Names", 44 },
};

const long gFactorySoupCount = 1;
