/*
	File:		host/FactorySoups.h

	Contains:	The soups a Newton's internal store already has by the time
				the ROM's boot runs - the ones its built-in applications
				keep - as the name and the magic pointer of the index list
				each application's soup supervisor carries.

				FactorySoups.cpp is generated by
				tools/newton-rom/analysis/soupdefs.py from the ROM; do not
				edit it.  host/HostStores.h says what it is for.
*/

#ifndef __FACTORYSOUPS_H
#define __FACTORYSOUPS_H

struct FactorySoup
{
	const char*	fName;			// the soup's name
	long		fIndexes;		// the magic pointer of its index list
};

extern const FactorySoup	gFactorySoups[];
extern const long			gFactorySoupCount;

#endif	/* __FACTORYSOUPS_H */
