/*
	File:		host/HostStores.h

	Contains:	The store the host boots with.

				A Newton boots with its internal store already there - the
				flash the PSS manager formats and mounts long before any
				script runs - and the ROM's NewtonScript boot takes that for
				granted: the first thing Rbootinitnsglobals does with stores
				is index GetStores()[0].

				DEVIATION: there is no flash here and TPSSManager is not
				reconstructed, so GetInternalStore answers nil and the host
				puts a THostStore (stores/host/HostStore.h, the in-memory
				one) in its place - formatted empty, marked internal, and
				registered so that GetStores answers it.  What the store
				holds survives the program when one is named
				(HostSetStoreFile, below) and not when none is.

				DEVIATION: and the store is then *prepared*, because an
				empty one is not what the ROM's boot expects either.  A
				Newton has been used by the time its boot runs: the soups
				its built-in applications keep are already on the flash, and
				the boot takes that for granted - PreSetupUserConfig asks
				the internal store for the Cardfile's "Names" soup and sends
				Query to what it gets, without looking to see whether it got
				one, and the six init functions after it pay for the throw
				(docs/newt/README.md).  The applications make those soups
				when they are first opened, which on the real machine
				happened long ago and here has not happened at all, so
				HostPrepareStore makes them: the names and index lists are
				the ROM's own (host/FactorySoups.h, generated by
				analysis/soupdefs.py).
*/

#ifndef __HOSTSTORES_H
#define __HOSTSTORES_H

#ifndef __OBJECTS_H
#include "objects.h"
#endif

// The soup and query globals, and an internal store mounted and
// prepared.  Wants the object system started (InitObjects); does nothing
// the second time.
void	HostMountStores(void);

// The file the internal store is kept in between runs, which is what
// the flash is on the machine: named before HostMountStores, it is read
// in if it is there and written out again on every commit.  With none
// named the store is memory only and the machine starts at the Setup
// assistant every time.
void	HostSetStoreFile(const char* path);

// Whether the store was read back from that file rather than formatted
// fresh - which is to say whether the machine has been used before.
Boolean	HostStoreWasRestored(void);

// The soups a used machine's store already has, made on the store if they
// are not there.  HostMountStores does this; a test that mounts its own
// store can call it for itself.
void	HostPrepareStore(RefArg store);

#endif	/* __HOSTSTORES_H */
