/*
	File:		user/ExceptionNames.cpp

	Contains:	The exception names the ROM defines (DefineException): each is
				a dotted path, and Subexception matches on prefixes, so
				"evt.ex.msg" is an exRootException ("evt.ex").

	Generated by tools/newton-rom/analysis/exception_names.py from the ROM
	image; do not edit by hand.
*/

#include "Newton.h"
#include "NewtonExceptions.h"

extern const ExceptionName exRootException;
extern const ExceptionName exSkia;
extern const ExceptionName exMsgException;
extern const ExceptionName exDivideByZero;
extern const ExceptionName exAbort;
extern const ExceptionName exBusError;
extern const ExceptionName exAlignment;
extern const ExceptionName exIllegalInstr;
extern const ExceptionName exPermissionViolation;
extern const ExceptionName exWriteProtected;
extern const ExceptionName exOutOfStack;
extern const ExceptionName exLongErrorException;
extern const ExceptionName exErrorException;
extern const ExceptionName exNoSoupDefException;
extern const ExceptionName exDateQuery;
extern const ExceptionName exGrafException;
extern const ExceptionName exCommException;
extern const ExceptionName exAll;
extern const ExceptionName exNewtException;
extern const ExceptionName exFaxBufOverrunException;
extern const ExceptionName exCompiler;
extern const ExceptionName exCompilerWithFrameData;
extern const ExceptionName exStoreError;
extern const ExceptionName exInterpreter;
extern const ExceptionName exInterpreterWithFrameData;
extern const ExceptionName exFrames;
extern const ExceptionName exFramesWithFrameData;
extern const ExceptionName exBadType;
extern const ExceptionName exBadTypeWithFrameData;
extern const ExceptionName exOutOfMemory;
extern const ExceptionName exStdioPipeException;
extern const ExceptionName exCompressionException;
extern const ExceptionName exPipeException;
extern const ExceptionName exTranslatorException;
extern const ExceptionName exRosetta;

const ExceptionName	exRootException = (ExceptionName) "evt.ex";	// ROM 0x003712a4 exRootException
const ExceptionName	exSkia = (ExceptionName) "evt.ex.skia";	// ROM 0x003712a8 exSkia
const ExceptionName	exMsgException = (ExceptionName) "evt.ex.msg";	// ROM 0x003712ac exMsgException
const ExceptionName	exDivideByZero = (ExceptionName) "evt.ex.div0";	// ROM 0x003712b0 exDivideByZero
const ExceptionName	exAbort = (ExceptionName) "evt.ex.abt";	// ROM 0x003712b4 exAbort
const ExceptionName	exBusError = (ExceptionName) "evt.ex.abt.bus";	// ROM 0x003712b8 exBusError
const ExceptionName	exAlignment = (ExceptionName) "evt.ex.abt.align";	// ROM 0x003712bc exAlignment
const ExceptionName	exIllegalInstr = (ExceptionName) "evt.ex.abt.instr";	// ROM 0x003712c0 exIllegalInstr
const ExceptionName	exPermissionViolation = (ExceptionName) "evt.ex.abt.perm";	// ROM 0x003712c4 exPermissionViolation
const ExceptionName	exWriteProtected = (ExceptionName) "evt.ex.abt.wp";	// ROM 0x003712c8 exWriteProtected
const ExceptionName	exOutOfStack = (ExceptionName) "evt.ex.abt.stack";	// ROM 0x003712cc exOutOfStack
const ExceptionName	exLongErrorException = (ExceptionName) "evt.ex.longerror";	// ROM 0x003712d0 exLongErrorException
const ExceptionName	exErrorException = (ExceptionName) "evt.ex.error";	// ROM 0x003712d4 exErrorException
const ExceptionName	exNoSoupDefException = (ExceptionName) "evt.ex.nosoupdef";	// ROM 0x003712d8 exNoSoupDefException
const ExceptionName	exDateQuery = (ExceptionName) "evt.ex.root";	// ROM 0x003712dc exDateQuery
const ExceptionName	exGrafException = (ExceptionName) "evt.ex.graf";	// ROM 0x003712e0 exGrafException
const ExceptionName	exCommException = (ExceptionName) "evt.ex.comm";	// ROM 0x003712e4 exCommException
const ExceptionName	exAll = (ExceptionName) "evt.ex";	// ROM 0x003712e8 exAll
const ExceptionName	exNewtException = (ExceptionName) "evt.ex.msg.newt";	// ROM 0x003712ec exNewtException
const ExceptionName	exFaxBufOverrunException = (ExceptionName) "evt.ex";	// ROM 0x003712f0 exFaxBufOverrunException
const ExceptionName	exCompiler = (ExceptionName) "evt.ex.fr.comp";	// ROM 0x003712f4 exCompiler
const ExceptionName	exCompilerWithFrameData = (ExceptionName) "evt.ex.fr.comp;type.ref.frame";	// ROM 0x003712f8 exCompilerWithFrameData
const ExceptionName	exStoreError = (ExceptionName) "evt.ex.fr.store";	// ROM 0x003712fc exStoreError
const ExceptionName	exInterpreter = (ExceptionName) "evt.ex.fr.intrp";	// ROM 0x00371300 exInterpreter
const ExceptionName	exInterpreterWithFrameData = (ExceptionName) "evt.ex.fr.intrp;type.ref.frame";	// ROM 0x00371304 exInterpreterWithFrameData
const ExceptionName	exFrames = (ExceptionName) "evt.ex.fr";	// ROM 0x00371308 exFrames
const ExceptionName	exFramesWithFrameData = (ExceptionName) "evt.ex.fr;type.ref.frame";	// ROM 0x0037130c exFramesWithFrameData
const ExceptionName	exBadType = (ExceptionName) "evt.ex.fr.type";	// ROM 0x00371310 exBadType
const ExceptionName	exBadTypeWithFrameData = (ExceptionName) "evt.ex.fr.type;type.ref.frame";	// ROM 0x00371314 exBadTypeWithFrameData
const ExceptionName	exOutOfMemory = (ExceptionName) "evt.ex.outofmem";	// ROM 0x00371318 exOutOfMemory
const ExceptionName	exStdioPipeException = (ExceptionName) "evt.ex.stdio";	// ROM 0x0037131c exStdioPipeException
const ExceptionName	exCompressionException = (ExceptionName) "evt.ex.comp";	// ROM 0x00371320 exCompressionException
const ExceptionName	exPipeException = (ExceptionName) "evt.ex.pipe";	// ROM 0x00371324 exPipeException
const ExceptionName	exTranslatorException = (ExceptionName) "evt.ex.translator";	// ROM 0x00371328 exTranslatorException
const ExceptionName	exRosetta = (ExceptionName) "evt.ex.Rosetta";	// ROM 0x003774f8 exRosetta
