/*
	File:		user/ExceptionNames.cpp

	Contains:	The exception names the ROM defines (DefineException): each is
				a dotted path, and Subexception matches on prefixes, so
				"evt.ex.msg" is an exRootException ("evt.ex").

	Generated by tools/newton-rom/analysis/exception_names.py from the ROM
	image; do not edit by hand.
*/

#include "Newton.h"
#include "NewtonExceptions.h"

extern const ExceptionName exRootException;
extern const ExceptionName exSkia;
extern const ExceptionName exMsgException;
extern const ExceptionName exDivideByZero;
extern const ExceptionName exAbort;
extern const ExceptionName exBusError;
extern const ExceptionName exAlignment;
extern const ExceptionName exIllegalInstr;
extern const ExceptionName exPermissionViolation;
extern const ExceptionName exWriteProtected;
extern const ExceptionName exOutOfStack;
extern const ExceptionName exLongErrorException;
extern const ExceptionName exErrorException;
extern const ExceptionName exNoSoupDefException;
extern const ExceptionName exDateQuery;
extern const ExceptionName exGrafException;
extern const ExceptionName exCommException;
extern const ExceptionName exAll;
extern const ExceptionName exNewtException;
extern const ExceptionName exFaxBufOverrunException;
extern const ExceptionName exCompiler;
extern const ExceptionName exCompilerWithFrameData;
extern const ExceptionName exStoreError;
extern const ExceptionName exInterpreter;
extern const ExceptionName exInterpreterWithFrameData;
extern const ExceptionName exFrames;
extern const ExceptionName exFramesWithFrameData;
extern const ExceptionName exBadType;
extern const ExceptionName exBadTypeWithFrameData;
extern const ExceptionName exOutOfMemory;
extern const ExceptionName exStdioPipeException;
extern const ExceptionName exCompressionException;
extern const ExceptionName exPipeException;
extern const ExceptionName exTranslatorException;
extern const ExceptionName exRosetta;

const ExceptionName	exRootException = (ExceptionName) "evt.ex";	// ROM 0x00346458 exRootException
const ExceptionName	exSkia = (ExceptionName) "evt.ex.skia";	// ROM 0x0034645c exSkia
const ExceptionName	exMsgException = (ExceptionName) "evt.ex.msg";	// ROM 0x00346460 exMsgException
const ExceptionName	exDivideByZero = (ExceptionName) "evt.ex.div0";	// ROM 0x00346464 exDivideByZero
const ExceptionName	exAbort = (ExceptionName) "evt.ex.abt";	// ROM 0x00346468 exAbort
const ExceptionName	exBusError = (ExceptionName) "evt.ex.abt.bus";	// ROM 0x0034646c exBusError
const ExceptionName	exAlignment = (ExceptionName) "evt.ex.abt.align";	// ROM 0x00346470 exAlignment
const ExceptionName	exIllegalInstr = (ExceptionName) "evt.ex.abt.instr";	// ROM 0x00346474 exIllegalInstr
const ExceptionName	exPermissionViolation = (ExceptionName) "evt.ex.abt.perm";	// ROM 0x00346478 exPermissionViolation
const ExceptionName	exWriteProtected = (ExceptionName) "evt.ex.abt.wp";	// ROM 0x0034647c exWriteProtected
const ExceptionName	exOutOfStack = (ExceptionName) "evt.ex.abt.stack";	// ROM 0x00346480 exOutOfStack
const ExceptionName	exLongErrorException = (ExceptionName) "evt.ex.longerror";	// ROM 0x00346484 exLongErrorException
const ExceptionName	exErrorException = (ExceptionName) "evt.ex.error";	// ROM 0x00346488 exErrorException
const ExceptionName	exNoSoupDefException = (ExceptionName) "evt.ex.nosoupdef";	// ROM 0x0034648c exNoSoupDefException
const ExceptionName	exDateQuery = (ExceptionName) "evt.ex.root";	// ROM 0x00346490 exDateQuery
const ExceptionName	exGrafException = (ExceptionName) "evt.ex.graf";	// ROM 0x00346494 exGrafException
const ExceptionName	exCommException = (ExceptionName) "evt.ex.comm";	// ROM 0x00346498 exCommException
const ExceptionName	exAll = (ExceptionName) "evt.ex";	// ROM 0x0034649c exAll
const ExceptionName	exNewtException = (ExceptionName) "evt.ex.msg.newt";	// ROM 0x003464a0 exNewtException
const ExceptionName	exFaxBufOverrunException = (ExceptionName) "evt.ex";	// ROM 0x003464a4 exFaxBufOverrunException
const ExceptionName	exCompiler = (ExceptionName) "evt.ex.fr.comp";	// ROM 0x003464a8 exCompiler
const ExceptionName	exCompilerWithFrameData = (ExceptionName) "evt.ex.fr.comp;type.ref.frame";	// ROM 0x003464ac exCompilerWithFrameData
const ExceptionName	exStoreError = (ExceptionName) "evt.ex.fr.store";	// ROM 0x003464b0 exStoreError
const ExceptionName	exInterpreter = (ExceptionName) "evt.ex.fr.intrp";	// ROM 0x003464b4 exInterpreter
const ExceptionName	exInterpreterWithFrameData = (ExceptionName) "evt.ex.fr.intrp;type.ref.frame";	// ROM 0x003464b8 exInterpreterWithFrameData
const ExceptionName	exFrames = (ExceptionName) "evt.ex.fr";	// ROM 0x003464bc exFrames
const ExceptionName	exFramesWithFrameData = (ExceptionName) "evt.ex.fr;type.ref.frame";	// ROM 0x003464c0 exFramesWithFrameData
const ExceptionName	exBadType = (ExceptionName) "evt.ex.fr.type";	// ROM 0x003464c4 exBadType
const ExceptionName	exBadTypeWithFrameData = (ExceptionName) "evt.ex.fr.type;type.ref.frame";	// ROM 0x003464c8 exBadTypeWithFrameData
const ExceptionName	exOutOfMemory = (ExceptionName) "evt.ex.outofmem";	// ROM 0x003464cc exOutOfMemory
const ExceptionName	exStdioPipeException = (ExceptionName) "evt.ex.stdio";	// ROM 0x003464d0 exStdioPipeException
const ExceptionName	exCompressionException = (ExceptionName) "evt.ex.comp";	// ROM 0x003464d4 exCompressionException
const ExceptionName	exPipeException = (ExceptionName) "evt.ex.pipe";	// ROM 0x003464d8 exPipeException
const ExceptionName	exTranslatorException = (ExceptionName) "evt.ex.translator";	// ROM 0x003464dc exTranslatorException
const ExceptionName	exRosetta = (ExceptionName) "evt.ex.Rosetta";	// ROM 0x00354938 exRosetta
