// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> kHiliteTracedCurve@0x00377390:i32:17 -o src/views/PolygonViewTables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const int	kHiliteTracedCurve[17];

// ROM 0x00377390 (unnamed) - kHiliteTracedCurve
const int	kHiliteTracedCurve[17] = {
	65536, 65407, 65021, 64373, 63454, 62253, 60753, 58931,
	56755, 54184, 51159, 47591, 43347, 38204, 31727, 22805,
	    0,
};
