add_executable(test_TXArray test_TXArray.cpp)
target_link_libraries(test_TXArray PRIVATE text memory)
add_test(NAME text.TXArray COMMAND test_TXArray)
set_tests_properties(text.TXArray PROPERTIES TIMEOUT 120)

add_executable(test_TXStream test_TXStream.cpp)
target_link_libraries(test_TXStream PRIVATE text memory)
add_test(NAME text.TXStream COMMAND test_TXStream)
set_tests_properties(text.TXStream PROPERTIES TIMEOUT 120)

add_executable(test_TXRuler test_TXRuler.cpp)
target_link_libraries(test_TXRuler PRIVATE text memory)
target_compile_definitions(test_TXRuler PRIVATE "NEWTON_ROM_BIN=\"${NEWTON_ROM_BIN}\"")
add_test(NAME text.TXRuler COMMAND test_TXRuler)
set_tests_properties(text.TXRuler PROPERTIES TIMEOUT 120)

add_executable(test_TXObjectRange test_TXObjectRange.cpp)
target_link_libraries(test_TXObjectRange PRIVATE text memory)
add_test(NAME text.TXObjectRange COMMAND test_TXObjectRange)
set_tests_properties(text.TXObjectRange PROPERTIES TIMEOUT 120)

add_executable(test_TXRunRange test_TXRunRange.cpp)
target_link_libraries(test_TXRunRange PRIVATE text memory)
add_test(NAME text.TXRunRange COMMAND test_TXRunRange)
set_tests_properties(text.TXRunRange PROPERTIES TIMEOUT 120)

add_executable(test_TXUtilities test_TXUtilities.cpp)
target_link_libraries(test_TXUtilities PRIVATE text memory)
add_test(NAME text.TXUtilities COMMAND test_TXUtilities)
set_tests_properties(text.TXUtilities PROPERTIES TIMEOUT 120)
