add_executable(test_DotPrinter test_DotPrinter.cpp)
target_link_libraries(test_DotPrinter PRIVATE print os600_kernel os600_user)
add_test(NAME print.DotPrinter COMMAND test_DotPrinter)
set_tests_properties(print.DotPrinter PROPERTIES TIMEOUT 60 PASS_REGULAR_EXPRESSION "test_DotPrinter: all passed")

add_executable(test_PSPrinter test_PSPrinter.cpp)
target_link_libraries(test_PSPrinter PRIVATE print os600_kernel os600_user)
target_compile_definitions(test_PSPrinter PRIVATE "NEWTON_OBJECTS=\"${NEWTON_OBJECTS_FILE}\"")
add_test(NAME print.PSPrinter COMMAND test_PSPrinter)
set_tests_properties(print.PSPrinter PROPERTIES TIMEOUT 60 PASS_REGULAR_EXPRESSION "test_PSPrinter: all passed")

add_executable(test_HPPCL test_HPPCL.cpp)
target_link_libraries(test_HPPCL PRIVATE print)
add_test(NAME print.HPPCL COMMAND test_HPPCL)
set_tests_properties(print.HPPCL PROPERTIES TIMEOUT 60 PASS_REGULAR_EXPRESSION "test_HPPCL: all passed")

add_executable(test_HostIPP test_HostIPP.cpp)
target_link_libraries(test_HostIPP PRIVATE print)
add_test(NAME print.HostIPP COMMAND test_HostIPP)
set_tests_properties(print.HostIPP PROPERTIES TIMEOUT 30 PASS_REGULAR_EXPRESSION "test_HostIPP: all passed")
