/*
	File:		MemObjTables.cpp

	Contains:	The memory object tables of the 2.1 (717006) ROM - the domains (two
				variants, by RAM size), the environments with their domain lists,
				and the data areas - as MemObjManager reads them.

	Generated by tools/newton-rom/analysis/memobj_tables.py --cpp from the ROM
	image; do not edit by hand.  docs/os600/memobj-tables.md is the same data.
*/

#include "MemObjManager.h"

// ROM 0x0c1011bc g1MegDomainTable
const DomainTableEntry	g1MegDomainTable[] =
{
	{ 'krnl', 0x0C100000, 0x00100000, 0x0, 0x0, 0x0 },
	{ 'kstk', 0x0C200000, 0x00200000, 0x80000, 0x0, 0x4 },
	{ 'user', 0x0C400000, 0x00600000, 0x80000, 0x60000, 0x4 },
	{ 'prot', 0x0CA00000, 0x00200000, 0x80000, 0x0, 0x7 },
	{ 'rams', 0x0CC00000, 0x00800000, 0x0, 0xFFFFFFFF, 0x27 },
	{ 'romc', 0x60000000, 0x08000000, 0x0, 0x0, 0x6 },
	{ 'ccl0', 0x70000000, 0x20000000, 0x0, 0x0, 0x0 },
	{ 'csk0', 0x90000000, 0x40000000, 0x0, 0x0, 0x0 },
	{ 'LicD', 0xE0000000, 0x08000000, 0x0, 0x0, 0x0 },
	{ 0, 0, 0, 0, 0, 0 }
};

// ROM 0x0c1012ac g4MegDomainTable
const DomainTableEntry	g4MegDomainTable[] =
{
	{ 'krnl', 0x0C100000, 0x00100000, 0x0, 0x0, 0x0 },
	{ 'kstk', 0x0C200000, 0x00400000, 0x100000, 0x0, 0x4 },
	{ 'user', 0x0C600000, 0x01000000, 0x380000, 0x200000, 0x4 },
	{ 'prot', 0x0D600000, 0x00800000, 0x100000, 0x0, 0x7 },
	{ 'rams', 0x0DE00000, 0x00800000, 0x0, 0xFFFFFFFF, 0x27 },
	{ 'romc', 0x60000000, 0x08000000, 0x0, 0x0, 0x6 },
	{ 'ccl0', 0x70000000, 0x20000000, 0x0, 0x0, 0x0 },
	{ 'csk0', 0x90000000, 0x40000000, 0x0, 0x0, 0x0 },
	{ 'LicD', 0xE0000000, 0x08000000, 0x0, 0x0, 0x0 },
	{ 0, 0, 0, 0, 0, 0 }
};

// 0x0c1013b4
static const ULong	kDomainList_0c1013b4[] = { 'user', 'krnl', 'kstk', 0 };
// 0x0c1013c4
static const ULong	kDomainList_0c1013c4[] = { 'user', 'krnl', 'kstk', 'prot', 'rams', 'csk0', 'ccl0', 'romc', 0 };
// 0x0c1013f8
static const ULong	kDomainList_0c1013f8[] = { 'user', 'krnl', 'kstk', 'csk0', 'ccl0', 'romc', 0 };
// 0x0c101414
static const ULong	kDomainList_0c101414[] = { 'prot', 0 };
// 0x0c1013e8
static const ULong	kDomainList_0c1013e8[] = { 'kstk', 0 };
// 0x0c1013f0
static const ULong	kDomainList_0c1013f0[] = { 'rams', 0 };
// 0x0c10141c
static const ULong	kDomainList_0c10141c[] = { 'user', 'prot', 'rams', 'ccl0', 'kstk', 0 };
// 0x0c101434
static const ULong	kDomainList_0c101434[] = { 'romc', 0 };

// ROM 0x0c10143c gEnvTable
const EnvTableEntry	gEnvTable[] =
{
	{ 'krnl', 'krnl', 'kstk', 'kstk', kDomainList_0c1013b4, nil },
	{ 'ksrv', 'kstk', 'kstk', 'kstk', kDomainList_0c1013b4, nil },
	{ 'cdfm', 'kstk', 'kstk', 'kstk', kDomainList_0c1013b4, nil },
	{ 'user', 'user', 'user', 'user', kDomainList_0c1013c4, nil },
	{ 'prot', 'user', 'user', 'user', kDomainList_0c1013f8, kDomainList_0c101414 },
	{ 'rams', 'rams', 'kstk', 'kstk', kDomainList_0c1013e8, kDomainList_0c1013f0 },
	{ 'romc', 'kstk', 'user', 'user', kDomainList_0c10141c, kDomainList_0c101434 },
	{ 0, 0, 0, 0, nil, nil }
};

// ROM 0x00000040 DataAreaTable
const DataAreaEntry	DataAreaTable[] =
{
	{ 'data', 0x0071A95C, 0x0C100800, 0x0C105AF0, 0x52F0, 0x2324 },
	{ 0, 0, 0, 0, 0, 0 }
};
