/*
	File:		utility/DES.h

	Contains:	The ROM's DES: the Data Encryption Standard as the desktop
				connection's password exchange and the store passwords use
				it.  A block is two 32-bit words (the ROM's first word the
				high half of the standard's 64-bit block); a key is two
				words as well, its parity bits ignored.

				DESKeySched makes the sixteen rounds' subkeys (32 words)
				from a key; DESEncode/DESDecode run blocks through them in
				place, a pointer that the call advances past what it did;
				DESEncodeNonce/DESDecodeNonce do one block under a key;
				DESCharToKey turns a password (a UniChar string) into a
				key - the string taken four characters at a time, each
				piece encrypted under the key made of the pieces before it
				(the first under "W@h`bmtd"), and the result given odd
				parity.

				The permutations are the ROM's tables (DESTables.cpp,
				generated by romtable.py): a table is bit numbers, 32 and
				up in the first word, below 32 in the second, counted from
				the least significant bit; 0x40 starts the second output
				word and anything above it ends the table.

	Reconstructed from the MP2x00 US ROM; each function cites its origin.
*/

#ifndef __UTILITY_DES_H
#define __UTILITY_DES_H

#ifndef __NEWTON_H
#include "Newton.h"
#endif

#include <stdint.h>

typedef uint32_t	DESWord;

void	DESpermute(const unsigned char* table, DESWord hi, DESWord lo, DESWord* out);
void	DESip(DESWord hi, DESWord lo, DESWord* out);
DESWord	DESfrk(DESWord k0, DESWord k1, DESWord r);
void	DESKeySched(const DESWord* key, DESWord* schedule);		// schedule: 32 words
void	DESEncode(const DESWord* schedule, long length, DESWord** data);
void	DESDecode(const DESWord* schedule, long length, DESWord** data);
void	DESEncodeNonce(const DESWord* key, DESWord* block);
void	DESDecodeNonce(const DESWord* key, DESWord* block);
void	DESCharToKey(const UniChar* password, DESWord* key);

#endif	/* __UTILITY_DES_H */
