/*
	File:		toolbox/Angles.h

	Contains:	Angles as the recogniser and the graphics code keep them:
				16.16 degrees in (-180, 180], normalised by MapDegrees, and
				the arithmetic that keeps them there (AddAngle, DeltaAngle,
				MidAngle).  The angle between two fixed-point points is
				PtsToAngle - GetSlope is that to the nearest whole degree,
				which is the form the gesture tests compare - and
				AngleFromSlope is the arctangent underneath, a table lookup
				answering whole degrees.

				PtsToAngleR is the odd one out: it answers 16.16 *radians*
				from FixedAtan2, and NORM is its normaliser (to (-pi, pi]).
				FixedLength is the length of a vector without a square root.

				The tables AngleFromSlope reads are AngleTables.cpp,
				generated by analysis/romtable.py.

	Reconstructed from the MP2x00 US ROM; each function cites its origin.
*/

#ifndef __ANGLES_H
#define __ANGLES_H

#ifndef __FIXEDMATH_H
#include "FixedMath.h"
#endif
#ifndef __NEWTONTYPES_H
#include "NewtonTypes.h"
#endif


// 180 and 360 degrees, and pi, in 16.16
enum {
	kHalfTurnDegrees	= 0x00b40000,
	kFullTurnDegrees	= 0x01680000,
	kPiRadians			= 0x0003243f
};

long	MapDegrees(long degrees);					// ROM 0x00030c3c MapDegrees - into (-180, 180]
Fixed	DegToRad(long degrees);						// ROM 0x00030c68 DegToRad
long	DeltaAngle(long from, long to);				// ROM 0x00030c8c DeltaAngle - to - from, mapped
long	AddAngle(long a, long b);					// ROM 0x00030c94 AddAngle
long	MidAngle(long a, long b);					// ROM 0x00030c9c MidAngle - half way from a to b the short way round

ULong	AngleFromSlope(Fixed slope);				// ROM 0x002aa530 AngleFromSlope__Fl - whole degrees, 0..180
long	PtsToAngle(const FPoint* a, const FPoint* b, Fixed unit);	// ROM 0x00030cc0 PtsToAngle - rounded to a multiple of unit
long	GetSlope(const FPoint* a, const FPoint* b);	// ROM 0x00030d50 GetSlope - PtsToAngle to the whole degree
Fixed	PtsToAngleR(const FPoint* a, const FPoint* b);	// ROM 0x00030d58 PtsToAngleR__FP6FPointT1 - 16.16 radians, 0 outside +/-4
void	NORM(long* radians);						// ROM 0x00030dbc NORM__FPl - into (-pi, pi]

#endif	/* __ANGLES_H */
