// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> speedMantissasX10:u8:16 speedExps:u32:8 kPowerMantissas@0x00366e58:u8:16 kPowerExponents@0x00366e68:u32:8 sCISRamDevice:u8:5 sCISNoLink:u8:2 sCISEnd:u8:1 sCISTarget:u8:5 sCISLevel2:u8:19 -o src/pcmcia/CISTables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const unsigned char	speedMantissasX10[16];
extern const unsigned int	speedExps[8];
extern const unsigned char	kPowerMantissas[16];
extern const unsigned int	kPowerExponents[8];
extern const unsigned char	sCISRamDevice[5];
extern const unsigned char	sCISNoLink[2];
extern const unsigned char	sCISEnd[1];
extern const unsigned char	sCISTarget[5];
extern const unsigned char	sCISLevel2[19];

// ROM 0x0c100918 speedMantissasX10
const unsigned char	speedMantissasX10[16] = {
	0x00, 0x0a, 0x0c, 0x0d, 0x0f, 0x14, 0x19, 0x1e, 0x23, 0x28, 0x2d, 0x32, 0x37, 0x3c, 0x46, 0x50,
};

// ROM 0x0c100928 speedExps
const unsigned int	speedExps[8] = {
	0x00000001, 0x0000000a, 0x00000064, 0x000003e8, 0x00002710, 0x000186a0, 0x000f4240, 0x00989680,
};

// ROM 0x00366e58 (unnamed) - kPowerMantissas
const unsigned char	kPowerMantissas[16] = {
	0x0a, 0x0c, 0x0d, 0x0f, 0x14, 0x19, 0x1e, 0x23, 0x28, 0x2d, 0x32, 0x37, 0x3c, 0x46, 0x50, 0x5a,
};

// ROM 0x00366e68 (unnamed) - kPowerExponents
const unsigned int	kPowerExponents[8] = {
	0x00000001, 0x0000000a, 0x00000064, 0x000003e8, 0x00002710, 0x000186a0, 0x000f4240, 0x00989680,
};

// ROM 0x0c1008e8 sCISRamDevice
const unsigned char	sCISRamDevice[5] = {
	0x01, 0x03, 0x61, 0x06, 0xff,
};

// ROM 0x0c1008f0 sCISNoLink
const unsigned char	sCISNoLink[2] = {
	0x14, 0x00,
};

// ROM 0x0c1008f4 sCISEnd
const unsigned char	sCISEnd[1] = {
	0xff,
};

// ROM 0x0c1008f8 sCISTarget
const unsigned char	sCISTarget[5] = {
	0x13, 0x03, 0x43, 0x49, 0x53,
};

// ROM 0x0c100900 sCISLevel2
const unsigned char	sCISLevel2[19] = {
	0x40, 0x11, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x01, 0x4e, 0x65, 0x77, 0x74, 0x4f,
	0x53, 0x00, 0x00,
};
