// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> speedMantissasX10:u8:16 speedExps:u32:8 kPowerMantissas@0x00366e58:u8:16 kPowerExponents@0x00366e68:u32:8 kNewtOSStrings@0x0c100974:cstr:1 kArmCPU610Strings@0x0c100978:cstr:1 kNullStrings@0x0c10097c:cstr:1 -o src/pcmcia/CISTables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const unsigned char	speedMantissasX10[16];
extern const unsigned int	speedExps[8];
extern const unsigned char	kPowerMantissas[16];
extern const unsigned int	kPowerExponents[8];
extern const char* const	kNewtOSStrings[1];
extern const char* const	kArmCPU610Strings[1];
extern const char* const	kNullStrings[1];

// ROM 0x0c100918 speedMantissasX10
const unsigned char	speedMantissasX10[16] = {
	0x00, 0x0a, 0x0c, 0x0d, 0x0f, 0x14, 0x19, 0x1e, 0x23, 0x28, 0x2d, 0x32, 0x37, 0x3c, 0x46, 0x50,
};

// ROM 0x0c100928 speedExps
const unsigned int	speedExps[8] = {
	0x00000001, 0x0000000a, 0x00000064, 0x000003e8, 0x00002710, 0x000186a0, 0x000f4240, 0x00989680,
};

// ROM 0x00366e58 (unnamed) - kPowerMantissas
const unsigned char	kPowerMantissas[16] = {
	0x0a, 0x0c, 0x0d, 0x0f, 0x14, 0x19, 0x1e, 0x23, 0x28, 0x2d, 0x32, 0x37, 0x3c, 0x46, 0x50, 0x5a,
};

// ROM 0x00366e68 (unnamed) - kPowerExponents
const unsigned int	kPowerExponents[8] = {
	0x00000001, 0x0000000a, 0x00000064, 0x000003e8, 0x00002710, 0x000186a0, 0x000f4240, 0x00989680,
};

// ROM 0x0c100974 (unnamed) - kNewtOSStrings
const char* const	kNewtOSStrings[1] = {
	"NewtOS",
};

// ROM 0x0c100978 (unnamed) - kArmCPU610Strings
const char* const	kArmCPU610Strings[1] = {
	"Arm610",
};

// ROM 0x0c10097c (unnamed) - kNullStrings
const char* const	kNullStrings[1] = {
	"",
};
