// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> kFaxFineLetter@0x00378be4:u32:3 kFaxStandardLetter@0x00378bf0:u32:3 kFaxFineA4@0x00378bfc:u32:3 kFaxStandardA4@0x00378c08:u32:3 -o src/print/FaxDriverTables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const unsigned int	kFaxFineLetter[3];
extern const unsigned int	kFaxStandardLetter[3];
extern const unsigned int	kFaxFineA4[3];
extern const unsigned int	kFaxStandardA4[3];

// ROM 0x00378be4 (unnamed) - kFaxFineLetter
const unsigned int	kFaxFineLetter[3] = {
	0x00c80000, 0x00c80000, 0x08020672,
};

// ROM 0x00378bf0 (unnamed) - kFaxStandardLetter
const unsigned int	kFaxStandardLetter[3] = {
	0x00c80000, 0x00640000, 0x04010672,
};

// ROM 0x00378bfc (unnamed) - kFaxFineA4
const unsigned int	kFaxFineA4[3] = {
	0x00c80000, 0x00c80000, 0x088c063c,
};

// ROM 0x00378c08 (unnamed) - kFaxStandardA4
const unsigned int	kFaxStandardA4[3] = {
	0x00c80000, 0x00640000, 0x0446063c,
};
