// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> gPostscriptHeader:text gPostscriptHeader2:text gOpenPageHeader:text gPSLandscape:text gClosePageHeader:text gPSBinToHex:u16:256 gPSStatusStrings:icstr:15 -o src/print/PSPrinterTables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

#include "print/PSPrinter.h"

extern const char	gPostscriptHeader[3502];
extern const char	gPostscriptHeader2[2414];
extern const char	gOpenPageHeader[102];
extern const char	gPSLandscape[12];
extern const char	gClosePageHeader[48];
extern const unsigned short	gPSBinToHex[256];
extern const IntCString	gPSStatusStrings[15];

// ROM 0x00378c9c gPostscriptHeader
const char	gPostscriptHeader[3502] =
	"%%Copyright: \251 Copyright Apple Computer, Inc. 1989-93 All Rights Reserved.\r"
	"%%EndComments\r"
	"%%BeginProlog\r"
	"/Bdf { bind def } bind def\r"
	"/Xdf { exch def } Bdf\r"
	"/CP { closepath } Bdf\r"
	"/LnTo { lineto } Bdf\r"
	"/RLnTo { rlineto } Bdf\r"
	"/CT { curveto } Bdf\r"
	"/CLW { currentlinewidth } Bdf\r"
	"/CurPt { currentpoint } Bdf\r"
	"/MvTo { moveto } Bdf\r"
	"/SLW { setlinewidth } Bdf\r"
	"/FlipCTM {\r"
	"\t[ 1 0 0 -1 \r"
	"\tclippath pathbbox\r"
	"\texch pop exch pop] concat\r"
	"\t} Bdf\r"
	"/Pen { /penV Xdf /penH Xdf } Bdf \r"
	"/SclPen { gsave penH penV scale stroke grestore } Bdf\r"
	"/StdRect { \r"
	"  /right Xdf /bottom Xdf /left Xdf /top Xdf\r"
	"  left top MvTo right top LnTo right bottom LnTo left bottom LnTo\r"
	"  } Bdf\r"
	"/FrameOval {\r"
	"  /endArc Xdf /startArc Xdf\r"
	"  /right Xdf /bottom Xdf /left Xdf /top Xdf\r"
	"  /width right left sub def /height bottom top sub def\r"
	"  /centerX right left add 2 div def /centerY bottom top add 2 div def\r"
	"  /curMatrix matrix currentmatrix def\r"
	"  centerX centerY translate\r"
	"  1 height width div scale\r"
	"  0 0 width 2 div startArc endArc arc\r"
	"  curMatrix setmatrix\r"
	"  } Bdf\r"
	"/MacVec 256 array def\r"
	"/NUL/SOH/STX/ETX/EOT/ENQ/ACK/BEL/BS/HT/LF/VT/FF/CR/SO/SI\r"
	"/DLE/DC1/DC2/DC3/DC4/NAK/SYN/ETB/CAN/EM/SUB/ESC/FS/GS/RS/US\r"
	"MacVec 0 32 getinterval astore pop\r"
	"MacVec 32/Times-Roman findfont/Encoding get\r"
	"32 96 getinterval putinterval MacVec dup 39/quotesingle put 96/grave put\r"
	"MacVec 128\r"
	"[/Adieresis/Aring/Ccedilla/Eacute/Ntilde/Odieresis/Udieresis/aacute\r"
	"/agrave/acircumflex/adieresis/atilde/aring/ccedilla/eacute/egrave\r"
	"/ecircumflex/edieresis/iacute/igrave/icircumflex/idieresis/ntilde/oacute\r"
	"/ograve/ocircumflex/odieresis/otilde/uacute/ugrave/ucircumflex/udieresis\r"
	"/dagger/degree/cent/sterling/section/bullet/paragraph/germandbls\r"
	"/registered/copyright/trademark/acute/dieresis/notequal/AE/Oslash\r"
	"/infinity/plusminus/lessequal/greaterequal/yen/mu/partialdiff/summation\r"
	"/product/pi/integral/ordfeminine/ordmasculine/Omega/ae/oslash\r"
	"/questiondown/exclamdown/logicalnot/radical/florin/approxequal/Delta/guillemotleft\r"
	"/guillemotright/ellipsis/blank/Agrave/Atilde/Otilde/OE/oe\r"
	"/endash/emdash/quotedblleft/quotedblright/quoteleft/quoteright/divide/lozenge\r"
	"/ydieresis/Ydieresis/fraction/currency/guilsinglleft/guilsinglright/fi/fl\r"
	"/daggerdbl/periodcentered/quotesinglbase/quotedblbase/perthousand/Acircumflex/Ecircumflex/Aacute\r"
	"/Edieresis/Egrave/Iacute/Icircumflex/Idieresis/Igrave/Oacute/Ocircumflex\r"
	"/apple/Ograve/Uacute/Ucircumflex/Ugrave/dotlessi/circumflex/tilde\r"
	"/macron/breve/dotaccent/ring/cedilla/hungarumlaut/ogonek/caron] putinterval\r"
	"/EncodeFont {\r"
	"  findfont\r"
	"  dup length dict begin\r"
	"    {1 index /FID ne {def} {pop pop} ifelse} forall\r"
	"    /Encoding MacVec def\r"
	"    currentdict\r"
	"  end\r"
	"  definefont pop\r"
	"  } Bdf\r"
	"/SF { /fSize Xdf findfont [fSize 0 0 fSize neg 0 0] makefont setfont } Bdf\r"
	"/UL {\r"
	"\tCLW CurPt 9 3 roll\r"
	"\t1 eq {1.5 mul} {} ifelse\r"
	"\t18 div dup .5 lt {pop .5} {} ifelse\r"
	"\tdup /tempVal Xdf SLW\r"
	"\tnewpath\r"
	"\ttempVal 2 div add 1 add MvTo tempVal 2 div add 1 add LnTo stroke MvTo SLW\r"
	"} Bdf\r"
	" /concatprocs {\r"
	"  /proc2 exch cvlit def\r"
	"  /proc1 exch cvlit def\r"
	"  /newproc proc1 length proc2 length add array def\r"
	"  newproc 0 proc1 putinterval\r"
	"  newproc proc1 length proc2 putinterval\r"
	"  newproc cvx\r"
	"  } Bdf\r"
	"/PreC { currentfont grestore gsave newpath } Bdf\r"
	"/PoC { clip newpath setfont } Bdf\r"
	"/jn{/statusdict where exch pop{statusdict exch /jobname exch put}if}Bdf\r"
	"/bimage {\r"
	"\t/depth Xdf\r"
	"  /scanlines Xdf\r"
	"  /width Xdf\r"
	"\tsave \r"
	"\t/picstr width depth mul 7 add 8 div cvi string def\r"
	"  width scanlines depth [width 0 0 scanlines 0 0]\r"
	"  {currentfile picstr readhexstring pop}\r"
	"  image\r"
	"\trestore \r"
	"  } def\r";

// ROM 0x00379a4c gPostscriptHeader2
const char	gPostscriptHeader2[2414] =
	"systemdict /languagelevel known not {/LLDan 1 def}  {/LLDan languagelevel def} ifelse\r"
	"/BeginDefineForLevel1 { LLDan 2 ge {save} if } Bdf\r"
	"/EndDefineForLevel1\t{ LLDan 2 ge {restore} if } Bdf\r"
	"/BeginDefineForLevel2 { LLDan 2 lt {save} if } Bdf\r"
	"/EndDefineForLevel2\t{ LLDan 2 lt {restore} if } Bdf\r"
	"/Grid\r"
	"{transform\r"
	"round exch round exch\r"
	"itransform\r"
	"} Bdf\r"
	"BeginDefineForLevel1\r"
	"/PatternBuildChar\r"
	"{pop begin 8 0 bitsPerPixel 1 eq \r"
	"{0 0 8 8 setcachedevice\r"
	"8 8 true matrix {PatternData} imagemask}\r"
	"{setcharwidth 8 8 bitsPerPixel matrix {PatternData} image\t}\r"
	"ifelse end\r"
	"} Bdf\r"
	"/MakePatternFont\r"
	"{10 dict begin\r"
	"/PatternData exch def\r"
	"/bitsPerPixel exch def\r"
	"/orMode exch def\r"
	"/FontType 3 def\r"
	"/FontMatrix matrix def\r"
	"/FontBBox [0 0 8 8] def\r"
	"/BuildChar /PatternBuildChar load def\r"
	"/Encoding StandardEncoding def\r"
	"currentdict\r"
	"end\r"
	"} Bdf\r"
	"EndDefineForLevel1\r"
	"BeginDefineForLevel2\r"
	"/PatternPaintProc\r"
	"{begin bitsPerPixel 1 eq\r"
	"{8 8 true matrix {PatternData} imagemask}\r"
	"{8 8 bitsPerPixel matrix {PatternData} image}\r"
	"ifelse end} Bdf\r"
	"/MakeL2PatternDict\r"
	"{9 dict begin /PatternData exch def /bitsPerPixel exch def /orMode exch def bitsPerPixel 1 eq orMode and\r"
	"{/PaintType 2 def}\r"
	"{/PaintType 1 def} ifelse\r"
	"/PatternType 1 def /TilingType 1 def /BBox [0 0 8 8] def /XStep 8 def /YStep 8 def /PaintProc /PatternPaintProc load def\r"
	"currentdict end\r"
	"matrix makepattern} Bdf\r"
	"/PatternFill\r"
	"{gsave CurrentPattern setpattern fill grestore newpath } Bdf\r"
	"EndDefineForLevel2\r"
	"/CurrentPattern null def\r"
	"/SetCurrentPattern \r"
	"{dup null ne \r"
	"{LLDan 1 eq \r"
	"{7 dict begin\r"
	"MakePatternFont /PatternFont exch definefont /theFont exch def /griddedWidth 0 def /griddedHeight 0 def\r"
	"/pBBoxX1 0 def\r"
	"/pBBoxY1 0 def\r"
	"/pBBoxX2 0 def\r"
	"/pBBoxY2 0 def\r"
	"currentdict end}\r"
	"{MakeL2PatternDict} ifelse } if\r"
	"/CurrentPattern exch def\r"
	"} Bdf\r"
	"BeginDefineForLevel1\r"
	"/PatternFill\r"
	"{gsave CurrentPattern begin\r"
	"theFont /bitsPerPixel get 1 eq theFont /orMode get and\r"
	"{1.0 setgray fill grestore gsave }\r"
	"if 8 8 Grid /griddedHeight exch def /griddedWidth exch def\r"
	"theFont\r"
	"griddedWidth 8 div griddedHeight 8 div\r"
	"matrix scale\r"
	"makefont\r"
	"setfont\r"
	"pathbbox\r"
	"griddedHeight div ceiling /pBBoxY2 exch def\r"
	"griddedWidth div ceiling /pBBoxX2 exch def\r"
	"griddedHeight div floor /pBBoxY1 exch def\r"
	"griddedWidth div floor /pBBoxX1 exch def\r"
	"save clip pBBoxX2 pBBoxX1 sub 1 add cvi string\r"
	"pBBoxY1 1 pBBoxY2 \r"
	"{griddedHeight mul pBBoxX1 griddedWidth mul exch moveto dup show }\r"
	"for pop restore end\r"
	"grestore\r"
	"newpath\r"
	"} Bdf\r"
	"EndDefineForLevel1\r";

// ROM 0x0037a3bc gOpenPageHeader
const char	gOpenPageHeader[102] =
	"%%BeginPageSetup\r"
	"/pgSave save def\r"
	"FlipCTM\r"
	"1 setlinejoin\r"
	"/Times-Roman-Mac 12 SF\r"
	"gsave\r"
	"%%EndPageSetup\r"
	"\r";

// ROM 0x0037a424 gPSLandscape
const char	gPSLandscape[12] =
	" 90 rotate\r";

// ROM 0x0037a430 gClosePageHeader
const char	gClosePageHeader[48] =
	"grestore\r"
	"pgSave restore\r"
	"showpage\r"
	"%%PageTrailer\r";

// ROM 0x0037a4dc gPSBinToHex
const unsigned short	gPSBinToHex[256] = {
	0x3030, 0x3031, 0x3032, 0x3033, 0x3034, 0x3035, 0x3036, 0x3037,
	0x3038, 0x3039, 0x3041, 0x3042, 0x3043, 0x3044, 0x3045, 0x3046,
	0x3130, 0x3131, 0x3132, 0x3133, 0x3134, 0x3135, 0x3136, 0x3137,
	0x3138, 0x3139, 0x3141, 0x3142, 0x3143, 0x3144, 0x3145, 0x3146,
	0x3230, 0x3231, 0x3232, 0x3233, 0x3234, 0x3235, 0x3236, 0x3237,
	0x3238, 0x3239, 0x3241, 0x3242, 0x3243, 0x3244, 0x3245, 0x3246,
	0x3330, 0x3331, 0x3332, 0x3333, 0x3334, 0x3335, 0x3336, 0x3337,
	0x3338, 0x3339, 0x3341, 0x3342, 0x3343, 0x3344, 0x3345, 0x3346,
	0x3430, 0x3431, 0x3432, 0x3433, 0x3434, 0x3435, 0x3436, 0x3437,
	0x3438, 0x3439, 0x3441, 0x3442, 0x3443, 0x3444, 0x3445, 0x3446,
	0x3530, 0x3531, 0x3532, 0x3533, 0x3534, 0x3535, 0x3536, 0x3537,
	0x3538, 0x3539, 0x3541, 0x3542, 0x3543, 0x3544, 0x3545, 0x3546,
	0x3630, 0x3631, 0x3632, 0x3633, 0x3634, 0x3635, 0x3636, 0x3637,
	0x3638, 0x3639, 0x3641, 0x3642, 0x3643, 0x3644, 0x3645, 0x3646,
	0x3730, 0x3731, 0x3732, 0x3733, 0x3734, 0x3735, 0x3736, 0x3737,
	0x3738, 0x3739, 0x3741, 0x3742, 0x3743, 0x3744, 0x3745, 0x3746,
	0x3830, 0x3831, 0x3832, 0x3833, 0x3834, 0x3835, 0x3836, 0x3837,
	0x3838, 0x3839, 0x3841, 0x3842, 0x3843, 0x3844, 0x3845, 0x3846,
	0x3930, 0x3931, 0x3932, 0x3933, 0x3934, 0x3935, 0x3936, 0x3937,
	0x3938, 0x3939, 0x3941, 0x3942, 0x3943, 0x3944, 0x3945, 0x3946,
	0x4130, 0x4131, 0x4132, 0x4133, 0x4134, 0x4135, 0x4136, 0x4137,
	0x4138, 0x4139, 0x4141, 0x4142, 0x4143, 0x4144, 0x4145, 0x4146,
	0x4230, 0x4231, 0x4232, 0x4233, 0x4234, 0x4235, 0x4236, 0x4237,
	0x4238, 0x4239, 0x4241, 0x4242, 0x4243, 0x4244, 0x4245, 0x4246,
	0x4330, 0x4331, 0x4332, 0x4333, 0x4334, 0x4335, 0x4336, 0x4337,
	0x4338, 0x4339, 0x4341, 0x4342, 0x4343, 0x4344, 0x4345, 0x4346,
	0x4430, 0x4431, 0x4432, 0x4433, 0x4434, 0x4435, 0x4436, 0x4437,
	0x4438, 0x4439, 0x4441, 0x4442, 0x4443, 0x4444, 0x4445, 0x4446,
	0x4530, 0x4531, 0x4532, 0x4533, 0x4534, 0x4535, 0x4536, 0x4537,
	0x4538, 0x4539, 0x4541, 0x4542, 0x4543, 0x4544, 0x4545, 0x4546,
	0x4630, 0x4631, 0x4632, 0x4633, 0x4634, 0x4635, 0x4636, 0x4637,
	0x4638, 0x4639, 0x4641, 0x4642, 0x4643, 0x4644, 0x4645, 0x4646,
};

// ROM 0x00378c20 gPSStatusStrings
const IntCString	gPSStatusStrings[15] = {
	{ -44006, "limitcheck" },
	{ -44006, "dictfull" },
	{ -44000, "Flushing: rest of job" },
	{ -44104, "out of paper" },
	{ -44102, "no paper tray" },
	{ -44000, "rinter resetting" },
	{ -44000, "timeout" },
	{ 0, "arming up" },
	{ -44107, "over open" },
	{ -44106, "jam" },
	{ -44105, "no toner" },
	{ 0, "idle" },
	{ -44003, "busy" },
	{ -44003, "waiting" },
	{ -44003, "printing" },
};
