#!/usr/bin/env python3
"""Emit the handwriting engine's bigram grammar as C++.

Usage:
    python bigrammar.py <build_dir> -o <src/recognition/ROMGrammar.cpp> [--doc <docs/...md>]
    build/venv/Scripts/python tools/newton-rom/analysis/bigrammar.py build/MP2x00US -o src/recognition/ROMGrammar.cpp --doc docs/recognition/grammar.md

`ROMGrammar` (ROM 0x00366e0c) is what `BiGrammarsLoad` answers: the eight
grammars the engine reads a word against - General, Date, Numbers&Money,
Numbers, Phone, Time, Money and PostalCode - and a field asks for one by
name (`WordRecogSetContext`).

Each grammar is a `BiGrammar` holding an array of `BiGSlice`s, and a slice
is *a kind of word*: a lexicon out of `gROMDictionaryData` with a score of
its own and, for every kind that may follow it, another score.  So the
grammar is a bigram model over lexicons rather than over characters, which
is what its name says.  The scores are the arithmetic coder's
(`ArProbDecodeLu` turns one into a probability) and 0x7ffe means "never".

The graph is entirely inside the ROM: nothing points outside its own
grammar, no two slices share a transition array, and no two share a name
string, so it is written out one grammar at a time.  The struct layouts are
`recognition/RosEngine.h`'s, taken from `BiGrammarNew` (0x0003de8c) and
`BiGSliceNew` (0x0003dfb4).

The output should not be edited by hand: regenerate it after a re-import.
"""

from __future__ import annotations

import argparse
import json
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import romid			# the ROM names itself in what this writes


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build_dir")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--doc", help="also write the grammar out as a document")
    args = ap.parse_args(argv)

    with open(os.path.join(args.build_dir, "rom.bin"), "rb") as f:
        rom = f.read()
    with open(os.path.join(args.build_dir, "symbols.json"), encoding="utf-8") as f:
        data = json.load(f)
    by_name = {}
    by_addr = {}
    for s in data["symbols"]:
        if "jt_index" not in s:
            by_name.setdefault(s["name"], s["address"])
            by_addr.setdefault(s["address"], s["name"])

    if "ROMGrammar" not in by_name:
        print("error: no ROMGrammar symbol", file=sys.stderr)
        return 1

    def word(a): return struct.unpack(">I", rom[a:a + 4])[0]
    def half(a): return struct.unpack(">h", rom[a:a + 2])[0]
    def byte(a): return rom[a]
    def cstr(a):
        end = rom.index(b"\0", a)
        return rom[a:end].decode("mac-roman")

    def cite(addr):
        """The `// ROM ...` line for a thing in the grammar."""
        name = by_addr.get(addr)
        return f"// ROM 0x{addr:08x} {name}" if name else f"// ROM 0x{addr:08x} (unnamed)"

    grammar = by_name["ROMGrammar"]
    count = word(grammar)
    contexts = word(grammar + 4)

    out = ["// Generated by tools/newton-rom/analysis/bigrammar.py; do not edit.",
           f"//   build/venv/Scripts/python tools/newton-rom/analysis/bigrammar.py {args.build_dir.replace(os.sep, '/')} -o {args.output.replace(os.sep, '/')}",
           "// The handwriting engine's bigram grammar: the eight grammars a word is",
           f"// read against, from the {romid.rom_version(args.build_dir)} ROM at the addresses cited.",
           "//",
           "// A slice is a kind of word - a lexicon out of gROMDictionaryData, a score",
           "// of its own, and a score for every kind that may follow it.  0x7ffe means",
           "// never.",
           "",
           '#include "RosEngine.h"',
           ""]
    doc = []
    names = []

    def cname(addr, fallback):
        """The ROM's own name for a thing, which it has for all of these."""
        return by_addr.get(addr, fallback)

    for i in range(count):
        ctx = word(contexts + i * 4)
        ctx_name = cstr(word(ctx))
        symbol = cname(ctx, f"kBiG{i}")
        slices = word(ctx + 0x10)
        n = word(ctx + 8)
        index = {word(slices + k * 4): k for k in range(n)}
        slice_addrs = [word(slices + k * 4) for k in range(n)]
        slice_names = [cname(a2, f"{symbol}Slice{k}") for k, a2 in enumerate(slice_addrs)]

        out.append(f"/*--------------------------------------------------------------------")
        out.append(f"	{ctx_name}: {n} kinds of word.")
        out.append(f"--------------------------------------------------------------------*/")
        for k in range(n):
            out.append(f"extern const BiGSlice	{slice_names[k]};")
        out.append("")

        # the transitions first, because the slices point at them
        for k in range(n):
            s2 = slice_addrs[k]
            m = word(s2 + 0x20)
            if m == 0:
                continue
            nxt, wts = word(s2 + 0x24), word(s2 + 0x28)
            targets = []
            for j in range(m):
                t = word(nxt + j * 4)
                if t not in index:
                    print(f"error: {ctx_name} slice {k} goes outside its own grammar", file=sys.stderr)
                    return 1
                targets.append("&" + slice_names[index[t]])
            ln = cname(nxt, f"{slice_names[k]}Next")
            lp = cname(wts, f"{slice_names[k]}Weights")
            out.append(cite(nxt))
            out.append(f"extern const BiGSlice* const	{ln}[{m}] = {{")
            for j in range(0, m, 3):
                out.append("	" + ", ".join(targets[j:j + 3]) + ",")
            out[-1] = out[-1][:-1]
            out.append("};")
            out.append(cite(wts))
            weights = ", ".join("%d" % half(wts + j * 2) for j in range(m))
            out.append(f"extern const short	{lp}[{m}] = {{ {weights} }};")
            out.append("")

        doc.append(f"### {ctx_name}")
        doc.append("")
        doc.append("| | kind of word | lexicon | score | may be followed by |")
        doc.append("|---|---|---|---|---|")
        for k in range(n):
            s2 = slice_addrs[k]
            m = word(s2 + 0x20)
            nxt = cname(word(s2 + 0x24), f"{slice_names[k]}Next") if m else "nil"
            wts = cname(word(s2 + 0x28), f"{slice_names[k]}Weights") if m else "nil"
            fields = [
                '"%s"' % cstr(word(s2)),
                "%d" % word(s2 + 4),
                "%d, %d" % (half(s2 + 8), half(s2 + 0x0a)),
                "%d, %d" % (half(s2 + 0x0c), half(s2 + 0x0e)),
                "0x%08x" % word(s2 + 0x10),
                "%d, %d" % (half(s2 + 0x14), half(s2 + 0x16)),
                "%d, %d" % (half(s2 + 0x18), half(s2 + 0x1a)),
                "%d" % word(s2 + 0x1c),
                "%d" % m,
                nxt, wts,
                "0x%02x" % byte(s2 + 0x2c),
            ]
            out.append(cite(s2))
            out.append(f"extern const BiGSlice	{slice_names[k]} =")
            out.append("	{ " + ", ".join(fields) + " };")
            follows = "-"
            if m:
                parts = []
                for j in range(m):
                    target = word(word(s2 + 0x24) + j * 4)
                    parts.append("%s&nbsp;%d" % (cstr(word(target)), half(word(s2 + 0x28) + j * 2)))
                follows = ", ".join(parts)
            doc.append("| %d | `%s` | %d | %d | %s |" % (k, cstr(word(s2)), word(s2 + 4), half(s2 + 8), follows))
        out.append("")
        doc.append("")

        listname = cname(slices, f"{symbol}List")
        out.append(cite(slices))
        out.append(f"extern const BiGSlice* const	{listname}[{n}] = {{")
        for k in range(0, n, 3):
            out.append("	" + ", ".join("&" + slice_names[j] for j in range(k, min(k + 3, n))) + ",")
        out[-1] = out[-1][:-1]
        out.append("};")
        out.append("")
        out.append(cite(ctx))
        out.append(f"extern const BiGrammar	{symbol} = {{")
        out.append('	"%s", %d, %d, %d, %s,' % (ctx_name, word(ctx + 4), n, word(ctx + 0x0c), listname))
        limits = ", ".join(str(byte(ctx + 0x15 + i)) for i in range(10))
        out.append("	%d, { %s }" % (byte(ctx + 0x14), limits))
        out.append("};")
        out.append("")
        names.append(symbol)

    out.append(cite(contexts))
    top = by_addr.get(contexts, "kROMGrammarContexts")
    out.append(f"extern const BiGrammar* const\t{top}[{count}] = {{")
    for n2 in names:
        out.append(f"\t&{n2},")
    out[-1] = out[-1][:-1]
    out.append("};")
    out.append("")
    out.append(cite(grammar))
    out.append("extern const BiGrammars\tROMGrammar = { %d, %s };" % (count, top))
    out.append("")

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {args.output}: {count} grammars")

    if args.doc:
        head = ["# The handwriting engine's bigram grammar", "",
                "Generated by `tools/newton-rom/analysis/bigrammar.py`; do not edit.",
                "",
                f"`ROMGrammar` (ROM 0x{grammar:08x}) holds the {count} grammars the engine reads a",
                "word against. A field asks for one by name, and each is a list of",
                "*kinds of word*: a lexicon out of `gROMDictionaryData`, a score of its",
                "own, and a score for every kind that may follow it. A lower score is",
                "better and 0x7ffe (32766) means never.",
                "",
                "The lexicon column is the index into `gROMDictionaryData`",
                "(`src/recognition/ROMDictionaryTable.cpp` names them); 0 is the",
                "placeholder an area's own dictionary is put into.",
                ""]
        with open(args.doc, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(head + doc))
        print(f"wrote {args.doc}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
