#!/usr/bin/env python3
"""Emit the handwriting engine's classifier net and its trained tables as C++.

Usage:
    python bpnet.py <build_dir> -o <src/recognition/BPNetTables.cpp>
    build/venv/Scripts/python tools/newton-rom/analysis/bpnet.py build/MP2x00US -o src/recognition/BPNetTables.cpp

At the bottom of reading a word is a back-propagation net.  `BPNetCreateNumOut`
(ROM 0x0003b1cc) makes one by copying a 0x84-byte template, `bpNet`
(0x0036e618), into a block of its own - the same trick `CharInitialize` uses
for the common info - and the template points at the trained tables:

  bpWeight          one byte per connection, biased by 128
  newtConnects      the connection program: one word per group of connections
  numConnectRanges  the ranges those words are divided into
  bpNGS, bpCSS      the net's structure
  inputType         what each of the four input groups is
  bpParam, arBPParam  the net's and the arithmetic coder's parameters
  QSigLu            the sigmoid, 0..255 with 128 for a sum of nought

This script writes the template out as a `BPNet` initialiser with those
tables emitted beside it, exactly as `rosci.py` does for the common info.
The struct's field order is `recognition/BPNet.h`'s and is repeated in
FIELDS below; a field nothing has been seen to read is `fFieldNN` there and
here.

The output should not be edited by hand: regenerate it after a re-import.
"""

from __future__ import annotations

import argparse
import json
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import romid			# the ROM names itself in what this writes


# The tables the template points at: name, element type, and how many.
# A count of None is worked out from the next symbol after it.
TABLES = [
    ("bpNGS", "ULong", None), ("bpCSS", "ULong", None),
    ("inputType", "ULong", None), ("numConnectRanges", "ULong", None),
    ("bpParam", "ULong", None), ("arBPParam", "ULong", None),
    ("bpWeight", "UByte", None), ("newtConnects", "ULong", None),
]

# The sigmoid is not named by the template - `BPNetEvaluate` reaches it
# through a literal of its own - so it is emitted on its own account.
EXTRA = [("QSigLu", "UByte", None)]

# The 0x84-byte template, word by word: the C field name, whether the word
# holds a pointer to one of the tables above, and how many words the field
# covers.  This is `BPNet`'s declaration in recognition/BPNet.h.
FIELDS = [
    ("fField00", "word", 3),		# +0x00
    ("fNGS", "ptr", 1),				# +0x0c  bpNGS
    ("fInputType", "ptr", 1),		# +0x10  inputType
    ("fField14", "word", 1),		# +0x14
    ("fCSS", "ptr", 1),				# +0x18  bpCSS
    ("fConnectRanges", "ptr", 1),	# +0x1c  numConnectRanges
    ("fConnects", "ptr", 1),		# +0x20  newtConnects
    ("fField24", "word", 2),		# +0x24
    ("fBlock", "nil", 1),			# +0x2c  made by BPNetAllocateNet
    ("fField30", "word", 2),		# +0x30
    ("fWeights", "ptr", 1),			# +0x38  bpWeight
    ("fUnits", "nil", 1),			# +0x3c  ... and these two with it
    ("fOutputs", "nil", 1),			# +0x40
    ("fCounts44", "halves", 1),		# +0x44  inputs, outputs
    ("fCounts48", "halves", 1),		# +0x48  units, computed
    ("fCounts4c", "halves", 1),		# +0x4c  hidden, -
    ("fField50", "word", 1),		# +0x50
    ("fWeightSize", "word", 1),		# +0x54
    ("fField58", "word", 5),		# +0x58 .. +0x68
    ("fParamCount", "word", 1),		# +0x6c
    ("fParams", "ptr", 1),			# +0x70  bpParam
    ("fArParams", "ptr", 1),		# +0x74  arBPParam
    ("fField78", "word", 1),		# +0x78
    ("fField7c", "bytes", 1),		# +0x7c  (+0x7d is cleared by an evaluate)
    ("fLearning", "bytes", 1),		# +0x80
]

ELEM = {"ULong": (4, ">I", "0x%08x", 6), "UByte": (1, "B", "0x%02x", 12)}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build_dir")
    ap.add_argument("-o", "--output", required=True)
    args = ap.parse_args(argv)

    with open(os.path.join(args.build_dir, "rom.bin"), "rb") as f:
        rom = f.read()
    with open(os.path.join(args.build_dir, "symbols.json"), encoding="utf-8") as f:
        data = json.load(f)
    by_name, addresses = {}, []
    for s in data["symbols"]:
        if "jt_index" not in s:
            by_name.setdefault(s["name"], s["address"])
            addresses.append(s["address"])
    addresses = sorted(set(addresses))

    def next_after(addr):
        import bisect
        i = bisect.bisect_right(addresses, addr)
        return addresses[i] if i < len(addresses) else len(rom)

    for name, _, _ in TABLES + EXTRA + [("bpNet", None, None)]:
        if name not in by_name:
            print(f"error: no symbol {name} in {args.build_dir}", file=sys.stderr)
            return 1
    by_addr = {by_name[n]: n for n, _, _ in TABLES}

    out = ["// Generated by tools/newton-rom/analysis/bpnet.py; do not edit.",
           f"//   build/venv/Scripts/python tools/newton-rom/analysis/bpnet.py {args.build_dir.replace(os.sep, '/')} -o {args.output.replace(os.sep, '/')}",
           "// The handwriting engine's classifier net and its trained tables, read",
           f"// from the {romid.rom_version(args.build_dir)} ROM at the addresses cited.",
           "",
           '#include "BPNet.h"',
           ""]

    for name, kind, count in TABLES + EXTRA:
        addr = by_name[name]
        size, fmt, form, per = ELEM[kind]
        if count is None:
            count = (next_after(addr) - addr) // size
        values = [struct.unpack(fmt, rom[addr + i * size: addr + (i + 1) * size])[0] for i in range(count)]
        out.append(f"// ROM 0x{addr:08x} {name}")
        out.append(f"extern const {kind}\t{name}[{count}];")
        out.append(f"const {kind}\t{name}[{count}] = {{")
        for i in range(0, count, per):
            out.append("\t" + ", ".join(form % v for v in values[i:i + per]) + ",")
        out[-1] = out[-1][:-1]
        out.append("};")
        out.append("")

    addr = by_name["bpNet"]
    words = [struct.unpack(">I", rom[addr + i * 4: addr + i * 4 + 4])[0] for i in range(0x84 // 4)]
    out.append(f"// ROM 0x{addr:08x} bpNet")
    out.append("// The template `BPNetCreateNumOut` copies into a block of its own.")
    out.append("const BPNet\tbpNet = {")
    at = 0
    for name, kind, count in FIELDS:
        values = words[at:at + count]
        at += count
        if kind == "ptr":
            if values[0] not in by_addr:
                print(f"error: {name} points at 0x{values[0]:08x}, not one of the tables", file=sys.stderr)
                return 1
            out.append(f"\t{by_addr[values[0]]},\t// {name}")
        elif kind == "nil":
            if values[0] != 0:
                print(f"error: {name} is not nought in the template", file=sys.stderr)
                return 1
            out.append(f"\tnil,\t// {name}")
        elif kind == "halves":
            out.append("\t%d, %d,\t// %s" % (values[0] >> 16, values[0] & 0xffff, name))
        elif kind == "bytes":
            out.append("\t%s,\t// %s" % (", ".join("0x%02x" % ((values[0] >> s) & 0xff)
                                                  for s in (24, 16, 8, 0)), name))
        elif count == 1:
            out.append(f"\t0x{values[0]:08x},\t// {name}")
        else:
            out.append("\t{ %s },\t// %s" % (", ".join("0x%08x" % v for v in values), name))
    out[-1] = out[-1].replace(",\t//", "\t//", 1)
    out.append("};")
    out.append("")

    if at != len(words):
        print(f"error: FIELDS covers {at} words, the template is {len(words)}", file=sys.stderr)
        return 1

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {args.output}: {len(TABLES) + len(EXTRA)} tables and the template")
    return 0


if __name__ == "__main__":
    sys.exit(main())
