#!/usr/bin/env python3
"""Generate the exception name definitions (src/os600/user/ExceptionNames.cpp)
from the ROM.

Usage:
    python exception_names.py <build_dir> -o src/os600/user/ExceptionNames.cpp

The ROM's `ex*` / `ev*` symbols (0x00346454-) are words holding the address
of each exception's name string ("evt.ex.msg", ...), as DefineException lays
them out; NewtonExceptions.h only declares them.  Every symbol whose name
starts with `ex` or `ev`, lies in that table and points at a printable
string is emitted as `const ExceptionName name = "string";`.
"""

from __future__ import annotations

import argparse
import json
import os
import struct
import sys


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build_dir")
    ap.add_argument("-o", "--output", required=True)
    args = ap.parse_args(argv)
    with open(os.path.join(args.build_dir, "symbols.json"), encoding="utf-8") as f:
        data = json.load(f)
    items = data["symbols"] if isinstance(data, dict) and "symbols" in data else data
    with open(os.path.join(args.build_dir, "rom.bin"), "rb") as f:
        rom = f.read()

    def cstring(addr):
        end = rom.index(b"\0", addr)
        s = rom[addr:end]
        if not s or any(c < 32 or c > 126 for c in s):
            return None
        return s.decode("ascii")

    rows = []
    for s in sorted(items, key=lambda s: s["address"]):
        name = s["name"]
        if not (name.startswith("ex") or name.startswith("ev")) or "__" in name or len(name) < 3 or not name[2].isupper():
            continue
        addr = s["address"]
        if addr + 4 > len(rom):
            continue
        target = struct.unpack(">I", rom[addr:addr + 4])[0]
        if target >= len(rom):
            continue
        text = cstring(target)
        if text is None or not text.startswith("evt."):
            continue
        rows.append((addr, name, text))

    lines = [
        "/*",
        "\tFile:\t\tuser/ExceptionNames.cpp",
        "",
        "\tContains:\tThe exception names the ROM defines (DefineException): each is",
        "\t\t\t\ta dotted path, and Subexception matches on prefixes, so",
        "\t\t\t\t\"evt.ex.msg\" is an exRootException (\"evt.ex\").",
        "",
        "\tGenerated by tools/newton-rom/analysis/exception_names.py from the ROM",
        "\timage; do not edit by hand.",
        "*/",
        "",
        '#include "Newton.h"',
        '#include "NewtonExceptions.h"',
        "",
    ]
    # a namespace-scope const is internal unless declared extern; the header
    # declares the common ones, this covers the rest
    for addr, name, text in rows:
        lines.append(f"extern const ExceptionName {name};")
    lines.append("")
    for addr, name, text in rows:
        lines.append(f"const ExceptionName\t{name} = (ExceptionName) \"{text}\";\t// ROM 0x{addr:08x} {name}")
    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{len(rows)} exception names")
    return 0


if __name__ == "__main__":
    sys.exit(main())
