#!/usr/bin/env python3
"""Dump the memory object tables MemObjManager reads: the environment table
(gEnvTable, initialised RAM), the data-area table (DataAreaTable, ROM) and
the two domain tables (g1MegDomainTable / g4MegDomainTable, ROM; InitCGlobals
points gDomainTable at one of them by RAM size).

Usage:
    python memobj_tables.py <build_dir> [-o docs/os600/memobj-tables.md] [--cpp src/os600/kernel/MemObjTables.cpp]

Each entry is six words; names are four-character codes.  Produced from
rom.bin + layout.json + symbols.json, so it can be regenerated after a
re-import; the header of the output says so.
"""

from __future__ import annotations

import argparse
import json
import os
import struct
import sys


def fourcc(v: int) -> str:
    b = v.to_bytes(4, "big")
    return "'" + "".join(chr(c) if 32 <= c < 127 else "?" for c in b) + "'"


class Image:
    def __init__(self, build_dir):
        with open(os.path.join(build_dir, "layout.json"), encoding="utf-8") as f:
            self.layout = json.load(f)
        with open(os.path.join(build_dir, "symbols.json"), encoding="utf-8") as f:
            data = json.load(f)
        items = data["symbols"] if isinstance(data, dict) and "symbols" in data else data
        self.symbols = {s["name"]: s["address"] for s in items}
        with open(os.path.join(build_dir, "rom.bin"), "rb") as f:
            self.rom = f.read()
        rw = next(r for r in self.layout["regions"] if r["name"] == "ROM_RWINIT")
        hdr = self.layout["aif_header"]
        self.data_base = hdr["data_base"]
        self.rw_size = hdr["rw_area_size"]
        self.zi_size = hdr["zero_init_area_size"]
        self.rw_offset = rw["rom_offset"]

    def word(self, addr: int) -> int:
        if addr < len(self.rom) and addr < self.data_base:
            return struct.unpack(">I", self.rom[addr:addr + 4])[0]
        off = addr - self.data_base
        if 0 <= off < self.rw_size:
            return struct.unpack(">I", self.rom[self.rw_offset + off:self.rw_offset + off + 4])[0]
        if self.rw_size <= off < self.rw_size + self.zi_size:
            return 0
        raise ValueError(f"address 0x{addr:08x} not in ROM or initialised data")

    def words(self, addr: int, n: int):
        return [self.word(addr + 4 * i) for i in range(n)]

    def name_list(self, addr: int):
        names = []
        while addr and (v := self.word(addr)) != 0:
            names.append(fourcc(v))
            addr += 4
        return names


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build_dir")
    ap.add_argument("-o", "--output", help="write Markdown here instead of stdout")
    ap.add_argument("--cpp", help="also write the tables as C++ (src/os600/kernel/MemObjTables.cpp)")
    args = ap.parse_args(argv)
    img = Image(args.build_dir)
    out = []
    out.append("# Memory object tables (MP2100 D)\n")
    out.append("Generated by `tools/newton-rom/analysis/memobj_tables.py` from the ROM; do not edit by hand.\n")
    out.append("`MemObjManager` (0x0011ea90-0x0011fbd8) answers questions about named domains, "
               "environments and heaps from these tables; see docs/os600/README.md.\n")

    env = img.symbols["gEnvTable"]
    out.append(f"## Environments (`gEnvTable`, 0x{env:08x}, initialised RAM)\n")
    out.append("| name | default heap | heap domain | stack domain | client domains | manager domains |")
    out.append("|---|---|---|---|---|---|")
    addr = env
    while (w := img.words(addr, 6))[0] != 0:
        out.append(f"| {fourcc(w[0])} | {fourcc(w[1])} | {fourcc(w[2])} | {fourcc(w[3])} | "
                   f"{', '.join(img.name_list(w[4])) or '-'} | {', '.join(img.name_list(w[5])) or '-'} |")
        addr += 24

    dat = img.symbols["DataAreaTable"]
    out.append(f"\n## Data areas (`DataAreaTable`, ROM 0x{dat:08x})\n")
    out.append("Each domain's globals: where the initialised data lives in ROM, where it goes in RAM, and its sizes (DomainInfo::InitGlobalInfo).\n")
    out.append("| name | ROM base | RAM base | word 3 | init size | zero size |")
    out.append("|---|---|---|---|---|---|")
    addr = dat
    while (w := img.words(addr, 6))[0] != 0:
        out.append(f"| {fourcc(w[0])} | 0x{w[1]:08x} | 0x{w[2]:08x} | 0x{w[3]:08x} | 0x{w[4]:x} | 0x{w[5]:x} |")
        addr += 24

    for sym, note in (("g1MegDomainTable", "RAM of 1 MB or less"), ("g4MegDomainTable", "more RAM")):
        dom = img.symbols[sym]
        out.append(f"\n## Domains (`{sym}`, 0x{dom:08x} in the initialised data: {note})\n")
        out.append("`gDomainTable` points at one of these, chosen by InitCGlobals (0x00046000) from TRAMTable::GetRamSize.  "
                   "Heap flags: 1 persistent, 2 read-only, 4 cacheable, 8 exception on no memory, 0x10 make heap domain, 0x20 hunk-o-memory (DomainInfo).\n")
        out.append("| name | base | size | heap size | handle heap size | heap flags |")
        out.append("|---|---|---|---|---|---|")
        addr = dom
        while (w := img.words(addr, 6))[0] != 0:
            out.append(f"| {fourcc(w[0])} | 0x{w[1]:08x} | 0x{w[2]:x} | 0x{w[3]:x} | 0x{w[4]:x} | 0x{w[5]:x} |")
            addr += 24

    text = "\n".join(out) + "\n"
    if args.output:
        with open(args.output, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    else:
        sys.stdout.write(text)
    if args.cpp:
        with open(args.cpp, "w", encoding="utf-8", newline="\n") as f:
            f.write(cpp_tables(img))
    return 0


def cpp_tables(img: Image) -> str:
    """The same tables as C++ initialisers for src/os600/kernel/MemObjTables.cpp."""
    def cc(v):
        return fourcc(v)

    lines = [
        "/*",
        "\tFile:\t\tMemObjTables.cpp",
        "",
        "\tContains:\tThe memory object tables of the MP2100 D ROM - the domains (two",
        "\t\t\t\tvariants, by RAM size), the environments with their domain lists,",
        "\t\t\t\tand the data areas - as MemObjManager reads them.",
        "",
        "\tGenerated by tools/newton-rom/analysis/memobj_tables.py --cpp from the ROM",
        "\timage; do not edit by hand.  docs/os600/memobj-tables.md is the same data.",
        "*/",
        "",
        '#include "MemObjManager.h"',
        "",
    ]
    for sym, cname in (("g1MegDomainTable", "g1MegDomainTable"), ("g4MegDomainTable", "g4MegDomainTable")):
        addr = img.symbols[sym]
        lines.append(f"// ROM 0x{addr:08x} {sym}")
        lines.append(f"const DomainTableEntry\t{cname}[] =")
        lines.append("{")
        a = addr
        while (w := img.words(a, 6))[0] != 0:
            lines.append(f"\t{{ {cc(w[0])}, 0x{w[1]:08X}, 0x{w[2]:08X}, 0x{w[3]:X}, 0x{w[4]:X}, 0x{w[5]:X} }},")
            a += 24
        lines.append("\t{ 0, 0, 0, 0, 0, 0 }")
        lines.append("};")
        lines.append("")

    env = img.symbols["gEnvTable"]
    lists = {}
    a = env
    rows = []
    while (w := img.words(a, 6))[0] != 0:
        rows.append(w)
        for ptr in (w[4], w[5]):
            if ptr and ptr not in lists:
                lists[ptr] = img.name_list(ptr)
        a += 24
    for ptr, names in lists.items():
        lines.append(f"// 0x{ptr:08x}")
        lines.append(f"static const ULong\tkDomainList_{ptr:08x}[] = {{ {', '.join(names)}, 0 }};")
    lines.append("")
    lines.append(f"// ROM 0x{env:08x} gEnvTable")
    lines.append("const EnvTableEntry\tgEnvTable[] =")
    lines.append("{")
    for w in rows:
        c = f"kDomainList_{w[4]:08x}" if w[4] else "nil"
        m = f"kDomainList_{w[5]:08x}" if w[5] else "nil"
        lines.append(f"\t{{ {cc(w[0])}, {cc(w[1])}, {cc(w[2])}, {cc(w[3])}, {c}, {m} }},")
    lines.append("\t{ 0, 0, 0, 0, nil, nil }")
    lines.append("};")
    lines.append("")

    dat = img.symbols["DataAreaTable"]
    lines.append(f"// ROM 0x{dat:08x} DataAreaTable")
    lines.append("const DataAreaEntry\tDataAreaTable[] =")
    lines.append("{")
    a = dat
    while (w := img.words(a, 6))[0] != 0:
        lines.append(f"\t{{ {cc(w[0])}, 0x{w[1]:08X}, 0x{w[2]:08X}, 0x{w[3]:08X}, 0x{w[4]:X}, 0x{w[5]:X} }},")
        a += 24
    lines.append("\t{ 0, 0, 0, 0, 0, 0 }")
    lines.append("};")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    sys.exit(main())
