#!/usr/bin/env python3
"""Emit the modem tool's command and result strings and its result table.

Purpose
    The ROM's modem tool (TClassOneModem, src/comms/ModemTool.h) builds its
    AT commands out of C strings kept one after another in the ROM's data
    (cmdPrefix "AT", cmdHangUp "H0", kModemDialPrefStr, the identify
    strings of the modems it knows, ...) and parses the modem's answers
    with modemRspParseTable, a list of (string, length, result code)
    entries ending with a nil string.  This writes them as C++ source, each
    cited by its ROM address, so nothing is typed in by hand.

Usage
    python tools/newton-rom/analysis/modemstrings.py build/MP2x00US -o src/comms/ModemStrings.cpp
    (writes src/comms/ModemStrings.h as well)

Inputs / outputs
    The build directory's rom.bin and symbols.json.  The strings are every
    data symbol from cmdDC1 up to modemRspParseTable, each the C string at
    its address (a symbol's bytes after its terminator are padding); the
    table is read entry by entry, each string named by its symbol.  The
    header beside the output (ModemStrings.h for ModemStrings.cpp) is
    written too: the ModemResponse entry and a declaration of each.
"""

import argparse
import json
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import romid  # noqa: E402

FIRST = "cmdDC1"
TABLE = "modemRspParseTable"


def c_literal(raw: bytes) -> str:
    out = []
    for b in raw:
        c = chr(b)
        if c == "\\":
            out.append("\\\\")
        elif c == '"':
            out.append('\\"')
        elif c == "\r":
            out.append("\\r")
        elif c == "\n":
            out.append("\\n")
        elif 0x20 <= b < 0x7f:
            out.append(c)
        else:
            out.append("\\x%02x\"\"" % b)
    return '"' + "".join(out) + '"'


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("build_dir")
    ap.add_argument("-o", "--output", required=True)
    args = ap.parse_args()
    with open(os.path.join(args.build_dir, "rom.bin"), "rb") as f:
        rom = f.read()
    with open(os.path.join(args.build_dir, "symbols.json"), encoding="utf-8") as f:
        symbols = [s for s in json.load(f)["symbols"] if "jt_index" not in s]
    by_name = {s["name"]: s["address"] for s in symbols}
    by_address = {s["address"]: s["name"] for s in symbols}
    first, table = by_name[FIRST], by_name[TABLE]
    strings = sorted((a, n) for a, n in by_address.items() if first <= a < table)

    out = ["// Generated by tools/newton-rom/analysis/modemstrings.py; do not edit.",
           "//   python tools/newton-rom/analysis/modemstrings.py <build_dir> -o " + args.output.replace(os.sep, "/"),
           "// The modem tool's strings and result table, read from the %s ROM at the" % romid.rom_version(args.build_dir),
           "// addresses cited.", "",
           '#include "ModemStrings.h"', ""]
    for address, name in strings:
        raw = rom[address:rom.index(b"\0", address)]
        out.append("// ROM 0x%08x %s" % (address, name))
        out.append("const char\t%s[] = %s;" % (name, c_literal(raw)))
    out.append("")
    out.append("// ROM 0x%08x %s" % (table, TABLE))
    out.append("const ModemResponse\t%s[] = {" % TABLE)
    address = table
    while True:
        string, length, result = struct.unpack(">IIi", rom[address:address + 12])
        if string == 0:
            out.append("\t{ 0, 0, 0 }")
            break
        out.append("\t{ %s, %d, %d }," % (by_address[string], length >> 16, result))
        address += 12
    out.append("};")
    out.append("")
    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    header = os.path.splitext(args.output)[0] + ".h"
    guard = "__COMMS_" + os.path.basename(header).upper().replace(".", "_")
    h = ["// Generated by tools/newton-rom/analysis/modemstrings.py; do not edit.",
         "// The modem tool's strings (%s)." % os.path.basename(args.output), "",
         "#ifndef " + guard, "#define " + guard, "",
         "// an entry of modemRspParseTable: a result the modem answers, its",
         "// length, and the result code it is parsed as",
         "struct ModemResponse", "{",
         "\tconst char*\tfString;", "\tshort\t\tfLength;", "\tlong\t\tfResult;", "};", ""]
    for address, name in strings:
        h.append("extern const char\t%s[];" % name)
    h += ["", "extern const ModemResponse\t%s[];" % TABLE, "", "#endif\t/* %s */" % guard, ""]
    with open(header, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(h))
    print("%d strings and %s -> %s" % (len(strings), TABLE, args.output))
    return 0


if __name__ == "__main__":
    sys.exit(main())
