#!/usr/bin/env python3
"""Report which of the ROM's native functions the reconstruction answers.

Usage:
    python natives.py [--src src] [--unbound] [--bound] [--area <name>]
                      [--ready] [--check] [--csv <file>]

A ROM function object holds the address of a C function; on the host that
address is looked up in a registry of host implementations bound by the
symbol the function had in the ROM (`frames/NativeFunctions.h`).  So a
native is *answered* when some `RegisterNativeFunction("FFoo", ...)` call
names its symbol - and calling one that nothing names throws
`kNSErrNativeNotReconstructed`, which is how a boot reports a hole.

This compares the two sides:

  * the ROM's own tables, `src/frames/ROMNatives.cpp` - generated by
    `nsfunctions.py --natives`, one row per native built-in
    (`gROMNativeEntries`) and one per native method of a prototype frame
    (`gROMMethodEntries`);
  * every `RegisterNativeFunction("...")` in src/ (including through the
    `NATIVE(...)` macro the frames library uses).

It reports how many of each table are answered, lists what is not, and
groups the unanswered ones by the src/ area their machinery would belong
to - which is the useful thing, because a native whose area is already
reconstructed is usually a thin wrapper and a native from an area that is
NOT YET is a project of its own.  The grouping is a guess from the name
and is documentation, not a fact about the ROM.

`--sizes <build dir>` adds the size of each native's ROM function, taken
from symbols.json as the distance to the next code symbol, and sorts the
listing by it.  A native of a few dozen bytes is almost always a thin
wrapper over machinery that may already be there; a native of several
kilobytes is a piece of work in its own right.  That is the quickest way
to pick the next ones worth doing.

`--ready` narrows the unanswered ones to those whose ROM function is
*already reconstructed* - its address carries a `// ROM 0x...` citation
somewhere in src/ - so all that is missing is the registration.  Those are
the cheap ones.

`--check` exits 1 when a RegisterNativeFunction call names a symbol that no
row of either table carries, which is otherwise silent: the registry simply
matches nothing, and the registration has no effect.  That is either a typo
or - as it happens for a handful of them - a ROM function that this ROM
holds no function object for, so no script can reach it whatever we bind.

Reproducible from a clean checkout; reads only the repository.
"""

from __future__ import annotations

import argparse
import csv
import os
import re
import sys
from collections import OrderedDict


ROW = re.compile(
    r'\{\s*"((?:[^"\\]|\\.)*)"\s*,\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\s*,'
    r'\s*(-?\d+)\s*,\s*"((?:[^"\\]|\\.)*)"\s*\}')
REGISTER = re.compile(r'RegisterNativeFunction\(\s*"((?:[^"\\]|\\.)*)"')
NATIVE_MACRO = re.compile(r'\bNATIVE\(\s*"((?:[^"\\]|\\.)*)"')
CITE = re.compile(r"//\s*ROM\s+(0x[0-9A-Fa-f]+)\s+([^\s+]\S*)(?:\s+\+0x[0-9A-Fa-f]+)?")


class Native:
    def __init__(self, name, func_ptr, target, num_args, symbol, table):
        self.name = name
        self.func_ptr = func_ptr
        self.target = target
        self.num_args = num_args
        self.symbol = symbol
        self.table = table          # "builtin" or "method"


def read_rom_natives(path):
    """The two tables of src/frames/ROMNatives.cpp, in order."""
    with open(path, encoding='utf-8', newline='') as f:
        text = f.read()
    split = text.find('gROMMethodEntries')
    if split < 0:
        raise SystemExit('%s: no gROMMethodEntries table' % path)
    natives = []
    for table, part in (('builtin', text[:split]), ('method', text[split:])):
        for name, func_ptr, target, num_args, symbol in ROW.findall(part):
            natives.append(Native(name, int(func_ptr, 16), int(target, 16),
                                  int(num_args), symbol, table))
    return natives


def read_sizes(build):
    """Each code symbol's size: the distance to the next one."""
    import json
    path = os.path.join(build, 'symbols.json')
    with open(path, encoding='utf-8') as f:
        symbols = json.load(f)
    entries = symbols['symbols'] if isinstance(symbols, dict) else symbols
    code = sorted(int(e['address']) for e in entries
                  if e.get('class') == 'code' and int(e['address']) < 0x01000000)
    sizes = {}
    for i, address in enumerate(code):
        nxt = code[i + 1] if i + 1 < len(code) else address
        sizes[address] = max(nxt - address, 0)
    return sizes


def read_citations(src):
    """Every ROM address src/ cites, so a native's target can be looked up."""
    cited = set()
    for root, dirs, files in os.walk(src):
        dirs[:] = [d for d in dirs if d not in ('.git', 'build')]
        for name in files:
            if not name.endswith(('.cpp', '.h')):
                continue
            with open(os.path.join(root, name), encoding='utf-8',
                      errors='replace', newline='') as f:
                for address, _ in CITE.findall(f.read()):
                    cited.add(int(address, 16))
    return cited


def read_registered(src):
    """Every symbol some RegisterNativeFunction call names -> the files."""
    registered = {}
    for root, dirs, files in os.walk(src):
        dirs[:] = [d for d in dirs if d not in ('.git', 'build')]
        for name in files:
            if not name.endswith(('.cpp', '.h')):
                continue
            path = os.path.join(root, name)
            with open(path, encoding='utf-8', errors='replace', newline='') as f:
                text = f.read()
            for pattern in (REGISTER, NATIVE_MACRO):
                for symbol in pattern.findall(text):
                    registered.setdefault(symbol, set()).add(
                        os.path.relpath(path, src).replace('\\', '/'))
    return registered


# Where a native's machinery would live.  The first pattern that matches a
# native's symbol wins; a name that matches nothing is "?".  This is a guess
# from the name, kept here rather than in the report so it can be corrected
# in one place as areas are reconstructed.
AREAS = OrderedDict((
    ('comms', r'AppleTalk|NBP|^CI|^FConn|Endpoint|Modem|^FSerial|Online|Remote'
              r'|^Zap|Beam|IrDA|^FSetupTethered|NTK|^Fpkg|^FDES'),
    ('books', r'Book|Topic|Kiosk|^FQuickLook|Bookmark|CurrentPage|CountPages'),
    ('testing', r'^FTest|TestAgent|^FJournal|^FDebug|^FUriah|^FStdio|Sniffing'
                r'|^FInitSerialDebugging|^FPreInitSerialDebugging|^FHobbleTablet'
                r'|^FInsertTabletSample|BypassTablet'),
    ('assist', r'^DS|^IA|^Lex|Phrase|^Utter|Template|^Favor|Phone(Index|String|Sym)'
               r'|^GetRelevantTemplates|^StringToFrameMapper|^GuessAddressee'),
    ('packages', r'Package|^FPid|^FPssid|^FObjectPid|^FObjectPkgRef|Import|Export|Pkg'),
    ('stores', r'^FLB|^Store|Soup|Cursor|^FGetBinary|^FIsLargeBinary|VBO'),
    ('recognition', r'Recogni|^FWRec|Stroke|^FUnit|Gesture|Letter|Shape|Dict'
                    r'|^FAirus|Training|Correct|WordInfo|^FCleanString|InkWord'
                    r'|^FMakeInk|^FInkConvert|^FCalcInkBounds|^FExpandUnit'
                    r'|^FAddWordInfo|^FAddUnitInfo|TryString|^FMatchedChar'
                    r'|^FModalRecognition|^FRosettaExtension|^FScanNextWord'
                    # methods of the unit and correction-info protos whose
                    # names say nothing (their ROM addresses sit among the
                    # recognition system's)
                    r'|^FGetWordArray|^FGetScoreArray|^FPenPos|^FGetAlternates'
                    r'|^FExtractRange$|^FHandleUnit|^FHandleRawInk'
                    r'|^FLookupCompletions|^FVoteOnWordUnit'),
    ('views', r'^FView|View|Caret|Hilite|Clipboard|KeyCommand|Popup|^FTie'
              r'|Paragraph|^FInsert|^FSetFont|^FGetFont|^FMakeCompactFont'
              r'|^FChangeStyles|^FDrawInto|^FGetEditArray|^FGetRangeText'),
    ('qd', r'^FMakeBitmap|Bitmap|^FMakePict|^FPictToShape|^FMungeShape'
           r'|^FGetShapeInfo|^FFindShape|^FPackRGB|^FGetRed|^FGetGreen|^FGetBlue'
           r'|Font|^FStrWidth|^FDraw'),
    ('sound', r'Sound|^FSetInputGain|^FSetOutputDevice|^FGetTone|^FIsEqualTone'),
    ('intl', r'^FGetMeeting|^FRepeatInfo|Meeting|^FMeasuredNumberStr|Zone'),
    ('system', r'Gestalt|Power|^FReboot|^FUnmountCard|^FGetCardSlotStores'
               r'|^FBootSucceeded|^FClassInfo|^FNextClassInfo|^FNewByName'
               r'|^FDestroyProtocol|^FDispatchProtocol|^FIsProtocolPartInUse'),
    ('frames', r'^F[A-Z]|^[A-Z]'),
))


def area_of(symbol):
    for area, pattern in AREAS.items():
        if re.search(pattern, symbol):
            return area
    return '?'


def main(argv=None):
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.abspath(os.path.join(here, '..', '..', '..'))
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--src', default=os.path.join(repo, 'src'),
                    help='the reconstruction (default: src)')
    ap.add_argument('--unbound', action='store_true', help='list what is not answered')
    ap.add_argument('--bound', action='store_true', help='list what is')
    ap.add_argument('--area', help='only that area (see the summary for the names)')
    ap.add_argument('--sizes', metavar='BUILD',
                    help="add each native's ROM function size (from BUILD/symbols.json) "
                         'and sort by it')
    ap.add_argument('--ready', action='store_true',
                    help='with --unbound: only those whose ROM function is already '
                         'reconstructed, so only the registration is missing')
    ap.add_argument('--check', action='store_true',
                    help='exit 1 when a registration binds nothing')
    ap.add_argument('--csv', help='write every native and its state to a file')
    args = ap.parse_args(argv)

    table = os.path.join(args.src, 'frames', 'ROMNatives.cpp')
    natives = read_rom_natives(table)
    registered = read_registered(args.src)

    known = set(n.symbol for n in natives)
    unknown = sorted(s for s in registered if s not in known)

    cited = read_citations(args.src) if args.ready else set()
    sizes = read_sizes(args.sizes) if args.sizes else None

    rows = []
    for n in natives:
        rows.append((n, n.symbol in registered, area_of(n.symbol)))
    if args.ready:
        rows = [r for r in rows if r[1] or r[0].target in cited]

    if args.area:
        rows = [r for r in rows if r[2] == args.area]

    if args.csv:
        with open(args.csv, 'w', encoding='utf-8', newline='') as f:
            out = csv.writer(f)
            out.writerow(['name', 'symbol', 'table', 'args', 'funcPtr', 'target',
                          'area', 'answered'])
            for n, bound, area in rows:
                out.writerow([n.name, n.symbol, n.table, n.num_args,
                              '0x%08x' % n.func_ptr, '0x%08x' % n.target,
                              area, '1' if bound else '0'])

    if sizes is not None:
        rows.sort(key=lambda r: sizes.get(r[0].target, 1 << 30))

    if args.unbound or args.bound:
        want = args.bound
        for n, bound, area in rows:
            if bound != want:
                continue
            size = '' if sizes is None else '%6d' % sizes.get(n.target, -1)
            print('%-10s %-8s %-34s %d  %-34s %s %s'
                  % (area, n.table, n.name or '(no name)', n.num_args,
                     n.symbol, '0x%08x' % n.target, size))
        print()

    # the summary, by area
    print('%-12s %8s %8s %8s' % ('area', 'answered', 'total', 'per cent'))
    by_area = OrderedDict()
    for n, bound, area in rows:
        have, total = by_area.get(area, (0, 0))
        by_area[area] = (have + (1 if bound else 0), total + 1)
    for area in sorted(by_area, key=lambda a: -by_area[a][1]):
        have, total = by_area[area]
        print('%-12s %8d %8d %7.1f%%' % (area, have, total, 100.0 * have / total))
    have = sum(1 for _, bound, _ in rows if bound)
    print('%-12s %8d %8d %7.1f%%' % ('all', have, len(rows),
                                     100.0 * have / max(len(rows), 1)))
    builtins = [r for r in rows if r[0].table == 'builtin']
    methods = [r for r in rows if r[0].table == 'method']
    print('  built-ins %d of %d, prototype methods %d of %d'
          % (sum(1 for r in builtins if r[1]), len(builtins),
             sum(1 for r in methods if r[1]), len(methods)))

    if unknown:
        print('\nregistered but not a ROM native (%d):' % len(unknown))
        for symbol in unknown:
            print('  %-40s %s' % (symbol, ', '.join(sorted(registered[symbol]))))

    return 1 if (args.check and unknown) else 0


if __name__ == '__main__':
    sys.exit(main())
