#!/usr/bin/env python3
"""Emit the handwriting engine's renderer tables as C++.

Usage:
    python render.py <build_dir> -o <src/recognition/RenderTables.cpp>
    build/venv/Scripts/python tools/newton-rom/analysis/render.py build/MP2x00US -o src/recognition/RenderTables.cpp

The engine draws a piece of writing into a small grid to show it to the
classifier (`recognition/Render.h`).  Two kinds of table go with that:

* the **dot stencils** (`raw1`, `raw2`, `raw4`), one set per pen size.  A
  set is eight pre-shifted bitmaps of the dot, one per position within a
  byte, so that drawing a point is an OR and never a shift.

* the **anti-aliasing tables** (`rat0` .. `rat3`), one per scale.  The
  engine draws at two, four or eight times the size into a one-bit bitmap
  and then counts the set sub-pixels; the table answers, for each of the
  256 byte values, how much each output cell of that byte gains.  A set
  sub-pixel is worth 15, so a four-by-four block comes to 240.

Both are tables of pointers in the ROM, so they are written out as nested
C arrays: a host pointer is eight bytes and the ROM's four would not have
indexed.

The output should not be edited by hand: regenerate it after a re-import.
"""

from __future__ import annotations

import argparse
import json
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import romid			# the ROM names itself in what this writes


STENCILS = ["raw1", "raw2", "raw4"]
AATABLES = ["rat0", "rat1", "rat2", "rat3"]
# which stencil set a pen of each size uses; the ROM's `DotStencils` is a
# table of six, of which three are nil
DOT_SIZES = [None, "raw1", "raw2", None, "raw4", None]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build_dir")
    ap.add_argument("-o", "--output", required=True)
    args = ap.parse_args(argv)

    with open(os.path.join(args.build_dir, "rom.bin"), "rb") as f:
        rom = f.read()
    with open(os.path.join(args.build_dir, "symbols.json"), encoding="utf-8") as f:
        data = json.load(f)
    by_name = {s["name"]: s["address"] for s in data["symbols"] if "jt_index" not in s}

    for name in STENCILS + AATABLES:
        if name not in by_name:
            print(f"error: no symbol {name} in {args.build_dir}", file=sys.stderr)
            return 1

    def word(a): return struct.unpack(">I", rom[a:a + 4])[0]

    out = ["// Generated by tools/newton-rom/analysis/render.py; do not edit.",
           f"//   build/venv/Scripts/python tools/newton-rom/analysis/render.py {args.build_dir.replace(os.sep, '/')} -o {args.output.replace(os.sep, '/')}",
           "// The handwriting engine's renderer tables, read from the",
           f"// {romid.rom_version(args.build_dir)} ROM at the addresses cited.",
           "",
           '#include "Render.h"',
           ""]

    # the dot stencils: eight pre-shifted bitmaps per pen size
    for name in STENCILS:
        addr = by_name[name]
        out.append(f"// ROM 0x{addr:08x} {name}")
        for phase in range(8):
            rec = word(addr + phase * 4)
            width, rows, bits = word(rec), word(rec + 4), word(rec + 8)
            body = ", ".join("0x%02x" % b for b in rom[bits:bits + width * rows])
            out.append(f"static const UByte\t{name}Bits{phase}[{width * rows}] = {{ {body} }};")
        out.append(f"extern const RenderStencil\t{name}[8];")
        out.append(f"const RenderStencil\t{name}[8] = {{")
        for phase in range(8):
            rec = word(addr + phase * 4)
            out.append("\t{ %d, %d, %sBits%d }%s"
                       % (word(rec), word(rec + 4), name, phase, "," if phase < 7 else ""))
        out.append("};")
        out.append("")

    # which set a pen of each size uses
    out.append("// ROM 0x0036f0d0 xDotStencils - what the global `DotStencils` points at")
    out.append(f"extern const RenderStencil* const\tkDotStencils[{len(DOT_SIZES)}];")
    out.append(f"const RenderStencil* const\tkDotStencils[{len(DOT_SIZES)}] = {{")
    out.append("\t" + ", ".join(n if n else "nil" for n in DOT_SIZES))
    out.append("};")
    out.append("")

    # the anti-aliasing tables: what each output cell of a byte gains
    for shift, name in enumerate(AATABLES):
        addr = by_name[name]
        cells = 8 >> shift
        out.append(f"// ROM 0x{addr:08x} {name}")
        out.append(f"extern const UByte\t{name}[256][{cells}];")
        out.append(f"const UByte\t{name}[256][{cells}] = {{")
        rows = []
        for b in range(256):
            entry = word(addr + 4 + b * 4)
            rows.append("{ " + ", ".join("0x%02x" % v for v in rom[entry:entry + cells]) + " }")
        per = 4 if cells <= 2 else 2
        for i in range(0, 256, per):
            out.append("\t" + ", ".join(rows[i:i + per]) + ",")
        out[-1] = out[-1][:-1]
        out.append("};")
        out.append("")

    aa = by_name.get("AAtables")
    out.append(f"// ROM 0x{aa:08x} AAtables" if aa else "// AAtables")
    out.append(f"extern const UByte* const\tkAATables[{len(AATABLES)}];")
    out.append(f"const UByte* const\tkAATables[{len(AATABLES)}] = {{")
    out.append("\t" + ", ".join("(const UByte*) %s" % n for n in AATABLES))
    out.append("};")
    out.append("")

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {args.output}: {len(STENCILS)} stencil sets and {len(AATABLES)} scales")
    return 0


if __name__ == "__main__":
    sys.exit(main())
