#!/usr/bin/env python3
"""rombugs.py - list the ROM's known bugs in the reconstruction, kept or fixed.

The reconstruction ports the ROM's behaviour bugs included, and marks each bug
it finds with a comment ("ROM BUG, kept: ...", "BUG (the ROM's): ...", "ROM
bug: ...", "leak kept").  Since 2026-10-06 each one is also fixed, behind the
switch in src/host/RomBugs.h (fixed by default, NEWTON_ROM_BUGS=1 for the
ROM's behaviour; docs/rom-bugs.md).  A fixed bug's comment says so: its
marker carries "(fixed)" - "ROM BUG (fixed): ..." - and the file calls
RomBugFixed().

Inputs:  the source tree (default src/, tests and thirdparty/ excluded).
Outputs: a list of the bug sites, kept and fixed, by area, on stdout; with
         --markdown FILE the same as a generated page (docs/rom-bugs-list.md).

    python tools/newton-rom/analysis/rombugs.py [src] [--kept] [--area A]
                                                [--markdown docs/rom-bugs-list.md]
                                                [--check]

--kept       only the bugs still kept (the work left)
--area A     only files under src/A (repeatable)
--check      exit 1 if a file marks a bug fixed but never asks RomBugFixed()
"""
import argparse
import os
import re
import sys

# a comment that introduces a bug of the ROM's
BUG = re.compile(r"\bROM\s+BUGS?\b|\bBUG\s+\(the ROM's\)|\bbug kept\b|\bBUG,\s+kept\b|\bBUG\s+\(kept\)|\bleak kept\b|\(sic:", re.I)
# a mention that points at another one rather than introducing a bug
BACKREF = re.compile(r"ROM\s+bugs?\s*(:\s*see\b|above\b|below\b)|\(the ROM bug|see the ROM bug|kept and described at|ROM\s+bugs?\s+fixed\b", re.I)
FIXED = re.compile(r"\(fixed\)", re.I)
SKIP_DIRS = {"tests", "thirdparty", "ddk", "demo"}
EXTS = (".cpp", ".h", ".c")


def scan(root, areas):
	sites = []
	for dirpath, dirnames, filenames in os.walk(root):
		dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
		rel = os.path.relpath(dirpath, root).replace(os.sep, "/")
		area = rel.split("/")[0] if rel != "." else ""
		if areas and area not in areas:
			continue
		for name in sorted(filenames):
			if not name.endswith(EXTS):
				continue
			path = os.path.join(dirpath, name)
			with open(path, encoding="utf-8", errors="replace") as f:
				lines = f.read().splitlines()
			text = "\n".join(lines)
			asks = "RomBugFixed(" in text
			for i, line in enumerate(lines):
				if not ("//" in line or line.lstrip().startswith("*") or "/*" in line):
					continue
				if not BUG.search(line) or BACKREF.search(line):
					continue
				# the description: the rest of the line, and the comment lines after it
				desc = BUG.split(line, 1)[-1].strip(" :,.*-)(")
				j = i + 1
				while len(desc) < 60 and j < len(lines) and lines[j].strip().startswith("//"):
					desc += " " + lines[j].strip().lstrip("/ ")
					j += 1
				sites.append({
					"area": area,
					"file": os.path.relpath(path, root).replace(os.sep, "/"),
					"line": i + 1,
					"fixed": bool(FIXED.search(line)),
					"asks": asks,
					"desc": re.sub(r"\s+", " ", desc)[:100],
				})
	return sites


def main():
	ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
	ap.add_argument("src", nargs="?", default=os.path.join(os.path.dirname(__file__), "..", "..", "..", "src"))
	ap.add_argument("--kept", action="store_true")
	ap.add_argument("--area", action="append", default=[])
	ap.add_argument("--markdown")
	ap.add_argument("--check", action="store_true")
	args = ap.parse_args()

	sites = scan(os.path.normpath(args.src), set(args.area))
	shown = [s for s in sites if not (args.kept and s["fixed"])]
	kept = sum(1 for s in sites if not s["fixed"])
	fixed = len(sites) - kept

	out = []
	if args.markdown:
		out += ["# ROM bugs: kept and fixed", "",
				"Generated by `tools/newton-rom/analysis/rombugs.py --markdown docs/rom-bugs-list.md`;",
				"regenerate, don't edit.  What the fixes are and how to switch them off: `docs/rom-bugs.md`.", "",
				f"{len(sites)} bug sites: {fixed} fixed, {kept} kept.", ""]
	area = None
	for s in shown:
		if s["area"] != area:
			area = s["area"]
			n = [x for x in sites if x["area"] == area]
			head = f"{area}: {sum(x['fixed'] for x in n)}/{len(n)} fixed"
			out += (["", "## " + head, ""] if args.markdown else ["", head])
		mark = "fixed" if s["fixed"] else "kept "
		if args.markdown:
			out.append(f"- {mark} `{s['file']}:{s['line']}` {s['desc']}")
		else:
			out.append(f"  {mark} {s['file']}:{s['line']}  {s['desc']}")
	if not args.markdown:
		out += ["", f"{len(sites)} bug sites: {fixed} fixed, {kept} kept"]

	text = "\n".join(out) + "\n"
	if args.markdown:
		with open(args.markdown, "w", encoding="utf-8", newline="\n") as f:
			f.write(text)
	else:
		sys.stdout.write(text)

	if args.check:
		bad = sorted({s["file"] for s in sites if s["fixed"] and not s["asks"]})
		for b in bad:
			print(f"error: {b} marks a ROM bug fixed but never asks RomBugFixed()", file=sys.stderr)
		return 1 if bad else 0
	return 0


if __name__ == "__main__":
	sys.exit(main())
