#!/usr/bin/env python3
"""Emit the ROM's frames constants as C++ source: the RSSYM symbol constants,
the R/RS object constants and the whereabouts of the ROM's object area.

Usage:
    python romconstants.py <build_dir> -o <dir>
    python romconstants.py build/MP2100D -o src/frames

The ROM's C++ refers to NewtonScript objects through Ref constants named
R<name> (1102 of them at 0x00637f2c-...) and to symbols through RSSYM<name>
(1765 at 0x0063a1a0-...).  Each is a two-word pair: the Ref, then a
RefStruct pointing back at it (its `h`, which is what the symbol names in
the RS<name>/RSSYM<name> case; the R<name> symbol names the Ref word).  A
symbol constant's Ref points at a symbol object in the ROM's object area
(a binary of class kSymbolClass: header, class, 32-bit hash, C-string
name); the mangled debug names (`_2A` for '*') are not used - the real
names are read from the objects and their hashes checked against
SymbolHashFunction.  An object constant's Ref is a pointer into the object
area or a magic pointer.

The ROM's object area ("ROM soup") is gROMSoupData, gROMSoupDataSize bytes
of consecutive objects; gROMMagicPointerTable is the count and entries of
magic pointer table 0; the ROM symbol table is the array InitSymbols
(0x0032d97c) names and the built-in functions frame the object
ResolveMagicPtr (0x002f87d0) resolves magic pointer 1.2 to - both are
checked to be what they should be.

The script writes four files:

* RSSymbols.h / RSSymbolTable.cpp - `extern Ref RSSYM<name>;` for each,
  and gRSSymbolEntries[]: name, hash, the ROM ref and the Ref to fill,
  which InitROMSymbols (Symbols.cpp) interns into the host's read-only
  symbol space, or the ROM object importer translates;
* ROMConstants.h / ROMConstants.cpp - `extern Ref R<name>;` for each,
  gROMConstantEntries[]: name, the ROM ref and the Ref to fill (the
  importer translates them), and the kROM... layout constants.

The files name this script, so they can be regenerated after a re-import
and should not be edited by hand.
"""

from __future__ import annotations

import argparse
import json
import os
import struct
import sys

SYMBOL_CLASS = 0x55552
ROM_SYMBOL_TABLE = 0x53eba1			# the literal in InitSymbols (0x0032d97c)
ROM_BUILTIN_FUNCTIONS = 0x62418d	# the literal in ResolveMagicPtr (0x002f87d0), magic pointer 1.2


def symbol_hash(name: str) -> int:
    """SymbolHashFunction (ROM 0x0032dab8): sum of upper-cased bytes times the golden ratio."""
    total = 0
    for b in name.encode("latin-1"):
        total += ord(chr(b).upper()) if b < 128 else b
    return (total * 0x9E3779B9) & 0xFFFFFFFF


def c_string(s: str) -> str:
    out = []
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 32 <= o < 127:
            out.append(ch)
        else:
            out.append("\\%03o" % o)
    return '"' + "".join(out) + '"'


HEADER = [
    "// Generated by tools/newton-rom/analysis/romconstants.py; do not edit.",
    "//   python tools/newton-rom/analysis/romconstants.py <build_dir> -o src/frames",
]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build_dir")
    ap.add_argument("-o", "--output-dir", required=True)
    args = ap.parse_args(argv)

    with open(os.path.join(args.build_dir, "rom.bin"), "rb") as f:
        rom = f.read()
    with open(os.path.join(args.build_dir, "symbols.json"), encoding="utf-8") as f:
        data = json.load(f)

    def word(addr: int) -> int:
        return struct.unpack(">I", rom[addr:addr + 4])[0]

    by_name = {}
    for s in data["symbols"]:
        if "jt_index" not in s:
            by_name.setdefault(s["name"], s["address"])

    # the object area
    soup = by_name["gROMSoupData"]
    soup_size = word(by_name["gROMSoupDataSize"])
    mp_table = by_name["gROMMagicPointerTable"]
    a = soup
    count = 0
    while a < soup + soup_size:
        h = word(a)
        size = h >> 8
        if size < 8:
            print(f"error: bad object header {h:#x} at {a:#x}", file=sys.stderr)
            return 1
        a += (size + 3) & ~3
        count += 1
    if a != soup + soup_size:
        print(f"error: the object area does not end at gROMSoupData + gROMSoupDataSize ({a:#x})", file=sys.stderr)
        return 1
    st = ROM_SYMBOL_TABLE - 1
    st_slots = ((word(st) >> 8) - 12) // 4
    if (word(st) & 3) != 1 or st_slots != 32768:
        print(f"error: the object at {ROM_SYMBOL_TABLE:#x} is not the symbol table", file=sys.stderr)
        return 1
    bf = ROM_BUILTIN_FUNCTIONS - 1
    if (word(bf) & 3) != 3:
        print(f"error: the object at {ROM_BUILTIN_FUNCTIONS:#x} is not a frame", file=sys.stderr)
        return 1
    mp_count = word(mp_table)

    symbols = []
    objects = []
    seen = set()
    for s in sorted(data["symbols"], key=lambda s: s["address"]):
        name = s["name"]
        addr = s["address"]
        if "jt_index" in s or name in seen or addr >= 0x0c000000:
            continue
        if name.startswith("RSSYM"):
            seen.add(name)
            ref = word(addr - 4)
            if ref & 3 != 1:
                print(f"error: {name} at {addr:#x}: ref {ref:#x} is not a pointer", file=sys.stderr)
                return 1
            obj = ref - 1
            if word(obj + 8) != SYMBOL_CLASS:
                print(f"error: {name}: object at {obj:#x} is not a symbol", file=sys.stderr)
                return 1
            size = word(obj) >> 8
            h = word(obj + 12)
            end = rom.index(b"\0", obj + 16, obj + size)
            text = rom[obj + 16:end].decode("latin-1")
            if symbol_hash(text) != h:
                print(f"error: {name} '{text}': hash {h:#x} != {symbol_hash(text):#x}", file=sys.stderr)
                return 1
            symbols.append((name, addr, text, h, ref))
        elif name.startswith("RS") and ("R" + name[2:]) in by_name and by_name["R" + name[2:]] == addr - 4:
            # RS<name> at addr, R<name> at addr - 4: an object constant
            rname = "R" + name[2:]
            seen.add(name)
            seen.add(rname)
            ref = word(addr - 4)
            if ref & 3 == 1 and not (soup <= ref - 1 < soup + soup_size):
                print(f"warning: {rname}: pointer {ref:#x} outside the object area", file=sys.stderr)
            objects.append((rname, addr - 4, ref))

    sym_h = HEADER + [
        "// The ROM's RSSYM symbol constants (RefStructs at 0x%08x-0x%08x): here" % (symbols[0][1], symbols[-1][1]),
        "// the Refs InitROMSymbols fills in from the table in RSSymbolTable.cpp,",
        "// or the ROM object importer translates.",
        "",
        "#ifndef __RSSYMBOLS_H",
        "#define __RSSYMBOLS_H",
        "",
        "#ifndef __OBJECTS_H",
        '#include "objects.h"',
        "#endif",
        "",
        "struct RSSymbolEntry",
        "{",
        "\tconst char*\t\tfName;",
        "\tunsigned int\tfHash;\t\t// SymbolHashFunction of the name, as stored in the ROM's symbol",
        "\tunsigned int\tfROMRef;\t// the Ref in the ROM: a pointer into its object area",
        "\tRef*\t\t\tfRef;",
        "};",
        "",
        "extern const RSSymbolEntry\tgRSSymbolEntries[];",
        "extern const long\t\t\tgRSSymbolCount;",
        "",
    ]
    for name, addr, text, h, ref in symbols:
        sym_h.append(f"extern Ref {name};\t\t// '{text}")
    sym_h += ["", "#endif\t/* __RSSYMBOLS_H */", ""]

    sym_cpp = HEADER + [
        "// The ROM's RSSYM symbol constants: each Ref is cited at the RefStruct's",
        "// address in the ROM, the table gives its name, hash and ROM ref.",
        "",
        '#include "RSSymbols.h"',
        "",
    ]
    for name, addr, text, h, ref in symbols:
        sym_cpp.append(f"Ref {name} = NILREF;\t// ROM 0x{addr:08x} {name}")
    sym_cpp += ["", "const RSSymbolEntry gRSSymbolEntries[] = {"]
    for name, addr, text, h, ref in symbols:
        sym_cpp.append(f"\t{{ {c_string(text)}, 0x{h:08x}, 0x{ref:08x}, &{name} }},")
    sym_cpp += ["};", "", f"const long gRSSymbolCount = {len(symbols)};", ""]

    obj_h = HEADER + [
        "// The ROM's R<name> object constants (Refs at 0x%08x-0x%08x, each with" % (objects[0][1], objects[-1][1]),
        "// its RefStruct RS<name> after it): here the Refs the ROM object importer",
        "// fills in from the table in ROMConstants.cpp - NILREF until a ROM is",
        "// imported - and where the ROM's object area and tables are.",
        "",
        "#ifndef __ROMCONSTANTS_H",
        "#define __ROMCONSTANTS_H",
        "",
        "#ifndef __OBJECTS_H",
        '#include "objects.h"',
        "#endif",
        "",
        "struct ROMConstantEntry",
        "{",
        "\tconst char*\t\tfName;",
        "\tunsigned int\tfROMRef;\t// the Ref in the ROM: a pointer into its object area, or a magic pointer",
        "\tRef*\t\t\tfRef;",
        "};",
        "",
        "extern const ROMConstantEntry\tgROMConstantEntries[];",
        "extern const long\t\t\t\tgROMConstantCount;",
        "",
        "// the ROM's object area and tables (physical ROM addresses)",
        f"const unsigned int kROMSoupBase = 0x{soup:08x};\t\t\t\t// gROMSoupData",
        f"const unsigned int kROMSoupSize = 0x{soup_size:08x};\t\t\t\t// gROMSoupDataSize: {count} objects",
        f"const unsigned int kROMMagicPointerTable = 0x{mp_table:08x};\t// gROMMagicPointerTable: the count, then {mp_count} refs",
        f"const unsigned int kROMSymbolTable = 0x{ROM_SYMBOL_TABLE:08x};\t\t// the array of {st_slots} slots InitSymbols (0x0032d97c) names",
        f"const unsigned int kROMBuiltinFunctions = 0x{ROM_BUILTIN_FUNCTIONS:08x};\t// the frame magic pointer 1.2 resolves to (ResolveMagicPtr, 0x002f87d0)",
        "",
    ]
    for name, addr, ref in objects:
        obj_h.append(f"extern Ref {name};")
    obj_h += ["", "#endif\t/* __ROMCONSTANTS_H */", ""]

    obj_cpp = HEADER + [
        "// The ROM's R<name> object constants: each Ref is cited at its address in",
        "// the ROM, the table gives its ROM value.",
        "",
        '#include "ROMConstants.h"',
        "",
    ]
    for name, addr, ref in objects:
        obj_cpp.append(f"Ref {name} = NILREF;\t// ROM 0x{addr:08x} {name}")
    obj_cpp += ["", "const ROMConstantEntry gROMConstantEntries[] = {"]
    for name, addr, ref in objects:
        obj_cpp.append(f"\t{{ \"{name[1:]}\", 0x{ref:08x}, &{name} }},")
    obj_cpp += ["};", "", f"const long gROMConstantCount = {len(objects)};", ""]

    os.makedirs(args.output_dir, exist_ok=True)
    for fname, lines in [("RSSymbols.h", sym_h), ("RSSymbolTable.cpp", sym_cpp),
                         ("ROMConstants.h", obj_h), ("ROMConstants.cpp", obj_cpp)]:
        with open(os.path.join(args.output_dir, fname), "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(lines))
    print(f"wrote {len(symbols)} symbols and {len(objects)} object constants to {args.output_dir}; "
          f"object area {soup:#x}+{soup_size:#x} ({count} objects), {mp_count} magic pointers")
    return 0


if __name__ == "__main__":
    sys.exit(main())
