#!/usr/bin/env python3
"""Emit the table of lexicons built into the ROM as C++ source.

Usage:
    python romdicts.py <build_dir> -o <dir>
    python romdicts.py build/MP2x00US -o src/recognition

The ROM's dictionaries are not one table of data: they are a table of
*pointers*, `gROMDictionaryData` (ROM 0x0c106840), which lives in RAM and is
filled in at boot by `InitROMDictionaryData` (ROM 0x0019b0d4) - a long
straight line of `ldr rN,[pc,#...]` / `str rN,[r0,#slot*4]` pairs, one per
lexicon.  `GetROMDictionaryData(id, &size)` then reads the size word the
data begins with and answers the bytes after it, which is what
`BuildDictionaryFromPtr` opens a dictionary over.

So the table cannot be read out of the ROM the way `romtable.py` reads a
constant table: it has to be recovered from the code that writes it.  This
script decodes those two instruction forms from the ROM's own bytes -
nothing else appears in the function - keeping a value per register, and
writes out the slot number, the ROM address and the debug symbol's name for
each lexicon.

The output is `ROMDictionaryTable.cpp`, which defines
`gROMDictionaryTable[]`; the reconstruction's `InitROMDictionaryData` walks
it.  Its header names this script and the command line, so it can be
regenerated after a re-import and should not be edited by hand.
"""

from __future__ import annotations

import argparse
import json
import os
import struct
import sys


sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import romid			# the ROM names itself in what this writes

INIT_FUNCTION = "InitROMDictionaryData__Fv"
TABLE_SYMBOL = "gROMDictionaryData"


def decode(rom: bytes, start: int, limit: int = 0x1000):
    """The (register -> value) writes `InitROMDictionaryData` makes.

    Answers (base, {slot: value}) where `base` is the address the stores are
    made against.  Only the two instruction forms the function is built of
    are understood; anything else but its prologue and its return stops the
    walk, so a ROM whose function is shaped differently is noticed rather
    than half-read.
    """
    regs = {}
    writes = {}
    bases = set()
    addr = start
    while addr < start + limit:
        word = struct.unpack(">I", rom[addr:addr + 4])[0]
        cond, op = word >> 28, (word >> 20) & 0xff
        if word in (0xe8bd8000, 0xe49df004) or word == 0xe1a0f00e:
            break							# ldmia sp!,{pc} / ldr pc,[sp],#4 / mov pc,lr
        if cond != 0xe:
            raise ValueError(f"0x{addr:08x}: conditional instruction in the table's writer")
        if word == 0xe92d4000:				# stmdb sp!,{lr}
            addr += 4
            continue
        rd = (word >> 12) & 0xf
        rn = (word >> 16) & 0xf
        imm = word & 0xfff
        if op == 0x59 and rn == 15:			# ldr rD,[pc,#imm]
            at = addr + 8 + imm
            regs[rd] = struct.unpack(">I", rom[at:at + 4])[0]
        elif op in (0x58, 0x5a):			# str rD,[rN,#imm] (0x5a: ... with writeback)
            if rn not in regs:
                raise ValueError(f"0x{addr:08x}: a store against a register that was never loaded")
            bases.add(regs[rn])
            writes[imm // 4] = regs.get(rd)
            if op == 0x5a:
                regs[rn] += imm
        else:
            raise ValueError(f"0x{addr:08x}: unexpected instruction 0x{word:08x}")
        addr += 4
    if len(bases) != 1:
        raise ValueError(f"the writer stores against {len(bases)} bases, expected one")
    return bases.pop(), writes


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build_dir")
    ap.add_argument("-o", "--output", required=True, help="the directory to write ROMDictionaryTable.cpp into")
    args = ap.parse_args(argv)

    rom = romid.rom_bytes(args.build_dir)
    with open(os.path.join(args.build_dir, "symbols.json"), encoding="utf-8") as f:
        symbols = json.load(f)["symbols"]
    by_name = {}
    by_address = {}
    for s in symbols:
        if "jt_index" in s:
            continue
        by_name.setdefault(s["name"], s["address"])
        by_address.setdefault(s["address"], s["name"])
    if INIT_FUNCTION not in by_name:
        print(f"error: no {INIT_FUNCTION} in {args.build_dir}", file=sys.stderr)
        return 1

    start = by_name[INIT_FUNCTION]
    base, writes = decode(rom, start)
    table = by_name.get(TABLE_SYMBOL)
    if table is not None and table != base:
        print(f"error: the writes go to 0x{base:08x}, not {TABLE_SYMBOL} at 0x{table:08x}",
              file=sys.stderr)
        return 1
    count = max(writes) + 1

    lines = ["// Generated by tools/newton-rom/analysis/romdicts.py; do not edit.",
             f"//   python tools/newton-rom/analysis/romdicts.py <build_dir> -o {args.output.replace(os.sep, '/')}",
             f"// The lexicons built into the {romid.rom_version(args.build_dir)} ROM, as",
             f"// InitROMDictionaryData (ROM 0x{start:08x}) writes their addresses into",
             f"// gROMDictionaryData (ROM 0x{base:08x}).  A slot the ROM leaves alone has no",
             "// dictionary; the name is the debug symbol on the data.",
             "",
             '#include "ROMDictionaryData.h"',
             "",
             f"// ROM 0x{base:08x} {TABLE_SYMBOL}",
             f"const ROMDictionaryEntry\tgROMDictionaryTable[kROMDictionaryCount] =",
             "{"]
    for slot in range(count):
        value = writes.get(slot)
        if value is None:
            lines.append(f"\t{{ 0, nil }},\t\t\t\t\t\t\t// {slot}")
        else:
            name = by_address.get(value, "(unnamed)")
            lines.append(f'\t{{ 0x{value:08x}, "{name}" }},'.ljust(42) + f"// {slot}")
    lines += ["};", ""]

    os.makedirs(args.output, exist_ok=True)
    path = os.path.join(args.output, "ROMDictionaryTable.cpp")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    named = sum(1 for slot in range(count) if writes.get(slot))
    print(f"{path}: {named} of {count} slots")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
