#!/usr/bin/env python3
"""Emit constant tables from the ROM as C++ source.

Usage:
    python romtable.py <build_dir> NAME[:TYPE[:COUNT]]... -o <file.cpp> [--namespace-comment TEXT]
    python romtable.py build/MP2100D O10 O9 CopyValue:u8 LZCopyBits:u8 -o src/compression/LZTables.cpp

Each NAME is a data symbol of the ROM (symbols.json; the debug table marks
most data as code, so no class check is made).  TYPE is u8, u16, u32, i8,
i16 or i32 (default u32; the ROM is big-endian).  COUNT defaults to the
number of elements between the symbol and the next symbol after it, which
is right when tables follow one another (the LZ coder's do); give it when
the table is followed by something unnamed.

The output file declares each table `extern const <type> NAME[]` and
defines it with its ROM address as the citation, so coverage.py checks the
names; its header names this script and the command line, so it can be
regenerated after a re-import and should not be edited by hand.
"""

from __future__ import annotations

import argparse
import json
import os
import struct
import sys

TYPES = {
    "u8": ("unsigned char", 1, "B"), "i8": ("signed char", 1, "b"),
    "u16": ("unsigned short", 2, ">H"), "i16": ("short", 2, ">h"),
    "u32": ("unsigned int", 4, ">I"), "i32": ("int", 4, ">i"),
}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build_dir")
    ap.add_argument("tables", nargs="+", help="NAME[:TYPE[:COUNT]]")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--include", action="append", default=[], help="a header to #include (repeatable)")
    args = ap.parse_args(argv)

    with open(os.path.join(args.build_dir, "rom.bin"), "rb") as f:
        rom = f.read()
    with open(os.path.join(args.build_dir, "symbols.json"), encoding="utf-8") as f:
        data = json.load(f)
    by_name = {}
    addresses = []
    for s in data["symbols"]:
        if "jt_index" in s:
            continue
        by_name.setdefault(s["name"], s["address"])
        addresses.append(s["address"])
    addresses = sorted(set(addresses))

    def next_symbol_after(addr: int) -> int:
        import bisect
        i = bisect.bisect_right(addresses, addr)
        return addresses[i] if i < len(addresses) else len(rom)

    out = [f"// Generated by tools/newton-rom/analysis/romtable.py; do not edit.",
           f"//   python tools/newton-rom/analysis/romtable.py <build_dir> {' '.join(args.tables)} -o {args.output.replace(os.sep, '/')}",
           "// Constant tables read from the MP2100 D ROM (big-endian words) at the",
           "// addresses cited.", ""]
    for inc in args.include:
        out.append(f'#include "{inc}"')
    if args.include:
        out.append("")
    decls = []
    defs = []
    for spec in args.tables:
        parts = spec.split(":")
        name = parts[0]
        typ = parts[1] if len(parts) > 1 and parts[1] else "u32"
        if typ not in TYPES:
            print(f"error: unknown type {typ}", file=sys.stderr)
            return 1
        ctype, size, fmt = TYPES[typ]
        if name not in by_name:
            print(f"error: no symbol {name}", file=sys.stderr)
            return 1
        addr = by_name[name]
        if len(parts) > 2:
            count = int(parts[2], 0)
        else:
            count = (next_symbol_after(addr) - addr) // size
        values = [struct.unpack(fmt, rom[addr + i * size:addr + (i + 1) * size])[0] for i in range(count)]
        decls.append(f"extern const {ctype}\t{name}[{count}];")
        width = 4 if size == 1 else (6 if size == 2 else 10)
        per_line = 16 if size == 1 else 8
        lines = []
        for i in range(0, count, per_line):
            chunk = values[i:i + per_line]
            lines.append("\t" + " ".join(f"{v:#0{width}x}," if v >= 0 else f"{v}," for v in chunk))
        defs.append(f"// ROM 0x{addr:08x} {name}\nconst {ctype}\t{name}[{count}] = {{\n" + "\n".join(lines) + "\n};\n")
    out.extend(decls)
    out.append("")
    out.append("\n".join(defs))
    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"{len(args.tables)} tables -> {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
