#!/usr/bin/env python3
"""Emit constant tables from the ROM as C++ source.

Usage:
    python romtable.py <build_dir> NAME[@ADDR][:TYPE[:COUNT]]... -o <file.cpp>
    python romtable.py build/MP2100D O10 O9 CopyValue:u8 LZCopyBits:u8 -o src/compression/LZTables.cpp
    python romtable.py build/MP2100D gPrintLiterals:cstr:35 -o src/frames/PrintLiterals.cpp
    python romtable.py build/MP2100D kResampleFilter@0x0036dbe8:i32:262 -o src/sound/ResampleTables.cpp

Each NAME is a data symbol of the ROM (symbols.json; the debug table marks
most data as code, so no class check is made).  A table the debug symbols do
not name is given its address instead, as NAME@ADDR - the name is then ours
and the citation says `(unnamed)`, which is how coverage.py expects an
unnamed thing to be cited.  TYPE is u8, u16, u32, i8,
i16 or i32 (default u32; the ROM is big-endian), strN: a table of
fixed-width N-byte strings laid out one after another in the ROM and
padded with noughts (a COUNT is required), or cstr: a table of
pointers to C strings in the ROM, emitted as `const char*` literals (a 0
pointer becomes nil).  COUNT defaults to the number of elements between
the symbol and the next symbol after it, which is right when tables follow
one another (the LZ coder's do); give it when the table is followed by
something unnamed.  A table in the initialised RAM area (a global at
0x0C100800-, such as the interpreter's opcode names gPrintLiterals) is read
from the ROM's copy of that area (layout.json's ROM_RWINIT).

The output file declares each table `extern const <type> NAME[]` and
defines it with its ROM address as the citation, so coverage.py checks the
names; its header names this script and the command line, so it can be
regenerated after a re-import and should not be edited by hand.
"""

from __future__ import annotations

import argparse
import json
import os
import struct
import sys


sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import romid			# the ROM names itself in what this writes

TYPES = {
    "u8": ("unsigned char", 1, "B"), "i8": ("signed char", 1, "b"),
    "u16": ("unsigned short", 2, ">H"), "i16": ("short", 2, ">h"),
    "u32": ("unsigned int", 4, ">I"), "i32": ("int", 4, ">i"),
    "cstr": ("char*", 4, ">I"),
}


def c_string(rom: bytes, addr: int) -> str:
    """The C string at addr, as a C++ literal."""
    end = rom.index(b"\0", addr)
    text = rom[addr:end].decode("latin-1")
    escaped = text.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "\\r").replace("\n", "\\n").replace("\t", "\\t")
    return '"' + escaped + '"'


def citation(addr: int, name: str, given_address) -> str:
    """The `// ROM ...` line above a table: its symbol, or `(unnamed)` and our
    name for it when the debug symbols do not name it."""
    if given_address is None:
        return f"// ROM 0x{addr:08x} {name}"
    return f"// ROM 0x{addr:08x} (unnamed) - {name}"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build_dir")
    ap.add_argument("tables", nargs="+", help="NAME[@ADDR][:TYPE[:COUNT]]")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--include", action="append", default=[], help="a header to #include (repeatable)")
    args = ap.parse_args(argv)

    with open(os.path.join(args.build_dir, "rom.bin"), "rb") as f:
        rom = f.read()
    with open(os.path.join(args.build_dir, "symbols.json"), encoding="utf-8") as f:
        data = json.load(f)
    with open(os.path.join(args.build_dir, "layout.json"), encoding="utf-8") as f:
        layout = json.load(f)
    # the initialised RAM area, as the ROM holds it
    rwinit = next(r for r in layout["regions"] if r["name"] == "ROM_RWINIT")
    data_base = layout["aif_header"]["data_base"]
    rw_size = layout["aif_header"]["rw_area_size"]

    def read(addr: int, size: int) -> bytes:
        if data_base <= addr < data_base + rw_size:
            off = rwinit["rom_offset"] + (addr - data_base)
            return rom[off:off + size]
        return rom[addr:addr + size]
    by_name = {}
    addresses = []
    for s in data["symbols"]:
        if "jt_index" in s:
            continue
        by_name.setdefault(s["name"], s["address"])
        addresses.append(s["address"])
    addresses = sorted(set(addresses))

    def next_symbol_after(addr: int) -> int:
        import bisect
        i = bisect.bisect_right(addresses, addr)
        return addresses[i] if i < len(addresses) else len(rom)

    out = [f"// Generated by tools/newton-rom/analysis/romtable.py; do not edit.",
           f"//   python tools/newton-rom/analysis/romtable.py <build_dir> {' '.join(args.tables)} -o {args.output.replace(os.sep, '/')}",
           f"// Constant tables read from the {romid.rom_version(args.build_dir)} ROM (big-endian words)",
           "// at the addresses cited.", ""]
    for inc in args.include:
        out.append(f'#include "{inc}"')
    if args.include:
        out.append("")
    decls = []
    defs = []
    for spec in args.tables:
        parts = spec.split(":")
        name = parts[0]
        given_address = None
        if "@" in name:
            name, _, where = name.partition("@")
            given_address = int(where, 0)
        typ = parts[1] if len(parts) > 1 and parts[1] else "u32"
        if typ.startswith("str") and typ[3:].isdigit():
            stride = int(typ[3:])
            if given_address is not None:
                addr = given_address
            elif name in by_name:
                addr = by_name[name]
            else:
                print("error: no symbol %s (give its address as %s@0x...)" % (name, name), file=sys.stderr)
                return 1
            if len(parts) <= 2:
                print("error: %s: a strN table needs a count" % name, file=sys.stderr)
                return 1
            count = int(parts[2], 0)
            decls.append("extern const char\t%s[%d][%d];" % (name, count, stride))
            lines = []
            for i in range(count):
                raw = read(addr + i * stride, stride)
                text = raw.split(b"\0")[0].decode("latin-1")
                escaped = text
                for a, b in (("\\", "\\\\"), ('"', '\\"'), ("\r", "\\r"), ("\n", "\\n"), ("\t", "\\t")):
                    escaped = escaped.replace(a, b)
                lines.append('\t"' + escaped + '",')
            defs.append("%s\nconst char\t%s[%d][%d] = {\n%s\n};\n"
                        % (citation(addr, name, given_address), name, count, stride, "\n".join(lines)))
            continue
        if typ not in TYPES:
            print(f"error: unknown type {typ}", file=sys.stderr)
            return 1
        ctype, size, fmt = TYPES[typ]
        if given_address is not None:
            addr = given_address
        elif name in by_name:
            addr = by_name[name]
        else:
            print(f"error: no symbol {name} (give its address as {name}@0x...)", file=sys.stderr)
            return 1
        if len(parts) > 2:
            count = int(parts[2], 0)
        else:
            count = (next_symbol_after(addr) - addr) // size
        values = [struct.unpack(fmt, read(addr + i * size, size))[0] for i in range(count)]
        if typ == "cstr":
            decls.append(f"extern const char* const\t{name}[{count}];")
            lines = ["\t" + (c_string(rom, v) if v != 0 else "0") + "," for v in values]
            defs.append(f"{citation(addr, name, given_address)}\nconst char* const\t{name}[{count}] = {{\n" + "\n".join(lines) + "\n};\n")
            continue
        decls.append(f"extern const {ctype}\t{name}[{count}];")
        width = 4 if size == 1 else (6 if size == 2 else 10)
        per_line = 16 if size == 1 else 8
        signed_type = typ.startswith("i")	# a signed table reads better in decimal
        signed_width = max((len(str(v)) for v in values), default=1) if signed_type else 0
        lines = []
        for i in range(0, count, per_line):
            chunk = values[i:i + per_line]
            if signed_type:
                lines.append("\t" + " ".join(f"{v:>{signed_width}}," for v in chunk))
            else:
                lines.append("\t" + " ".join(f"{v:#0{width}x}," if v >= 0 else f"{v}," for v in chunk))
        defs.append(f"{citation(addr, name, given_address)}\nconst {ctype}\t{name}[{count}] = {{\n" + "\n".join(lines) + "\n};\n")
    out.extend(decls)
    out.append("")
    out.append("\n".join(defs))
    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"{len(args.tables)} tables -> {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
