#!/usr/bin/env python3
"""Emit the ROM's RSSYM symbol constants as C++ source.

Usage:
    python rssymbols.py <build_dir> -o <dir>
    python rssymbols.py build/MP2100D -o src/frames

The ROM's C++ refers to NewtonScript symbols through RefStruct constants
named RSSYM<name> (1765 of them at 0x0063a1a0-...).  Each is a two-word
pair: the word before the symbol's address is the Ref of the symbol object
(a binary of class kSymbolClass: header, class, 32-bit hash, C-string
name) and the word at the address is a RefStruct pointing back at it (its
`h`), so RSSYM<name> is `RefStruct`.  The names in the debug symbols are
mangled (`_2A` for '*'); the real names are read from the symbol objects
themselves, and their hashes are checked against SymbolHashFunction.

The script writes two files:

* RSSymbols.h - `extern Ref RSSYM<name>;` for each, and the table type;
* RSSymbolTable.cpp - the Refs and `gRSSymbolEntries[]`, name, hash and
  the Ref to fill, which InitROMSymbols (Symbols.cpp) interns into the
  host's read-only symbol space at start-up.

The files name this script, so they can be regenerated after a re-import
and should not be edited by hand.
"""

from __future__ import annotations

import argparse
import json
import os
import struct
import sys

SYMBOL_CLASS = 0x55552


def symbol_hash(name: str) -> int:
    """SymbolHashFunction (ROM 0x0032dab8): sum of upper-cased bytes times the golden ratio."""
    total = 0
    for b in name.encode("latin-1"):
        total += ord(chr(b).upper()) if b < 128 else b
    return (total * 0x9E3779B9) & 0xFFFFFFFF


def c_string(s: str) -> str:
    out = []
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 32 <= o < 127:
            out.append(ch)
        else:
            out.append("\\%03o" % o)
    return '"' + "".join(out) + '"'


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build_dir")
    ap.add_argument("-o", "--output-dir", required=True)
    args = ap.parse_args(argv)

    with open(os.path.join(args.build_dir, "rom.bin"), "rb") as f:
        rom = f.read()
    with open(os.path.join(args.build_dir, "symbols.json"), encoding="utf-8") as f:
        data = json.load(f)

    def word(addr: int) -> int:
        return struct.unpack(">I", rom[addr:addr + 4])[0]

    entries = []
    seen = set()
    for s in sorted(data["symbols"], key=lambda s: s["address"]):
        name = s["name"]
        if "jt_index" in s or not name.startswith("RSSYM") or name in seen:
            continue
        seen.add(name)
        addr = s["address"]
        ref = word(addr - 4)
        if ref & 3 != 1:
            print(f"error: {name} at {addr:#x}: ref {ref:#x} is not a pointer", file=sys.stderr)
            return 1
        obj = ref - 1
        if word(obj + 8) != SYMBOL_CLASS:
            print(f"error: {name}: object at {obj:#x} is not a symbol", file=sys.stderr)
            return 1
        size = word(obj) >> 8
        h = word(obj + 12)
        end = rom.index(b"\0", obj + 16, obj + size)
        text = rom[obj + 16:end].decode("latin-1")
        if symbol_hash(text) != h:
            print(f"error: {name} '{text}': hash {h:#x} != {symbol_hash(text):#x}", file=sys.stderr)
            return 1
        entries.append((name, addr, text, h))

    header = [
        "// Generated by tools/newton-rom/analysis/rssymbols.py; do not edit.",
        "//   python tools/newton-rom/analysis/rssymbols.py <build_dir> -o src/frames",
        "// The ROM's RSSYM symbol constants (RefStructs at 0x%08x-0x%08x): here" % (entries[0][1], entries[-1][1]),
        "// the Refs InitROMSymbols fills in from the table in RSSymbolTable.cpp.",
        "",
        "#ifndef __RSSYMBOLS_H",
        "#define __RSSYMBOLS_H",
        "",
        "#ifndef __OBJECTS_H",
        '#include "objects.h"',
        "#endif",
        "",
        "struct RSSymbolEntry",
        "{",
        "\tconst char*\t\tfName;",
        "\tunsigned int\tfHash;\t\t// SymbolHashFunction of the name, as stored in the ROM's symbol",
        "\tRef*\t\t\tfRef;",
        "};",
        "",
        "extern const RSSymbolEntry\tgRSSymbolEntries[];",
        "extern const long\t\t\tgRSSymbolCount;",
        "",
    ]
    for name, addr, text, h in entries:
        header.append(f"extern Ref {name};\t\t// '{text}")
    header += ["", "#endif\t/* __RSSYMBOLS_H */", ""]

    source = [
        "// Generated by tools/newton-rom/analysis/rssymbols.py; do not edit.",
        "//   python tools/newton-rom/analysis/rssymbols.py <build_dir> -o src/frames",
        "// The ROM's RSSYM symbol constants: each Ref is cited at the RefStruct's",
        "// address in the ROM, the table gives its name and hash.",
        "",
        '#include "RSSymbols.h"',
        "",
    ]
    for name, addr, text, h in entries:
        source.append(f"Ref {name} = NILREF;\t// ROM 0x{addr:08x} {name}")
    source += ["", "const RSSymbolEntry gRSSymbolEntries[] = {"]
    for name, addr, text, h in entries:
        source.append(f"\t{{ {c_string(text)}, 0x{h:08x}, &{name} }},")
    source += ["};", "", f"const long gRSSymbolCount = {len(entries)};", ""]

    os.makedirs(args.output_dir, exist_ok=True)
    with open(os.path.join(args.output_dir, "RSSymbols.h"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(header))
    with open(os.path.join(args.output_dir, "RSSymbolTable.cpp"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(source))
    print(f"wrote {len(entries)} symbols to {args.output_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
