#!/usr/bin/env python3
"""The soups the ROM extension's applications keep, as the host's store needs them.

Usage:
    python soupdefs.py <build_dir> [-o src/host/FactorySoups.cpp]
    python soupdefs.py build/MP2x00US

A Newton's internal store is not empty when the ROM's boot starts: the
machine has been used, and the soups its built-in applications keep are
already there.  The boot takes that for granted - PreSetupUserConfig asks
the internal store for the Cardfile's "Names" soup and sends Query to what
it gets, without looking to see whether it got one - so a host that mounts
a store which has never been written to has to prepare it first
(src/host/HostStores.h).

What to prepare it with is in the ROM.  An application that keeps a soup
does it through the soup supervisor proto (magic pointer 429): a frame with
a `soupName` and a `soupIndices` slot, whose MakeSoup creates the soup the
first time the application is opened.  Those frames are in the packages'
frames parts, but the name and the indexes they point at are ROM objects
reached through magic pointers, which is what makes this a table of the
ROM's own data rather than a made-up one.

This walks each frames part as a run of objects - the same layout as the
ROM's own object area, refs being addresses in the image - collects every
such frame, and writes the names with the magic pointer of their indexes.
The parts that are not a run of objects (the help book and ListView are
streamed NSOF) are walked as far as they go and what is found is kept.
"""

from __future__ import annotations

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, ".."))

import nsfunctions as nf
import packages as pkgs
import romid

kFramesPart = 1				# the part flags' kind: a NewtonScript part


def soup_frames(rom: nf.ROM, base: int, end: int):
    """(address, soupName ref, soupIndices ref) of every soup supervisor in
    the part: a frame with both a soupName and a soupIndices slot."""
    found = []
    a = base
    while a + 12 <= end:
        header = rom.word(a)
        size = header >> 8
        if size < 12 or a + size > end:
            break
        if (header & 3) == 3:
            try:
                slots = dict(rom.frame_slots(a | 1))
            except Exception:
                slots = {}
            name = slots.get("soupName")
            indexes = slots.get("soupIndices")
            if name not in (None, 2) and indexes not in (None, 2):
                found.append((a | 1, name, indexes))
        a += (size + 3) & ~3
    return found


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build_dir")
    ap.add_argument("-o", "--output", help="write the C++ table here instead of stdout")
    args = ap.parse_args(argv)

    rom = nf.ROM(args.build_dir)
    _, packages = pkgs.rex_packages(args.build_dir)

    soups = []
    for pkg in packages:
        for part in pkg["parts"]:
            if (part["flags"] & 3) != kFramesPart:
                continue
            base = pkg["base"] + pkg["directory_size"] + part["offset"]
            for address, name, indexes in soup_frames(rom, base, base + part["size"]):
                text = rom.describe(rom.resolve_magic(name))
                if not text.startswith('"'):
                    continue					# a name that is not a plain string: not ours to make
                if (indexes & 3) != 3:
                    continue					# the indexes must be a magic pointer into the ROM
                soups.append({
                    "package": pkg["name"], "address": address,
                    "name": text[1:-1], "magic": indexes >> 2,
                    "indexes": rom.resolve_magic(indexes),
                })

    if args.output is None:
        for s in soups:
            print("%-12s %-20s indexes @%d (%#010x)  from %#010x"
                  % (s["package"], '"' + s["name"] + '"', s["magic"], s["indexes"], s["address"]))
        return 0

    out = [
        "// Generated by tools/newton-rom/analysis/soupdefs.py; do not edit.",
        "//   python tools/newton-rom/analysis/soupdefs.py <build_dir> -o %s" % args.output.replace(os.sep, "/"),
        "// The soups the %s ROM's built-in applications keep: the name each" % romid.rom_version(args.build_dir),
        "// application's soup supervisor carries and the magic pointer of the",
        "// indexes beside it.  host/HostStores.cpp makes them, because a",
        "// Newton's internal store already has them and the boot takes that",
        "// for granted (the script says why).",
        "",
        '#include "FactorySoups.h"',
        "",
        "const FactorySoup gFactorySoups[] = {",
    ]
    for s in soups:
        # not a `// ROM` citation: the supervisor is in the package's frames
        # part rather than in the ROM's object area, which is all coverage.py
        # knows about.  The index list it points at is a ROM object.
        out.append("\t// the %s package's soup supervisor, at %#010x in the image;"
                   % (s["package"], s["address"]))
        out.append("\t// its index list is the ROM object %#010x, magic pointer %d"
                   % (s["indexes"], s["magic"]))
        out.append('\t{ "%s", %d },' % (s["name"], s["magic"]))
    out.append("};")
    out.append("")
    out.append("const long gFactorySoupCount = %d;" % len(soups))
    out.append("")

    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print("%d soups -> %s" % (len(soups), args.output))
    return 0


if __name__ == "__main__":
    sys.exit(main())
