#!/usr/bin/env python3
"""Emit the spelling checker's character maps as C++ source.

Usage:
    python spellmaps.py <build_dir> -o <dir>
    python spellmaps.py build/MP2x00US -o src/recognition

The checker guesses what a word was meant to be by walking the dictionary
with a *map*: a list of (what is written, what it might stand for) pairs.
There are two of them, both in the initialised RAM area:

    wc_map            0x0c104490, 56 entries  - what a character may be
                      read as, and what the wildcard `?` may stand for
    substitution_map  0x0c104658, 181 entries - the letter groups that
                      are written for one another ("ph" for "f", and so on)

Each entry is two pointers: the pattern (a C string) and a list of
alternatives.  The list is an array of words which are *either* a pointer
to a C string or a small number: a number is the cost of everything that
follows it, and 9 ends the list.  That overload is the ROM's own, and it
is what this writes out - a run of items each of which is a string or a
number.

The tables are pointers into the ROM, so `romtable.py` cannot emit them:
the strings have to be followed and written out.  Their header names this
script and the command line, so they can be regenerated after a re-import
and should not be edited by hand.
"""

from __future__ import annotations

import argparse
import json
import os
import struct
import sys


sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import romid			# the ROM names itself in what this writes

MAPS = ["wc_map", "substitution_map"]
kEndOfList = 9			# the value that ends an alternatives list


class Rom:
    """The ROM's bytes, with the initialised RAM area read from the ROM's
    copy of it (both tables live there)."""

    def __init__(self, build_dir: str):
        self.rom = romid.rom_bytes(build_dir)
        with open(os.path.join(build_dir, "layout.json"), encoding="utf-8") as f:
            layout = json.load(f)
        self.rw = next(r for r in layout["regions"] if r["name"] == "ROM_RWINIT")
        self.data_base = layout["aif_header"]["data_base"]
        self.rw_size = layout["aif_header"]["rw_area_size"]

    def read(self, addr: int, size: int) -> bytes:
        if self.data_base <= addr < self.data_base + self.rw_size:
            off = self.rw["rom_offset"] + (addr - self.data_base)
            return self.rom[off:off + size]
        return self.rom[addr:addr + size]

    def word(self, addr: int) -> int:
        return struct.unpack(">I", self.read(addr, 4))[0]

    def cstring(self, addr: int) -> str:
        data = self.read(addr, 256)
        return data[:data.index(b"\0")].decode("latin-1")


def c_literal(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    out = []
    for ch in escaped:
        out.append(ch if 0x20 <= ord(ch) < 0x7f else "\\x%02x" % ord(ch))
    return '"' + "".join(out) + '"'


def read_items(rom: Rom, addr: int):
    """The alternatives list at addr, as a list of str (a spelling) and int
    (the cost of what follows, or 9 to end)."""
    items = []
    while True:
        value = rom.word(addr)
        addr += 4
        if value < 0x10:
            items.append(value)
            if value == kEndOfList:
                return items
        else:
            items.append(rom.cstring(value))
        if len(items) > 512:
            raise ValueError("an alternatives list that does not end")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("build_dir")
    ap.add_argument("-o", "--output", required=True, help="the directory to write SpellMaps.cpp into")
    args = ap.parse_args(argv)

    rom = Rom(args.build_dir)
    with open(os.path.join(args.build_dir, "symbols.json"), encoding="utf-8") as f:
        symbols = json.load(f)["symbols"]
    by_name = {}
    for s in symbols:
        if "jt_index" not in s:
            by_name.setdefault(s["name"], s["address"])

    lines = ["// Generated by tools/newton-rom/analysis/spellmaps.py; do not edit.",
             f"//   python tools/newton-rom/analysis/spellmaps.py <build_dir> -o {args.output.replace(os.sep, '/')}",
             f"// The spelling checker's character maps, out of the {romid.rom_version(args.build_dir)}",
             "// ROM.  Each entry is a pattern and the spellings it may stand for; a",
             "// number among the spellings is the cost of everything after it, and 9",
             "// ends the list.",
             "",
             '#include "Spelling.h"',
             ""]
    tables = []
    for name in MAPS:
        if name not in by_name:
            print(f"error: no symbol {name} in {args.build_dir}", file=sys.stderr)
            return 1
        base = by_name[name]
        entries = []
        addr = base
        while True:
            pattern = rom.word(addr)
            items = rom.word(addr + 4)
            addr += 8
            if pattern == 0:
                break
            entries.append((rom.cstring(pattern), read_items(rom, items)))

        # the alternatives lists first, one array each
        for index, (pattern, items) in enumerate(entries):
            lines.append(f"static const SpellItem\tk{name}_{index}[] =")
            lines.append("{")
            row = []
            for item in items:
                row.append(f"{{ {c_literal(item)} }}" if isinstance(item, str)
                           else f"{{ nil, {item} }}")
            lines.append("\t" + ", ".join(row))
            lines.append("};")
        lines.append("")
        lines.append(f"// ROM 0x{base:08x} {name}")
        lines.append(f"const SpellMapEntry\tg{name}[] =")
        lines.append("{")
        for index, (pattern, items) in enumerate(entries):
            lines.append(f"\t{{ {c_literal(pattern)}, k{name}_{index} }},")
        lines.append("\t{ nil, nil }")
        lines.append("};")
        lines.append("")
        tables.append((name, len(entries)))

    os.makedirs(args.output, exist_ok=True)
    path = os.path.join(args.output, "SpellMaps.cpp")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(path + ": " + ", ".join(f"{n} {c} entries" for n, c in tables))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
