// Generated by tools/newton-rom/analysis/romtable.py; do not edit.
//   python tools/newton-rom/analysis/romtable.py <build_dir> IrBaudRateTable:u32:5 IrExtraBOFsTable:u8:8 IrMaxTurnTimeTable:u32:4 IrMinTurnTimeTable:u32:8 IrLinkDiscThreshold:u32:8 IrMinTurnInBytesTable:u8:40 IrMaxLineCapacityTable1:u32:4 IrMaxLineCapacityTable2:u32:4 IrSlotCounts:u8:4 -o src/comms/IrDATables.cpp
// Constant tables read from the 2.1 (717006) ROM (big-endian words)
// at the addresses cited.

extern const unsigned int	IrBaudRateTable[5];
extern const unsigned char	IrExtraBOFsTable[8];
extern const unsigned int	IrMaxTurnTimeTable[4];
extern const unsigned int	IrMinTurnTimeTable[8];
extern const unsigned int	IrLinkDiscThreshold[8];
extern const unsigned char	IrMinTurnInBytesTable[40];
extern const unsigned int	IrMaxLineCapacityTable1[4];
extern const unsigned int	IrMaxLineCapacityTable2[4];
extern const unsigned char	IrSlotCounts[4];

// ROM 0x0037178c IrBaudRateTable
const unsigned int	IrBaudRateTable[5] = {
	0x00002580, 0x00004b00, 0x00009600, 0x0000e100, 0x0001c200,
};

// ROM 0x003717a0 IrExtraBOFsTable
const unsigned char	IrExtraBOFsTable[8] = {
	0x30, 0x18, 0x0c, 0x06, 0x03, 0x02, 0x01, 0x00,
};

// ROM 0x003717a8 IrMaxTurnTimeTable
const unsigned int	IrMaxTurnTimeTable[4] = {
	0x001c1f38, 0x000e0f9c, 0x00059fd8, 0x0002cfec,
};

// ROM 0x003717b8 IrMinTurnTimeTable
const unsigned int	IrMinTurnTimeTable[8] = {
	0x00008ffc, 0x000047fe, 0x00000e66, 0x000007d0, 0x00000190, 0x000000c8, 0x00000028, 0x00000000,
};

// ROM 0x003717d8 IrLinkDiscThreshold
const unsigned int	IrLinkDiscThreshold[8] = {
	0x00a8c000, 0x01c20000, 0x02a30000, 0x03840000, 0x04650000, 0x057e4000, 0x06978000, 0x08ca0000,
};

// ROM 0x003717f8 IrMinTurnInBytesTable
const unsigned char	IrMinTurnInBytesTable[40] = {
	0x0a, 0x05, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, 0x0a, 0x02, 0x01, 0x00, 0x00, 0x00, 0x00,
	0x28, 0x14, 0x04, 0x02, 0x00, 0x00, 0x00, 0x00, 0x3a, 0x1d, 0x06, 0x03, 0x01, 0x00, 0x00, 0x00,
	0x73, 0x3a, 0x0c, 0x06, 0x01, 0x01, 0x00, 0x00,
};

// ROM 0x00371820 IrMaxLineCapacityTable1
const unsigned int	IrMaxLineCapacityTable1[4] = {
	0x00000190, 0x00000320, 0x00000640, 0x00000938,
};

// ROM 0x00371830 IrMaxLineCapacityTable2
const unsigned int	IrMaxLineCapacityTable2[4] = {
	0x000012c0, 0x00000960, 0x000003c0, 0x000001e0,
};

// ROM 0x00371840 IrSlotCounts
const unsigned char	IrSlotCounts[4] = {
	0x01, 0x06, 0x08, 0x10,
};
