// Generated by tools/newton-rom/analysis/modemstrings.py; do not edit.
//   python tools/newton-rom/analysis/modemstrings.py <build_dir> -o src/comms/ModemStrings.cpp
// The modem tool's strings and result table, read from the 2.1 (717006) ROM at the
// addresses cited.

#include "ModemStrings.h"

// ROM 0x0036f974 cmdDC1
const char	cmdDC1[] = "\x11""";
// ROM 0x0036f978 cmdDC2
const char	cmdDC2[] = "\x12""";
// ROM 0x0036f97c cmdPrefix
const char	cmdPrefix[] = "AT";
// ROM 0x0036f980 cmdSuffix
const char	cmdSuffix[] = "\r";
// ROM 0x0036f984 cmdEscape2CmdMode
const char	cmdEscape2CmdMode[] = "+++";
// ROM 0x0036f988 cmdSRegister
const char	cmdSRegister[] = "S";
// ROM 0x0036f98c cmdReport
const char	cmdReport[] = "?";
// ROM 0x0036f990 cmdEqual
const char	cmdEqual[] = "=";
// ROM 0x0036f994 cmdRecallFactorySettings
const char	cmdRecallFactorySettings[] = "&FE0V1";
// ROM 0x0036f99c cmdIdentify
const char	cmdIdentify[] = "I0";
// ROM 0x0036f9a0 cmdIdentify3
const char	cmdIdentify3[] = "I3";
// ROM 0x0036f9a4 cmdIdentify4
const char	cmdIdentify4[] = "I4";
// ROM 0x0036f9a8 cmdIdentify5
const char	cmdIdentify5[] = "I5";
// ROM 0x0036f9ac cmdSpeakerOn
const char	cmdSpeakerOn[] = "M1";
// ROM 0x0036f9b0 cmdSpeakerOff
const char	cmdSpeakerOff[] = "M0";
// ROM 0x0036f9b4 cmdSpeakerVolume
const char	cmdSpeakerVolume[] = "L";
// ROM 0x0036f9b8 cmdOffLineEcho
const char	cmdOffLineEcho[] = "E";
// ROM 0x0036f9bc cmdSecondaryDefaults
const char	cmdSecondaryDefaults[] = "%J&P1%D0";
// ROM 0x0036f9c8 cmdDialTone
const char	cmdDialTone[] = "DT";
// ROM 0x0036f9cc cmdDialPulse
const char	cmdDialPulse[] = "DP";
// ROM 0x0036f9d0 cmdHangUp
const char	cmdHangUp[] = "H0";
// ROM 0x0036f9d4 cmdAnswer
const char	cmdAnswer[] = "A";
// ROM 0x0036f9d8 cmdOriginate
const char	cmdOriginate[] = "O0";
// ROM 0x0036f9dc cmdTAPIOffHook
const char	cmdTAPIOffHook[] = "X1H1";
// ROM 0x0036f9e4 cmdTAPIOnHook
const char	cmdTAPIOnHook[] = "H0X";
// ROM 0x0036f9e8 cmdTAPITurnOnBlindDial
const char	cmdTAPITurnOnBlindDial[] = "X1";
// ROM 0x0036f9ec dialModTone
const char	dialModTone[] = "T";
// ROM 0x0036f9f0 dialModPulse
const char	dialModPulse[] = "P";
// ROM 0x0036f9f4 dialModReverse
const char	dialModReverse[] = "R";
// ROM 0x0036f9f8 dialModWait
const char	dialModWait[] = "W";
// ROM 0x0036f9fc dialModReturn
const char	dialModReturn[] = ";";
// ROM 0x0036fa00 dialModWaitQuite
const char	dialModWaitQuite[] = "@";
// ROM 0x0036fa04 dialModPause
const char	dialModPause[] = ",";
// ROM 0x0036fa08 cmdFClass
const char	cmdFClass[] = "+FCLASS=%s";
// ROM 0x0036fa14 cmdGetFClass
const char	cmdGetFClass[] = "+FCLASS?";
// ROM 0x0036fa20 cmdC1FTS
const char	cmdC1FTS[] = "+FTS=";
// ROM 0x0036fa28 cmdC1FRS
const char	cmdC1FRS[] = "+FRS=";
// ROM 0x0036fa30 cmdC1FTM
const char	cmdC1FTM[] = "+FTM=";
// ROM 0x0036fa38 cmdC1FRM
const char	cmdC1FRM[] = "+FRM=";
// ROM 0x0036fa40 cmdC1FTH
const char	cmdC1FTH[] = "+FTH=";
// ROM 0x0036fa48 cmdC1FRH
const char	cmdC1FRH[] = "+FRH=";
// ROM 0x0036fa50 paramV21Ch2Mod
const char	paramV21Ch2Mod[] = "3";
// ROM 0x0036fa54 paramV27Ter24Mod
const char	paramV27Ter24Mod[] = "24";
// ROM 0x0036fa58 paramV27Ter48Mod
const char	paramV27Ter48Mod[] = "48";
// ROM 0x0036fa5c paramV29_72Mod
const char	paramV29_72Mod[] = "72";
// ROM 0x0036fa60 paramV17_72Mod
const char	paramV17_72Mod[] = "73";
// ROM 0x0036fa64 paramV17st_72Mod
const char	paramV17st_72Mod[] = "74";
// ROM 0x0036fa68 paramV29_96Mod
const char	paramV29_96Mod[] = "96";
// ROM 0x0036fa6c paramV17_96Mod
const char	paramV17_96Mod[] = "97";
// ROM 0x0036fa70 paramV17st_96Mod
const char	paramV17st_96Mod[] = "98";
// ROM 0x0036fa74 paramV17_12Mod
const char	paramV17_12Mod[] = "121";
// ROM 0x0036fa78 paramV17st_12Mod
const char	paramV17st_12Mod[] = "122";
// ROM 0x0036fa7c paramV17_14Mod
const char	paramV17_14Mod[] = "145";
// ROM 0x0036fa80 paramV17st_14Mod
const char	paramV17st_14Mod[] = "146";
// ROM 0x0036fa84 cmdC2FMFR_Q
const char	cmdC2FMFR_Q[] = "+FMFR?";
// ROM 0x0036fa8c cmdC2FMDL_Q
const char	cmdC2FMDL_Q[] = "+FMDL?";
// ROM 0x0036fa94 cmdC2FREV_Q
const char	cmdC2FREV_Q[] = "+FREV?";
// ROM 0x0036fa9c cmdC2FDCC_Q
const char	cmdC2FDCC_Q[] = "+FDCC=?";
// ROM 0x0036faa4 cmdC2FCR_Q
const char	cmdC2FCR_Q[] = "+FCR=?";
// ROM 0x0036faac cmdC2FLPL_Q
const char	cmdC2FLPL_Q[] = "+FLPL=?";
// ROM 0x0036fab4 cmdC2FECM_Q
const char	cmdC2FECM_Q[] = "+FECM=?";
// ROM 0x0036fabc cmdC2FCQ_Q
const char	cmdC2FCQ_Q[] = "+FCQ=?";
// ROM 0x0036fac4 cmdC2FVRFC_Q
const char	cmdC2FVRFC_Q[] = "+FVRFC=?";
// ROM 0x0036fad0 cmdC2FDFFC_Q
const char	cmdC2FDFFC_Q[] = "+FDFFC=?";
// ROM 0x0036fadc cmdC2FLNFC_Q
const char	cmdC2FLNFC_Q[] = "+FLNFC=?";
// ROM 0x0036fae8 cmdC2FWDFC_Q
const char	cmdC2FWDFC_Q[] = "+FWDFC=?";
// ROM 0x0036faf4 cmdC2FREL_Q
const char	cmdC2FREL_Q[] = "+FREL=?";
// ROM 0x0036fafc cmdC2FBOR
const char	cmdC2FBOR[] = "+FBOR=";
// ROM 0x0036fb04 cmdC2FCIG
const char	cmdC2FCIG[] = "+FCIG=\"%s\"";
// ROM 0x0036fb10 cmdC2FDCC
const char	cmdC2FDCC[] = "+FDCC=%c,%c,%c,%c,%c,%c,%c,%c";
// ROM 0x0036fb30 cmdC2FDIS
const char	cmdC2FDIS[] = "+FDIS=%c,%c,%c,%c,%c,%c,%c,%c";
// ROM 0x0036fb50 cmdC2FECM
const char	cmdC2FECM[] = "+FECM=";
// ROM 0x0036fb58 cmdC2FK
const char	cmdC2FK[] = "+FK";
// ROM 0x0036fb5c cmdC2FLID
const char	cmdC2FLID[] = "+FLID=\"%s\"";
// ROM 0x0036fb68 cmdC2FLNFC
const char	cmdC2FLNFC[] = "+FLNFC=";
// ROM 0x0036fb70 cmdC2FLPL
const char	cmdC2FLPL[] = "+FLPL=";
// ROM 0x0036fb78 cmdC2FMINSP
const char	cmdC2FMINSP[] = "+FMINSP=";
// ROM 0x0036fb84 cmdC2FPTS
const char	cmdC2FPTS[] = "+FPTS=";
// ROM 0x0036fb8c cmdC2FREL
const char	cmdC2FREL[] = "+FREL=";
// ROM 0x0036fb94 cmdC2FSPL
const char	cmdC2FSPL[] = "+FSPL=";
// ROM 0x0036fb9c cmdC2FVRFC
const char	cmdC2FVRFC[] = "+FVRFC=";
// ROM 0x0036fba4 cmdC2FWDFC
const char	cmdC2FWDFC[] = "+FWDFC=";
// ROM 0x0036fbac cmdC2FDFFC
const char	cmdC2FDFFC[] = "+FDFFC=";
// ROM 0x0036fbb4 cmdC2FAA
const char	cmdC2FAA[] = "+FAA=0";
// ROM 0x0036fbbc cmdC2FCQ
const char	cmdC2FCQ[] = "+FCQ=";
// ROM 0x0036fbc4 cmdC2FCR
const char	cmdC2FCR[] = "+FCR=";
// ROM 0x0036fbcc cmdC2FDR
const char	cmdC2FDR[] = "+FDR";
// ROM 0x0036fbd4 cmdC2FDT
const char	cmdC2FDT[] = "+FDT";
// ROM 0x0036fbdc cmdC2FET
const char	cmdC2FET[] = "+FET=";
// ROM 0x0036fbe4 cmdC20FDT
const char	cmdC20FDT[] = "+FDT";
// ROM 0x0036fbec cmdC20FDR
const char	cmdC20FDR[] = "+FDR";
// ROM 0x0036fbf4 cmdC20FKS
const char	cmdC20FKS[] = "+FKS";
// ROM 0x0036fbfc cmdC20FIP
const char	cmdC20FIP[] = "+FIP=";
// ROM 0x0036fc04 cmdC20FMI
const char	cmdC20FMI[] = "+FMI?";
// ROM 0x0036fc0c cmdC20FMM
const char	cmdC20FMM[] = "+FMM?";
// ROM 0x0036fc14 cmdC20FMR
const char	cmdC20FMR[] = "+FMR?";
// ROM 0x0036fc1c cmdC20FCC
const char	cmdC20FCC[] = "+FCC=%c,%c,%c,%c,%c,%c,%c,%c";
// ROM 0x0036fc3c cmdC20FCC_Q
const char	cmdC20FCC_Q[] = "+FCC=?";
// ROM 0x0036fc44 cmdC20FIS
const char	cmdC20FIS[] = "+FIS=%c,%c,%c,%c,%c,%c,%c,%c";
// ROM 0x0036fc64 cmdC20FCS
const char	cmdC20FCS[] = "+FCS?";
// ROM 0x0036fc6c cmdC20FLI
const char	cmdC20FLI[] = "+FLI=\"%s\"";
// ROM 0x0036fc78 cmdC20FPI
const char	cmdC20FPI[] = "+FPI=\"%s\"";
// ROM 0x0036fc84 cmdC20FLP
const char	cmdC20FLP[] = "+FLP=";
// ROM 0x0036fc8c cmdC20FLP_Q
const char	cmdC20FLP_Q[] = "+FLP?";
// ROM 0x0036fc94 cmdC20FSP
const char	cmdC20FSP[] = "+FSP=";
// ROM 0x0036fc9c cmdC20FSP_Q
const char	cmdC20FSP_Q[] = "+FSP?";
// ROM 0x0036fca4 cmdC20FNR
const char	cmdC20FNR[] = "+FNR=%c,%c,%c,%c";
// ROM 0x0036fcb8 cmdC20FIE
const char	cmdC20FIE[] = "+FIE=";
// ROM 0x0036fcc0 cmdC20FPS
const char	cmdC20FPS[] = "+FPS=";
// ROM 0x0036fcc8 cmdC20FCQ
const char	cmdC20FCQ[] = "+FCQ=%c";
// ROM 0x0036fcd0 cmdC20FCQ_2
const char	cmdC20FCQ_2[] = "+FCQ=%c,%c";
// ROM 0x0036fcdc cmdC20FCQ_Q
const char	cmdC20FCQ_Q[] = "+FCQ?";
// ROM 0x0036fce4 cmdC20FLO
const char	cmdC20FLO[] = "+FLO=";
// ROM 0x0036fcec cmdC20FPR
const char	cmdC20FPR[] = "+FPR=";
// ROM 0x0036fcf4 cmdC20FPP
const char	cmdC20FPP[] = "+FPP=";
// ROM 0x0036fcfc cmdC20FBO
const char	cmdC20FBO[] = "+FBO=";
// ROM 0x0036fd04 cmdC20FEA
const char	cmdC20FEA[] = "+FEA=";
// ROM 0x0036fd0c cmdC20FNS
const char	cmdC20FNS[] = "+FNS";
// ROM 0x0036fd14 cmdC20FCR
const char	cmdC20FCR[] = "+FCR=";
// ROM 0x0036fd1c cmdC20FCR_Q
const char	cmdC20FCR_Q[] = "+FCR?";
// ROM 0x0036fd24 cmdC20FBU
const char	cmdC20FBU[] = "+FBU=";
// ROM 0x0036fd2c cmdC20FRQ
const char	cmdC20FRQ[] = "+FRQ=%c,%c";
// ROM 0x0036fd38 cmdC20FAA
const char	cmdC20FAA[] = "+FAA=";
// ROM 0x0036fd40 cmdC20FCT
const char	cmdC20FCT[] = "+FCT=";
// ROM 0x0036fd48 cmdC20FHS
const char	cmdC20FHS[] = "+FHS?";
// ROM 0x0036fd50 cmdC20FRY
const char	cmdC20FRY[] = "+FRY=";
// ROM 0x0036fd58 cmdC20FMS
const char	cmdC20FMS[] = "+FMS=";
// ROM 0x0036fd60 cmdC20FFC
const char	cmdC20FFC[] = "+FFC=%c,%c,%c,%c";
// ROM 0x0036fd74 cmdC20FBS
const char	cmdC20FBS[] = "+FBS?";
// ROM 0x0036fd7c resultVOK
const char	resultVOK[] = "OK";
// ROM 0x0036fd80 resultVConnect
const char	resultVConnect[] = "CONNECT";
// ROM 0x0036fd88 resultVRing
const char	resultVRing[] = "RING";
// ROM 0x0036fd90 resultVNoCarrier
const char	resultVNoCarrier[] = "NO CARRIER";
// ROM 0x0036fd9c resultVError
const char	resultVError[] = "ERROR";
// ROM 0x0036fda4 resultVNoDialTone
const char	resultVNoDialTone[] = "NO DIALTONE";
// ROM 0x0036fdb0 resultVBusy
const char	resultVBusy[] = "BUSY";
// ROM 0x0036fdb8 resultVNoAnswer
const char	resultVNoAnswer[] = "NO ANSWER";
// ROM 0x0036fdc4 resultVFCError
const char	resultVFCError[] = "+FCERROR";
// ROM 0x0036fdd0 resultVDataCnct
const char	resultVDataCnct[] = "DATA";
// ROM 0x0036fdd8 resultVFaxCnct
const char	resultVFaxCnct[] = "FAX";
// ROM 0x0036fddc resultConnectN
const char	resultConnectN[] = "CONNECT ";
// ROM 0x0036fde8 resultLCS
const char	resultLCS[] = "LCS";
// ROM 0x0036fdec resultVFCIG
const char	resultVFCIG[] = "+FCIG:";
// ROM 0x0036fdf4 resultVFCFR
const char	resultVFCFR[] = "+FCFR";
// ROM 0x0036fdfc resultVFCON
const char	resultVFCON[] = "+FCON";
// ROM 0x0036fe04 resultVFCSI
const char	resultVFCSI[] = "+FCSI:";
// ROM 0x0036fe0c resultVFDCS
const char	resultVFDCS[] = "+FDCS:";
// ROM 0x0036fe14 resultVFDIS
const char	resultVFDIS[] = "+FDIS:";
// ROM 0x0036fe1c resultVFDTC
const char	resultVFDTC[] = "+FDTC:";
// ROM 0x0036fe24 resultVFET
const char	resultVFET[] = "+FET:";
// ROM 0x0036fe2c resultVFHNG
const char	resultVFHNG[] = "+FHNG:";
// ROM 0x0036fe34 resultVFHR
const char	resultVFHR[] = "+FHR:";
// ROM 0x0036fe3c resultVFHT
const char	resultVFHT[] = "+FHT:";
// ROM 0x0036fe44 resultVFNSC
const char	resultVFNSC[] = "+FNSC:";
// ROM 0x0036fe4c resultVFNSF
const char	resultVFNSF[] = "+FNSF:";
// ROM 0x0036fe54 resultVFNSS
const char	resultVFNSS[] = "+FNSS:";
// ROM 0x0036fe5c resultVFPOLL
const char	resultVFPOLL[] = "+FPOLL";
// ROM 0x0036fe64 resultVFPPR
const char	resultVFPPR[] = "+FPPR:";
// ROM 0x0036fe6c resultVFPTS
const char	resultVFPTS[] = "+FPTS:";
// ROM 0x0036fe74 resultVFRBC
const char	resultVFRBC[] = "+FRBC:";
// ROM 0x0036fe7c resultVFTSI
const char	resultVFTSI[] = "+FTSI:";
// ROM 0x0036fe84 resultVFVOICE
const char	resultVFVOICE[] = "+FVOICE";
// ROM 0x0036fe8c resultC20FCO
const char	resultC20FCO[] = "+FCO";
// ROM 0x0036fe94 resultC20FVO
const char	resultC20FVO[] = "+FVO";
// ROM 0x0036fe9c resultC20FDM
const char	resultC20FDM[] = "+FDM";
// ROM 0x0036fea4 resultC20FHS
const char	resultC20FHS[] = "+FHS:";
// ROM 0x0036feac resultC20FCS
const char	resultC20FCS[] = "+FCS:";
// ROM 0x0036feb4 resultC20FIS
const char	resultC20FIS[] = "+FIS:";
// ROM 0x0036febc resultC20FTC
const char	resultC20FTC[] = "+FTC:";
// ROM 0x0036fec4 resultC20FPO
const char	resultC20FPO[] = "+FPO";
// ROM 0x0036fecc resultC20FTI
const char	resultC20FTI[] = "+FTI:";
// ROM 0x0036fed4 resultC20FCI
const char	resultC20FCI[] = "+FCI:";
// ROM 0x0036fedc resultC20FPI
const char	resultC20FPI[] = "+FPI";
// ROM 0x0036fee4 resultC20FNF
const char	resultC20FNF[] = "+FNF:";
// ROM 0x0036feec resultC20FNS
const char	resultC20FNS[] = "+FNS:";
// ROM 0x0036fef4 resultC20FNC
const char	resultC20FNC[] = "+FNC:";
// ROM 0x0036fefc resultC20FET
const char	resultC20FET[] = "+FET:";
// ROM 0x0036ff04 resultC20FPS
const char	resultC20FPS[] = "+FPS";
// ROM 0x0036ff0c resultC20FHT
const char	resultC20FHT[] = "+FHT";
// ROM 0x0036ff14 resultC20FHR
const char	resultC20FHR[] = "+FHR";
// ROM 0x0036ff1c kModemIdStr224
const char	kModemIdStr224[] = "242";
// ROM 0x0036ff20 kModemHCodeVersionStr224
const char	kModemHCodeVersionStr224[] = "C2501-H0";
// ROM 0x0036ff2c kModemIdStr96V24A
const char	kModemIdStr96V24A[] = "RC96V24AC-C !!!";
// ROM 0x0036ff3c kModemIdStr96V24B
const char	kModemIdStr96V24B[] = "RC96V24AC !!!!";
// ROM 0x0036ff4c kModemIdStr96V24D
const char	kModemIdStr96V24D[] = "RC96V24AC-W !!!";
// ROM 0x0036ff5c kModemIdStr96V24F
const char	kModemIdStr96V24F[] = "RC96V24ACS !!!";
// ROM 0x0036ff6c kModemIdStr9624ACW
const char	kModemIdStr9624ACW[] = "RC9624AC-W2!!!!";
// ROM 0x0036ff7c kModemIdStrACL
const char	kModemIdStrACL[] = "RC32ACL";
// ROM 0x0036ff84 kModemIdStrELSA
const char	kModemIdStrELSA[] = "MicroLink 2460";
// ROM 0x0036ff94 kModemIdStrBicHS
const char	kModemIdStrBicHS[] = "NEWT I HS USA";
// ROM 0x0036ffa4 kModemIdStrUnknown
const char	kModemIdStrUnknown[] = "Unknown";
// ROM 0x0036ffac kModemCmdStrACLSet144
const char	kModemCmdStrACLSet144[] = "ATF10\r";
// ROM 0x0036ffb4 kModemCmdStrACLSetAutoMode
const char	kModemCmdStrACLSetAutoMode[] = "ATF0\r";
// ROM 0x0036ffbc kModemCmdStr224BrickModemHack
const char	kModemCmdStr224BrickModemHack[] = "ATE0S12=12\r";
// ROM 0x0036ffc8 kModemCmdStr224
const char	kModemCmdStr224[] = "ATE0&C1S12=12\r";
// ROM 0x0036ffd8 kModemCmdStrNoECGeneric
const char	kModemCmdStrNoECGeneric[] = "ATE0&C1S12=12W2&K4&Q6\r";
// ROM 0x0036fff0 kModemCmdStrNoEC
const char	kModemCmdStrNoEC[] = "ATE0&C1S12=12W2&K3&Q6\r";
// ROM 0x00370008 kModemCmdStrECOnly
const char	kModemCmdStrECOnly[] = "ATE0&C1S12=12W2&K3&Q5S36=4\r";
// ROM 0x00370024 kModemCmdStrECFallBack
const char	kModemCmdStrECFallBack[] = "ATE0&C1S12=12W2&K3&Q5\r";
// ROM 0x0037003c kModemCmdStrDirect
const char	kModemCmdStrDirect[] = "ATE0&C1S12=12W2&K0&Q0\r";
// ROM 0x00370054 kModemCmdStrCellular
const char	kModemCmdStrCellular[] = "ATE0&C1S12=12W2%E1)M1\r";
// ROM 0x0037006c kModemCmdStrNoECELSA
const char	kModemCmdStrNoECELSA[] = "ATE0&C1S12=12\\Q3\\N0\r";
// ROM 0x00370084 kModemCmdStrECOnlyELSA
const char	kModemCmdStrECOnlyELSA[] = "ATE0&C1S12=12\\Q3\\N6\r";
// ROM 0x0037009c kModemCmdStrECFallBackELSA
const char	kModemCmdStrECFallBackELSA[] = "ATE0&C1S12=12\\Q3\\N3\r";
// ROM 0x003700b4 kModemCmdStrDirectELSA
const char	kModemCmdStrDirectELSA[] = "ATE0&C1S12=12\\Q0\\N1\r";
// ROM 0x003700cc kModemCmdStrNoECBicHSBrickModemHack
const char	kModemCmdStrNoECBicHSBrickModemHack[] = "ATE0\\V0&C0S12=12\\N0\r";
// ROM 0x003700e4 kModemCmdStrECOnlyBicHSBrickModemHack
const char	kModemCmdStrECOnlyBicHSBrickModemHack[] = "ATE0\\V0&C0S12=12\\N5\r";
// ROM 0x003700fc kModemCmdStrECFallBackBicHSBrickModemHack
const char	kModemCmdStrECFallBackBicHSBrickModemHack[] = "ATE0\\V0&C0S12=12\\N6\r";
// ROM 0x00370114 kModemCmdStrDirectBicHSBrickModemHack
const char	kModemCmdStrDirectBicHSBrickModemHack[] = "ATE0\\V0&C0S12=12\\Q0\\N1\r";
// ROM 0x0037012c kModemCmdStrNoECBicHS
const char	kModemCmdStrNoECBicHS[] = "ATE0\\V0S12=12\\N0\r";
// ROM 0x00370140 kModemCmdStrECOnlyBicHS
const char	kModemCmdStrECOnlyBicHS[] = "ATE0\\V0S12=12\\N5\r";
// ROM 0x00370154 kModemCmdStrECFallBackBicHS
const char	kModemCmdStrECFallBackBicHS[] = "ATE0\\V0S12=12\\N6\r";
// ROM 0x00370168 kModemCmdStrDirectBicHS
const char	kModemCmdStrDirectBicHS[] = "ATE0\\V0S12=12\\Q0\\N1\r";
// ROM 0x00370180 kModemDialPrefStr
const char	kModemDialPrefStr[] = "ATM1L2X4S7=060S8=001S6=003S0=000\r";

// ROM 0x003701a4 modemRspParseTable
const ModemResponse	modemRspParseTable[] = {
	{ resultVOK, 2, 0 },
	{ resultConnectN, 8, 17 },
	{ resultVConnect, 7, 1 },
	{ resultVRing, 4, 2 },
	{ resultVNoCarrier, 10, 3 },
	{ resultVError, 5, 4 },
	{ resultVNoDialTone, 11, 6 },
	{ resultVBusy, 4, 7 },
	{ resultVNoAnswer, 9, 8 },
	{ resultVFCError, 8, 16 },
	{ resultVDataCnct, 4, 13 },
	{ resultVFaxCnct, 3, 15 },
	{ resultVFCIG, 6, 19 },
	{ resultVFCFR, 5, 18 },
	{ resultVFCON, 5, 20 },
	{ resultVFCSI, 6, 21 },
	{ resultVFDCS, 6, 22 },
	{ resultVFDIS, 6, 23 },
	{ resultVFDTC, 6, 24 },
	{ resultVFET, 5, 25 },
	{ resultVFHNG, 6, 26 },
	{ resultVFHR, 5, 27 },
	{ resultVFHT, 5, 28 },
	{ resultVFNSC, 6, 31 },
	{ resultVFNSF, 6, 32 },
	{ resultVFNSS, 6, 33 },
	{ resultVFPOLL, 6, 34 },
	{ resultVFPPR, 6, 35 },
	{ resultVFPTS, 6, 36 },
	{ resultVFRBC, 6, 37 },
	{ resultVFTSI, 6, 39 },
	{ resultVFVOICE, 7, 40 },
	{ resultC20FCO, 4, 41 },
	{ resultC20FVO, 4, 42 },
	{ resultC20FDM, 4, 43 },
	{ resultC20FHS, 5, 44 },
	{ resultC20FCS, 5, 45 },
	{ resultC20FIS, 5, 46 },
	{ resultC20FTC, 5, 47 },
	{ resultC20FPO, 4, 48 },
	{ resultC20FTI, 5, 49 },
	{ resultC20FCI, 5, 50 },
	{ resultC20FPI, 4, 51 },
	{ resultC20FNF, 5, 52 },
	{ resultC20FNS, 5, 53 },
	{ resultC20FNC, 5, 54 },
	{ resultC20FET, 5, 55 },
	{ resultC20FPS, 4, 56 },
	{ resultC20FHT, 4, 57 },
	{ resultC20FHR, 4, 58 },
	{ 0, 0, 0 }
};
