add_executable(test_IMACodec test_IMACodec.cpp)
target_link_libraries(test_IMACodec PRIVATE sound)
add_test(NAME sound.IMACodec COMMAND test_IMACodec)
set_tests_properties(sound.IMACodec PROPERTIES TIMEOUT 60)

add_executable(test_SampleConvert test_SampleConvert.cpp)
target_link_libraries(test_SampleConvert PRIVATE sound)
add_test(NAME sound.SampleConvert COMMAND test_SampleConvert)
set_tests_properties(sound.SampleConvert PROPERTIES TIMEOUT 60)

add_executable(test_Resample test_Resample.cpp)
target_link_libraries(test_Resample PRIVATE sound)
add_test(NAME sound.Resample COMMAND test_Resample)
set_tests_properties(sound.Resample PROPERTIES TIMEOUT 60)

add_executable(test_ResampleFiltered test_ResampleFiltered.cpp)
target_link_libraries(test_ResampleFiltered PRIVATE sound)
add_test(NAME sound.ResampleFiltered COMMAND test_ResampleFiltered)
set_tests_properties(sound.ResampleFiltered PROPERTIES TIMEOUT 60)

add_executable(test_SoundCodec test_SoundCodec.cpp)
target_link_libraries(test_SoundCodec PRIVATE sound os600_kernel os600_user)
add_test(NAME sound.SoundCodec COMMAND test_SoundCodec)
set_tests_properties(sound.SoundCodec PROPERTIES TIMEOUT 60)

add_executable(test_SoundVolume test_SoundVolume.cpp)
target_link_libraries(test_SoundVolume PRIVATE sound frames)
add_test(NAME sound.SoundVolume COMMAND test_SoundVolume)
set_tests_properties(sound.SoundVolume PROPERTIES TIMEOUT 60)

add_executable(test_SoundServer test_SoundServer.cpp)
target_link_libraries(test_SoundServer PRIVATE sound hal_host_sound os600_kernel os600_user)
add_test(NAME sound.SoundServer COMMAND test_SoundServer)
set_tests_properties(sound.SoundServer PROPERTIES TIMEOUT 60)

add_executable(test_PlaySound test_PlaySound.cpp)
target_link_libraries(test_PlaySound PRIVATE newt host_views hal_host_display hal_host_sound)
target_compile_definitions(test_PlaySound PRIVATE "NEWTON_ROM_BIN=\"${NEWTON_ROM_BIN}\"")
add_test(NAME sound.PlaySound COMMAND test_PlaySound)
set_tests_properties(sound.PlaySound PROPERTIES TIMEOUT 120)

add_executable(test_GSM test_GSM.cpp)
target_link_libraries(test_GSM PRIVATE sound)
add_test(NAME sound.GSM COMMAND test_GSM)
set_tests_properties(sound.GSM PROPERTIES TIMEOUT 60)
